### ISSUE TITLE
2012-13 GEOS-FP native resolution data

### ISSUE THREAD

**Issue by xin-chen-github** [geoschem/geos-chem#1019]
### Ask a question about GEOS-Chem:
Dear GCST,

I'm wondering whether the native resolution GEOS-FP data for 2012 (post-April) and 2013 are available and kept somewhere? It seems that the washu and computecanada servers only have the 0.25-degree GEOS-FP data starting from 2014. 

Thank you,
Xin

**Comment by lizziel** [comment]
Hi @xin-chen-github, thanks for asking about this. Native resolution GEOS-FP data for before 2014 is not available. When we began processing GEOS-FP fields for GEOS-Chem we did not archive the processed global 0.25x0.3125 fields since at the time we did not have a use for them (this was before GCHP and FlexGrid). The time period you want corresponds to GEOS-5.7.2, which is considered by GMAO to be pre-GEOS-FP, and they no longer offer that data to download.

For time periods before 2014 we recommend using MERRA2 which is available at 0.5 x 0.625 native resolution. In general we typically recommend using MERRA-2 anyway as it is a frozen analysis product. The met fields are created at GMAO with the same version of the assimilation system, so it’s a stable product. GEOS-FP, on the other hand, is an operational product, and they update the assimilation system every so often.  That means that there could be inconsistency between newer GEOS-FP and older GEOS-FP met fields.
