### ISSUE TITLE
[QUESTION] CH4-O3 simulation

### ISSUE THREAD

**Issue by kenichi0225703** [geoschem/geos-chem#1032]
### Ask a question about GEOS-Chem:
Hello,
I would like to evaluate the effect of CH4 anthropogenic emission on O3 concentration, is this possible with the full-chem simulations ? Looking at the default HEMCO_config.rc, the line about CH4 anthropogenic emission such as CEDS and CMIP6 is commented out (Comment out CH4 for full-chem simulations: do not use CH4 emissions). Why is this ? Does the full-chem model take into account the impact of CH4 anthropogenic emissions?

**Comment by djxjacob** [comment]
CH4 in the full-chemistry simulation is specified as a surface boundary condition. The easiest way to determine the effect of changing CH4 on O3 is to change that boundary condition.  Daniel

From: kenichi0225703 ***@***.***>
Sent: Friday, November 26, 2021 8:20 AM
To: geoschem/geos-chem ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [geoschem/geos-chem] [QUESTION] CH4-O3 simulation (Issue #1032)

Ask a question about GEOS-Chem:

Hello,
I would like to evaluate the effect of CH4 anthropogenic emission on O3 concentration, is this possible with the full-chem simulations ? Looking at the default HEMCO_config.rc, the line about CH4 anthropogenic emission such as CEDS and CMIP6 is commented out (Comment out CH4 for full-chem simulations: do not use CH4 emissions). Why is this ? Does the full-chem model take into account the impact of CH4 anthropogenic emissions?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_geoschem_geos-2Dchem_issues_1032&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=B2X5VPB2_jRHVtidSW533OC4iiv8qADr7SWInwbKv13wmvi7OP0IoDGUiiWDuAby&s=fvfJg1MFrtcSsowHTtwPD2N3rIjGWd2LT6dvJUfsvbQ&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKHHSVITOVQSZFJY7QQUMOLUN6CPPANCNFSM5I2U322A&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=B2X5VPB2_jRHVtidSW533OC4iiv8qADr7SWInwbKv13wmvi7OP0IoDGUiiWDuAby&s=8DpsQDIYNXRzfPTH1mbCwYEkjPXhcD7GFNfUxSnNftk&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=B2X5VPB2_jRHVtidSW533OC4iiv8qADr7SWInwbKv13wmvi7OP0IoDGUiiWDuAby&s=fB6rFfr7SpgLIpbueq3hMOsxU0K1xoHK1aBPY6BX-7I&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=B2X5VPB2_jRHVtidSW533OC4iiv8qADr7SWInwbKv13wmvi7OP0IoDGUiiWDuAby&s=RbT3WILRssOG0I-b2D5QF3-th_7WVEJ_ChZP_kCajxg&e=>.

**Comment by kenichi0225703** [comment]
Thank you Daniel.
If so, does this mean that CH4 anthropogenic emission data is not available for full-chem simulations ?

**Comment by djxjacob** [comment]
You can if you want but you need to disable the surface BC and add the HEMCO anthro methane emissions. Then you need to set correct initial conditions and spin up the model for decades because of the 17-year mode. It’s a whole different kind of simulation.

**Comment by kenichi0225703** [comment]
I got it. Thank you for your kindness.

**Comment by yantosca** [comment]
I will close out this issue now.  Thanks for writing.
