### ISSUE TITLE
[BUG/ISSUE] Wrong growth factor used on PM2.5ss in aerosol_mod.F

### ISSUE THREAD

**Issue by chfite** [geoschem/geos-chem#1033]
In the aerosol_conc subroutine of aerosol_mod.F the growth factor for organic aerosol is being used in calculating and assigning values to the PM25ss variable for sea salt. It lists `SALA(I,J,L) * ORG_GROWTH ` when assigning values to PM25ss, while it should read `SALA(I,J,L) * SSA_GROWTH `.  

The calculation of total PM2.5 further up in the subroutine is correct and scales SALA by SSA_GROWTH, so this is only an issue in the assignment to PM25ss. I happened to notice the issue in v12.6.0 but it appears to still exist in more recent versions as well.

**Comment by yantosca** [comment]
Thanks @chfite.  We will try to get this into 13.4.0, which is under prep now.

**Comment by yantosca** [comment]
Hi @chfite, I took a look at the 13.3.3 code and it does seem that the PM25ss computation multiplies SALA * SSA_GROWTH.

https://github.com/geoschem/geos-chem/blob/4252e96ff0614772dd1228c4d08c5d8dbc3d2a37/GeosCore/aerosol_mod.F90#L970-L976

This was fixed in commit 04bf01e2 by @msulprizio for version 13.3.0.

With your permission, I will close out this issue.

**Comment by chfite** [comment]
@yantosca Ah, I see. Good to know it's already been fixed. You can close out. Thanks!
