### ISSUE TITLE
[FEATURE REQUEST] Update methane simulation to use GFEI v2 emissions for the oil, gas, and coal sectors

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1043]
GFEI v2 emission grids for 2019 by sector and subsector are available for download from
the Harvard Dataverse at https://doi.org/10.7910/DVN/HH4EUM (Scarpelli et al., 2021). The 2010-2018 emission grids are available upon request. 

**Reference**

>Scarpelli, T.R., D.J. Jacob, S. Grossman, X. Lu, Z. Qu, M.P. Sulprizio, Y. Zhang, F. Reuland, and D. Gordon, _Updated Global Fuel Exploitation Inventory (GFEI) for methane emissions from the oil, gas, and coal sectors: evaluation with inversions of atmospheric methane observations_, Atmos. Chem. Phys. Discuss. [preprint], https://doi.org/10.5194/acp-2021-911, in review, 2021.

**Comment by djxjacob** [comment]
Hi Melissa – we only need the 2019 emission grids for now in the IMI and in version 13.4.  Daniel

From: Melissa Sulprizio ***@***.***>
Sent: Sunday, December 5, 2021 3:14 PM
To: geoschem/geos-chem ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [geoschem/geos-chem] [FEATURE REQUEST] Add GFEI methane emissions from oil, gas, and coal sectors (Issue #1043)


GFEI v2 emission grids for 2019 by sector and subsector are available for download from
the Harvard Dataverse at https://doi.org/10.7910/DVN/HH4EUM<https://urldefense.proofpoint.com/v2/url?u=https-3A__doi.org_10.7910_DVN_HH4EUM&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=tMjhwV7Wu5lVoxyG6hO30UckWOBSRVTQeiNE-T7Lss1LYXObqywXYq-FOi25rqj-&s=1o-_OG9lXmllisnx3USKy7JUeueaOU-0mzJhxUzYmf8&e=> (Scarpelli et al., 2021). The 2010-2018 emission grids are available upon request.

Reference

Scarpelli, T.R., D.J. Jacob, S. Grossman, X. Lu, Z. Qu, M.P. Sulprizio, Y. Zhang, F. Reuland, and D. Gordon, Updated Global Fuel Exploitation Inventory (GFEI) for methane emissions from the oil, gas, and coal sectors: evaluation with inversions of atmospheric methane observations, Atmos. Chem. Phys. Discuss. [preprint], https://doi.org/10.5194/acp-2021-911<https://urldefense.proofpoint.com/v2/url?u=https-3A__doi.org_10.5194_acp-2D2021-2D911&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=tMjhwV7Wu5lVoxyG6hO30UckWOBSRVTQeiNE-T7Lss1LYXObqywXYq-FOi25rqj-&s=e0Lcp4XlfujHnS4t8XS3XGeRUs0CBYS_uFgEvelMZm4&e=>, in review, 2021.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_geoschem_geos-2Dchem_issues_1043&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=tMjhwV7Wu5lVoxyG6hO30UckWOBSRVTQeiNE-T7Lss1LYXObqywXYq-FOi25rqj-&s=tJfpZ4s2HRuvp-KTg-hsBQ4xRHwuuckGS7F2D0Hn_0E&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKHHSVOO4PJJRH5K7NYOIWTUPPB2DANCNFSM5JNE64DA&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=tMjhwV7Wu5lVoxyG6hO30UckWOBSRVTQeiNE-T7Lss1LYXObqywXYq-FOi25rqj-&s=GaxxbsDjaxOrESEaLVBqafZejNAWxl4KW388P5tbA5c&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=tMjhwV7Wu5lVoxyG6hO30UckWOBSRVTQeiNE-T7Lss1LYXObqywXYq-FOi25rqj-&s=Rc6PdxukgYW5Ux08t1ACjFkERmDpXGF7ZEEwc7SpXuQ&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=tMjhwV7Wu5lVoxyG6hO30UckWOBSRVTQeiNE-T7Lss1LYXObqywXYq-FOi25rqj-&s=ABKMssgiHftGb4TXcnk9A31ytBhF1JEUPo_aIz0lTrk&e=>.

**Comment by msulprizio** [comment]
> Hi Melissa – we only need the 2019 emission grids for now in the IMI and in version 13.4. Daniel

Thanks @djxjacob! I will proceed with just the 2019 GFEI emissions.

**Comment by yantosca** [comment]
Linked PR #1104 has now been merged into the 13.4.0 development stream.  We can now close this issue.
