### ISSUE TITLE
[BUG/ISSUE] concEduct threshold too low

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#1115]
### What institution are you from?
MIT

### Description of the problem
KPP sometimes crashes with an excessive heterogeneous chemistry rate. This occurs because the educt concentration becomes too low. This was previously caught by only proceeding with the calculation if the concentration was > 100 molec/cm3, but at some point that was reduced to 1e-20 molec/cm3. A previous commit (https://github.com/geoschem/geos-chem/commit/7e2be0db4cb484bf174f3730c6c8d7c346cba67b) attempted to address this by raising the limit to 1e-8 molec/cm3, but this is still not conservative enough.

### Description of troubleshooting performed
We have found that raising the limit to 1 molec/cm3 prevents the crash. This is a reasonable number; 1 molec/cm3 is equivalent, at the top of the model grid, the air number density is around 4e14 molec/cm3, so 1 molec/cm3 is of the order of 0.01 parts per trillion. At the surface the air number density is more like 2.5e19, so a threshold of 1 molec/cm3 is of the order of 0.01 parts per quintillion.

### GEOS-Chem version
13.4.0

### Description of modifications
Change concEduct limit to 1.0e+0 (https://github.com/geoschem/geos-chem/blob/7e2be0db4cb484bf174f3730c6c8d7c346cba67b/KPP/fullchem/rateLawUtilFuncs.F90#L118).

**Comment by sdeastham** [comment]
Tagging @SadiaToma as this is related to an issue they have been seeing.

**Comment by djxjacob** [comment]
Hi Seb – I think that 1 molecule cm-3 is too large a threshold.  Mean Cl atom concentration is ~100 molecules cm-3 . I would be OK with a 1.E-3 threshold for not doing the chemical calculation. We could otherwise take other measures, such as prevent concentrations from dropping below a threshold. Daniel

From: Sebastian David Eastham ***@***.***>
Sent: Friday, February 4, 2022 11:01 AM
To: geoschem/geos-chem ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [geoschem/geos-chem] [BUG/ISSUE] concEduct threshold too low (Issue #1115)

What institution are you from?

MIT

Description of the problem

KPP sometimes crashes with an excessive heterogeneous chemistry rate. This occurs because the educt concentration becomes too low. This was previously caught by only proceeding with the calculation if the concentration was > 100 molec/cm3, but at some point that was reduced to 1e-20 molec/cm3. A previous commit (7e2be0d<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_geoschem_geos-2Dchem_commit_7e2be0db4cb484bf174f3730c6c8d7c346cba67b&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=qKFRcAZkCUwkBfm9oMgB1R_CLtg_c8s981Ha4NasbPhYDoCQecIbi3ud5ukw-aPd&s=8Hj7UQbu-nYp93eHvN3n6R_ldF1WmWO1t4XWOglE6vI&e=>) attempted to address this by raising the limit to 1e-8 molec/cm3, but this is still not conservative enough.

Description of troubleshooting performed

We have found that raising the limit to 1 molec/cm3 prevents the crash. This is a reasonable number; 1 molec/cm3 is equivalent, at the top of the model grid, the air number density is around 4e14 molec/cm3, so 1 molec/cm3 is of the order of 0.01 parts per trillion. At the surface the air number density is more like 2.5e19, so a threshold of 1 molec/cm3 is of the order of 0.01 parts per quintillion.

GEOS-Chem version

13.4.0

Description of modifications

Change concEduct limit to 1.0e+0 (https://github.com/geoschem/geos-chem/blob/7e2be0db4cb484bf174f3730c6c8d7c346cba67b/KPP/fullchem/rateLawUtilFuncs.F90#L118<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_geoschem_geos-2Dchem_blob_7e2be0db4cb484bf174f3730c6c8d7c346cba67b_KPP_fullchem_rateLawUtilFuncs.F90-23L118&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=qKFRcAZkCUwkBfm9oMgB1R_CLtg_c8s981Ha4NasbPhYDoCQecIbi3ud5ukw-aPd&s=_o4R_pMr34gz-sM33QaIpOt8Srivv6nE3v_4txm9RT8&e=>).

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_geoschem_geos-2Dchem_issues_1115&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=qKFRcAZkCUwkBfm9oMgB1R_CLtg_c8s981Ha4NasbPhYDoCQecIbi3ud5ukw-aPd&s=bQ2Q5Szz0i-__63A9n2z6SAp0u7G73iqoLoo85xNPeE&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKHHSVIEWCL3ZATBHLGRKVDUZPZ2FANCNFSM5NSFB7SQ&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=qKFRcAZkCUwkBfm9oMgB1R_CLtg_c8s981Ha4NasbPhYDoCQecIbi3ud5ukw-aPd&s=naFInXibMYWZGDji3hxBHBAdoxL7wJl5Ti2A3_Rz2P0&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=qKFRcAZkCUwkBfm9oMgB1R_CLtg_c8s981Ha4NasbPhYDoCQecIbi3ud5ukw-aPd&s=0R9G_Lq5ASUr39Tv6tY3kQL4ev4K5iGjOzXcK5Hk7Xk&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=qKFRcAZkCUwkBfm9oMgB1R_CLtg_c8s981Ha4NasbPhYDoCQecIbi3ud5ukw-aPd&s=4KcWphgPy0cXoTvs4xppnYZ9sJ3_vK_JWXWH_DOX6IY&e=>.

**Comment by sdeastham** [comment]
Hi @djxjacob  - thanks for your input! To be clear, this only affects the second argument, which is expected to be the "abundant" species. In the current usage of this function the second argument species are BrSALA, BrSALC, SALACl, SALCCl, H2O, HCl, and HBr. Would those concentrations drop to < 100 molec/cm3 while these reactions are still relevant? Genuine question as I have no idea!

**Comment by djxjacob** [comment]
Oh, I see, sorry! If we apply the concentration threshold only to the species in excess in hetchem reactions then 1 molecule cm-3 is just fine. I was concerned that you might want to apply it as a general threshold in KPP.

**Comment by yantosca** [comment]
Thanks @sdeastham and @djxjacob.  Thanks for looking into this.  That was a holdover from the old gckpp_HetRates code where the original threshold was 100.  But I found that this didn't prevent div-by-zero errors so I tightened up somewhat arbitrarily.  I'll do testing with the new threshold = 1.

We can get this into 14.0.0, as we have already started benchmarking the 13.4.0 code.  Easy fix.

**Comment by yantosca** [comment]
@msulprizio, could we get this into 13.4.0 while the benchmarking is still open?

**Comment by msulprizio** [comment]
Yes, let's plan on including this in 13.4.0.

**Comment by msulprizio** [comment]
Pull request #1123 has now been merged into `dev` and will be included in GEOS-Chem 13.4.0.
