### ISSUE TITLE
[DISCUSSION] A pre-release versioning scheme for GEOS-Chem

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/geos-chem#114]
Hi everyone,

I'd like to propose a pre-release versioning scheme because pre-release tags are a nice way to trigger expensive CI tests, and it's also a clean way to document the testing that goes into a GEOS-Chem release. Below is a description of [Semantic Versioning 2.0.0](https://semver.org/) fitted to GEOS-Chem's validation workflow.

## Pre-release stages
| Stage | Tag format | Stage description | 
|----|----|----|
| **alpha** | X.Y.Z&#8209;alpha.N | Alpha tags are tags that undergo initial tests. Right now, this "initial testing" is running the build-matrix, but these could be expanded in the future. <br><br> Alpha tags are made from `dev/*` branches. Alpha tags are only for testing.  |
| **beta** | X.Y.Z&#8209;beta.N | Beta tags are tags that undergo benchmarking. Logically, beta testing is one step past alpha testing. <br><br> Beta tags are made from `dev/*` branches.  Beta tags are only for testing. |
| **release candidate** | X.Y.Z&#8209;rc.N | RC tags are tags are benchmarks that get sent to the steering commitee. <br><br> Note that a RC tag is a also a beta tag. The beta tag is the version that got benchmarked, and if it looks good enough to send to the steering commitee, it is also tagged as a release candidate. |
| **official release** | X.Y.Z | Official release. Unchanged. |  

**Note**:  Release candidates (which tags a commit on `dev/X.Y.Z`) can be merged into the master branch upon approval. This is the mechanism for moving dev -> master.
**Note**: N is just an integer that increments (e.g. 1, 2, 3, ..., 9, 10, 11, etc.)
**Note**: SemVer 2.0.0 defines the precedence: X.Y.Z-alpha.N < X.Y.Z-beta.N < X.Y.Z-rc.N < X.Y.Z

## Reasons to use pre-release tags
- Tags are free. As long as there's a well-defined naming scheme, there's no reason to be conservative with tagging.
- It helps document the validation process
  - Pre-release tags have a specific meaning
  - Problems or manual tests can be documented in the pre-release's notes (on GitHub)
- It facilitates talking about tests and issues (now and in the future)
  - It's useful for archiving issues. 
      - E.g. In the archive of GitHub issues, an issue that says "my test yesterday failed" is a lot less useful in a year or two than an issue that says "my test on 12.6.1-alpha.1 failed".
      - E.g. #113 could say "this issue was fixed in `12.6.1-alpha.X`". In the future, it's easy to find the build matrix test for `12.6.1-alpha.X`.
  - It's easier to talk about pre-release tags than commit hashes. 
      - E.g. "I saw XXXX problem with 12.7.0-beta.3" vs. "I saw XXXX problem when I ran this test with the last commit ce7a87b"
- It's something to trigger expensive CI tests on
- Inline with standard practices
  - Good for future-proofing
      - Many software distribution tools understand semantic versioning

Looking forward to hearing what everyone thinks!

Liam

**Comment by msulprizio** [comment]
@yantosca @lizziel @WilliamDowns and I discussed this today. We have no objections and will test this out for 12.7.0. Will the appropriate tests be triggered now (really later this week or next week when we begin benchmarking) if I add the tags or is more work needed to add this feature?

**Comment by LiamBindle** [comment]
Hi @msulprizio. I believe the triggers are set up correctly for this.

Below is the part of the build matrix pipeline's configuration that should cause the pipeline to trigger on prerelease tags. https://github.com/geoschem/geos-chem/blob/5f25c0fc6ff27ec076d766ac178554d9b91bf636/.ci-pipelines/build-matrix.yml#L15-L19

**Comment by msulprizio** [comment]
Do we need separate alpha and beta tags? Would it make more sense to have beta tags represent internal benchmarks and then release-candidate tags that represent official benchmarks that are sent to the GCSC? I'm not sure we need alpha tags at all.

An internal benchmark is really a benchmark we run for ourselves to test each new feature that goes into a version so that we can isolate the impacts from that feature. We do not send the internal benchmarks to the steering committee, but keep them locally on our machine until the version is officially approved. We occasionally send the internal benchmark to the developer of that feature to ensure the updates were implemented properly.

We generally don't run multiple benchmarks for a version release. We almost always send benchmarks to the steering committee unless it's clear something is disastrously wrong with the output, but that should have been caught by an earlier internal benchmark. Occasionally, benchmarks (e.g. X.Y.Z-rc.1) are sent back to us if the steering committee has concerns, we implement a fix, then rerun the benchmark. That would essentially be an X.Y.Z-rc.2 version.

**Comment by LiamBindle** [comment]
@msulprizio that sounds good to me. I don't see anything wrong with skipping alpha tags in minor releases (like X and Y releases), but I think they are useful for documenting one-off tests and sanity checks between releases with large structural changes.

For example @lizziel and I have been running checks like "does the model run to completion?" and "does our wind regridding look right?", and I think alpha tags are useful for documenting tests like these.

For pre-release tags to be effective and useful to the development community, I think the important thing is that each type of pre-release tag has a specific meaning, so I think it's perfectly fine if most GEOS-Chem releases skip alpha tags. What do you think?

**Comment by msulprizio** [comment]
For the version tag names, do we want it to be 0- or 1-based? For 12.7.0, we had 12.7.0-rc.0 and 12.7.0-rc.1 but from now on should we start with 1 as described above?

@yantosca and I are leaning towards 0-based because that's what we use for X.Y.Z versioning. 

@LiamBindle @lizziel Any preferences on your end? What have you been using in GCHPctm?

**Comment by LiamBindle** [comment]
@msulprizio 0-based sounds good to me. That's what we started using in GCHPctm as well.

**Comment by msulprizio** [comment]
Excellent! Thanks for confirming @LiamBindle. We'll stick with 0-based.

**Comment by msulprizio** [comment]
This versioning scheme is in use as of 12.7.0.
