### ISSUE TITLE
[QUESTION] How to initialize the CO2 simulation in lieu of a spin-up?

### ISSUE THREAD

**Issue by sumengqian** [geoschem/geos-chem#1152]
Hi, I am a beginner. I am trying to run a CO2 simulation and am confused about the 5th point in the answer of #911 . You mentioned that the best approach is to initialize them by scaling to observations (such as background latitudinal profiles) in lieu of any spin-up. Could you please explain that in detail, or is there any more detailed guidance? Should I change the benchmark restart file or keep using it and change some parameters or variables in other places?

Otherwise, I noticed some scholars begin with a uniform global distribution of a specific CO2 concentration in the simulation. I am wondering how to realize this? Could this be done by changing the CO2 Background_VV in the species_database.yml file?   If species could be found in the restart file, do the default background concentrations specified by the Background_VV field in the species_database.yml file matter?

I am looking forward to your answer! Thank you!
@yantosca @msulprizio

**Comment by djxjacob** [comment]
Spinning up a CO2 simulation is not useful because of the long lifetime. This is why it’s necessary to treat it as an initial value problem and to start from initial conditions matching observations, as for example from the NOAA database.

From: sumengqian ***@***.***>
Sent: Monday, March 7, 2022 9:25 PM
To: geoschem/geos-chem ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [geoschem/geos-chem] How to initialize the CO2 simulation in lieu of a spin-up? (Issue #1152)


Hi @msulprizio<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_msulprizio&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=0M4rbbZY6KeWuM8iHLxevvWE2Kpqbgm42_ek8wlicqJcmE48kvlWPcYR98jmBbyC&s=DFzzImlt4QQX059avRxSPhP-37FNNklJDmCikVmuBLg&e=> , I am a beginner. I am trying to run a CO2 simulation and am confused about the 5th point. You mentioned that the best approach is to initialize them by scaling to observations (such as background latitudinal profiles) in lieu of any spin-up. Could you please explain that in detail, or is there any more detailed guidance? Should I change the benchmark restart file or keep using it and change some parameters or variables in other places?

Otherwise, I noticed some scholars begin with a uniform global distribution of a specific CO2 concentration in the simulation. I am wondering how to realize this? Could this be done by changing the CO2 Background_VV in the species_database.yml file? If species could be found in the restart file, do the default background concentrations specified by the Background_VV field in the species_database.yml file matter?

I am looking forward to your answer! Thank you!

Originally posted by @sumengqian<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sumengqian&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=0M4rbbZY6KeWuM8iHLxevvWE2Kpqbgm42_ek8wlicqJcmE48kvlWPcYR98jmBbyC&s=FCrq_ZP-ne5x7sgJzimSvKnhKHZX6fprfa5V1gsJ3is&e=> in #911 (reply in thread)<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_geoschem_geos-2Dchem_discussions_911-23discussioncomment-2D2186913&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=0M4rbbZY6KeWuM8iHLxevvWE2Kpqbgm42_ek8wlicqJcmE48kvlWPcYR98jmBbyC&s=W_R_oByCMLegYejEyP3UpNQzJnNDQaO3TJfQ1Po4GkU&e=>

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_geoschem_geos-2Dchem_issues_1152&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=0M4rbbZY6KeWuM8iHLxevvWE2Kpqbgm42_ek8wlicqJcmE48kvlWPcYR98jmBbyC&s=LLQ3O7-MxUP11xZDxZ7YYetMgkxR30uZGU3d2UVM4yk&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKHHSVNKI2Q3F27DRWVM7J3U62275ANCNFSM5QFBCQXA&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=0M4rbbZY6KeWuM8iHLxevvWE2Kpqbgm42_ek8wlicqJcmE48kvlWPcYR98jmBbyC&s=pv8JweAqyZGlK8WT2zcIYZY6H_nOwSWYTiy5mBDQEis&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=0M4rbbZY6KeWuM8iHLxevvWE2Kpqbgm42_ek8wlicqJcmE48kvlWPcYR98jmBbyC&s=wHomjmKgjD9Gsq08CYD28KxcNPnDCJrFDwUsh0m11lw&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=0M4rbbZY6KeWuM8iHLxevvWE2Kpqbgm42_ek8wlicqJcmE48kvlWPcYR98jmBbyC&s=AzLowCEergGtcLvo4jRpR-UKQ5oPtW6G6wOYXtO9c2I&e=>.

**Comment by sumengqian** [comment]
Thanks for the reply, @djxjacob . I understand what you mean. 

My problem is how to realize it ( in GC v13.1.2 )? How to begin a CO2 simulation with the specific value(the real global mean co2 concentration)? Should I change the  CO2 Background_VV  in the species_database.yml file and keep using the benchmark restart file? 
Or did you mean I should create a new restart file using the initial conditions that match observations?

**Comment by yantosca** [comment]
> Or did you mean I should create a new restart file using the initial conditions that match observations?

I think that is the best way forward.

**Comment by sumengqian** [comment]
Thanks, @yantosca! I will have a try.

**Comment by yantosca** [comment]
I will close out this issue.  Feel free to contact us again if you are still having problems.

**Comment by SonofCeasar** [comment]
> > Or did you mean I should create a new restart file using the initial conditions that match observations?
> 
> I think that is the best way forward.

Hello, I would like to ask how to create a new restart file? mean create a new nc file?
