### ISSUE TITLE
[QUESTION] The file name read by the model is inconsistent with the downloaded data file name

### ISSUE THREAD

**Issue by Yuan-yuan-2021** [geoschem/geos-chem#1204]
### Ask a question about GEOS-Chem:
Hello.
I am using a nested model in Asia, but the meteorological data read by the model does not have the suffix AS，like MERRA2.20180701.A1.05x0625.nc4, and the data I downloaded has the suffix AS, like tihis MERRA2.20180701.A1.05x0625.AS.nc4，so the model cannot recognize my meteorological data due to inconsistent names, please tell me how to solve this, thank you .

**Comment by yantosca** [comment]
Thanks for writing @Yuan-yuan-2021.  You must have the global 0.5 x 0.625 met fields.  You can use these but your nested-grid simulation will take a log longer as there will be overhead incurred from the data I/O and regridding due to the larger size of the data.

To fix this, remove the "AS" from the file names for met fields in your `HEMCO_Config.rc` file in the run directory.  NOTE: If you are using 13.3.0 or later, then this will be found in `HEMCO_Config.rc.gmao_metfields`, also in the run directory.

**Comment by XR-peking** [comment]
According to your answers, we can not used the regional_nested_grid anymore? But this is so inconvenient for users due to the huge disk space occupied by the global nested fields.
So, is there any other way to use the regional nested (such as 0.5x0.625) meteorological fields, like in earlier versions?

**Comment by yantosca** [comment]
@XR-peking, you can still use the regional nested-grid met fields.  Sorry if I was unclear in my response.  I meant to say that you probably have the global 0.5 x 0.625 met fields on your disk but the code is looking for the nested met fields that are cut down to size.

In either case, you will need to make sure that the file names in HEMCO_Config.rc (or HEMCO_Config.rc.gmao_metfields in 13.3.0 and later) match the file names that you have on disk.

**Comment by XR-peking** [comment]
yeah, I tried to change it, but there was only the METDIR can be changed in HEMCO_Config.rc which was shown in the picture below.


In the simulation, even I already changed the METDIR in order to use the regional one (from GEOS_0.5x0.625 to GEOS_0.5x0.625_AS) , well, the HEMCO.log still showed that the global nested met files could not be found (such as HEMCO: REQUIRED FILE NOT FOUND /ExtData/GEOS_0.5x0.625_AS/MERRA2/2015/01/MERRA2.20150106.A1.05x0625.nc4). 
wasn't it should automatically searching for the /ExtData/GEOS_0.5x0.625_AS/MERRA2/2015/01/MERRA2.20150106.A1.05x0625.AS.nc4 ?


So, maybe the specific met file path can not easily be changed in HEMCO_Config.rc, right?
Hence, I should look for it in relative Code? 


I would really appreciate it if you have an impression of finding and modifying the path to the nested met files.




--
Rui Xiong 
College of Urban and Environmental Science, Peking University



发件人：Bob Yantosca ***@***.***>
发送日期：2022-04-19 22:27:34
收件人：geoschem/geos-chem ***@***.***>
抄送人：XR-peking ***@***.***>,Mention ***@***.***>
主题：Re: [geoschem/geos-chem] [QUESTION] The file name read by the model is inconsistent with the downloaded data file name (Issue #1204)

@XR-peking, you can still use the regional nested-grid met fields. Sorry if I was unclear in my response. I meant to say that you probably have the global 0.5 x 0.625 met fields on your disk but the code is looking for the nested met fields that are cut down to size.
In either case, you will need to make sure that the file names in HEMCO_Config.rc (or HEMCO_Config.rc.gmao_metfields in 13.3.0 and later) match the file names that you have on disk.

**Comment by yantosca** [comment]
Also tagging @msulprizio

**Comment by msulprizio** [comment]
In addition to adding `_AS` to METDIR, you will also need to modify all of the met field entries to include `.AS`. For example, change:

```
* ALBEDO    $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.A1.$RES.$NC     ALBEDO   1980-2021/1-12/1-31/*/+30minute EFY xy  1  * -  1 1
* CLDTOT    $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.A1.$RES.$NC     CLDTOT   1980-2021/1-12/1-31/*/+30minute EFY xy  1  * -  1 1
```

to:

```
* ALBEDO    $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.A1.$RES.AS.$NC     ALBEDO   1980-2021/1-12/1-31/*/+30minute EFY xy  1  * -  1 1
* CLDTOT    $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.A1.$RES.AS.$NC     CLDTOT   1980-2021/1-12/1-31/*/+30minute EFY xy  1  * -  1 1
```

You can do this with a simple search and replace in your text editor (e.g. replace all `$RES` with `$RES.AS`). This should be done automatically when you execute the `./createRunDir` script and select one of the pre-defined nested domains (AS, NA, EU), but it looks like that step was removed at some point. We can restore it in our next release.

**Comment by XR-peking** [comment]
Thanks so much

From: Melissa Sulprizio ***@***.***>
Date: 2022-04-20 22:13:48
To: geoschem/geos-chem ***@***.***>
Cc: XR-peking ***@***.***>,Mention ***@***.***>
Subject: Re: [geoschem/geos-chem] [QUESTION] The file name read by the model is inconsistent with the downloaded data file name (Issue #1204)

In addition to adding _AS to METDIR, you will also need to modify all of the met field entries to include .AS. For example, change:
* ALBEDO    $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.A1.$RES.$NC     ALBEDO   1980-2021/1-12/1-31/*/+30minute EFY xy  1  * -  1 1
* CLDTOT    $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.A1.$RES.$NC     CLDTOT   1980-2021/1-12/1-31/*/+30minute EFY xy  1  * -  1 1
to:
* ALBEDO    $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.A1.$RES.AS.$NC     ALBEDO   1980-2021/1-12/1-31/*/+30minute EFY xy  1  * -  1 1
* CLDTOT    $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.A1.$RES.AS.$NC     CLDTOT   1980-2021/1-12/1-31/*/+30minute EFY xy  1  * -  1 1
You can do this with a simple search and replace in your text editor (e.g. replace all $RES with $RES.AS). This should be done automatically when you execute the ./createRunDir script and select one of the pre-defined nested domains (AS, NA, EU), but it looks like that step was removed at some point. We can restore it in our next release.
