### ISSUE TITLE
Geos-Chem run directory is soft linking the wrong file for CodeDir folder[BUG/ISSUE]

### ISSUE THREAD

**Issue by map06** [geoschem/geos-chem#1239]
### Description of the problem
When I created run directory using the `./createRundir.sh`,  the Codedir folder generated always points to the home directory 

### Description of troubleshooting performed
I commented out `#cd ../../` from `createRundir` so that it points to the correct file

### GEOS-Chem version
13.4.0

### Description of modifications
Describe your modifications here.

### Log files
```
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /home/mala/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.4.0/gcc-9.2.0-bo6tpsymozxrcsr2zwnwc5zkt7q4tpup/bin/gcc
-- Check for working C compiler: /home/mala/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.4.0/gcc-9.2.0-bo6tpsymozxrcsr2zwnwc5zkt7q4tpup/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/mala/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.4.0/gcc-9.2.0-bo6tpsymozxrcsr2zwnwc5zkt7q4tpup/bin/g++
-- Check for working CXX compiler: /home/mala/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.4.0/gcc-9.2.0-bo6tpsymozxrcsr2zwnwc5zkt7q4tpup/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:20 (get_repo_version):
  Unknown CMake command "get_repo_version".


-- Configuring incomplete, errors occurred!
See also "/home/mala/Desktop/project/geos_new/13.4/gc_merra2_fullchem/build/CMakeFiles/CMakeOutput.log".
```

- Build log (if applicable):
- Run logs (if applicable):
[CMakeOutput.log](https://github.com/geoschem/geos-chem/files/8654054/CMakeOutput.log)

- Run script (if applicable):

### Software versions
- CMake version: 3.10.2

- Compilers (Intel or GNU, and version):7.5.0

- NetCDF version:

**Comment by lizziel** [comment]
Hi @map06, are you generating the run directory from within `code.gcclassic/run`? If you are in the `code.gcclassic/run` directory and type `pwd -P`, what do you get? I wonder if the command is not working as expected on your system.

**Comment by map06** [comment]
@lizziel I am in `Code/run/GCClassic`.  `pwd -P` points to the same directory. I ran it in the cloud too, but there too, the CodeDir folder points to home directory.

**Comment by lizziel** [comment]
Aha, I think I know what the issue is. Your "Code" directory must be the [github.com/geoschem/geos-chem ](https://github.com/geoschem/geos-chem)repository, and you must have downloaded it to your home directory. Is that true?

Have you recently switched to GEOS-Chem 13? Starting in that version we added the wrapper repository [gcclassic](https://github.com/geoschem/gcclassic) to use [HEMCO](https://github.com/geoschem/hemco) and [GEOS-Chem](https://github.com/geoschem/geos-chem) as git submodules, now maintained as separate source code repositories. After cloning the gcclassic repository you need to do `git submodule update --init --recursive` to check out the submodules. See our GEOS-Chem 13 documentation for more information [here](http://wiki.seas.harvard.edu/geos-chem/index.php/Getting_Started_with_GEOS-Chem).

After downloading the GEOS-Chem Classic wrapper repository and checking out the submodules you can then `cd` into the top-level directory called `run`. This is actually a symbolic link to `src/GEOS-Chem/run/GCClassic`. You can then execute the `createRunDir`. The various `cd ../..` within the `createRunDir` script will now work since they will navigate upwards into the GEOS-Chem wrapper repository which is two levels up from the GEOS-Chem repository.

**Comment by map06** [comment]
@lizziel  Thank you. Yes, I switched to 13. I  was trying to directly use the Geos-Chem model without checking out the submodules. Using `git submodule update --init --recursive` solved my issues.

**Comment by lizziel** [comment]
Great, glad it is fixed!
