### ISSUE TITLE
[QUESTION] HPC resources for running GEOS-Chem?

### ISSUE THREAD

**Issue by nadineunger** [geoschem/geos-chem#1263]
### Ask a question about GEOS-Chem:
Hello GEOS-Chem Community & Friends,
I would be very happy for information / experiences about HPC and typical CPU resources required for running GEOS-Chem Asia nested grid and GCHP; (i) full chemistry and aerosols in trop and strat and (ii) tropchem with the advanced SOA aerosol schemes? Say, to run 10 model years of each model type?
Many thanks for any information

**Comment by lizziel** [comment]
Hi Nadine, thanks for reaching out about this. For GCHP global simulations you can use the timing results presented in the following paper:

Martin, R.V., S.D. Eastham, L. Bindle, E.W. Lundgren, T.L. Clune, C.A. Keller, W. Downs, D. Zhang, R.A. Lucchesi, M.P. Sulprizio, R.M. Yantosca, Y. Li, L. Estrada, W.M. Putman, B.M. Auer, A.L. Trayanov, S. Pawson, and D. J.  Jacob, [Improved Advection, Resolution, Performance, and Community Access in the New Generation (Version 13) of the High Performance GEOS-Chem Global Atmospheric Chemistry Model (GCHP)](https://gmd.copernicus.org/preprints/gmd-2022-42/), Geophys. Model Dev. Discuss. [preprint], in review, 2022.

Results for 7-day full chemistry simulations are presented in Figure 3 for several combinations of grid resolution, core count, MPI, and platform. This should give you a sense of how many cores you will need for the grid resolution you would like to run at and your target speed. This includes both tropospheric and stratospheric chemistry. Tropchem runs are not possible in GCHP.

For the nested Asia simulation you will be limited to running on a single node since it uses GEOS-Chem Classic. Timing scales with number of cores so we recommend using a node with as many cores as possible to get maximum speed. The GEOS-Chem Support Team does not perform timing tests on the nested grid simulation, but you might be able to find out typical timing from the user community. I will alert members of the ACMG group at Harvard about this question to see if they have any numbers to provide.

If you want to do high resolution runs focused on Asia you could use the stretched grid capability in GCHP. This would allow you to use many nodes for your simulation. @LiamBindle is the contact person on the Support Team for the stretched grid resolution if you have any questions about it.

**Comment by JFBrewer** [comment]
Hi Nadine - I have a lot of experience running the nested grid over just China and Korea (smaller than the full Asia grid) with the SVPOA complex scheme. When running on one node with 28 cores, it takes me about 5.5 days of wall-clock time to run one month in the model. I would imagine running 10 years in this style would be extremely time-consuming. I think GCHP might be a better fit if you need to go for such a long period of time.
