### ISSUE TITLE
[QUESTION]  How to calculate aerosol extinction coefficient per km for Dust and other AOD components from Geos-Chem output?

### ISSUE THREAD

**Issue by chakri6023** [geoschem/geos-chem#1283]
Ask a question about GEOS-Chem:
Is AOD and aerosol extinction coefficients are same? If they are different then how to calculate aerosol extinction coefficient per km for Dust and other AOD components from Geos-Chem NetCDF output? Any help will be highly appreciated.

**Comment by yantosca** [comment]
Thanks for writing @chakri6023.  This is more of a science question and is probably better directed to the Aerosols Working Group.

**Comment by lizziel** [comment]
I am pinging Aerosols WG Co-chairs on this question: @beckyalexander, @theloniuspunk, @wporter

**Comment by theloniuspunk** [comment]
Hi,

Yes, AOD per length is the extinction coefficient. If I recall the diagnostics, the output regarding AOD is AOD per layer, so to get the extinction coefficient, one would need to divide by the layer height. I believe that this can be outputted in the diagnostics. I haven't ran the model much since the diagnostics were updated though.

Jeff
