### ISSUE TITLE
[QUESTION] Using KppID for Prod/Loss Diagnostic

### ISSUE THREAD

**Issue by ktravis213** [geoschem/geos-chem#1300]
### Ask a question about GEOS-Chem:
In the prod/loss diagnostic, it appears that the diagnostic has 'nSlots' per whatever is listed in gckpp.kpp, and the slot number is used as the index in State_Diag.  See the code below.  Is there a way to go from id_POx, or some other unique POx identifier, to the slot number so that I can check in plane flight_mod.F90 and use it to write out POx, or another prod/loss reaction without having to hard code the slot number? Thanks!

In fullchem_mod.F90
```F90
       ! Chemical production of species or families [molec/cm3/s]
       IF ( State_Diag%Archive_Prod ) THEN
          DO S = 1, State_Diag%Map_Prod%nSlots
             KppID = State_Diag%Map_Prod%slot2Id(S)
             State_Diag%Prod(I,J,L,S) = VAR(KppID) / DT
             !WRITE(*,*) 'State_Diag', KppId, &
             !     State_Diag%Prod(I,J,L,S)
          ENDDO
       ENDIF
```

**Comment by yantosca** [comment]
Thanks for writing @ktravis213.  The idea with the "slots" is to only store as many values as is needed in the diagnostic arrays, which saves memory.

If you have this specified in the Prod/Loss collection of `HISTORY.rc`:
```console
  ProdLoss.fields:            'Prod_?PRD?                    ',
                              'Loss_?LOS?                    ',
```

Then this will store all of the prod/loss species specified in the `#FAMILIES` section of gckpp.kpp (i.e. POx, LOx, PCO, LCO, PSO4, LCH4, PH2O2). 

 Then in this DO loop :
```F90
    DO S = 1, State_Diag%Map_Prod%nSlots
          KppID = State_Diag%Map_Prod%slot2Id(S)
          State_Diag%Prod(I,J,L,S) = VAR(KppID) / DT
   ENDDO
````
- When S = 1, KppId = ind_POx
- When S = 2, KppId = ind_LOx,
- When S = 3, KppId = ind_PCO
- etc

But let's say you don't want to archive all of those species, just PCO.  Then if you change your HISTORY.rc,
so that it just has:
```console
  ProdLoss.fields:            'Prod_CO                    ',
```
Then there is only 1 slot, and when S =1, KppId = ind_CO.

So you could use a similar loop to the one above in the Planeflight module to pick out POx.  But you would also need to make sure that `Prod_Ox` is being archived in HISTORY.rc, since that's where you'll need to take the value from.  Ditto for the other families.

Hope this helps!
