### ISSUE TITLE
[BUG/ISSUE] Methane molar mass

### ISSUE THREAD

**Issue by XueyingYu-1993** [geoschem/geos-chem#1312]
### Description of the problem
The current molar mass in GC is 16.05, while it should be 16.04.

### GEOS-Chem version
V13

**Comment by yantosca** [comment]
Thanks @XueyingYu-1993.  This can be updated in the species_database.yml file.  

I am also tagging @msulprizio because this will have implications for the methane simulations and related codes such as the Integrated Methane Inversion.  The change is small enough that it will cause differences when trying to compare to prior versions.

**Comment by msulprizio** [comment]
I believe this is a rounding error that came in with the [species database update](https://github.com/geoschem/geos-chem/commit/49e868af64a10406b5799de67041b390e6167dbb) to change all molecular weights to 2 decimal places. For hydrocarbons, this was computed by summing molecular weights of H (1.01 g/mol) and C (12.01 g/mol), so for CH4 computed this way we get 16.05 g/mol. You are correct though that the [actual value of CH4 is 16.0425 g/mol](https://webbook.nist.gov/cgi/cbook.cgi?ID=74-82-8), rounded to 16.04. We can correct this in 14.1.0.

**Comment by msulprizio** [comment]
This fix has now been merged into the dev/14.1.0 branch.
