### ISSUE TITLE
HTAPv3

### ISSUE THREAD

**Issue by deepangsu** [geoschem/geos-chem#1313]
Is the HEMCO_Config.rc provided by @msulprizio working fine to pull the HCOX_Volcano input files?

**Comment by deepangsu** [comment]
[runlog.txt](https://github.com/geoschem/geos-chem/files/9153979/runlog.txt)

**Comment by lizziel** [comment]
Try checking HEMCO.log to see if there is more information about the run problem. Could you confirm this issue is not about HTAPv3 (you titled this issue with that), and provide information we request from users who are asking questions on GitHub? See http://wiki.seas.harvard.edu/geos-chem/index.php/Submitting_GEOS-Chem_support_requests#What_do_I_need_to_include_in_my_support_request.3F.

**Comment by deepangsu** [comment]
Hi @lizziel, Thanks for your response. I might have something to do with HTAPv3.  I might have figured out something.

**Comment by LiamBindle** [comment]
@deepangsu Please include more information in issues. It's hard and time consuming to help without a paragraph describing what you're trying to do, what's happening, and log files. Just a note for future issues.
