### ISSUE TITLE
Is HNO3 uptake on SALA & SALC to form NIT and NITs being done twice?

### ISSUE THREAD

**Issue by msl3v** [geoschem/geos-chem#1320]
### Ask a question about GEOS-Chem:
I recently updated KPP/fullchem to include reactions previously computed in sulfate_mod.F90. This included the following reactions (as currently used in fullchem.eqn):
HNO3 + SALAAL = NIT
HNO3 + SALCAL = NITs
These form NIT and NITs but are intentionally limited by alkalinity.

It looks like ISORROPIA is also calculating NIT and NITs based on SALA & SALC abundance (though not titrating alkalinity).
So the question is: Are NIT and NITs being calculated twice in two very different ways? Or is the partitioning computed in ISORROPIA (using SALA and SALC) somehow justified?

**Comment by yantosca** [comment]
Am tagging the Aerosols WG co-chairs: @beckyalexander @theloniuspunk @wporter

**Comment by beckyalexander** [comment]
In the past, HNO3 uptake onto sea salt aerosol was calculated to titrate sea salt aerosol alkalinity in competition with SO2 uptake, and to form NITs. There was no effect on NIT because the HNO3/NIT partitioning was calculated in ISORROPIA. NITs is not in ISORROPIA because it is coarse mode, but I know that with the implementation of the Cly chemistry that there is some partitioning of HCl out of the coarse mode sea salt aerosol driven in part by HNO3 uptake. I need to familiarize myself with the new sulfur and alkalinity chemistry in KPP to figure out if this is being double counted. I'm working on this. Xuan Wang may know since it is related to Cly chemistry. There is also an improved calculation of NITs formation for nitrate aerosol photolysis that Prasad implemented, which is currently an optional feature.

**Comment by pkasibhatla** [comment]
I am not sure how things are currently implemented in GC. In my GC implementation (see  https://acp.copernicus.org/articles/18/11185/2018/) I replaced the alkalinity-limited uptake by a mass-transfer equation in which the driving force is the difference between ambient and equilibrium gas-phase HNO3 concentration, with the latter calculated by calling ISOROPIA.

**Comment by msl3v** [comment]
Thanks for the comments.
@beckyalexander: The alkalinity titration by HNO3 and SO2 is preserved in the KPP implementation. It looks like Xuan Wang (xnw?) added the SALA version of your original alkalinity titration, hence the addition of reaction
           HNO3 + SALAAL = NIT 
in the KPP reimplementaiton.

Currently, in isorropiaII_mod.F90, there's the code, 
          IF (N == 1) THEN
             ...
             Spc(id_NIT   )%Conc(I,J,L) = TNIT
             ...
          ELSE
             ...                                                                                                                                
             Spc(id_NITs  )%Conc(I,J,L) = &
                            Spc(id_NITs  )%Conc(I,J,L) * (1.0_fp-AlkR) + TNIT
             ...
          ENDIF
N loops over 1, for fine, and 2 for coarse sea salt aerosol. Neither SALAAL nor SALCAL are updated.

So it does appear that NIT & NITs are being updated in both ISORROPIA & KPP. I'm not familiar enough with ISORROPIA to understand how to proceed.

**Comment by beckyalexander** [comment]
I had a chance to investigate the alkalinity titration HNO3 + SALAAL = NIT. I think it is fine as is. ISORROPIA will repartition the HNO3/NIT so it doesn't matter if you form HNO3 or NIT. For example, N2O5 hydrolysis produces HNO3 in the model, not NIT. The point of HNO3 + SALAAL is to remove alkalinity. ISORROPIA will partition HNO3/NIT.

Because ISORROPIA doesn't handle the coarse mode, I do think we have to be careful not to double count the formation of NITs. However, I don't think we are double counting this. HNO3 + SALCAL = NITs forms NITs and depletes alkalinity. But just because the alkalinity has been titrated doesn't mean that HNO3 will not continue to partition onto coarse-mode sea salt aerosol as NITs. Alkalinity is calcium carbonate that acts as a buffer to maintain sea salt aerosol pH = 8. Once the alkalinity is titrated the pH is initially still high and acids can continue to partition onto the aerosol until the pH drops below a certain point. This is what the code by @pkasibhatla does.

In sum, I think this is OK as is.

**Comment by msl3v** [comment]
Great explanation. Thank you @beckyalexander and @pkasibhatla
