### ISSUE TITLE
[ISSUE] Potential typos on the "Species in GEOS-Chem" wiki page

### ISSUE THREAD

**Issue by LukeFakes** [geoschem/geos-chem#1324]
I've been looking at the [wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/Species_in_GEOS-Chem#S) for fine and coarse mode sea salt aerosol and chloride in sea salt (SALA, SALC, SALACL, SALCCL) and I'm not sure if there might be a couple of mistakes or I'm misunderstanding things.

- Molecular Weights for SALACCL and SALCAL. Should these be 35.45 (mass of Chloride) rather than 31.4, as in the `species_database.yml` file?
- The definition of Fine mode aerosols is 0.01-0.05 microns: Is that correct or should it be 0.01-0.5? 

I also have one question relating to PM2.5 composition. Coarse mode sea salt aerosol is defined as 0.5-8 microns, so why is it not included in the formula for PM2.5? 
`PM25 = ( NH4 + NIT  + SO4 ) * 1.10
     + BCPI 
     + BCPO 
     + ( OCPO + ( OCPI * 1.05 ) ) * (OM/OC ratio)  # OM/OC ratio = 2.1 by default
     + DST1 
     + DST2 * 0.30                                 # F. Yu suggests 30% of DST2 (Nov 2011); prior value was 38% of DST2
     + SALA * 1.86
     + SOA  * 1.05`

**Comment by yantosca** [comment]
Thanks for writing @LukeFakes.  

  1. There is a reason why SALACL and SALCAL are the MW of sea salt rather than chlorine but now I can't remember why. It may be because it is internally mixed.  Tagging @beckyalexander and @msl3v.
  2. Yes, SALA should be 0.1 - 0.5 and SALC is 0.5 - 8 um.  I'll fix that.
  3. We have used the PM25 definition provided to us by the Aerosols WG. Tagging @beckyalexander and @theloniuspunk.

Also note, a lot of the wiki doc hasn't been updated since 12.8.0.  We are in the process of migrating the user manuals to our ReadTheDocs pages for 14.0.0 (https://geos-chem.readthedocs.org).  We hope to be able to provide updated species documentation that is pegged to each GEOS-Chem version (perhaps by parsing the species database into a table or something,... it remains to be seen).

**Comment by theloniuspunk** [comment]
Not sure about #1. Maybe that's the average MW of the ions in sea-salt?

For coarse mode sea salt, where is it defined as 0.5-8 microns? Is that radius or diameter? I suspect it's radius, making diameter 1-16 um. Certainly 1 < 2.5, but I suspect that 1-2.5 um has a trivial fraction of the coarse-mode mass. I think that Fangqun's group was refining the fractions in this definition for sea-salt and dust using APM.

**Comment by yantosca** [comment]
@theloniuspunk The sea salt radius bin sizes are defined in `input.geos`.  Soon to be `geoschem_config.yml`.

**Comment by theloniuspunk** [comment]
Thanks, Bob. I think my rational holds as to why SALC is left out of the PM2.5 calculation (only a tiny fraction of this mode had Dp < 2.5 um), but I think Fangqun's updated calculation should help.

**Comment by LukeFakes** [comment]
Hi @yantosca, thanks for letting me know that had been updated. 

And thanks @theloniuspunk for giving further clarification

**Comment by yantosca** [comment]
I can close out this issue.  We now have the [species guide](https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/species-guide.html) at ReadTheDocs that link to the most recent species database files.
