### ISSUE TITLE
[QUESTION] Verifying wavelengths used for AOD in Planeflight and HISTORY.rc

### ISSUE THREAD

**Issue by chfite** [geoschem/geos-chem#1340]
I just want to verify my understanding of how the user-defined wavelengths are used for AOD in the model. I am wanting AOD output at two different wavelengths and it is my understanding that in `input.geos` I can just list the two wavelengths I want in the radiation menu like so:
 `
AOD Wavelength (nm)     : 532 500`

I am wanting to use the Planeflight diagnostic to sample AOD at 532 nm for instrument comparison. Looking at the planeflight code for AOD I see `IWVSELECT(2,1)` and `IWVSELECT(1,1)` referenced throughout. Am I correct to interpret that the first dimension being indexed (with 1 and 2) represents the wavelengths used for interpolating optical property information to the user-defined wavelength, and that the second dimension (which is always 1 in this code) is referencing the the _first_ wavelength input by the user (532 nm) in this case? Please correct me if this is wrong. I mostly just want to verify that Planeflight would sample based on the first AOD wavelength input.

Second, I am wanting to output hourly AOD at 500 nm in HISTORY.rc rather than 532 nm. It is my understanding that I would just need to change my desired output variables from `AODHygWL1_?HYG?` to `AODHygWL2_?HYG?`, for example, to sample at 500 nm? In this way I can get both of my desired gridded output at 500 nm and planeflight output at 532 nm. Thanks!

**Comment by yantosca** [comment]
Hi @chfite.  As is my understanding, the AOD wavelengths read from input.geos are used in the `CALC_AOD` routine in `GeosCore/fast_jx_mod.F90` ([see code here](https://github.com/geoschem/geos-chem/blob/7e51a0674aba638c8322fef493ac9251095e8cf4/GeosCore/fast_jx_mod.F90#L2668-L2910)).  This sets up the `IWVSELECT` array.

`IWVSELECT` is declared in `Headers/CMN_FJX_MOD.F90` as   

```F90
INTEGER :: IWVSELECT(2,3) !index of requested wavelengths
```
so I think the 2nd dimension is wavelength and the 1st dimension are the bounding wavelengths in the FAST-JX lookup table.  If `IWVSELECT(2,N) = IWVSELECT(1,N)` then you are on one of the FAST-JX wavelengths.  Otherwise FAST-JX has to interpolate your desired wavelength between the 2 bounding wavelengths in the lookup table.

I think the `planeflight_mod.F90` may be hardwired just to output one wavelength (as this is what we usually do for regular GEOS-Chem simulations).  You could maybe add code to planeflight_mod.F90 to handle the additional wavelength, it would go here:

```F90
             !---------------------------------------------------------------
             ! Column aerosol optical  depths [unitless]
             !---------------------------------------------------------------
             CASE ( 2001:2005 ) ! SULF, BLKC, ORGC, SALA, SALC

                ! Remove MISSING flag
                VARI(V) = 0e+0_fp

                ! Aerosol number
                N = PVAR(V) - 2000

                IF ( .not. LINTERP ) THEN
                   DO LL = 1, State_Grid%NZ
                      ! Accumulate
                      VARI(V) = VARI(V) + ODAER(I,J,LL,IWVSELECT(1,1),N)
                   ENDDO
                ELSE
                   DO LL = 1, State_Grid%NZ
                      ! Interpolated using angstrom exponent between
                      ! Closest available wavelengths
                      ! (coefs pre-calculated in CALC_AOD)
                      !catch any zero values before interpolation
                      IF ((ODAER(I,J,LL,IWVSELECT(2,1),N).GT.0).AND. &
                          (ODAER(I,J,LL,IWVSELECT(1,1),N).GT.0)) THEN
                         VARI(V) = VARI(V) + &
                           (ODAER(I,J,LL,IWVSELECT(2,1),N)*ACOEF_WV(1)**   &
                           (BCOEF_WV(1)*LOG(ODAER(I,J,LL,IWVSELECT(1,1),N)/&
                           ODAER(I,J,LL,IWVSELECT(2,1),N))))
                      ENDIF
                   ENDDO
                ENDIF
```
You might need to define the AOD wavelengths as a separate variable for `VARI(V)` and then have some way of associating that with the 2nd dimension index of `IWVSELECT`.

Also tagging @lizziel and @Jourdan-He for reference.  @lizziel is working on replacing FAST-JX with Cloud-J in GEOS-Chem (but that is a long-term work in progress).

**Comment by yantosca** [comment]
Closing out this issue
