### ISSUE TITLE
[QUESTION]How to get the Historical GCAP2.0 restart file to start the simulation ?

### ISSUE THREAD

**Issue by zhiweistu** [geoschem/geos-chem#1352]
### Ask a question about GEOS-Chem:
Dear GCAP2.0 developer,
My GC version is 13.4.1. I want to use the GCAP2.0 meteorology to run 2014-year-simulation(standard fullchem). It remind me I need GEOSChem.Restart.20140701_000z.nc4.
But I find there are only GCAP2.Restart.fullchem.20190101_0000z.nc4 and GCAP2.Restart.fullchem.20190701_0000z.nc4 in GCAP2_Restart. 
How can I get the GCAP2.Restart.fullchem.20140701_0000z.nc4 and GCAP2.Restart.fullchem.20140101_0000z.nc4?
Thanks for your help

**Comment by yantosca** [comment]
Thanks for writing @zhiweistu.  The restart files provided are only sample restarts that you can use to get your simulation up and running.  We don't provide an archive of restart files.

You can try editing the time in the restart file with the Climate Data Operators (cdo) so that the start date matches what you want.
```console
$ cdo settime,2014-07-01 GCAP2.Restart.fullchem.20190101_0000z.nc4 GCAP2.Restart.fullchem.20140101_0000z.nc4
$ cdo settime,2014-07-01 GCAP2.Restart.fullchem.20190701_0000z.nc4 GCAP2.Restart.fullchem.20140701_0000z.nc4
```
Note that you should spin up your simulation for at least 6 months to a year before starting a production simulation.

Also tagging @ltmurray and @Jourdan-He.

**Comment by zhiweistu** [comment]
Thanks@yantosca!
It means that if my run simulation start date is 2014-01-01, I should use GEOSChem.Restart.20130701_000z.nc4 to spin up 6 month. So I need use cdo to edit GCAP2.Restart.fullchem.20190701_0000z.nc4 to GCAP2.Restart.fullchem.20130701_0000z.nc4.
Thanks for your help again!

**Comment by yantosca** [comment]
Yes... I looked up the proper cdo command.  It should be:

```bash
cdo setreftime,2013-07-01,00:00:00 GCAP2.Restart.fullchem.20190701_0000z.nc4 GCAP2.Restart.fullchem.20130701_0000z.nc4
```
`cdo settime` only changes the time and `cdo setyear` only changes the year.  But `cdo setreftime` lets you change both at once.

**Comment by zhiweistu** [comment]
Thanks@yantosca, I used cdo setdate, it can successfully change the date. My questions solved.
Thanks for your helps again!@yantosca@ltmurray @Jourdan-He

**Comment by yantosca** [comment]
Thanks @zhiweistu.  I'll close out this issue now.
