### ISSUE TITLE
[QUESTION]questions about GCAP2.0 HEMCO Configure

### ISSUE THREAD

**Issue by zhiweistu** [geoschem/geos-chem#1355]
### Ask a question about GEOS-Chem:
Dear GEOSChem developer and GCAP2.0 developer,

My GC version is 13.4.1. I want to use GCAP2.0 to simulate sulfur dioxide, sulfate, etc. I am not sure which emissions data I should choose in HEMCO.Configure.rc. I want to ask you some questions. 

1.Is the default settings of emission inventory in GCAP2.0 complete? If I want to run sulfur simulation, Do I need to keep any more emission inventory on? (Such as GFED...)

2.I noticed the default settings in Merra2 and GCAP2.0 is different. For example, global inventory CEDS in Merra2 is on, but in GCAP2.0 is off. CMIP6 ANTHRO EMISSIONS / BOUNDARY CONDITIONS in Merra2 is off, but in GCAP2.0 is on. Why?

3.I found the simulation result is different when only keeping CEDS and keeping CEDS and CMIP6 ANTHRO EMISSIONS on. If I keep CEDS inventory on, does EDGARV43 and CMIP6 ANTHRO EMISSIONS / BOUNDARY CONDITIONS in HEMCO.Configure.rc have to be off and why?
I would be very grateful if you could give me some advice.
Best Regards,

[HEMCO_Config_merra2.txt](https://github.com/geoschem/geos-chem/files/9395763/HEMCO_Config_merra2.txt)
[HEMCO_Config_gcap2.txt](https://github.com/geoschem/geos-chem/files/9395765/HEMCO_Config_gcap2.txt)

**Comment by yantosca** [comment]
Thanks for writing @zhiweistu,  I believe the GCAP2 simulations need to use different emissions than runs with GEOS-FP or MERRA2.  I am tagging @ltmurray who can probably give you a better answer on this than I can.

Also tagging @Jourdan-He

**Comment by msulprizio** [comment]
Hi @zhiweistu. If you use `createRunDir.sh` to set up your run directory and select "GISS ModelE2.1 (GCAP 2.0)" when prompted for your meteorology choice then your run directory will automatically be set up with the recommended emissions to use for GCAP 2.0 simulations. You are correct in that the default emissions differ from those selected when choosing MERRA-2 or GEOS-FP meteorology and that is intentional. The emissions fields used for GCAP 2.0 simulations are for extended years to allow for historical and future scenarios.

Please see the GCAP 2.0 reference paper for details: https://gmd.copernicus.org/articles/14/5789/2021/gmd-14-5789-2021.html.

**Comment by ltmurray** [comment]
Thanks, @msulprizio, that is correct. The default inventories for GCAP 2.0 are those that are consistent with the CMIP model design; the default MERRA2 and GEOS-FP emissions are those recommended for the present-day by the GEOS-Chem Steering Committee. @zhiweistu, please make sure that you are using the most recent version of createRunDir.sh that addresses issue #1323.

**Comment by zhiweistu** [comment]
Thanks for your detailed answers@ltmurray, @msulprizio,@yantosca. I benefited a lot. My issue solved. 
Thanks again!
