### ISSUE TITLE
[QUESTION] Adding Met_H GEOS-FP variable to registry

### ISSUE THREAD

**Issue by arianatribby** [geoschem/geos-chem#1370]
Hi! 

I am trying to get Met_H as an output during a full standard chemistry run using GEOS-FP meteorology. The "H" variable (geopotential height, in m) is not available in the standard output but it is a product of GEOS-FP meteorology https://gmao.gsfc.nasa.gov/GMAO_products/documents/GEOS-5_Filespec_Glossary.pdf . (Note this is different than the variable already available, PHIS, which doesn't have a z-coordinate.)

I add "Met_H" to the SpeciesConc Collection in HISTORY.rc. I edited state_met_mod.F90 by adding similar blocks of code that are present for other 3D variables for the H variable (I've attached the F90 file). Then, I recompiled and the simulation ran with no errors. The H variable is present in the GEOSChem.SpeciesConc.nc file, however, the values are all zero. Did I miss something? Thanks! 

## Files of interest
state_met_mod.F90: [statemetmod_edit.txt](https://github.com/geoschem/geos-chem/files/9523021/statemetmod_edit.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/9523032/HEMCO_Config.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/9523037/HISTORY.rc.txt)
[run-2.log.txt](https://github.com/geoschem/geos-chem/files/9523100/run-2.log.txt)

## Steps to reproduce run on AWS

1) AMI ami-0491da4eeba0fe986 . 
2) c5x4 large 
3) Install code and create run directory

```
mkdir ~/GC  
cd ~/GC
git clone https://github.com/geoschem/GCClassic.git Code.GC
cd Code.GC
git submodule update --init --recursive
cd ~/GC/Code.GC/run
./createRunDir.sh # 4x5 resolution, geosfp

cd ~/GC/rundirs/YOUR_RUN_DIRECTORY
cd build/
cmake ../CodeDir -DRUNDIR=..
make -j
make install
cd ..
```

4) Edit input.geos , time period is 20160601-20160602
5) Dry Run: 

```
./gcclassic --dryrun | tee log.dryrun
source activate geo
./download_data.py log.dryrun --aws
conda deactivate
```
11) Edit HISTORY.rc  
12) Edit F90 file at ~/GC/rundirs/gc_4x5_geosfp_fullchem/CodeDir/src/GEOS-Chem/Headers/state_met_mod.F90
13) cd run ~/GC/rundirs/YOUR_RUN_DIRECTORY/build
```
cmake ../CodeDir -DRUNDIR=..
make -j
make install
cd ..
```
12) Run: 

```
tmux
./gcclassic | tee run.log
Type `Ctrl + b`, and then type `d`, to detach from the tmux session

tail -f run.log  # display the output message dynamically
Type `Ctrl + c` to quit the message display. Won't affect model simulation.
```

**Comment by lizziel** [comment]
Hi @arianatribby, thanks for reaching out about this.

You are seeing zeros in the output since `State_Met%H` was not set after initialization to zero. To output a new GEOS-FP field as a new `State_Met` field you would also need to (1) read the GEOS-FP data into the model, and (2) populate the new `State_Met` field with those values. The data to read would be specified for GC-Classic in file `HEMCO_Config.rc.gmao_metfields` which is included in `HEMCO_Config.rc` at run-time. To populate `State_Met%H` with the input values in GC-Classic you would need to add the GEOS-FP field to file `GeosCore/flexgrid_read_mod.F90`. 

All that being said, I believe the GEOS-Chem pre-processed input data does not contain field `H` (@YanshunLi-washu, correct me if I am wrong on that). If you need geopotential height per level you could either read in the native resolution file retrieved from GMAO or simply compute it using other met-fields.

**Comment by lizziel** [comment]
Hi @arianatribby, is this issue resolved?

**Comment by arianatribby** [comment]
Hi @lizziel , yes thanks. We decided to calculate it using other met variables.

**Comment by yantosca** [comment]
Thanks @arianatribby.  We can close out this issue now.
