### ISSUE TITLE
[BUG/ISSUE] Excessive fall velocity

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1383]
### Ask a question about GEOS-Chem:
GEOS-Chem.14.0.0 run 0.25x0.3125 an error. I want to know how to solve
![微信截图_20220919183044](https://user-images.githubusercontent.com/51811371/190999285-33bac002-e9d5-47b0-9bad-6086650096da.png)

**Comment by lizziel** [comment]
Switching to 13.4.1 won't avoid the bug since it was introduced in 13.4.0. However, the problem should only impact the global simulation runs since the nested runs use a different pressure fixer. I wonder if the error you are getting has to do with starting on a day towards the end of the month. Did you spin up your run to get restart files for that day? The message indicates no HEMCO restart file was found.

**Comment by yangning-code** [comment]
Thank you, I try @lizziel
