### ISSUE TITLE
[BUG/ISSUE] Sulfate production in size-resolved cloud droplets

### ISSUE THREAD

**Issue by beckyalexander** [geoschem/geos-chem#1429]
### What institution are you from?
University of Washington

### Description of the problem
The in-cloud sulfate production rate is enhanced over the oceans under certain conditions to account for heterogeneity in cloud droplet size and thus pH, the latter of which is non-linear. The enhanced in-cloud sulfate production (calculated in the subroutine fullchem_HetDropChem) attempts to resolve a model underestimate in sulfite (SO32-) due to an underestimate in cloud pH when assuming that cloud drop size and pH are homogeneous. Since SO32- + O3 is fast, the enhanced sulfate production is supposed to be attributed to S(IV) oxidation by ozone, but in the current version of the model (13.4.1) it is mistakenly attributed to S(IV) oxidation by O2 catalyzed by transition metals. 

### Description of troubleshooting performed
I fixed the problem in the code and it had negligible changes for O3 and SO4. A diff figure for a one-month simulation (July 2019) is attached.
[single_level.pdf](https://github.com/geoschem/geos-chem/files/9747931/single_level.pdf)

### GEOS-Chem version
13.4.1

### Description of modifications
There is a change to one line of code each in fullchem_mod.F90 and in fullchem_SulfurChemFuncs.F90. I've created a patch file. Please advise on how to get this patch file to you as it won't let me upload it here.

### Log files
- Build log (if applicable):
- Run logs (if applicable):
- Run script (if applicable):

### Software versions
- CMake version:
- Compilers (Intel or GNU, and version):
- NetCDF version:

**Comment by yantosca** [comment]
Thanks @beckyalexander.  You should be able to upload the patch file here if you add the `.txt` extension to the file.

**Comment by beckyalexander** [comment]
[my-patch-file.txt](https://github.com/geoschem/geos-chem/files/9758480/my-patch-file.txt)
This patch file also contains the pressure fixer fix and the HOCl/HOBr + SO2 fix in fullchem.eqn previously reported. The relevant changes to this bug are in fullchem_mod.F90 and fullchem_SulfurChemFuncs.F90 (one line of code in each).

**Comment by yantosca** [comment]
Hi @beckyalexander, thanks for the patch.  I think only patches 4/5 and 5/5 apply for this fix.  We typically bring in updates one at a time so that we can benchmark them separately.  The pressure fixer has already been added and the HOCl/HOBr + SO2 updates will be added in a separate pull request.

```console
From af628359936179565c3787436d1c8b9ac8ef079f Mon Sep 17 00:00:00 2001
From: Becky Alexander <beckya@atmos.washington.edu>
Date: Thu, 6 Oct 2022 15:00:05 -0700
Subject: [PATCH 4/5] Added a comment for testing

---
 KPP/fullchem/fullchem_SulfurChemFuncs.F90 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/KPP/fullchem/fullchem_SulfurChemFuncs.F90 b/KPP/fullchem/fullchem_SulfurChemFuncs.F90
index 355831d8d..03f26b309 100644
--- a/KPP/fullchem/fullchem_SulfurChemFuncs.F90
+++ b/KPP/fullchem/fullchem_SulfurChemFuncs.F90
@@ -746,7 +746,7 @@ CONTAINS
        ! additional sulfate production that can be
        ! attributed to ozone [ug/m3/timestep]
        ! Don't allow SR to be negative
-       SR = MAX( ( DSVI - B ), 0.0_dp )
+       SR = MAX( ( DSVI - B ), 0.0_dp ) ! I need to change this
 
        ! Skip further computation if SR = 0
        IF ( SR > 0.0_dp ) THEN
-- 
2.20.1


From 48a01233784f50342baffd111374127c8b0d7678 Mon Sep 17 00:00:00 2001
From: Becky Alexander <beckya@atmos.washington.edu>
Date: Thu, 6 Oct 2022 15:36:41 -0700
Subject: [PATCH 5/5] Changed SR to go to enhancing the S(IV)+O3 oxidation rate
 instead of the S(IV) + O2 oxidation rate
```git
---
 GeosCore/fullchem_mod.F90                 | 4 ++--
 KPP/fullchem/fullchem_SulfurChemFuncs.F90 | 2 +-
 2 files changed, 3 insertions(+), 3 deletions(-)

diff --git a/GeosCore/fullchem_mod.F90 b/GeosCore/fullchem_mod.F90
index 75c1ec613..19960f490 100644
--- a/GeosCore/fullchem_mod.F90
+++ b/GeosCore/fullchem_mod.F90
@@ -949,9 +949,9 @@ CONTAINS
                                         State_Met = State_Met,               &
                                         State_Chm = State_Chm               )
 
-             ! Add result as an enhancement to O2 metal catalysis rate
+             ! Add result as an enhancement to O3 rate
              ! as a 1st order reaction
-             K_CLD(3) = K_CLD(3) + SR
+             K_CLD(2) = K_CLD(2) + SR
           ENDIF
 
           ! Stop timer
diff --git a/KPP/fullchem/fullchem_SulfurChemFuncs.F90 b/KPP/fullchem/fullchem_SulfurChemFuncs.F90
index 03f26b309..54cdceed7 100644
--- a/KPP/fullchem/fullchem_SulfurChemFuncs.F90
+++ b/KPP/fullchem/fullchem_SulfurChemFuncs.F90
@@ -757,7 +757,7 @@ CONTAINS
           ! Don't produce more SO4 than SO2 available after AQCHEM_SO2
           ! -- SR is dSO4/timestep (v/v) continue onvert
           !    to 1st order rate
-          SR = MIN( SR, SO2 / 1.0e12_dp ) / ( C(ind_SO2) * CVF * DT )
+          SR = MIN( SR, SO2 / 1.0e12_dp ) / ( C(ind_SO2) * C(ind_O3) * CVF * DT )
        ENDIF
     ENDIF
 
-- 
2.20.1
```

**Comment by yantosca** [comment]
Also we plan on rebuilding mechanisms with KPP 3.0.0 in GEOS-Chem 14.1.0.

**Comment by beckyalexander** [comment]
Hi Bob,
Yes, it is those last two changes that are relevant for this patch. I'm new to GIT and am still trying to understand it. My view of my changes to this branch on gitk only shows those two changes, but when I made a patch file it brought in changes from two other branches as well. 
Thanks,
Becky

**Comment by yantosca** [comment]
No worries Becky!  I've opened PR #1434 with just those 2 commtis off of 13.4.1.  We'll get this into 14.1.0.

**Comment by msulprizio** [comment]
These changes are no longer needed as they are superseded by the updates in https://github.com/geoschem/geos-chem/pull/1630.
