### ISSUE TITLE
[ISSUE] Add 09/2022 GEOS-FP met fields to geoschemdata.wustl.edu

### ISSUE THREAD

**Issue by eamarais** [geoschem/geos-chem#1455]
When will the 09/2022 GEOS-FP met fields be added to http://geoschemdata.wustl.edu/?

**Comment by yantosca** [comment]
I will let @Jourdan-He reply.  I think there is a delay of a few weeks before data is available at WashU.

**Comment by Jourdan-He** [comment]
Hi @eamarais , @SaptSinha is working on regridding the GEOS-FP datasets, he mentioned to me that he planned to upload in November.

**Comment by eamarais** [comment]
Hi @Jourdan-He. Thanks for the update. I appreciate this is a lot to ask, but is there any chance    chance it could be earlier than that? We were working under the assumption that this is a relatively automated process and that the data typically appears on WashU a few days after the end of the month.

**Comment by Jourdan-He** [comment]
Hi @eamarais , I asked @SaptSinha last week and he replied he would try and see if he could upload the data earlier. I am not sure about his current status, it would be best for @SaptSinha to reply on this.

**Comment by SaptSinha** [comment]
Hello @eamarais ,


Thanks to you and @Jourdan-He for reaching out regarding the re-gridding and uploading of GEOS-FP & MERRA2 datasets.

I recently took over this responsibility from Yanshun and have been working on this for a while. The reason for the delay is because I have been unable to obtain permission from the nasa.gov servers to download the raw data, which I can then re-grid and upload. This is why it has been taking a while as I am encountering accessibility restrictions (attached sample screenshot).

Although I am preparing for my relocation from India to USA in the upcoming week, and am officially not working till Nov 13 (WashU start date being Nov 14), I will continue working on this and if I am authenticated by the nasa.gov servers, I will regrid and upload the following datasets as per the order below:
-- MERRA2 202208, GEOS-FP 202209
-- MERRA2 202209, GEOS-FP 202210
-- MERRA2 202106
-- MERRA2 202107
-- MERRA2 202108
-- MERRA2 202109

I will also attempt to send you an update on the status of uploading the processed data via this thread. Please also feel free to reach out directly to me via sinha.s@wustl.edu (preferred) or saptarss@alumni.cmu.edu if there is anything else I can assist you with.


Sincerely,
Saptarshi Sinha
![Capture](https://user-images.githubusercontent.com/70730479/199983739-90f0e92d-775d-45e1-9475-8a0810f7a4b6.JPG)

**Comment by eamarais** [comment]
Thanks for the update @SaptSinha. Let me know when you have these processed and I'll download these to our local servers.

**Comment by SaptSinha** [comment]
Hello @eamarais, thank you for reaching out regarding this issue.

I just wanted to let you and other community members know that the processing of all the GEOS-FP datasets that were made available for this year are now complete. You can obtain them from: http://geoschemdata.wustl.edu/ExtData/GEOS_0.25x0.3125/GEOS_FP/2022/

This however, excludes the dataset for December 2022 that will be made available in the first week of January 2023 as far as I know. Once it is available, I will make sure to start processing it right away.

I will now start the processing of the MERRA2 datasets and am closing this issue. Please do not hesitate to open another issue if there are any other aspects regarding the GEOS-FP MetFields datasets that I can assist you with.

Thank you very much for your patience and for raising this issue to me.
