### ISSUE TITLE
[BUG/ISSUE] Could not find DQRLSAN in HEMCO data list!

### ISSUE THREAD

**Issue by croy64** [geoschem/geos-chem#1497]
### Description of the problem
I am running GC 14.0.0 to do a global 4x5 fullchem simulation for 20190701 - 20190703. After a dry run, I have downloaded the relevant input files. However, I got the following error.
While running the GEOS-Chem full chemistry simulation, I am getting the following error:

```console
GEOS-CHEM ERROR: Could not find DQRLSAN in HEMCO data list!
STOP at GET_MET_3D (get_met_mod.F90)
===============================================================================
===============================================================================
GEOS-CHEM ERROR: Could not find DQRCU in HEMCO data list!
     - Found all A3dyn  met fields for 2019/07/01 01:30
STOP at GET_MET_3D (get_met_mod.F90)
========================================================
```

**Comment by yantosca** [comment]
Thanks for writing @croy64.  Were you able to do a [dry-run simulation](https://geos-chem.readthedocs.io/en/stable/gcc-guide/04-data/dry-run.html) or otherwise [download the met data](https://geos-chem.readthedocs.io/en/stable/gcc-guide/04-data/download-data.html) to disk?  It could be that the A3dyn field is missing from your ExtData path and that a re-download will fix this issue.

**Comment by yantosca** [comment]
Closing out this issue.  If you are still having problems please open a new issue.

**Comment by yantosca** [comment]
In [netcdf-scripts v0.15](https://github.com/geoschem/netcdf-scripts/releases/tag/v0.1.5), we have added more error checks in order to identify issues that make a netCDF file unreadable by GCHP.  We can now close out this issue.
