### ISSUE TITLE
[QUESTION] Nested-grid questions

### ISSUE THREAD

**Issue by psadavarte** [geoschem/geos-chem#1510]
### Ask a question about GEOS-Chem:
I am new to GEOS-Chem and with the help of documentation, I successfully ran the GEOS-Chem model (classic version). For my study, I would like to know two things:
1) How to choose 0.25 deg x 0.3125 deg resolution of the model? The geos-chem website that provides support for creating the run directory shows three possible resolutions: 4 x 5 deg, 2 x 2.5 deg and 0.5 x 0.625 deg? 
2) How to select nested grids? For eg, I want to have a resolution of 0.25 x 0.3125 deg over US and 4 x 5 deg elsewhere?

Any help on the above two queries is highly appreciated.

**Comment by yantosca** [comment]
Thanks for writing @psadavarte. 

> 1. How to choose 0.25 deg x 0.3125 deg resolution of the model? The geos-chem website that provides support for creating the run directory shows three possible resolutions: 4 x 5 deg, 2 x 2.5 deg and 0.5 x 0.625 deg?

If you select the GEOS-FP meteorology, you will have an option to select 0.25 x 0.3125 met fields. This is because the native resolution of the GEOS-FP met is 0.25 x 0.3125 but the native resolution of the MERRA-2 met is 0.5 x 0.625.

> 2. How to select nested grids? For eg, I want to have a resolution of 0.25 x 0.3125 deg over US and 4 x 5 deg elsewhere?

To run the nested-grid simulation, you need to create 2 run directories: one for 0.25 x 0.3125 degrees for the NA grid, and one at 4x5 degrees for the global grid.  You will run the 4x5 simulation first, to create boundary conditions.  Then you will use the boundary conditions as input to your 0.25 x 0.3125 simulation.

**Comment by yantosca** [comment]
You might find this presentation useful: [Getting started with GEOS-Chem](https://geos-chem.seas.harvard.edu/files/acmg-geos/files/igc10_clinic_getting_started_with_geos-chem.pdf)

**Comment by psadavarte** [comment]
Awesome!! Thanks a lot for your swift response Bob.

**Comment by yantosca** [comment]
Thanks @psadavarte.  I'll close out this issue now.  Feel free to open a new issue if you are still having problems.
