### ISSUE TITLE
How to speed up simulation？

### ISSUE THREAD

**Issue by xuexb1230** [geoschem/geos-chem#1514]
I want to use GEOS-Chem gcclassic at 0.5*0.625 resolution. Since I need to run it for a long time, I wonder if it supports multiple nodes?

**Comment by yantosca** [comment]
Thanks for writing @xuexb1230.  GEOS-Chem Classic can only be run on a single computational node due to the fact that it uses OpenMP parallelization (which is shared-memory parallelization).

However, we would invite you to look at using GCHP if you wish to run on multiple nodes.  You could use a stretched-grid simulation to increase the resolution over an area of interest.  See our GCHP manual at https://gchp.readthedocs.io.

**Comment by xuexb1230** [comment]
Thanks!  :)
