### ISSUE TITLE
[QUESTION] Is it necessary to update MEGAN isoprene emission factors (AEF)

### ISSUE THREAD

**Issue by dxy8413** [geoschem/geos-chem#1535]
### Ask a question about GEOS-Chem:
Dear Bob,

I noticed that the online MEGAN would apply annual emission factor (AEF) for some species (e.g., isoprene, beta-pinene) from this DEFAULT file "MEGAN/v2020-02/MEGAN2.1_EF.geos.025x03125.nc". I made a similar file by using the standard emission factor (Table 2 in Guenther et al., 2012, GMD) and the MODIS PFT (mapped from MCD12Q1 products to CLM defined categories), but found there is large difference between the DEFAULT and mine. I assume the difference was mainly caused by PFT data, but couldn't find more information regarding the PFT data used to generate the DEFAULT AEF file. Is it necessary to update the DEFAULT AEF file so it can represent the annual changes of PFT ?

Attached is the figure showing the difference between the DEFAULT AEF file (named as "ORIG") and mine (named as "2003" and "2019" for correponding years).
![AEF update](https://user-images.githubusercontent.com/48503084/204201821-0582b994-117f-4df2-9eb5-59e58fa669af.jpg)

Thanks for your time and help.

Best,

Xinyi

**Comment by yantosca** [comment]
Thanks for writing @dxy8413.  This is a science question, and as such, I would refer you to the Emissions and Surface-Atmosphere Exchange Working Groups. Tagging @jgeddes85 @cdholmes @dylanbm @amospktai @eamarais @jaegle.

Also tagging @Jourdan-He and @SaptSinha for reference

**Comment by jgeddes85** [comment]
If I understand @dxy8413's comment correctly, then I would agree that the likely culprit is the underlying maps of PFT data used in calculating the base emission factor maps -- although those differences seem pretty extreme (to my eye) so it may be worth investigating further. 

In any case, as far as I know, the base emission factor maps are not updated frequently for GEOS-Chem (i.e., PFT distribution is highly static). I worked on a solution to this in https://doi.org/10.5194/acp-16-2323-2016, but alas our module didn't make it into a public release of GEOS-Chem and the model architecture has significantly advanced so that updating it now would be a lot of effort.

The comment/question is well taken. The Surface-Atmosphere Exchange working group is very interested in increasing the temporal frequency of updates to land descriptions for GEOS-Chem, which would include PFT distributions and LAI. In the meantime, I would encourage some additional sleuthing into the source/documentation of the base emission factor maps currently used in the most recent GEOS-Chem releases. Please keep an eye out for follow up, now that we know you have interests in this topic, @dxy8413!

**Comment by dylanbm** [comment]
Hi all: Yes, the MEGAN implementation uses pre-computed AEF maps for some VOCs while for other species it computes the EFs online based on the CLM PFTs. For better-characterized species like isoprene, the pre-computed AEF maps that come as part of the MEGAN distribution incorporate more resolved information (e.g. plant species-specific EFs) than can be accommodated by the coarse CLM PFTs. When I updated MEGAN in GC the decision of which VOCs used precomputed AEFs and which derived the EFs online was made based on recommendations from the MEGAN PI Alex Guenther. However users are free to modify the approach for their own purposes. The online EF derivation from PFTs allows the benefit of incorporating alternative land cover data.

**Comment by dxy8413** [comment]
Dear Bo, Jeff, and Dylan,

Thanks for the prompt replies, they are very helpful and clear. 

I have one more question: what is the PFT data and emission factor utilized to generate the pre-computed AEF map? With this information I might be able to examine why the difference shown in above figure was so big, as it might be either due to the temporal changes of PFT or due to the updates of standard emission factors. The wiki suggested the document by Mike Barkley may have it described but the link is invalid now: http://acmg.seas.harvard.edu/geos/wiki_docs/emissions/megan.pdf

It's good to know the Surface-Atmosphere Exchange working group is interested in this issue. I will proceed with my testruns and update the results once they are available. 

Best,

Xinyi

**Comment by dylanbm** [comment]
The precomputed AEF maps are not something we create, they are provided as part of the MEGAN distro. To get the underlying data I expect you'd need to reach out to them.

**Comment by dxy8413** [comment]
> The precomputed AEF maps are not something we create, they are provided as part of the MEGAN distro. To get the underlying data I expect you'd need to reach out to them.

@dylanbm Thanks a lot for this information ! I have one more quick question, the impact of soil moisture on isoprene is not considered in the model, is it for the same reason as recommended by the MEGAN distro ?

**Comment by dylanbm** [comment]
Hi! Sorry that I lost track of this question. I’m away from my computer and can’t check this immediately but I believe that’s right. As I recall we also decided that since this was quite an uncertain term and ecosystem dependent to leave it off by default. It may be worth revisiting at this point whether that is still appropriate. For your own research purposes you are free to use the soil moisture adjustment or not, of course.

**Comment by yantosca** [comment]
Closing out this issue.  Feel free to open a new issue if you are still having problems.
