### ISSUE TITLE
Ask questions about GEOS-Chem Classic

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#1543]
I am new to GEOS-Chem and with the help of documentation, I successfully ran the GEOS-Chem Classic  coupled with RRTMG model(using full chemistry run directory ). Then I have two questions:
1. What methods can be used to simulate the concentration of individual aerosol components? For example, I want to simulate the concentration of black carbon alone. I tried to turn off the other species(eg. dust,sea_salt ) in the geoschem_config file for simulation, but the program does not work properly.I'm not quite sure what operations need to be performed. 
![image](https://user-images.githubusercontent.com/115625689/205000233-f0f7eb0d-4178-48c6-ab55-a2405149e1f3.png)
2. Further, if I want to obtain the direct radiation effect of black carbon, what modifications should be made to the RRTMG model ?
Any help on the above  queries is highly appreciated. Extremely grateful!

**Comment by yantosca** [comment]
Thanks for writing @yangbyy.  We would recommend using the aerosol-only simulation, as then you can edit the configuration files to remove species that you don't want.  Because the fullchem simulation uses KPP, removing species from the `geoschem_config.yml` file would lead to inconsistencies with the KPP mechanism.  So we don't recommend doing that.

Also, we are not able to answer your question about RRTMG because we are not experts in aerosol chemistry.  That question should be directed to the Aerosols Working Group.  Tagging @beckyalexander @theloniuspunk @wporter

Also tagging @Jourdan-He and @SaptSinha for reference

**Comment by yangbyy** [comment]
Thanks for your reply! I will try using the aerosol-only simulation. Thanks again!
