### ISSUE TITLE
GEOS-Chem_nested grid

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#1558]
### Ask a question about GEOS-Chem:
Hi, all!
I am new to GEOS-Chem and with the help of documentation, I successfully ran the GEOS-Chem Classic coupled with RRTMG model(using full chemistry run directory ). Then I'm wondering if I choose nested grids, then 

- how long should a global simulation run? Is 3 hours all right?

Extremely grateful!

**Comment by yantosca** [comment]
Thanks for writing @yangbyy.  The length of your run will depend on the type of science you will be doing.  Most users run GEOS-Chem for one or more years (splitting up the run into e.g. monthly intervals).

It is OK to use a 3-hr interval (10800 seconds) for the `radiation_timestep` setting in `geoschem_config.yml`.  This is because RRTMG is computationally expensive and thus if it were to run on every timestep your simulation would take a long time.

**Comment by yantosca** [comment]
@yangbyy: Is your issue solved?

**Comment by yantosca** [comment]
Closing out this issue.
