### ISSUE TITLE
[QUESTION] Running GEOS-Chem TOMAS version 12.9.3

### ISSUE THREAD

**Issue by bzhang419** [geoschem/geos-chem#1568]
Hi, I ran into problems when using GEOS-Chem TOMAS version 12.9.3. If I understand correctly, in the SpeciesConc output, the unit of the bulk aerosol species and the unit of the size-resolved aerosol species are all mol mol-1 dry air, so I expect the amount for the same species from two outputs are the same (For example, SpeciesConc_SO4 = SpeciesConc_SF1 + SpeciesConc_SF2+...+SpeciesConcSF15). Is this correct? 
But in my results, the amount from the size-resolved species output is ~1e5 lower. And if I run with several different emission inventories, the amount from SpeciesConc_SO4 is different in different simulations, the amount from SpeciesConc_SF1-SpeciesConc_SF15 are exactly the same. I have checked the HEMCO Diagnostic file and confirmed emissions are applied to my simulations. Is this because I did not set something correctly? Attached is my input.geos and HEMCO_Config.rc files.
Thank you!

[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/10260511/HEMCO_Config.rc.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/10260512/input.geos.txt)

**Comment by yantosca** [comment]
Thanks for writing @bzhang419.  I am tagging @BettyCroft @theloniuspunk and @Jourdan-He who have been working with the TOMAS code.

NOTE: We are in the process of bringing TOMAS into a GEOS-Chem 14 version.  There are still some bugs to iron out.

**Comment by BettyCroft** [comment]
Hi @bzhang419 and @yantosca - Thanks for your message. Sounds like the secondary sulfate production rates are not being passed correctly to TOMAS in your simulation. TOMAS needs to use the ND65 diagnostic in v12.9.3. Looks like that is switched on in your input.geos file. My out-of-the-box input.geos for that version had a setting of 72 levels for ND65, whereas your file has 47 - not sure if that would help. Did you also compile with the flag -DBPCH_DIAG=y? 

As you mentioned, the sum of the TOMAS sulfate tracers should be about equal to the bulk simulation's SO4 - not lower by 1e5. Was that difference found in the surface layer? The TOMAS runlog usually prints out a debugging diagnostic for TOMAS' H2SO4RATE - what values does that have for your simulation? This rate is gas-phase sulfate production rate that TOMAS is using. You could also print out the values for PSO4_SO2AQ in sulfate_mod.F90 to check what TOMAS is using for the aqueous sulfate production rates in your simulation. That may help to identify where the problem is occurring. @theloniuspunk and @Jourdan-He may also have suggestions. We are working on sulfate-related updates for v14 that should make TOMAS less susceptible to such errors.

**Comment by bzhang419** [comment]
> Hi @bzhang419 and @yantosca - Thanks for your message. Sounds like the secondary sulfate production rates are not being passed correctly to TOMAS in your simulation. TOMAS needs to use the ND65 diagnostic in v12.9.3. Looks like that is switched on in your input.geos file. My out-of-the-box input.geos for that version had a setting of 72 levels for ND65, whereas your file has 47 - not sure if that would help. Did you also compile with the flag -DBPCH_DIAG=y?
> 
> As you mentioned, the sum of the TOMAS sulfate tracers should be about equal to the bulk simulation's SO4 - not lower by 1e5. Was that difference found in the surface layer? The TOMAS runlog usually prints out a debugging diagnostic for TOMAS' H2SO4RATE - what values does that have for your simulation? This rate is gas-phase sulfate production rate that TOMAS is using. You could also print out the values for PSO4_SO2AQ in sulfate_mod.F90 to check what TOMAS is using for the aqueous sulfate production rates in your simulation. That may help to identify where the problem is occurring. @theloniuspunk and @Jourdan-He may also have suggestions. We are working on sulfate-related updates for v14 that should make TOMAS less susceptible to such errors.

Dear Betty, thanks for your reply. I did compile with the flag -DBPCH_DIAG=y. Below is my compile log.
```
LAST BUILD INFORMATION:
  CODE_DIR     : ./CodeDir
  CODE_BRANCH  : 
  LAST_COMMIT  : 
  COMMIT_DATE  : 
  VERSION      : 12.9.3
  VERSION_TAG  : GC_12.9.3
  TRACEBACK    : y
  BOUNDS       : n
  DEBUG        : n
  FPE          : n
  OMP          : y
  CHEM         : Tropchem
  TOMAS12      : n
  TOMAS15      : yes
  TOMAS30      : n
  TOMAS40      : n
  APM          : /usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/intel-parallel-studio-cluster.2020.4-5mxdw276vo2p6wtdkoaghj5h2zkmozjt/advisor_2020.3.0.607294/perfmodels
  RRTMG        : n
  TAU_PROF     : n
  BPCH_DIAG    : y
  COMPILER     : ifort 19.1.3.304
  Datetime     : 2022/12/16 23:40
```
I checked the values in the surface layer and the values are still 1e5 lower. Also, not just sulfate, the TOMAS tracers of all other species are much lower compared with the bulk results. When I check my runlog file, no TOMAS debug outputs (such as TOMAS' H2SO4RATE) is printed. The content of my runlog file is almost identical to a standard GEOS-Chem simulation runlog file. Seems like TOMAS did not work in my simulations.

**Comment by theloniuspunk** [comment]
Just want to confirm that you compiled with the TOMAS flag as well?

**Comment by bzhang419** [comment]
@theloniuspunk @BettyCroft Thanks for your reply, now the issue has been solved. I added the TOMAS flag when compiling for the first time but it seems like the TOMAS flag did not work. I recompiled and now it works.

**Comment by theloniuspunk** [comment]
great!
