### ISSUE TITLE
[QUESTION] Restart file issues for ModelE2.1-CMIP6 in 2040

### ISSUE THREAD

**Issue by jiaying002** [geoschem/geos-chem#1578]
Happy New Year!

I have three questions here:
1. I am wondering how I can get a 2040 restart file for ModelE2.1. I found the GCAP2.0_restart file, but it ends on 20190701. (http://atmos.earth.rochester.edu/input/gc/ExtData/GCAP2_RESTARTS/) So, I used the 20200101 restart file from the Harvard database and changed the time stamp to 2040, but I am not sure if it is okay. If it is not, woule you please tell me what I should do?
2. I noticed that the user should spin up the restart file (https://geos-chem.readthedocs.io/en/latest/gcc-guide/04-data/restart-files-gc.html). I am wondering how I can spin up if I want to start the simulation from 20400101. 
3. When I ran the simulation for 20400101 to 20400102 in ModelE2.1 SSP119 using the 20200101 restart file (changed the time stamp to 20400101), I got no error, but the simulation ran for 1 hour and stopped here:
![image](https://user-images.githubusercontent.com/113654537/210763822-88b7da1f-51c7-4c97-9825-514fa316f296.png)
I am wondering is there any thing wrong? (Attached the files that maybe useful)
[GC.log](https://github.com/geoschem/geos-chem/files/10351594/GC.log)
[geoschem_config.yml.txt](https://github.com/geoschem/geos-chem/files/10351603/geoschem_config.yml.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/10351604/HISTORY.rc.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/10351605/HEMCO_Config.rc.txt)
Thank you in advance!

**Comment by yantosca** [comment]
Thanks for writing @jiaying002.  We do not provide restart files for the simulations other than the sample restart files that are taken from the latest 10-year benchmark.  

It is OK to take one of the sample restart files and redate them.  You will likely want to spin that restart file up using 2040 emissions for a sufficient period.  We usually recommend a 6-month spinup for fullchem simulations but you might want to use a 1 year spinup so that the emissions for 2040 get applied.

Also tagging @ltmurray. 

Tagging @Jourdan-He @SaptSinha for their reference.

**Comment by jiaying002** [comment]
Thank you so much, Mr. Yantosca!

For Q2, I have some follow-up questions.

1. What should I do to spin up? 
         The steps I should do, from my understanding are:
               1. Use the sample restart file (20200101) to run a full-chem simulation from 20400101 to 20410101. (Choose "Full chemistry when selecting the run directory and open the "Restart" and _"SpeciesConc"_(not sure) in the History.rc)
               2. After finishing step 1, use the 20400101 in the "Restart" folder to start the productive simulation.
 If those are the correct steps, then could you please hint me why I should do the spin-up since I have been using the same 20400101 file all along?

2. I saw this example provided in the guideline. "If you want to do a production simulation starting on 12/1/13, you could spin up the model for one year using the initial GEOS-FP restart file dated 7/1/13 and then use the new restart file to spin up the model for five additional months, from 7/1/13 to 12/1/13." I could not understand why we are spinning up from 7/1/13 to 7/1/14 but the 20131201 restart file. From my understanding, it would make the spin-up from 12/2/13 to 7/1/14 meaningless. 

I am pretty sure I got something wrong. Would you please help me figure it out?

Thank you!

**Comment by jiaying002** [comment]
@yantosca I am struggling these days. Would you please help me a little? Thank you in advance!

**Comment by jiaying002** [comment]
I believe I just got what spin-up means. 

From the example,  "If you want to do a production simulation starting on 12/1/13, you could spin up the model for one year using the initial GEOS-FP restart file dated 7/1/13 and then use the new restart file to spin up the model for five additional months, from 7/1/13 to 12/1/13." The new restart file means the 12/1/14 restart file, and change the time stamp of this restart file to 7/1/13 and run the simulation.

Correct me if I'm wrong. Thank you!

**Comment by ltmurray** [comment]
And to add to @yantosca 's comment, you need to initialize over a time period that is longer than a few lifetimes of your chemical species of interest. For most trospopheric gas-phase chemistry, we recommend at least 6 months (I always do at least 12 months). However, if you are running in a different decade, or if your results are sensitive to stratospheric composition, then you need to run for a longer period, to make sure that the stratosphere has time to adjust. You can plot a simple time series of your species of interest at a location of interest in the initialization period to confirm that it is varying about a mean state rather than drifting toward its equilibrium value.

**Comment by jiaying002** [comment]
@yantosca Thank you so much for answering my question, which perfectly solved my problem!
@ltmurray Thank you so much for giving me such a good suggestion. I see your point, and I'll plot a time series to check if it is moving toward its equilibrium value or not. Just a quick follow-up question to confirm, if it is indeed moving to the equilibrium value, does it mean I still need to do more spin-up?

**Comment by yantosca** [comment]
Thanks @jiaying002.  We can close out this issue now.

**Comment by ltmurray** [comment]
@jiaying002 , yes, if you still see drift, then you should continue spinning up until the new equilibrium has been achieved.

**Comment by jiaying002** [comment]
Thank you so much for answering my question, Dr. Murray! With your help, I now perfectly understand what to do next!
