### ISSUE TITLE
[QUESTION]create rundir

### ISSUE THREAD

**Issue by zhifeng1310** [geoschem/geos-chem#1580]
### Ask a question about GEOS-Chem:
Hello, The following problem occurred when I create rundir, GEOS-Chem version is13.0.0, and I don't have input.geos and restarts/GEOSChem.restart.YYYYMMDD_hhmmzz.nc4 file.
```console
-- This run directory has been set up to start on  and
     restart files for this date are in the Restarts subdirectory.

  -- Update start and end dates in geoschem_config.yml.

  -- Add restart files to Restarts as GEOSChem.Restart.YYYYMMDD_HHmmz.nc4.

  -- The default frequency and duration of diagnostics is set to monthly.
     You may modify these settings in HISTORY.rc and HEMCO_Config.rc.

  -- The following sample restart provided for this simulation was not found:
     /home/zf/geoschem/extdata/GEOSCHEM_RESTARTS/GC_14.0.0/GEOSChem.Restart.fullchem.20190701_0000z.nc4
     You will need to provide this initial restart file or disable
     GC_RESTARTS in HEMCO_Config.rc to initialize your simulation
     with default background species concentrations.
```
Look forward to your reply, thanks.

**Comment by yantosca** [comment]
Thanks for writing @zhifeng1310.  We would recommend doing a fresh clone of GEOS-Chem 14.0.2 (the current version) as described in https://geos-chem.readthedocs.io and creating a new run directory.  If you do a dry-run simulation that should download the proper restart files.

It seems like your issue may be caused by a mismatch between the GCClassic superproject and the underlying GEOS-Chem submodule.  A fresh clone should resolve this.
