### ISSUE TITLE
[FEATURE REQUEST] Split up OFFLINE_LIGHTNING fields into daily files instead of monthly files

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#160]
Currently, data in [ExtData/HEMCO/OFFLINE_LIGHTNING/v2019-01/](http://geoschemdata.computecanada.ca/ExtData/HEMCO/OFFLINE_LIGHTNING/v2019-01/) are stored as monthly files. To improve HEMCO file I/O, we would ideally store them as daily files so that data would be read in once daily for all hours, instead of hourly. I can easily do this via a shell script using CDO and store the new files in, for example, a v2019-12 subdirectory.

@ltmurray Any thoughts or concerns?

**Comment by sdeastham** [comment]
Would this actually degrade performance in GCHP? I have no idea, I'm just wondering if this is the right workaround. If nothing else, it means that opening and closing a larger number of files becomes unavoidable.

**Comment by ltmurray** [comment]
It will make version control problematic, since all the FP fields need to be updated each quarter, and that’s a lot of files to keep track of.

I would recommend holding off on splitting the lightning flash rates until the feature request for pre-multiplying two fields upon read by HEMCO is implemented. Then we can store the unconstrained flash rates at the native resolution (as daily files, without any need for updates other than when new met becomes available), and then the updated climatological scaling factors as a separate file that is updated each quarter.

At present, the scaling factors if stored separately would be re-gridded before they are applied to the re-gridded flash rates, and therefore not yield the same results.

On Dec 4, 2019, at 1:32 PM, Melissa Sulprizio <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently, data in ExtData/HEMCO/OFFLINE_LIGHTNING/v2019-01/<https://urldefense.proofpoint.com/v2/url?u=http-3A__geoschemdata.computecanada.ca_ExtData_HEMCO_OFFLINE-5FLIGHTNING_v2019-2D01_&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=FZTgar4ZcAerjX-R_LaBWCoXl65de8pQBuW_W4Wb_wQ&m=clHO2jHEJEaClvzsirbHelFCEUnW8R9vU4mQG3yrQpE&s=SDDqc7rbeRvJutiNIpdMbsWM8P1h8kT68P3D0W0LdGU&e=> are stored as monthly files. To improve HEMCO file I/O, we would ideally store them as daily files so that data would be read in once daily for all hours, instead of hourly. I can easily do this via a shell script using CDO and store the new files in, for example, a v2019-12 subdirectory.

@ltmurray<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ltmurray&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=FZTgar4ZcAerjX-R_LaBWCoXl65de8pQBuW_W4Wb_wQ&m=clHO2jHEJEaClvzsirbHelFCEUnW8R9vU4mQG3yrQpE&s=5Aj53e-pH5FkyEr_jGoUf4T4M-xFFzuG0lG-eTrc894&e=> Any thoughts or concerns?

**Comment by msulprizio** [comment]
> Would this actually degrade performance in GCHP? 

@seastham In GCC, essentially what we're doing now is reading these 3-hourly every hour which is excessive. For the 3-hourly met fields read directly from GEOS-FP and MERRA-2, I've made modifications that will go into 12.7.0 for reading all hours up front at the start of the day. With that improvement, we just open and read the met field file once instead of 24 times. We're still opening and reading the OFFLINE_LIGHTNING fields once every hour.

For GCHP, I believe the setting in ExtData for FLASH_DENS and CONV_DEPTH replicates what is done for the 3-hourly met fields (`F0;013000`). If I understand the [ExtData documentation](https://geos5.org/wiki/index.php?title=Using_the_ExtData_component#ExtData_Resource_File) correctly, I believe the F0 means refresh every time step. I don't know if ExtData is smart enough to know whether a file is daily or monthly, and whether it reads all data in a file up front or opens it at the specified refresh time.

**Comment by msulprizio** [comment]
@ltmurray I'm fine with waiting on this update until we implement the capability to apply scale factors before regridding in HEMCO.

**Comment by sdeastham** [comment]
@msulprizio Back in the early days of GCHP, ExtData only reopened files when there was a change in file template, and kept the file open between calls for data. Data was only actually read in when the left or right bracket (for interpolation) needed updating. The latter part is still true (minimizing "read" calls for infrequently-defined data, even when the refresh template is something like F0) but I'm not 100% sure if the former is still true.

Frankly we still need to implement that scale-before-regridding feature in GCHP as well, so it would be a good time to dig further into that question (and whether the time penalty of going to daily files would even matter for GCHP).

**Comment by msulprizio** [comment]
Sounds good. I will close the issue for now and we can reopen/reconsider again when we have the capability to scale before regridding.

**Comment by lizziel** [comment]
There is an issue in GCHP where MAPL is not correctly finding the right file to read offline lighting data: https://github.com/geoschem/GCHPctm/issues/61. The issue appears to be that MAPL ExtData is not entirely robust for the handling of non-climatology monthly files with high frequency data.

A quick fix for the purposes of the GCHP 13.0.0 1-year benchmark (set to begin in the next couple days) could be to create a daily file inventory from the monthly files for use solely with GCHP. However, there was discussion in this thread earlier about that potentially introducing a performance bottleneck for GCHP.

I propose that we use the daily files instead of monthly for the GCHP 13.0.0 1-year benchmark as a quick fix. Meanwhile, we can continue to investigate the issue in MAPL to come up with a robust fix that allows using the monthly files.

@sdeastham, what do you think of this proposal?

**Comment by sdeastham** [comment]
It seems good as a quick fix. Long term, I'm a bit worried that we'd be missing the woods for the trees - presumably this is going to happen every time we have a monthly file containing sub-monthly data. I think the only truly robust solution here will be to implement something which better does not assume that `frequency` is a fixed quantity, but rather (and maybe only if the frequency is >1 day) advances by one period at a time, recalculating each time.

**Comment by LiamBindle** [comment]
I think that reading monthly/annual files should be fixed now (geoschem/GCHPctm#62). Therefore, I think it's okay if we continue using monthly OFFLINE_LIGHTNING fields.

**Comment by yantosca** [comment]
I will close out this issue for now.
