### ISSUE TITLE
[QUESTION]the error about mask emission

### ISSUE THREAD

**Issue by pku-tjh** [geoschem/geos-chem#1617]
### Ask a question about GEOS-Chem:
Hi, everyone.
I am new to GC. My GC version is 13.0.0. I want to use my custom region file to mask SO2 emission(used CMIP6 emission). But when I used the mask file created by ARCGIS, global emission are zero.

I think the problem may from the mask file, can you give me some suggestions to modify it?
Thanks for your helps!

Mask file description(opened by panoply):
![image](https://user-images.githubusercontent.com/117807730/214247393-1fe68a77-9d17-4f93-a377-2c8d4deb8ccd.png)

![image](https://user-images.githubusercontent.com/117807730/214247489-5770677e-2ad3-4427-bb48-60e66df560f5.png)

![image](https://user-images.githubusercontent.com/117807730/214247543-ce882105-f757-4788-b43a-fb9f99e8d004.png)

Mask definition in HEMCO_Configure.rc
1100 NORAME_MASK $ROOT/MASKS/region_mask/region2_mask.nc        region2     2013/1/1/0 C xy 1 1 -180/-90/180/90
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/10487776/HEMCO_Config.txt)

SO2 EMISSION result:
![image](https://user-images.githubusercontent.com/117807730/214248027-7e84480d-a517-418a-bb53-aefab6b68dc1.png)
Emission are zero

**Comment by pku-tjh** [comment]
Hi, @yantosca. I tried other custom region whose data type is float, and rerun one month. But it still does not work. I do not know what the reason is. 
Looking forward your helps!
Thanks!

mask file description:
![image](https://user-images.githubusercontent.com/117807730/214476852-ee726d43-bbb7-41e6-9ae7-23551ffdc27a.png)
![image](https://user-images.githubusercontent.com/117807730/214476879-77f6bd00-fe50-47dd-b093-a9440341360b.png)

Emission result still are zero
![image](https://user-images.githubusercontent.com/117807730/214476939-ec75e91c-785c-469e-ac09-ba70872dd69b.png)

HEMCO FILE:
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/10495999/HEMCO_Config.txt)

**Comment by yantosca** [comment]
@pku-tjh: Can you run the isCoards script on your netCDF file?  That will tell you if the file has anything that would prevent it from being read.  You can get it from https://github.com/geoschem/netcdf-scripts.  Then run the script on the file with `isCoards myfile.nc` (or whatever the netCDF file name is).  You might have to edit some file attributes so that HEMCO can read it.

Your HEMCO_Config.rc file looks OK.

Also see the following supplemental guides:
- [Work with netCDF files](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/netcdf-guide.html)
- [Prepare COARDS-compliant netCDF files for](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/coards-guide.html)

**Comment by pku-tjh** [comment]
Thanks for the detailed guidance@yantosca. it is very helpful for me!

**Comment by yantosca** [comment]
Thanks @pju-tjh.  I'll close out this issue.
