### ISSUE TITLE
[FEATURE REQUEST] Add warning message to GCHP run directory; also provide a tool to degrade met field resolution in ExtData.rc

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#164]
Based on the discussion thread from https://github.com/geoschem/geos-chem/issues/143, we propose the following new features:

1. When creating GCHP run directories (with the run/GCHPctm/createRunDir.sh), a warning message should be printed to alert the user that high-resolution met fields (either 0.25 x 0.3125 GEOS-FP or 0.5 x 0.625 MERRA-2) will be used, and:
2. Provide a script (in a separate tools/ folder) to allow the user to change the resolution of the met fields if they do not have access to hi-res met.

We would always recommend using the highest-resolution meteorology for GCHP, but we do understand that some users might have limited storage that would preclude use of the highest-res met.

**Comment by JiaweiZhuang** [comment]
I have been using this command to switch the metfields:

```bash
sed -i -e 1,120s/025x03125.nc/4x5.nc/g ExtData.rc   # only scan the first few lines, do not modify non-metfields
```

See [set_4x5.met.sh](https://github.com/JiaweiZhuang/cloud-gchp-paper/blob/master/scripts/configure_rundir/set_4x5.met.sh) and [set_0.25met.sh](https://github.com/JiaweiZhuang/cloud-gchp-paper/blob/master/scripts/configure_rundir/set_0.25met.sh)

**Comment by lizziel** [comment]
During run directory creation the meteorology source options are now listed with their respective default resolutions. I expanded the section of the GCHP manual on changing meteorology resolution to include Seb's python code for easy update. A future version will include a tools folder, but not until v13.0.0 which will feature several major restructuring updates in GEOS-Chem. The delay is to give more thought to where the tools folder will live, how it will be structured, and what it will contain.

Run directory creation does not include instructions for changing the meteorology resolution since doing this is not encouraged. However, users who wish to do so should readily find the information on how to do it in the GCHP user manual, along with other configuration options not featured during run directory creation. We want to keep the run directory creation step very simple.
