### ISSUE TITLE
[QUESTION] Excessive fall velocity? STOP at  CALC_FALLVEL, UCX_mod

### ISSUE THREAD

**Issue by xpCH2** [geoschem/geos-chem#1652]
### Ask a question about GEOS-Chem:
Hello！
I am running a full-chemistry simulation with GEOS-Chem 14.1.0 ([Releases). But it take out an error:

![图片](https://user-images.githubusercontent.com/73470044/218429982-18486eb9-f884-4d41-8f82-8f44a0482aab.png)

What can I do to solve it, thank you!

[GC.log](https://github.com/geoschem/geos-chem/files/10721115/GC.log)

-GEOS-Chem version: 14.1.0

    CMake version: 3.13.2
    Compilers (Intel or GNU, and version): GNU 10.2.0
    NetCDF version: 4.9.0

**Comment by lizziel** [comment]
Hi @xpCH2, there have been several GitHub issues about this error in the past. Please search for "Excessive fall velocity" on the GitHub issues page and review the suggestions in those issues. The problem could be a number of things, but since it is happening in the very first timestep I suggest looking at the input data you are using for the simulation date you are running at, as suggesting the previous issues.

NOTE: We ask that users identify themselves and their institutions when requesting help. Please do this in the future.

**Comment by xpCH2** [comment]
Hi @lizziel , thank you for your reply! I have added some print statements to the IF block in "GCClassic-14.1.0/src/GEOS-Chem/GeosCore/ucx_mod.F90" before it stops (referenced #762 ) .But it didn't print any more statement in the log file. I tried to add some letter like change
`CALL ERROR_STOP(' Excessive fall velocity? ', ' CALC_FALLVEL, UCX_mod')`
to
`CALL ERROR_STOP(' ***Excessive fall velocity? ', ' CALC_FALLVEL, UCX_mod')`
But the output file also unchanged. Did I found the right file path of "ucx_mod.F90"? Or if the actually effective path of it has changed from a version like 13.0.0?

I have searched related issues before, but it seemed not work.  I'll try more ways to solve problems and I'm sorry about ignorine to identify myself. I am a graduate student from South China University of Technology.
