### ISSUE TITLE
[BUG/ISSUE] GEOS-Chem Classic v14.0.2 and v14.1.0 SpeciesConc, AerosolMass doesn't match v14.0.0 benchmark

### ISSUE THREAD

**Issue by LukeAParsons** [geoschem/geos-chem#1655]
### What institution are you from?
Duke University 

### Description of the problem
I am testing if the model output I am getting from the latest versions of GEOS-Chem Classic (v14.1.0 and v14.0.2) matches the output from the GCClassic (v14.0.0) benchmark simulations I am trying to run both of the Duke cluster and on AWS. The SpeciesConc and AerosolMass (surface) from my simulations don't match the benchmark simulations at all, specifically for TotalOC (Surface) and TotalBiogenicOA (Surface), which either really low (Biogenic OA) or zero (TotalOC) values across the globe for my 'out of the box' model runs. I tried running the model in two ways- both were global 4x5 model runs with 72 levels, with full chemistry.

I am a bit confused about what I did wrong- is there a default setting in the 'out of the box' version of the model that causes model runs to produce no surface OC and other output that is so dissimilar to the benchmark runs (as well as dissimilar to the 'real world', which I assume has surface OC and BiogenicOA in the tropics).

### Description of troubleshooting performed
1) About a month ago on the Duke cluster, I tried downloading the newest version of the model (v14.0.2), spinning  the model up from mid-2016 using a restart file downloaded from the dry run, and running the 'out of the box' version of the model through the end of 2019, saving Restart files and Boundary Conditions for all months, and specifically the SpeciesConc and AerosolMass suite (monthly mean) for Oct, 2019 for comparison with the online benchmark simulation data to be sure I was getting realistic values before performing regional nested experiments/runs.
I then downloaded the latest GCClassic v14.0.0 benchmark simulation output I could find (http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/14.0.0-rc.3/GCClassic/FullChem/OutputDir.tar.gz) to compare to my output. Although some species are similar, several species, such as TotalOC (Surface) show values of zero in my simulations. There are also strange hotspots of PM2.5 in what looks like the Himalayan plateau region in my simulations that don't show up in the benchmark files/figures.

2) I assumed I must have made some mistake in spinning the model up or in accidentally changing default settings in GCClassic, so yesterday I logged in to AWS, re-downloaded the latest version of GCClassic (v14.1.0) from GitHub, and downloaded the 2019 restart file from WU (and all global met, HEMCO files etc necessary). I ran the model for Oct, 2019, and still got zero TotalOC at surface and lots of mismatches with the benchmark online output described above.

See attached figures showing comparisons of the benchmark output to my model output.

### GEOS-Chem version
GCClassic v14.0.2 
GCClassic v14.1.0

### Description of modifications
None as far as I know - I ran the model without any modifications to the HEMCO_Config or History or geoschem config files except the dates of the run (Oct 2019 only for one, the other was mid-2016 through end of 2019) and toggling on BoundarConditions, AerosolMass, SpeciesConc, and Restart in the History.

![TotalOC](https://user-images.githubusercontent.com/7451769/219067960-f5f4c46c-2455-4bb8-bcda-8baa54b84c3c.png)
![PM25](https://user-images.githubusercontent.com/7451769/219068205-d20e3020-8485-44a1-b593-049bca610831.png)
![TotalBiogenicOA](https://user-images.githubusercontent.com/7451769/219068208-37f89ff5-44e6-4641-aae3-280ebf8d857f.png)

**Comment by yantosca** [comment]
Thanks for writing @LukeAParsons.  I am not sure we'd expect 14.1.0 to match the output of the 14.0.0 benchmark because there were some science updates/fixes added.  

Also note, if you did a standard simulation, then all of the complex SOA species will be zero, as this simulation only uses the simple SOA scheme.  The benchmark uses both simple and complex SOA but double-counting from the complex SOA is prevented.  I wonder if that is also causing the differences you are seeing.

**Comment by LukeAParsons** [comment]
@yantosca thanks for the continued feedback and help.

There seems to be two potential sources of mismatches in your answer:

1) Model version:
For both the GCClassic 14.1.0 AND the 14.0.2 simulations I ran, the aerosols didn't match the benchmark 14.0.0 output I downloaded, so I don't think it's the model version issue, unless a lot changed 14.0.0 to 14.0.2.

2) Complex SOA:
It sounds like I made the incorrect assumption that the 'out of the box model' version settings are similar to the benchmark run- I will have to download the benchmark config files and take a look at the differences. Thank you for highlighting the SOA scheme issue. This sounds like it is a more likely source of the differences I see in my runs vs benchmark.

**Comment by lizziel** [comment]
Hi @LukeAParsons, I see you closed this issue but I want to add a few more things.
1. The "out-of-the-box" version settings are the same as our benchmark run, as long as you choose "benchmark" when creating a run directory. It doesn't look like you specified which simulation you did. If you ran a benchmark simulation then your results should match, at least very closely given numerical noise due to different compilers etc, as long as you use exactly the same restart file, including both GEOS-Chem restart and HEMCO restart (not used for our benchmark, so should not be present in run directory).
2. Note that the default benchmark restart file changed in 14.0.2 so out-of-the-box runs of 14.0.0 and 14.0.2 will not match. You could try to reproduce the discrepancies you are seeing between 14.0.0 and 14.0.2 without spinning up your own restart and instead using what comes with 14.0.0.
3. You could also run 14.0.2 and 14.1.0 using the restarts they come with (which are the same) and compare with the 14.1.0 benchmark plots located [here](https://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_14.1.0#1-month_full-chemistry_benchmarks), which are the expected differences for a 1-month run in July 2019. Note that that benchmark compares 14.1.0 to 14.0.2 and not 14.1.0 to 14.0.0, because of the restart file discrepancy.
4. Regarding AerosolMass, it is also possible there's a parallelization error since we don't test parallelization in that collection. You could try running the same version multiple times, always using the same restart file, and making sure you get the same answer.
