### ISSUE TITLE
Inconsistent emissions from different biomass burning inventories

### ISSUE THREAD

**Issue by Mashiat25** [geoschem/geos-chem#1683]
Name: Mashiat Hossain
Institution: University of Illinois at Urbana-Champaign

Hello, as a part of my project I am currently working on identifying the contribution of biomass burning aerosols to cloud formation in the Benguela upwelling region. When I ran the model (GCClassic v13.3.3) with the default biomass burning inventory (GFED), it resulted in zero SO2 & CO emissions during the first six months, a transitional value for July, and constant emissions for the remaining five months. Next, I simulated SO2 and CO emissions for three different biomass burning inventories (GFED, QFED, GFAS) using the HEMCO standalone tool. I found that QFED best captured the seasonality of biomass burning, followed by GFED, while GFAS did not show any seasonality. The magnitudes of emissions also varied significantly among the inventories.

During the simulations, I made necessary changes to HEMCO_Diagn.rc (setting ExtNr to -1 for EmisPOG1_BioBurn) and HEMCO_Config.rc (turning on the current inventory for each simulation). I am wondering why the emissions show such variation among the inventories and whether I should use QFED instead of GFED for better representation of seasonality in future simulations.

Thanks,
Mashiat

**HEMCO files**
[HEMCO_Config_Biomass.txt](https://github.com/geoschem/geos-chem/files/10885229/HEMCO_Config_Biomass.txt)
[HEMCO_Diagn_Biomass.txt](https://github.com/geoschem/geos-chem/files/10885230/HEMCO_Diagn_Biomass.txt)

**Comment by yantosca** [comment]
Thanks for writing @Mashiat25.  I do know that the biomass inventories can show different results because they are constructed differently and make different assumptions.  From what I understand, GFED is a bottom-up approach (using burned area from VIIRS I think) and then scales from the amount of dry matter burned to get emissions per species. I also believe that QFED and GFAS are top-down approaches using satellite observations.  I would bring this up with the Emissions Working Group as they are more knowledgeable than the GCST in these matters.  Tagging @jaegle @eamarais

Also, when you are using GFED emissions, you might try using 111 for the extension number in HEMCO_Diagn.rc, and use 0 if you are using QFED or GFAS.  The -1 should work but in case there is some kind of issue why it does not, it'd be good to test that out.

Also note: there is a bug (now fixed in 14.1.1) that there was no entry in HEMCO_Config.rc for methanol from GFAS.  See issue #1631 and PR #1632.
