### ISSUE TITLE
[QUESTION] GCClassic version 12.8.0 vs GCClassic version 14.1.0

### ISSUE THREAD

**Issue by TylerElgiar** [geoschem/geos-chem#1716]
### Name and Institution (Required)

Name: Tyler Elgiar
Institution: Utah State University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

Hello, 

I have been running two different versions of GCClassic (Version 12.8.0 and version 14.1.0) for the Hg simulation.  I was having some issues displaying 'FluxHg2HgPfromAirToOcean' in version 12.8.0, and after reaching out, it was recommended that I use version 14.1.0 since it is the version with an updated Hg simulation. However, I am still not able to display 'FluxHg2HgPfromAirToOcean' using GCPy and version 14.1.0. Also, the modeled output for Hg0 and HgII using version 14.1.0 is ~17% and ~42% lower, respectively, when compared to version 12.8.0. I am just curious if anyone may know a reason for this, or if anyone has experienced something similar. I am trying to decide which version may be best to use for the time being. I am leaning more toward version 12.8.0. Any thoughts or information is greatly appreciated. Thanks!

**Comment by viral211** [comment]
Hi @TylerElgiar. The differences between version 12.8.0 and  14.1.0 are because of scientific updates to the chemical mechanism ([Shah et al. 2021](https://doi.org/10.1021/acs.est.1c03160)) and to Hg0 dry deposition ([Feinberg et al. 2022](https://doi.org/10.1039/D2EM00032F)). The lower concentrations of Hg(II) are primarily due to the updated chemistry.   Both the chemistry and deposition updates led to a change in the Hg(0) concentrations. In particular, Feinberg et al. recommended a higher Hg(0) dry deposition velocity. I suggest using version 14.1.0 because it is scientifically more up-to-date.

**Comment by viral211** [comment]
Yes, Hg2 is being deposited from the air to the ocean. You can calculate this flux offline from the dry and wet deposition flux diagnostics: `DryDep_`, `WetLossConv_` and `WetLossLS_`. You may need to do some unit conversion to add the dry and wet deposition fluxes. And yes, it is better to leave the dynamic ocean as false.

**Comment by TylerElgiar** [comment]
Okay, perfect. Thanks a lot for your help!
