### ISSUE TITLE
Local time error in satellite diagnostic code

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#1766]
https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/GeosCore/diagnostics_mod.F90#L686

The setting of the satellite diagnostics currently assumes that the local time can be calculated using only the first index (i.e. assumes the same longitude for all Y values). However, local time can vary across Y values in GCHP, meaning this code will give incorrect answers.

Contributor: Seb Eastham, MIT

**Comment by yantosca** [comment]
Thanks for writing @sdeastham.  This diagnostic was only ever tested in GEOS-Chem Classic, as the developer was using GEOS-Chem Classic and not GCHP.  

We can try to fix this in a 14.2.1 release, as we are wrapping up 14.2.0.

**Comment by lizziel** [comment]
See also https://github.com/geoschem/geos-chem/issues/770. It looks like there was no follow-up about testing in GCHP which must be why the diagnostic is not included in GCHP `HISTORY.rc` files. It is not actually supported for GCHP yet. This does not appear in any of our documentation because the netcdf satellite diagnostic is not in any of our documentation yet. According to the wiki you still need to use bpch and the netcdf option is not yet listed on ReadTheDocs. We can add that to the todo list for 14.2 as well.

**Comment by yantosca** [comment]
Closing out this issue.
