### ISSUE TITLE
spin-up problem

### ISSUE THREAD

**Issue by liwenjia12** [geoschem/geos-chem#1769]
### Name and Institution (Required)

Name: mayue
Institution:China university of petroleum

### Confirm you have reviewed the following documentation

- [yes ] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion

Please provide a clear and concise overview of the discussion topic or new feature requested.

I was doing a simulation study of carbon dioxide concentration, but every time I spin up, the carbon dioxide concentration will increase once. Now I have spun up about 15 years, but the concentration is still not stable and still increase, I would like to ask what's wrong with this.

**Comment by yantosca** [comment]
Thanks for writing @liwenjia12.  Have you tried doing any debugging of your simulation?  Please see our debugging guide here: https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html.

The GCST is unable to assist with scientific validation of your simulations, as that is more of a science issue rather than a coding issue.
