### ISSUE TITLE
[BUG/ISSUE] GCHP simulation dies in KPP solver

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#180]
I have added this issue on behalf of Hongjian Weng at PKU:

>When I run the GCHP master version model, some issue occur as follows: 
>It seems to be the KPP issue, and whether you know the cause? 
>It will be very helpful to me if you can take time to look at this! 
>The attachments are the log files and environment setting. 

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% USING O3 COLUMNS FROM THE MET FIELDS! %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
N_/L2_/L2-cutoff JXTRA:  601  146     0.00
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=  4.000000000000012E-057 and H=  3.717258950187215E-057
 ### INTEGRATE RETURNED ERROR AT:            1           1           1
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=  4.000000000000012E-057 and H=  3.717258950187215E-057
 ## INTEGRATE FAILED TWICE !!!
===============================================================================
GEOS-CHEM ERROR: Integrator error code : -7
STOP at INTEGRATE_KPP
===============================================================================
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=  4.000000000000018E-075 and H=  4.000000000000018E-075
 ### INTEGRATE RETURNED ERROR AT:            5           1           1
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=  4.000000000000018E-075 and H=  4.000000000000018E-075
 ## INTEGRATE FAILED TWICE !!!
```

Configuration files:
- [gchp.env.txt](https://github.com/geoschem/geos-chem/files/3979254/gchp.env.txt)
- [HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/3979259/HEMCO_Config.rc.txt)
- [runConfig.sh.txt](https://github.com/geoschem/geos-chem/files/3979260/runConfig.sh.txt)

Log files
- [compile.log.txt](https://github.com/geoschem/geos-chem/files/3979252/compile.log.txt)
- [gchp.log.txt](https://github.com/geoschem/geos-chem/files/3979255/gchp.log.txt)
- [HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/3979257/HEMCO.log.txt)

**Comment by lizziel** [comment]
What version of GCHP are you using? It looks like you are doing a benchmark run with MERRA2 meteorology based on your run directory name in the log file. We do not yet have unit testing for GCHP where we test MERRA2 in each simulation so there may be a bug. Our benchmarks only use GEOS-FP. If possible, could you do a test run with GEOS-FP and see if that works? Then we know it is isolated to MERRA2.

Also, I notice that you have diagnostics frequency and duration set to 1-month in runConfig.sh but are only doing a 1-hr run. With these settings you will not get any diagnostics output from the model. I recommend either turning off diagnostics by commenting out the collections listed at the top HISTORY.rc or updating runConfig.sh to have a 1-hr frequency and duration for diagnostics. The former will reduce the memory footprint of the run by not initializing diagnostic arrays. The latter will allow you to test diagnostics.

Finally, we reserve the benchmark simulation, which includes both simple and complex SOA, for formal GEOS-Chem benchmarks. Science runs should use the standard simulation. If you are trying to replicate the GEOS-Chem benchmark you should stick with benchmark but switch to GEOS-FP. Otherwise I suggest switching your simulation to standard.

**Comment by hongjianweng** [comment]
Following your suggests, I test the standard GEOS-FP version, the issue also occur!

**Comment by lizziel** [comment]
What version of GCHP are you using?

**Comment by hongjianweng** [comment]
I use the master version gchp and GEOS-Chem

**Comment by hongjianweng** [comment]
I have finally successfully run GCHP using version v12.6.0, and started the simulation on the 20160701 following the benchmark.
But the issue above occurred or the simulation would cut off suddenly if I changed the beginning time e.g., 20170701.
I wonder whether the beginning time will influence the simulation, and have you ever tested the model beginning with the other days.

**Comment by lizziel** [comment]
@hongjianweng, I am glad it now works starting on 20160701. Were you able to figure out what the issue was? If yes, let us know what it was and how you fixed it in case others run into the same problem.

Starting on the same day but a different year should be fine, but you may run into an issue with met-fields if you do not have them. Could you attach the config and log files for your 2017 run?

**Comment by lizziel** [comment]
I am closing this issue. If there is a still a problem, feel free to reopen.

**Comment by LiamBindle** [comment]
Hi all, I found this issue when I was searching for solution my own issue. 

I got a similar error message (crashing in FastJX with the `N_/L2_/L2-cutof` messages and the warnings that the integrator failed). I wasn't able to track down exactly what went wrong but the culprit was a bad metfield. I'm using custom metfields and one of mine was upside-down.

**Comment by yantosca** [comment]
Usually when you get that FAST_JX error, the aerosol loading is too high, and FAST-JX doesn't know how to deal with essentially infinite optical depth.  Could be an indicator of e.g. problematic emissions such as biomass burning.
