### ISSUE TITLE
Question: How to turn off a specific chemical reaction in GEOS-Chem v12.6.0

### ISSUE THREAD

**Issue by YanshunLi-washu** [geoschem/geos-chem#1829]
Hi GCST,

This is Yanshun from WashU.

I'm wondering how can I turn off specific chemical reactions in GEOS-Chem v12.6.0.

Taking the N2O5 uptake as an example.

Should I simply delete the line 
"N2O5 = 2.000HNO3 :                           HET(ind_N2O5,4);"
in GC12.6.0/KPP/Custom/Custom.eqn, regenerate the Fortran codes using KPP and then recompile GC12.6.0?

Or do I need to work on other files, for example editing the GC12.6.0/KPP/Custom/gckpp.kpp file to further change info about chemical families. (and under what circumstances should I edit chemical families in this file).

Is that possible to have a simple tutorial for removing this rxn in GEOS-Chem?

Btw, I'm curious about the physical meaning of the "HET" variable defined in GC12.6.0/KPP/Standard/gckpp_HetRates.F90. Assume it stands for some overall reaction rate with two dimensions,  but I'm particularly confused about the meaning of its second dimension. For example, what does 4 in HET(ind_N2O5,4) mean?

Thanks,
Yanshun

**Comment by yantosca** [comment]
Thanks for your patience @YanshunLi-washu.  Our cluster has undergone an OS update and that has required our attention in these days.

>Should I simply delete the line
>`N2O5 = 2.000HNO3 : HET(ind_N2O5,4);`
>in `GC12.6.0/KPP/Custom/Custom.eqn`, regenerate the Fortran codes using KPP and then recompile GC12.6.0?

To shut off the reaction you can change
```F90
N2O5 = 2.000HNO3 : HET(ind_N2O5,4)
```
to
```F90
N2O5 = 2.000HNO3 : 0.0d0;
```
and then regenerate the Fortran code.  That will set the rate to zero.  If you delete that reaction then KPP will reorder the reaction matrix and the results might differ slightly at the level of numerical noise.

> Is that possible to have a simple tutorial for removing this rxn in GEOS-Chem?

We do now have this tutorial on our ReadTheDocs pages.
- https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/using-kpp-with-gc.html

>Btw, I'm curious about the physical meaning of the "HET" variable defined in GC12.6.0/KPP/Standard/gckpp_HetRates.F90. Assume it stands for some overall reaction rate with two dimensions, but I'm particularly confused about the meaning of its second dimension. For example, what does 4 in HET(ind_N2O5,4) mean?

The `HET` array was a catch-all array set up by Mike Long (@msl3v) for the various KPP reactions.  The first dimension is the number of species.  The 2nd dimension is arbitrary. 

The `HET` array was removed in the cleanup that we did in version 13.3.0 and later versions. Each reaction now has a separate rate law function instead of computing all the reaction rates in `gckpp_HetRates.F90`.

**Comment by YanshunLi-washu** [comment]
Hi @yantosca Thanks for these helpful info! I'll follow your suggestions. It seems that the 2nd dimension of the HET array is the number of heterogeneous reactions of the specified involved species. Glad to learn to set rate to 0.0d0 instead of deleting the   equation (although difference in result should probably be negligible).
