### ISSUE TITLE
[DISCUSSION] Last modification to new array not captured in output diagnostics 

### ISSUE THREAD

**Issue by TerribleNews** [geoschem/geos-chem#183]
# Weird diagnostic behaviour

As part of the ongoing adjoint development work I've been doing, I've added a new array to state_chm. It seems to be behaving as expected, with one exception; on the final call to Run_ in the reverse integration (eg. if the run goes from 06:00 to 00:00 with a 10 minute chemistry timestep, on step 00:10) I modify the values in the array, printing them before and after the modification, and then values in the output diagnostic match the "before" value instead of the "after". @lizziel asked me to upload some files so she could help with this. This is a work in progress and also part of a larger set of a changes, so it might not be intelligible in its current state, but I appreciate any insight into what's going on with this.

[gchp.log.txt](https://github.com/geoschem/geos-chem/files/3986178/gchp.log.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/3986179/HISTORY.rc.txt)
[runConfig.sh.txt](https://github.com/geoschem/geos-chem/files/3986180/runConfig.sh.txt)
[Chem_GridCompMod.F90.txt](https://github.com/geoschem/geos-chem/files/3986181/Chem_GridCompMod.F90.txt)
[state_chm_mod.F90.txt](https://github.com/geoschem/geos-chem/files/3986182/state_chm_mod.F90.txt)

**Comment by lizziel** [comment]
Try doing a 7-hr run but still output the instantaneous values at the 6-hr mark. See if this fixes this issue. GCHP does a "soft" start in the first 10-minutes and I wonder if this is messing something up for that last timestep.

**Comment by TerribleNews** [comment]
Thanks for the suggestion! Same result; the nc4 data is the "before" value, not after. The way I implemented this change is I simply checked against 1 hour and 1 chemistry timestep before the end of the run and changed the duration of the run to 7 hrs, but let everything else the same. Log file except quoted below, which shows that the multiplication occurs on the 00:10 timestep, the diagnostic is output on the 00:00 timestep. 

>  Before conversion   0.486250382679633
>  After conversion   1.901938892658892E-004
>     Adjoint checking if 2014-08-31T23:00:00 == 2014-08-31T23:00:00
>     Adjoint multiplying SF_ADJ by ICS
>  AGCM Date: 2014/09/01  Time: 00:10:00
>                          Mem/Swap Used (MB) at MAPL_Cap:TimeLoop= 1.1790E+04 0.0
>  000E+00
>  offline_tracer_advection
> DryPLE0(debug) = 0.893450200000000017E+01
> DryPLE1(debug) = 0.893450200000000017E+01
>  AGCM Date: 2014/09/01  Time: 00:00:00
> 
>  Writing:     77 Slices to File:  OutputDir/GCHP.Emissions.20140901.nc4
>  Writing:     72 Slices to File:  OutputDir/GCHP.SpeciesConc.20140901.nc4
>  Writing:     72 Slices to File:  OutputDir/GCHP.Adjoint.20140901.nc4
>  Writing:    511 Slices to File:  OutputDir/GCHP.StateMet_avg.20140901.nc4
> 
>                          Mem/Swap Used (MB) at MAPL_Cap:TimeLoop= 1.1811E+04 0.0
>  000E+00
>

**Comment by lizziel** [comment]
I'm just going to throw out some thoughts. This may be kind of rambling. I'll be in Monday next week, then gone for a couple weeks.

Do you see the same behavior with other GEOS-Chem state arrays output as diagnostics? For example, if you output instantaneous meteorology at 10 minute frequency are the printed values n timesteps off from the output data? Is there a pattern? Would your current method of getting out the instantaneous value at 6 hrs work if you set for 6:10 rather than 6:00 in HISTORY.rc and did your simulation for 6 hrs 10 min?

Are you trying to get the product of Species and SpeciesAdj at the very end of the run, so no additional change to either? If yes, look to see if your checkpoint file (assuming one is created at the end) has Species and SpeciesAdj that you want (internal state names not those). If not, that is an interesting find that the internal state is also not output right. Work should then be done to make sure you can get it out at the end of the run and it matches the actual value at the end. I assume you would need that to start up the next consecutive run.

We generally don't calculate diagnostics by extracting time and doing a condition on it. Instead each diagnostics array is updated every heartbeat. We also generally try to keep it time-agnostic. If diagnostics need updates at irregular intervals then we do it post-processing. If you can get the SpeciesAdj (not overwritten as product) and Species out at the end you could calculate the product post-processing. Assuming you want it at the very end.

I've been assuming SpeciesAdj is updated every timestep like State_Chm%Species. Is it? Is it needed for consecutive runs and is it supposed to be advected? The end result of SpeciesAdj is the product of Species and SpeciesAdj. Is that it's definition every heartbeat?

**Comment by TerribleNews** [comment]
> We generally don't calculate diagnostics by extracting time and doing a condition on it. 

The time-dependence of this operation is caused by an `IF (FIRST) THEN` situation. Since the operation happened only on the first timestep in the forward run, it can only happen on the last timestep in the reverse run. Although in this case we can do the operation offline after the fact, there are usability reasons to not want to do so, and there are other situations that will eventually come up where the offline solution will not be available. Mostly I want this to work because the fact that it doesn't work means I don't understand how it's supposed to work. 

Thanks for all your suggestions so far! It took me a long time to get the variable to output in the checkpoint file (for reasons totally unrelated to this issue) but it appears to be the correct value there (it's slightly different because transport happens after chemistry, but I'm pretty sure it's the right value). So the internal state is being properly checkpointed but that state isn't being conveyed to the history output somehow.

>  Would your current method of getting out the instantaneous value at 6 hrs work if you set for 6:10 rather than 6:00 in HISTORY.rc and did your simulation for 6 hrs 10 min?

I also tried moving the multiplication operation to earlier than the last timestep (or later than the first timestep, if you like; reverse time is confusing) and that did not seem to change the output on that history step, that is, history was still outputting the pre-multiplication value.

In the meantime, I'm going to keep poking at this.  Let me know if that information brings anything else to me! Thanks again!

**Comment by TerribleNews** [comment]
New discovery: turning on bdry layer mixing or cloud convection results in the correct post-multiplication values being output in the diagnostics. I've looked through Chem_GridComMod::Run_ and I have no idea why that might be true.

**Comment by lizziel** [comment]
That is very interesting, and strange. Could you share the code that you added for the new diagnostics? Links to the relevant commits of your fork on github would be ideal.

**Comment by TerribleNews** [comment]
The code to alter the species adj variable on the last chemistry timestep is in Run_ in https://github.com/TerribleNews/gchp/blob/co2/Chem_GridCompMod.F90
The corresponding GEOS-Chem code is in https://github.com/TerribleNews/geos-chem/tree/co2

**Comment by TerribleNews** [comment]
Okay, I finally found it. My diagnostic was being copied during Set_Diagnostics_EndofTimestep which gets called in gigc_chunk_run, but before the unit conversion back to v/v. I ended up exposing Set_SpcAdj_Diagnostic, passing an extra flag into gigc_chunk_mod and moving the multiplication into gigc_chunk_mod after the last unit conversion on the last timestep in the reverse run. 

The upshot is:
All values that show up in the state_diag must be set before the call to Set_Diagnostics_EndofTimestep (or analogous functions for some diagnostics like Set_AerMass_Diagnostic) in gigc_chunk_run.

**Comment by lizziel** [comment]
I'm not sure I totally follow. What branch in your fork are you working in and is there a commit or series of commits on a branch that shows the changes? The Chem_GridCompMod.F90 link above shows the entire file but I'm looking for commit diffs.

**Comment by TerribleNews** [comment]
Sorry, I just moved the fix into a public branch. https://github.com/TerribleNews/gchp/commit/58c01c0744fd236e8d15815193f9e7a136318be8#diff-f38e184c89d87326b08ad612751d62af  Again, this was a problem with my understanding how how the values got from state_chm to the output diagnostics. I hadn't properly realized that there was a step with state_diag in between and that THAT copy to the history exports was NOT done in CopyGCStates2HistoryExports, but rather in Set_Diagnostics_EndofTimestep. The code around line 1300 of gigc_chunk_mod doing the multiplication of speciesAdj had previously been in Chem_GridCompMod, which meant it was executing AFTER Set_diagnostic_endoftimestep. I needed to do the multiplication inside gigc_chunk_mod but it turns out that even more than that I needed to add an extra copy step because I needed to do the multiplication on the un-converted values. Let me know if I'm not being clear enough.

**Comment by lizziel** [comment]
Okay, I think I understand now. Yes, State_Diag is not set in CopyGC2State2HistoryExports. That subroutine simply copies data from a GC state array to a MAPL export for each item in the linked list of HISTORY entries. Each item in the linked list has a GC state pointer that can point to either a State_Met, State_Chm, or State_Diag array, as well as a pointer to a MAPL export. The subroutine copies the snapshot of GC state array at the time of the call, but does not change it. It is up to the coder to set new State_Diag arrays prior to the call on every timestep. For most of GEOS-Chem the State_Diag arrays are updated in various components, such as chemistry. But for instances where the State_Diag array stores a transformation of a State_Chm array, such as State_Diag%SpeciesConc, the setting occurs after all components have run, but before the copy to the MAPL export.

I'm not sure why you would have a problem setting State_Diag before versus after Set_diagnostic_endoftimestep. That subroutine updates State_Diag%Species from State_Chm%Species, but doesn't change State_Chm%Species which you use to set your new State_Chm array. All that should matter is that you set the State_Diag array to the value you want before the call to CopyGCState2HistoryExports.

I took a look at your geos-chem fork updates as well, and it looks like you copied the subroutine for setting SpeciesConc and adapted it for the new adjoint species diagnostic subroutine. Beware that most of the code in that subroutine will not do anything in your copy. The unit conversions are only done for State_Chm%Species so would have no impact on your diagnostic. By including them you actually end up slowing down the model and introducing numerical noise.

Also, just a general comment. I had some trouble finding the proper commits to look at because the commit messages do not seem related. Our GEOS-Chem commit message standard is to describe what changed in the code, but it looks like you put general status messages. For example, the commit where subroutine Set_SpcAdj_Diagnostic was added has message "Finite difference testing available". A message such as "Add subroutine to set adjoint species diagnostic", followed by a blank line, and paragraph summary of the change would be more along our standards. It would definitely make browsing updates easier for others.
