### ISSUE TITLE
A question about species_database.yml

### ISSUE THREAD

**Issue by Fearlessssssss** [geoschem/geos-chem#1835]
### Name and Institution (Required)

Name:Tyler
Institution:THU

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

Hi, GCST, I have a puzzle about the molecule weight of species 'MONITA' and 'MONITS' listed in species_database.yml. As shown in chemical mechanism(KPP/fullchem), MONITA is the product of the aerosol uptake of MONITA, but their MW were defined differently.(14.01 for MONITA and 215.28 for MONITS). The same MW(14.01) is also defined for "IONITA' species.  So I wonder is there a special rule? Why 14.01 not 215.28 ?  Hope to your reply.
![species](https://github.com/geoschem/geos-chem/assets/127913691/ad6b3108-a01a-458a-ac4a-09ce104c3ada)
![mechanism](https://github.com/geoschem/geos-chem/assets/127913691/cf1283c9-2f0b-41f9-82b9-6b8500eca897)

**Comment by yantosca** [comment]
Thanks for writing @Fearlessssssss.  It would appear that the MONITA and IONITA have the same MW as nitrogen (14.01 g/mol).  So it looks like they track nitrate as nitrogen.  Tagging @kelvinhb who may be able to explain better than I can.

**Comment by kelvinhb** [comment]
Yep, @yantosca is right! Our aerosol-phase KPP species aren't perfect trackers of carbon right now, because species with different C-numbers get lumped together to form generic aerosol-phase products like MONITA, so instead we try to track nitrogen with those aerosol species and just give them the molar mass of however many nitrogens they carry. (Technically we don't do a perfect job with nitrogen either, since the gas-phase isoprene-derived dinitrate only produces one aerosol-phase nitrogen, but we're trying not to overload the mechanism with too many distinct aerosol-phase species). Since MONITS and MONITU are gas-phase species, they get the full molar mass of the compounds they represent. I think this is all a holdover from Jenny Fisher's 2016 paper (https://acp.copernicus.org/articles/16/5969/2016/acp-16-5969-2016.pdf).

**Comment by yantosca** [comment]
Thanks @kelvinhb for the explanation.  I'll close out this issue now.
