### ISSUE TITLE
RCP emission

### ISSUE THREAD

**Issue by jiaying002** [geoschem/geos-chem#1847]
### Name and Institution (Required)

Name: Jiaying Li
Institution: Nanyang Technological University

### Description of your issue or question
I am trying to use RCP emission to get future 2030 and 2050 air quality results. However, I occurred a few issues:
1. In the wustl database (http://geoschemdata.wustl.edu/ExtData/HEMCO/RCP/v2020-07/), RCP emission had been removed. I wonder if there is anything wrong or if I need to pay attention to it.
2. I tried to use the RCP emission I downloaded before to run the simulations. I tried both MERRA and GCAP, they all occurred with errors. I wonder if it is possible to run RCP without all the other base emissions?

Thank you so much for reading my questions! Look forward to your reply!

**Comment by msulprizio** [comment]
@SaptSinha Can you point @jiaying002 to the RCP files at WashU? Were they moved to an archive directory? If so, perhaps we should include a README somewhere to let users know where to find them.

For your second question @jiaying002. Could you please be more specific about the errors? Specifically, if you would upload a copy of your HEMCO_Config.rc and log file with error messages then we can better assist you.

**Comment by SaptSinha** [comment]
Hello @msulprizio and @jiaying002, the RCP data in question has been archived a while ago. You can still retrieve it from this [Globus endpoint](https://app.globus.org/file-manager?origin_id=f0fdc722-de1d-11ed-9721-e54704575ba0&origin_path=%2F~%2F). 

If it is helpful, I can add this information as a README.txt file in the WashU RCP database.

**Comment by jiaying002** [comment]
@msulprizio @SaptSinha Thank you so much for your reply!

I got the same error when running with GCAP and MERRA-2. 
![image](https://github.com/geoschem/geos-chem/assets/113654537/9aa9bb46-8d50-438d-99ea-385b1b35a1ef)
[GC.log](https://github.com/geoschem/geos-chem/files/11882149/GC.log)

Here is the HEMCO_Config.rc for MERRA-2.
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/11882147/HEMCO_Config.rc.txt)
[HEMCO_Config.rc.gmao_metfields.txt](https://github.com/geoschem/geos-chem/files/11882141/HEMCO_Config.rc.gmao_metfields.txt)

Btw, would you plz give me a suggestion of if I should change the default setting of the non-emission data in HEMCO_Config.rc? (I checked https://hemco.readthedocs.io/en/latest/hco-ref-guide/hemco-config.html#hco-cfg, but I cannot find an answer...)

**Comment by jiaying002** [comment]
I've solved the previous error by changing the time cycle flag of NOAA_GMD_CH4 to CYS in HEMCO_Config.rc file. 

Then I occurred this new error:
![image](https://github.com/geoschem/geos-chem/assets/113654537/0aab7392-d53e-4c07-80d0-f7a25fe666e6)

For now, I need to generate 2030 and 2050 air quality distribution. From this error, it seems like the system wants me to use the CMIP6 emission data. However, CMIP6 doesn't include data for 2030 and 2050....
I may misunderstand the reason for this error. Would you please do me a favor of telling me what I should do?

**Comment by jiaying002** [comment]
@msulprizio @SaptSinha 
I still cannot solve this error by myself. Would you please give me some help?

Thanks a lot!

**Comment by msulprizio** [comment]
The error above is caused by the settings in these lines in your HEMCO_Config.rc:

```
GCAPSCENARIO:                not_used
```

When you set up a simulation for GCAP meteorology using `createRunDir.sh` it should automatically prompt you to select a scenario. The script will then set `GCAPSCENARIO` in HEMCO_Config.rc accordingly. See these lines of code for details:

https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/run/GCClassic/createRunDir.sh#L338-L416

Also see [Murray et al. (2021) ](https://gmd.copernicus.org/articles/14/5789/2021/gmd-14-5789-2021.pdf) for details on GCAP simulations.  The RCP emissions were implemented many GEOS-Chem versions ago and I'm not sure if they're still recommended for use. I would defer to the Emissions Working Group for that. As far as I know, if you want to simulate past/future emissions then the best option is currently to use GCAP2 as described in that paper.

**Comment by yantosca** [comment]
Closing out this issue
