### ISSUE TITLE
[QUESTION]Emission addition problems about GC-12.6.3 in subroutine DO_TEND

### ISSUE THREAD

**Issue by huoxiao-C** [geoschem/geos-chem#190]
## Ask your question here!

Hello,
     I am running full year CO2 simulation by GEOS-Chem 12.6.3 in 2016. I found some problems in here. The CO2 concentration value at the end of 2016 has no obvious upward trend relative to the CO2 value at the beginning of 2016. I found that the emissions read through HEMCO were added to the concentration of the GEOS-Chem in the **DO_TEND subroutine** of the **DO_MIXING module**,the code as follow :
          `  State_Chm%Species(I,J,L,N) = State_Chm%Species(I,J,L,N) 
                                             + FLUX`
I print the flux and State_Chm% Species values and find that a dynamic step size (10min) **FLUX** is generally 10 ^ -7, **State_Chm%Species** is generally 90,000, even if we calculate the amount of **FLUX** for a year, it is only 10 **-7 * 6 * 24 * 365 = 0.005, which is almost one ten-millionth of **State_Chm% Species**, but CO2 rises by about 2pmmv a year, which is two hundredth of the total atmospheric CO2 concentration, so should the **FLUX**  be multiplied by 10 * * 6? The code  as follow:
          `  State_Chm%Species(I,J,L,N) = State_Chm%Species(I,J,L,N) 
                                             + FLUX*10**6`
Would you please tell If I am wrong, thank you very much !

**Comment by yantosca** [comment]
Thanks for writing.  I took a look in do_tend. I think you are referring to this section of code in mixing_mod.F90, which is at about line 857:

```F90
             !--------------------------------------------------------------
             ! Apply emissions.
             ! These are always taken from HEMCO
             !--------------------------------------------------------------
             IF ( EmisSpec .AND. ( L <= EMIS_TOP ) ) THEN

                ! Get HEMCO emissions. Units are [kg/m2/s].
                CALL GetHcoVal ( N, I, J, L, FND, emis=TMP )

                ! Add emissions (if any)
                ! Bug fix: allow negative fluxes. (ckeller, 4/12/17)
                !IF ( FND .AND. (TMP > 0.0_fp) ) THEN
                IF ( FND ) THEN

                   ! Flux: [kg/m2] = [kg m-2 s-1 ] x [s]
                   FLUX = TMP * TS

                   ! Add to species array
                   State_Chm%Species(I,J,L,N) = State_Chm%Species(I,J,L,N) &
                                              + FLUX
                ENDIF
             ENDIF
```
The State_Chm%Species array at this point is in units of kg/m2 so the data coming in from HEMCO is also converted to kg/m2.

One thing I think we have to be careful of is making sure we do the comparison in the right units.  The units of flux are kg/m2 so that would have to be converted to ppmv for an apples-to-apples comparison.

I did a little test by printing out the value of FLUX everywhere it was nonzero, i.e
```F90
                   ! Flux: [kg/m2] = [kg m-2 s-1 ] x [s]
                   FLUX = TMP * TS
                   IF ( FLUX > 0 ) THEN
                      print*, '@@@: ', I, J, L, N, Flux
                   ENDIF
````
The values I got with an "out-of-the-box" CO2 run were typically of order 1e-9 to 1e-13.  Also, the "out-of-the-box" CO2 simulation uses a 10 minute dynamic timestep but a 20 minute (1200 sec) emissions/chemistry timestep.  This would result in:
```
365 [d] * 86400 [sec/d] * 1 [timestep/1200 s]  = 26280 emission timseteps
```
Then if we take the upper limit,  we add ~1e-9 kg/m2 on every emissions timestep or 1e-9 * 26280 = 2.628e-5 kg/m2 added over the course of a whole  year.  If we multiply that by the surface area of the earth (5.1e14 m2) this would result in 13.4 Tg of CO2 added per year.  That doesn't seem to be an unreasonable number.

I would recommend that you follow up with the Carbon Cycle Working Group (geos-chem-carbon@g.harvard.edu) if you still have questions. The GCST focuses more on the software development aspect of GEOS-Chem rather than on science.

**Comment by huoxiao-C** [comment]
Dear Bob:

Thanks for your reply. Yes, I think emission value is reasonable.In the subroutine it first converted kg/kg to kg/m2, then converted emission to kg/m2 and added it to the concentration, But concentration value is CO2 mass divided by air mass and multiplied by 10**6, Therefore I think the flux of emission should also be multiplied by 10**6, so that it is the same scale as the concentration.

**Comment by huoxiao-C** [comment]
Dear Bob:
       This problem is because when I processed the initial concentration data, I multiplied it by 10 * 6 without calculating it with the actual concentration.Thank you very much.
Best regards!
huoxiao

**Comment by yantosca** [comment]
No worries!  Thanks for letting me know. I'll close this issue out but let us know if you still have problems.
