### ISSUE TITLE
How to simplify the chemical mechanism when there are 'other products' in the reaction product

### ISSUE THREAD

**Issue by ximuzi0709** [geoschem/geos-chem#1908]
### Name and Institution (Required)

Name: Yali Li
Institution:Southern University of Science and Technology

I want to add some new species by modifying the custom mechanism of KPP, and when I add the gas-phase reaction in 'custom.eqn', I encounter some problems: referring to the product branching ratios evaluated in JPL19-5, there will be some other products, and I don't know how to balance the chemistry, e.g., HFC- 152a reacts with O1D, the yield of O3P is about (0.45± 0.15), the yield of OH is about (0.15± 0.02) also produces 'other products' about (0.18± 0.62). The simplified chemical mechanism I wrote as O1D + HFC152a ---> 0.6O + 0.6HFC152a + 0.17OH, but this is unbalanced, how do I change it?

   The version I am using is GC Classic 14.0.2, KPP 2.5.0. Looking forward to your answer!

**Comment by yantosca** [comment]
Thanks for writing @ximuzi0709.  This is something that the GCST doesn't have a lot of experience in.  Tagging @kelvinhb and @msl3v who may be able to give you some tips on balancing a rxn.  You might have to add some dummy species into the mechanism.

**Comment by ximuzi0709** [comment]
> 

Ok，thanks for your reply @yantosca .

**Comment by kelvinhb** [comment]
Hi @ximuzi0709, sorry for the delay! Depending on what you're trying to test, it's not necessarily a bad thing to leave the reaction imbalanced; for example, if you're just trying to test the effects of the O3P and OH pathways from this reaction, it would be reasonable to have those as the only products, in the JPL-recommended 0.45 and 0.15 branching ratios, and KPP would be able to compute it just fine even though it's imbalanced. If you for sure want to conserve carbon, you can add something unreactive like CO2 as a carbon-containing byproduct so that it doesn't interfere with other chemistry. But without knowing (or having a good hypothesis for) the other products, I don't think we can recommend any particular solution here that represents the "other products" explicitly.

**Comment by yantosca** [comment]
Closing out this issue
