### ISSUE TITLE
[FEATURE REQUEST] Updated 0.1x0.1 degree timezone file including daylight savings

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1928]
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### New GEOS-Chem feature or discussion

I am opening this issue on behalf of Karn Vohra (UCL; @karnvoh) who has developed an updated timezone file at 0.1x0.1 degree resolution and accounting for daylight savings. The existing timezone file in HEMCO_Config.rc is 1x1 degree resolution.

**Comment by eamarais** [comment]
Hi @msulprizio, I've attached a pdf of the slides prepared by @karnvoh that I wasn't able to show at the GCSC meeting on 19 Sept due to time constraints. The slides show sample benchmark output, a recommendation for implementing the updated timezone file to avoid gridscale changes to ship emissions, and a potential issue with the soil NOx emissions (these might be using timezones in error).
[timezone-slides-29Sept2023.pdf](https://github.com/geoschem/geos-chem/files/12671420/timezone-slides-29Sept2023.pdf)
