### ISSUE TITLE
[QUESTION] GEOS-Chem GTMM 

### ISSUE THREAD

**Issue by Gujing-Grace** [geoschem/geos-chem#193]
#72  Ask your question here!
l want to use GTMM to simulate the terrestrial- atmospheric Hg exchange. However, I cannot find the suitable run floder and GTMM Hg rst file (bpch) in the website. I wonder if there is a new verison of the GTMM code and run floder.

**Comment by yantosca** [comment]
Thanks for writing.  The GTMM option is currently not functional in the newer standard GEOS-Chem versions (I think since v9).  The original developers of the GTMM option have since left the GEOS-Chem community, and so that option has gone unsupported.  Because GTMM is a 3rd-party package, it is not directly supported by the GEOS-Chem Support Team (we look to the community for guidance instead).

Colin Thackray (@cpthackray) had been working on bringing GTMM up to a more recent version of GEOS-Chem.  I am not sure if the work ever progressed out of the research stage, but I think he can give you more details.

It might also be a good idea to contact the [Hg and POPs Working Group](http://wiki.seas.harvard.edu/geos-chem/index.php/Hg_and_POPs_Working_Group) to see if anyone else in the community has been working on GTMM.

**Comment by cpthackray** [comment]
GTMM is still definitely in the research stage. I'm working with a PhD student (Ben Geyman; @bgeyman) on it, but there are still science developments that need to be made to get it to a useful state for the community.

**Comment by Gujing-Grace** [comment]
I have found the rundir of GTMM v9-02. However, I still need one restart file named: HgPools. This file isn't in the rundir, so where can I find it?

**Comment by yantosca** [comment]
I will close out this issue as it seems like there is quite a way to go for GTMM to be included in GEOS-Chem again (especially since there is a new Hg simulation).  @bgeyman, feel free to open a new feature request/pull request.
