### ISSUE TITLE
Update the CH4 module to simulate N2O

### ISSUE THREAD

**Issue by lshen2009** [geoschem/geos-chem#1940]
### Name and Institution (Required)

Name: Lu Shen
Institution: Peking University

### Confirm you have reviewed the following documentation
- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)
Yes, I have.

### Description of your issue or question
Dear GCST,

I am trying to modify global_ch4_mod.F so that we can simulate N2O as well. Here, I need to compute the decay of N2O by hv and O1D. I have some difficulty in coding.

O1D + N2O = N2 + O2 :                        GCARR_ac(4.63d-11, 20.0d0);
I can write the decay rate of N2O as KRATE    = 4.63d-11_fp * EXP( 20.0_fp / State_Met%T(I,J,L)). Is there any archived O1D concentration that I can use? Or can we archive O1D? 

N2O + hv = N2 + O1D :                        PHOTOL(36);  
(1) I am not able to find the PHOTOL function from KPP. Could you help point to the right place?
(2) Where can I find the hv variable? Is it archived in State_Met?

Thank you!

**Comment by lshen2009** [comment]
Thanks, Melissa. Is there a timeline for the carbon simulation? Is N2O included?

**Comment by lshen2009** [comment]
Thanks @yantosca. I am looking forward to use the carbon simulation. For N2O, I still have one question. 

For the following reaction, I can write the reaction rate as KRATE = 4.63d-11_fp * EXP( 20.0_fp / State_Met%T(I,J,L)).
O1D + N2O = N2 + O2 : GCARR_ac(4.63d-11, 20.0d0);

But I don't know how to write out the reaction rate of the below reaction? Could you give me an example? 
N2O + hv = N2 + O1D : PHOTOL(36);

Thanks.

**Comment by yantosca** [comment]
Hi @lshen.  Thanks for the feedback.  The gas-phase rxn is no problem.  For the photo-reaction:

- You would have to get the reaction out of FAST-JX and then store it in the PHOTOL array, as we do with the fullchem and Hg simulations. 
- This would also mean activating the FAST-JX for the carbon simulation because as it stands now the photolysis is not activated. 
- You need to make a new folder in `CHEM_INPUTS/FAST_JX/` with the `FJX_j2j.dat`, etc. files that describe the optical properties for the photolysis.  Then you would need to point to this folder from the `geoschem_config.yml` file.

I would take a look at what is done for the Hg simulation in `GeosCore/mercury_mod.F90`, as this simulation does have photolysis.  That would be the blueprint to follow.

**Comment by lshen2009** [comment]
Thanks @yantosca. I thought the photolysis rate was determined by radiation, so it should be provided by meteorological fields. Is my understanding correct here?

When I go to the mercury_mod.F90, I find that the photolysis rate is provided by ZPJ. Does it mean I can use ZPJ(L,id_phot_N2O,I,J)?  Thanks.

USE Cmn_FJX_Mod,    ONLY : ZPJ
         ! Instantaneous JNO2
          J_NO2 = ZPJ(L,id_phot_NO2,I,J)
         ! Get JBrO
          JBrO     = ZPJ(L,id_phot_BrO,I,J)

**Comment by yantosca** [comment]
HI @lshen2009.  Photolysis rates are not provided by the met fields, but are computed by FAST_JX.  

The `ZPJ` array in indeed the array of J-values within FAST-JX.  However, in the versions 14.2.0/14.2.1, which will ship shortly (fingers crossed!), we have reorganized the interface of photolysis into GEOS-Chem so that we can eventually swap out FAST-JX with Cloud-J.  So a lot of the USE statements from `CMN_FJX_MOD.F90` will be going away soon.

Tagging @lizziel, who has been working on the updated photolysis code, who has the most up-to-date knowledge of photolysis in GEOS-Chem.

**Comment by yantosca** [comment]
Thanks @lshen2009.  You can look at the `GeosCore/carbon_gases_mod.F90` and follow what is done for e.g. `GLOBAL_OH`.  This reads OH concentrations from the prior GEOS-Chem 10-yr benchmark and there is code to grab that data from HEMCO via the routine `HCO_EvalFld`.

For now I do not think photolysis will be added to the carbon simulation.

**Comment by lshen2009** [comment]
Thanks @yantosca for these information!

**Comment by yantosca** [comment]
Closing out this issue.  Feel free to open a new issue.
