### ISSUE TITLE
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

### ISSUE THREAD

**Issue by petersherman123** [geoschem/geos-chem#1969]
### Name and Institution (Required)

Name: Peter Sherman
Institution: Harvard

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

I'm running three simulations using GEOS-Chem v13.4.0, and all three crashed in unison but at different simulation dates. I'm getting a seg fault (`Program received signal SIGSEGV: Segmentation fault - invalid memory reference.`) and the following error in my GC.log for each of them:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Nccl:  NetCDF: HDF error
     65536

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Any help on this would be much appreciated. Thanks!

**Comment by petersherman123** [comment]
One of the log files, for reference: 

[GC.log](https://github.com/geoschem/geos-chem/files/12729795/GC.log)

**Comment by yantosca** [comment]
Hi @petersherman123, thanks for writing.

As described in our 14,2.0-preview documentation (https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/error-guide.html#netcdf-hdf-error), when there is an error like this it can mean:

- The netCDF file that is being read is corrupted
- A netCDF file cannot be written to disk.  Usually this happens when you are over quota or if the destination directory is not executable.
- It might also indicate a cluster issue (failure of the disk during I/O)

**Comment by yantosca** [comment]
Closing out this issue
