### ISSUE TITLE
detailed information for different version of OH file

### ISSUE THREAD

**Issue by liuyuyu223** [geoschem/geos-chem#1994]
### Name and Institution (Required)

Name:Yu Liu
Institution:MIT

### Confirm you have reviewed the following documentation

- [ ] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion
There are 3 different version of OH files on http://geoschemdata.wustl.edu/ExtData/HEMCO/OH/. Don't know whether there are more detailed explanations for the three versions, such as, which years are these files good for?or whether the OH files are calibrated with observations?

**Comment by yantosca** [comment]
Thanks for writing.   the OH data is 

The `HEMCO/v2022-11/v5-07-08` files are recommended for e.g. methane, CO2, and carbon simulations, even though these are from an older version.  This is because the mean OH is more in line with observations than newer versions of the OH data.

The OH is from model output and is not calibrated to observations.

**Comment by yantosca** [comment]
The data in the v5-07-08 files have a lower mean OH (compared to observations) because later versions of GEOS-Chem introduced chemistry updates (such as secondary organic aerosols, halogen chemistry, etc.) that cause the mean OH to be higher (more like 12-13 x 10^5 molec/cm3).  By experience we have found that using OH from newer versions of GEOS-Chem adversely impacts e.g. CH4 inversions.

**Comment by yantosca** [comment]
Closing out this issue.  Feel free to open a new issue if you have any further questions.

**Comment by liuyuyu223** [comment]
Yes. Thank you so much.


From: Bob Yantosca ***@***.***>
Date: Tuesday, November 21, 2023 at 10:42 AM
To: geoschem/geos-chem ***@***.***>
Cc: Yu Liu ***@***.***>, Author ***@***.***>
Subject: Re: [geoschem/geos-chem] detailed information for different version of OH file (Issue #1994)

Closing out this issue. Feel free to open a new issue if you have any further questions.
