### ISSUE TITLE
[QUESTION] Add Met_RH to the wiki of History collections for met fields and related quantities?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#200]
Hi there,

I found that we can archive relative humidity (RH) via ND49 BPCH diagnostics. In this [wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/List_of_diagnostics_archived_to_bpch_format#ND49:_Instantaneous_timeseries), I found it has a netCDF equivalent (Met_RH), which I found is missing in this [wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/History_collections_for_met_fields_and_related_quantities). As it is a common met diagnostic, I think it might be great to add it to the latter wiki?

Also I found that Met_T2M is a netCDF equivalent for Tracer # for GAMAP = 5 in this [wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/List_of_diagnostics_archived_to_bpch_format#ND49:_Instantaneous_timeseries). However, I only found Met_TS in this [wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/History_collections_for_met_fields_and_related_quantities) as well as GC codes. I suppose they are almost the same? We do not have Met_T2M in GC 12.5.0? Similar issue goes to Met_XLAI in this [wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/List_of_diagnostics_archived_to_bpch_format#ND49:_Instantaneous_timeseries) while Met_LAI in this [wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/History_collections_for_met_fields_and_related_quantities).

Yours faithfully,,
Fei

**Comment by FeiYao-Edinburgh** [comment]
Also would like to know when will you possibly release equivalent netCDF diagnostics for ND51 and ND51b?

**Comment by yantosca** [comment]
No firm timeline as of yet.

**Comment by yantosca** [comment]
Also -- any of the fields in the State_Met object can be sent to HISTORY diagnostics, as either time-averaged, or instantaneous.  

Met_T2M is the surface temperature at 2M, which is used as a proxy for surface temperature.  Met_TS is the skin temperature (which can be much higher because it is right above the ground), and can cause ISOP emissions to be much too high.  

Met_XLAI is the LAI variable in State_Met (this can be either Yuan XLAI or Modis_XLAI).    Met_LAI is the LAI variable in the GEOS-FP or MERRA-2 meteorology, which does not have an annual variation (so we don't use it anymore).

**Comment by FeiYao-Edinburgh** [comment]
> Met_TS is the skin temperature

According to this description [here](http://wiki.seas.harvard.edu/geos-chem/index.php/History_collections_for_met_fields_and_related_quantities), Met_TS is the surface temperature while Met_TSKIN is the surface skin temperature?

By using `grep -in Met%T2M */*.F*` I found no return. Does this mean Met_T2M is unavailable through HISTORY.rc? I will try to test it later...

I agree with your explanation on Met_XLAI and Met_LAI. I just do not found Met_XLAI in this [wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/History_collections_for_met_fields_and_related_quantities), though.

**Comment by yantosca** [comment]
In GeosCore/flexgrid_read_mod.F we have:

https://github.com/geoschem/geos-chem/blob/00e12f6bc04870dbfdb959bcf1e3cd0068c8ab35/GeosCore/flexgrid_read_mod.F90#L482-L490

Due to some historical baggage, 
1. The T2M field from the data file is copied into State_Met%TS field
2. The TS field from the data file is copied into State_Met%TSKIN

This goes back to when we were supporting 3 or 4 different types of GMAO met field products. This was necessary in order to get consistent quantities among differently-defined met fields.

**Comment by lizziel** [comment]
The quickest and easiest way to find if you can get diagnostic `Met_xxx` is by searching the GEOS-Chem code for variable `State_Met%xxx`. I did this for T2M using grep and found zero results. Adding `Met_T2M` to HISTORY.rc will therefore not be possible.

To find the definition of meteorology fields you can also look at the source code, in file `Headers/state_met_mod.F90`. In that file you can search for the `xxx `in diagnostic `Met_xxx` that you want. For example, for TS the first hit is:

`REAL(fp), POINTER :: TS            (:,:  ) ! Surface temperature [K]`

We try our best to keep the wiki up-to-date. However, sometimes we can only put partial information on the wiki and rely on users to also look at the code for more details.

**Comment by lizziel** [comment]
I also want to add that you can create a wiki account for yourself and be able to edit the wiki. Click on request account at the upper right corner. If there is something you think should be there that would be helpful to others we welcome you to add it in.

**Comment by FeiYao-Edinburgh** [comment]
> I also want to add that you can create a wiki account for yourself and be able to edit the wiki.

Thanks for letting know! I believe this can help discussion on wiki.

**Comment by lizziel** [comment]
Thanks @yantosca! It seems another useful reference is here on the wiki: [http://wiki.seas.harvard.edu/geos-chem/index.php/List_of_GEOS-FP_met_fields](http://wiki.seas.harvard.edu/geos-chem/index.php/List_of_GEOS-FP_met_fields).
