### ISSUE TITLE
Missing GEOS_FP data from geoschemdata.wustl.edu

### ISSUE THREAD

**Issue by jaeinjeong** [geoschem/geos-chem#2090]
### Name and Institution (Required)

Name: Jaein Jeong
Institution: Seoul National University

### Confirm you have reviewed the following documentation

- [O] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [O] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [O] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [O] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

The GEOS_0.5x0.625_AS GEOS_FP data from December 2019 through August 2020 could not be found on the http://geoschemdata.wustl.edu/ server.

**Comment by yidant** [comment]
Hi @jaeinjeong , thanks for asking! Could you please check if you need MERRA2 instead of GEOS-FP? We didn't maintain this GEOS-FP data because MERRA-2 native resolution is 0.5 x 0.625, so no regridding is needed. Also, GEOS-FP is an operational product whereas MERRA-2 is done with a frozen GCM version. 

Please let me know if you need GEOS-FP for a particular reason. We can look into it.

**Comment by yantosca** [comment]
Closing out this issue
