### ISSUE TITLE
GEOS-CF: Guidance on comparing "pm25_rh35_gcc" with measurements

### ISSUE THREAD

**Issue by tanksnr** [geoschem/geos-chem#2099]
### Name and Institution (Required)

Name: Mogesh Naidoo
Institution: CSIR (South Africa)

### Confirm you have reviewed the following documentation

- [ x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Hi all, 

I was wondering if anyone has experience comparing GEOS-Chem output PM2.5 with measurements. 
I am specifically using the GEOS-CF product at https://opendap.nccs.nasa.gov/dods/gmao/geos-cf/assim/ and looking at the provided variable pm25_rh35_gcc. 
Looking at http://wiki.seas.harvard.edu/geos-chem/index.php/Particulate_matter_in_GEOS-Chem, it seems there are quite a few modifications made to PM2.5 output. 
My issue is that the GEOS output (pm25_rh35_gcc) over-estimates by a very large degree over my region. 
I would like then to consider PM2.5 that has not gone through the process of RH and growth adjustments. 
Does this output readily exist? Or should I work backward to a non-adjusted value using other variables available?

regards,
Mogesh.

**Comment by christophkeller** [comment]
Hi Mogesh,
PM2.5 in GEOS-CF (version 1.0) is known to be biased high, as described in the [GEOS-CF description paper](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2020MS002413) (see section 3.6). 
We think this is due to a combination of the chemistry mechanism (v12.0.1), outdated anthropogenic emission inventories, and excessive biomass burning emissions.
We are in the process of updating GEOS-CF and expect that bias to be reduced significantly in CFv2.

If you have further questions, feel free to reach out to me directly: christoph.a.keller@nasa.gov

**Comment by yantosca** [comment]
Thanks @christophkeller and @tanksnr. I can close out this issue as it is pertains to GEOS-Chem in GEOS-CF.  Please correspond directly with @christophkeller as directed.  Happy New Year!
