### ISSUE TITLE
Can I get 3D budget (in fixed vertical altitude) instead of 2D budget?

### ISSUE THREAD

**Issue by linguo4** [geoschem/geos-chem#2132]
### Name and Institution (Required)

Name: Lin Guo
Institution: University of Illinois Urbana-Champaign

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
I'm seeing that you are adding the budget for flexible layer height. I need the budget for each cell on different altitudes (making it 3D) instead of the whole column. Is it possible to add this feature? Or is there any way I can get this?
GEOS-Chem version: 14.1.1

**Comment by lizziel** [comment]
Hi @linguo4, you could make changes to the existing full column diagnostic to be 3D rather than 2D by updating `Headers/state_diag_mod.F90` and `GeosCore/diagnostics_mod.F90`. The first file is where the arrays are declared and initialized and the second contains the subroutine that sets them by summing over levels. No changes would be needed within `HISTORY.rc`. Alternatively you could create a new diagnostic for this by copying and adapting code in those files.

The new budget for fixed layers will be limited to only one range per run.

**Comment by yantosca** [comment]
Closing out this issue

**Comment by zpleo** [comment]
@lizziel @linguo4 Hello, can you convert Budget output into 3D? How did you modify the code? Can you give me some reference? Thank you very much.

**Comment by lizziel** [comment]
@zpleo, the budget diagnostics are column only. You can implement your own 3D diagnostic by creating a new `State_Diag` array in `state_diag_mod.F90` and adding code to fill it within subroutine `Compute_Budget_Diagnostics` in `diagnostics_mod.F90`. For more information about adding new diagnostics see [GEOS-Chem ReadTheDocs section on adding new history diagnostics](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/history-diag-guide.html#adding-new-history-diagnostics).
