### ISSUE TITLE
GCHP fullchem simulation fails when switch on CMIP6_SFC_CH4

### ISSUE THREAD

**Issue by hazel008** [geoschem/geos-chem#2175]
### Name and Institution (Required)

Name: Hansen Cao
Institution: University of York

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.
Hi, I am running a fullchem simulation using GCHP14.2.2. It runs fine when I have GMD_SFC_CH4=true and CMIP6_SFC_CH4 =false. But it fails at the beginning, when I have GMD_SFC_CH4=false and CMIP6_SFC_CH4 =true. I would like to run a simulation representing the pre-industrial condition, that's why I want to use CMIP6_SFC_CH4, which has pre-industrial CH4 concentration. I have tried setting the CRE flat in HEMCO_Config.rc to RY, RF, and CYS as shown below, none of them works. 
 CMIP6_Sfc_CH4  $ROOT/CMIP6/v2020-03/2x2.5/CMIP6_GHG_surface_VMR_$YYYY.2x25.nc CH4 1750-1978/1-12/1/0 CYS xy ppbv * - 1 1 
Can you please help me? Thank you!
[STD_anthOFF_3780440.log](https://github.com/geoschem/geos-chem/files/14485814/STD_anthOFF_3780440.log)

I am also attaching my GCHP log file here.

**Comment by lizziel** [comment]
Hi @hazel008, the error message in your log file is this:
`pe=00076 FAIL at line=00803    ExtDataGridCompMod.F90                   <Found   1 unfulfilled imports in extdata>`

This indicates an error in the MAPL ExtData component which handles I/O. The `ExtData.rc` config file contains the list of imports to the model. In GCHP the imports needed by HEMCO are listed in `HEMCO_Config.rc` but they are defined in `ExtData.rc`, including filepath, read frequency, etc. The error message means that one of the expected imports configured in `HEMCO_Config.rc` was not found in `ExtData.rc`.

The error log associated with ExtData is called `allPEs.log`. Does that log file give any additional information? If not you can enable maximum ExtData prints within config file logging.yml in this section:
```
   CAP.EXTDATA:
       handlers: [mpi_shared]
       level: WARNING
       root_level: INFO   <=== Change this to DEBUG
```

Also see the following sections of GCHP ReadTheDocs:

- [Description of how HEMCO_Config.rc is used in GCHP, including what parts are ignored](https://gchp.readthedocs.io/en/stable/user-guide/config-files/HEMCO_Config_rc.html)
- [Description of config file ExtData.rc](https://gchp.readthedocs.io/en/stable/user-guide/config-files/ExtData_rc.html)
- [Description of config file logging.yml](https://gchp.readthedocs.io/en/stable/user-guide/config-files/logging_yml.html)
- [How to turn on/off emission inventories](https://gchp.readthedocs.io/en/stable/user-guide/rundir-config.html#turn-on-off-emissions-inventories)
- [Add new emissions files (might be relevant since no one has used CMIP6 with GCHP before to my knowledge)](https://gchp.readthedocs.io/en/stable/user-guide/rundir-config.html#add-new-emissions-files)
- [GCHP debugging page, including maximizing prints sent to logs](https://gchp.readthedocs.io/en/stable/user-guide/debugging.html)

**Comment by hazel008** [comment]
Hi @lizziel , Thanks for the quick response! 
I tried you suggestions and enabled the maximum ExtData prints within the file logging.yml and found out why the run failed. It was because the following line in ExtData.rc was commented out:
CMIP6_Sfc_CH4 ppbv N Y F%y4-%m2-01T00:00:00 none none CH4 ./HcoDir/CMIP6/v2020-03/2x2.5/CMIP6_GHG_surface_VMR_%y4.2x25.nc

Now I have uncommented it and the simulation runs fine.
I have another question regarding the flag in the HEMCO_Config.rc:
 CMIP6_Sfc_CH4  $ROOT/CMIP6/v2020-03/2x2.5/CMIP6_GHG_surface_VMR_$YYYY.2x25.nc CH4 1750-1978/1-12/1/0 EY xy ppbv * - 1 1

The flag is EY by default. My simulation year is 2022. If I want to drive the simulation using CMIP6_SRC_CH4 from pre-industrial years, which are the years before 1979, what flag should I use? As I understand, EY means the simulation year should be exactly the same year of NetCDF files, do I need to generate a NetCDF file specifically for the year of 2022 using the CH4 concentrations from the year 1978?
Thanks!

**Comment by hazel008** [comment]
@lizziel ,Sorry, typo error, I want to use CH4 concentration from the year of 1750 to drive the simulation for the year of 2022. Just wondering what flag should I use for the following line in HEMCO_Config.rc: 
CMIP6_Sfc_CH4 $ROOT/CMIP6/v2020-03/2x2.5/CMIP6_GHG_surface_VMR_$YYYY.2x25.nc CH4 1750-1978/1-12/1/0 EY xy ppbv * - 1 1
Thanks!

**Comment by lizziel** [comment]
Hi @hazel008, those flags in `HEMCO_Config.rc` are ignored in GCHP. See the [HEMCO_Config.rc page of ReadTheDocs](https://gchp.readthedocs.io/en/stable/user-guide/config-files/HEMCO_Config_rc.html) to learn what is used and what is not. Everything not used in `HEMCO_Config.rc` is in `ExtData.rc` for GCHP.

In the past we have run into an ESMF issue reading ExtData.rc because the file was too long. Commented out lines reduces the effective length. For this reason we comment out emissions that are not used by default in GCHP. As a courtesy they are still (mostly) included so you do not need to add optional inventories from scratch.

To use only 1750 CMIP6 data for later years you can configure it to use that year as climatology. Change this in ExtData.rc:
CMIP6_Sfc_CH4 ppbv N Y F%y4-%m2-01T00:00:00 none none CH4 ./HcoDir/CMIP6/v2020-03/2x2.5/CMIP6_GHG_surface_VMR_%y4.2x25.nc
to this:
CMIP6_Sfc_CH4 ppbv Y Y F2022-%m2-01T00:00:00 none none CH4 ./HcoDir/CMIP6/v2020-03/2x2.5/CMIP6_GHG_surface_VMR_2022.2x25.nc

**Comment by lizziel** [comment]
Hi @hazel008, were you able to resolve your issue?

**Comment by yantosca** [comment]
Closing out this issue
