### ISSUE TITLE
[BUG/ISSUE] Bug when running with TOMAS and chemistry time step under 1 hr

### ISSUE THREAD

**Issue by danamcguff** [geoschem/geos-chem#218]
## Describe the bug
In AEROPHYS subroutine of tomas_mod, the overall time step is 1 hour.
Here is a permalink to the hard-coded bug: https://github.com/geoschem/geos-chem/blob/6048e585ddab0dc4afd5eee0035c96e6d1f28fa6/GeosCore/tomas_mod.F#L703-L711
I suggest changing the definition of the time step so line 704 reads:
``` ADT     = GET_TS_CHEM() ```
You will also need to add a line of code to the beginning of AEROPHYS subroutine such as:
``` USE Time_Mod,    ONLY : GET_TS_CHEM ```

## Expected behavior
When running GC with TOMAS on and using a time step smaller than 1 hour for chemistry, the simulated aerosol microphysics are faster than they should be.

## Required information
 - GEOS-Chem version : discovered in 12.3.2 but also in current release (12.7.0)

**Comment by yantosca** [comment]
Thanks @danamcguff for bringing this to our attention.  This is now fixed by commit https://github.com/geoschem/geos-chem/commit/7a7f3d757e661a0a24b18ec366a94bb2ce69d5e4, which will go into GEOS-Chem 12.7.1.  

I also made a couple more updates as seen here: https://github.com/geoschem/geos-chem/blob/7a7f3d757e661a0a24b18ec366a94bb2ce69d5e4/GeosCore/tomas_mod.F#L670-L701

1. I moved ADT out of the parallel loop, since it does not need to be held PRIVATE (i.e. its value is the same for all threads).  This will prevent calling the `GET_TS_CHEM` function on each (I,J,L) iteration.

2. I had to add an IF statement around the `AD61_INST` array.  This will prevent a segfault if ND61 is not turned on.
