### ISSUE TITLE
How to turn off the secondary source of HCHO in the GEOS CHEM model

### ISSUE THREAD

**Issue by yanzx123** [geoschem/geos-chem#2216]
### Name and Institution (Required)

Name:Zhuoxian Yan
Institution:SUSTech

### Description of your issue or question
I want to analyze the influence range of terrestrial HCHO on HCHO over the ocean. I run a default GEOSCHEM model, and then I intend to run a version with both primary and secondary emissions of HCHO turned off in GEOSCHEM (14.0.2)

**Comment by yantosca** [comment]
Thanks for writing @yanzx123.  I suspect this would require modification of the KPP mechanism.  You can find general instructions on how to do that here: 

- https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/using-kpp-with-gc.html

We are not experts in chemistry, however.  Perhaps the Chemistry Working Group would be able to point you in the right direction.  Tagging Chemistry WG Co-Chairs: @barronh @luhu0 @jingqiumao.

**Comment by yanzx123** [comment]
Thank you very much for your helpful reply，I am learning KPP mechanism.

**Comment by barronh** [comment]
@yanzx123 I read your initial description and I want to make sure I understand before responding.

Primary and secondary are often used to refer to emissions (primary) and reaction products of other emitted species (secondary). In some cases, emissions actually include some secondary (i.e., reaction products) rather than the explicit compounds.

So when you say:

> run a version with both primary and secondary emissions of HCHO turned off in GEOSCHEM (14.0.2)

Do you mean with *ALL* emissions disabled? Or do you mean removing all emissions and all formaldehyde produced from any/all VOC? What about from methane?

It would likely be difficult to disable formaldehyde from just some VOC species. I say that because VOCs often share radical products in the mechanism that go on to make formaldehyde. If you disable the formaldehyde from an radical, it disables the formaldehyde from all species that make that radical. For example, MO2 is the methyl peroxy radical and it reacts with NO to create formaldehyde. MO2 is also produced by other VOC and radical reactants. So, if you wanted to keep formaldehyde from methane... that would be difficult.

If you plan to remove all formaldehyde products, I assume that you will still want the reactant species to be consumed. In that case, you set the stoichiometry to 0 for all CH2O products in all reactions. Then rebuild the mechanism following the instructions that @yantosca linked to.

I'll just note that so many VOCs create formaldehyde during their oxidation pathway. And, all that formaldehyde creates carbon monoxide. If you "turn off" the formaldehyde, the atmosphere might be kind of weird.

If I am misunderstanding you, please clarify.

**Comment by yantosca** [comment]
Closing out this issue
