### ISSUE TITLE
[QUESTION] Running the complexSOA_SVPOA simulation with biomass burning emissions form GFAS

### ISSUE THREAD

**Issue by MaggieMarvin** [geoschem/geos-chem#222]
Hi, I'm running the complexSOA_SVPOA simulation using GEOS-Chem v12.5.0 with biomass burning emissions from GFAS. But the out-of-the-box simulation setup seems to be producing biomass burning emissions that are much too low (almost negligible). I took a closer look at the HEMCO_Config.rc file (attached as txt), and it seems that the diurnal scaling factors from QFED (75) are applied to these emissions rather than the scaling factors that are specific to GFAS (300). Is this an error, and has it been corrected in later versions of GC?

[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/4182389/HEMCO_Config.txt)

**Comment by MaggieMarvin** [comment]
Oops, the txt file looks like it's been cut off. Maybe this will work?
[HEMCO_Config.log](https://github.com/geoschem/geos-chem/files/4182513/HEMCO_Config.log)

**Comment by lizziel** [comment]
Hi Maggie,

Use of the QFED (75) diurnal scale factors is intentional. The GFAS (300) scale factors are not diurnal scale factors, but are the mean altitude of maximum injection, variable `mami` in the GFAS files. They are used in the SrcDim column entry `xyL=1:scal300` for each GFAS variable in HEMCO_Config.rc.

When we received the data we also received some extra information from Killian Murphy (York) about the inventory. Here are the answers to a couple questions we got information on.

1. Is this data meant to replace another existing data set? Or it meant to be used as a research option?
 
Assuming that GFED remains as the primary biomass burning inventory, this is meant to be used as a research option
 
2. What scale factors (annual, monthly, daily, weekday/weekend) need to be applied to the data?
 
For the following variables, the QFED diurnal profile (HEMCO scaling factor 75) was used as a scaling factor:
 
    cofire, noxfire, bcfire, bcfire, ocfire, ocfire, co2fire, ch4fire, so2fire, nh3fire, c3h6ofire, c2h4ofire, hialkanesfire, hialkenesfire, c3h6fire, c2h6fire, c3h8fire, ch2ofire, c2h4fire, c5h8fire, c2h6sfire, c7h8fire, c6h6fire, c8h10fire
 
For the following variables, a speciation of hydrophilic and hydrophobic fraction was used. The HEMCO scaling factor number is noted after the variable name:
 
    bcfire (70), bcfire (71), ocfire (72), ocfire (73)
 
All variables were distributed vertically using a new scale factor, derived from the mami variable contained within the GFAS data files.

**Comment by MaggieMarvin** [comment]
Hi Lizzie,

Thanks very much! This helps to clarify a lot. The simulation I'm running is for 2018, and I've chosen to use GFAS as we've found the GFED emissions to be a bit unreliable for the years after 2016. Any thoughts on this, and which inventory you would recommend for these years?

A couple of quick follow-up questions: In order to use GFAS with the complexSOA_SVPOA chemistry, it looks like I need to add GFAS emissions tracers for POG1 and POG2... would these tracers be calculated from ocfire? And would any additional scaling factors need to be applied beyond the injection heights (300) and the QFED diurnal scaling factors (75)?

Best,
Maggie

**Comment by yantosca** [comment]
Thanks for writing. In answer to your questions:

1. You might want to ask the Emissions Working Group for recommendations on biomass burning inventories after 2016.   This is outside of the GCST's expertise.  GFAS is probably an OK option but there will be differences w/r/t GFED.

2. I think that the POG1 and POA1 would come from GFAS ocfire.  In the complex_SOA simulations we swap those in for OCPO and OCPI.

3. For the scaling factors, I would again ask the Emissions Working group.

**Comment by MaggieMarvin** [comment]
Ok, thanks Bob and Lizzie! I will follow up with the Emissions Working Group.
Best, Maggie
