### ISSUE TITLE
Free run with GEOS-Chem

### ISSUE THREAD

**Issue by croy64** [geoschem/geos-chem#2220]
### Name and Institution (Required)

Name: C Roy
Institution: IITM, Pune, India

### Description of your issue or question

I am trying to make a free-run with GEOS-Chem, and not a nudged-run. What are the steps to do that?
Thank you.

**Comment by yantosca** [comment]
@croy64: Are you using GEOS-Chem within CESM?  Tagging @lizziel

**Comment by croy64** [comment]
Can we run GEOS-Chem with input from any CMIP6 GCM?

**Comment by croy64** [comment]
Any updates on this question: Can we run GEOS-Chem with input from any CMIP6 GCM?

**Comment by msulprizio** [comment]
Hi @croy64. You should be able to do this as long as the input files are compatible with HEMCO. See the [HEMCO guide](https://hemco.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/coards-guide.html) for details.

I'm tagging @ltmurray, one of the Chemistry-Climate Working Group Chairs. He may have some advice on this.

**Comment by ltmurray** [comment]
At present, GEOS-Chem may be run in the following free-running models: CESM2 and WRF.  Otherwise, one is limited to using the archived meteorology from the GEOS-DAS reanalyses (e.g., MERRA2) or the CMIP6 runs from the GISS model as part of the GCAP2 project (Murray et al., GMD, 2021). The standard CMIP6 simulations do not archive sufficient temporal resolution or fields to drive GEOS-Chem, so one would need to re-run those simulations saving the necessary input fields as was done for GCAP2.

**Comment by yantosca** [comment]
Closing out this issue
