### ISSUE TITLE
O3 simulation problem

### ISSUE THREAD

**Issue by CraigYEUNG** [geoschem/geos-chem#2256]
I found that using default Restart file of 20190701 to simulate for one month, the O3 Concentration of restart file 0801 is much higher than the 0701's. And I compare it to the result by GEOS-Chem v12.9.3, the O3 concentration is about 50% higher. I also compare it to the  Restart file of Oxidant Field simulated from V14.0.0. 

all in all, the simulation O3 concentration of 0801 by v 14.3.0 and v13.4.0, is much higher than the oxidant field file in aeresol mode HEMCO reading. 
I think my simulation is wrong but don't know where and how to fix it.

![a33ec4c2a3cd0878806cac646e8d261](https://github.com/geoschem/geos-chem/assets/112837821/435eb2a4-1d9f-448e-b713-521198e33d43)

**Comment by yantosca** [comment]
Thanks for writing @CraigYEUNG.  There have been several updates that affect chemistry between GEOS-Chem versions 12.9.3 and 14.3.0.  The changes that you are seeing more than likely are caused by these updates.  Please see the [GEOS-Chem versions wiki page](http://wiki.geos-chem.org/GEOS-Chem_versions) for more information.

**Comment by CraigYEUNG** [comment]
Thanks for replying. But simulation surface O3 Concentration result in v14.3.0 fullchem, is 60% higher than oxidant-field file read by aerosol-only mode. Both of them are in the same date. I wonder if it is reasonable.
