### ISSUE TITLE
Bugs in GC Version 14.0.1

### ISSUE THREAD

**Issue by ChangpeiHe** [geoschem/geos-chem#2273]
### 

Name: He, Changpei
Institution: Tsinghua University

I confirm that I have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

When I run "./gcclassic --dryrun | tee log.dryrun" in GC 14.0.1 version, some issues occurred: 
![image](https://github.com/geoschem/geos-chem/assets/126058879/59d7be12-e927-4881-a972-88e80ce34d6b)

However, this issue won't occur in newer version (e.g., version 14.2.3).

Looking forward to your reply!

**Comment by yantosca** [comment]
Thanks for writing @ChangpeiHe.  If the issue doesn't happen in version 14.2.3, I would suggest that you use that version going forward.  There have been a few bug fixes for the dry-run simulation since 14.0.1, which is by now almost 2 years old.  See: https://github.com/geoschem/geos-chem/issues?q=is%3Aissue+label%3A%22topic%3A+Dry-Run+Simulation%22+

**Comment by ChangpeiHe** [comment]
Thanks for your prompt reply!
