### ISSUE TITLE
Where can I find the GEOSChemv13.3.2 user manual?

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#2278]
### Name and Institution (Required)

Name: Ning Yang
Institution: JNU

### Confirm you have reviewed the following documentation

- [ ] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion

Please provide a clear and concise overview of the discussion topic or new feature requested.

Where can I find the GEOSChemv13.3.2 user manual?

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  We have since retired the GEOS-Chem manual on the wiki page, as this has been superseded by ReadTheDocs.

Most of the information pertaining to 13.3.2 is probably similar to the latest manual that we have in the archive, if you would like to look at that;

- https://geoschem.github.io/gcclassic-manpage-archive/man.GC_12/index.html

Also information about e.g. the dry-run simulation and data portals is can be found at the current manual pages:

- https://geos-chem.readthedocs.io

**Comment by yangning-code** [comment]
Thank you very much @yantosca. 
I still have some needs, that is, I want the PDF manual of version 13.3.2 or the entire version 13. The reasons are as follows:
First of all, I saw on https://geos-chem.readthedocs.io that the PDF documents for 14.0.0-14.3.1 can be downloaded. I believe there are still some differences between each version. In addition, at https://geoschem.github.io/gcclassic-manpage-archive/man.GC_12/index.html is the manual for versions prior to 13.0.0. Last but not least, I am using the 13.3.2 manual and urgently need the corresponding version of the manual.
I hope you can help me, thank you again

**Comment by yangning-code** [comment]
Sorry, I want to ask if there is no manual for GEOS-Chem version 13？

**Comment by yangning-code** [comment]
I only want the manual for  GEOS-Chem Version 13
