### ISSUE TITLE
GEOS-CHEM ERROR:  Excessive fall velocity? STOP at  CALC_FALLVEL, UCX_mod

### ISSUE THREAD

**Issue by XunZhangNJU** [geoschem/geos-chem#2311]
### Your name

XunZhang

### Your affiliation

Nanjing University

### What happened? What did you expect to happen?

When I run the full chemistry model using GEOS-Chem 14.4.0, the following error is reported, GEOS-CHEM ERROR:  Excessive fall velocity? STOP at  CALC_FALLVEL, UCX_mod

### What are the steps to reproduce the bug?

When I run the full chemistry model using GEOS-Chem 14.4.0, the following error is reported：
```console
********************************************
* B e g i n   T i m e   S t e p p i n g !! *
********************************************

     - Creating file for BoundaryConditions; reference = 20000101 000000
        with filename = OutputDir/GEOSChem.BoundaryConditions.20000101_0000z.nc4
---> DATE: 2000/01/01  UTC: 00:00
 HEMCO already called for this timestep. Returning.
 Getting CH4 boundary conditions in GEOS-Chem from :NOAA_GMD_CH4
HEMCO (VOLCANO): Opening /home/sdc1/data/GCClassic/ExtData/HEMCO/VOLCANO/v2021-09/2000/01/so2_volcanic_emissions_Carns.20000101.rc
     - DO_LINEAR_CHEM: Linearized chemistry at 2000/01/01 00:00
     - LINOZ_CHEM3: Doing LINOZ
===============================================================================
GEOS-CHEM ERROR:  Excessive fall velocity?
STOP at  CALC_FALLVEL, UCX_mod
===============================================================================
===============================================================================
GEOS-CHEM ERROR:  Excessive fall velocity?
STOP at  CALC_FALLVEL, UCX_mod
===============================================================================
===============================================================================
GEOS-CHEM ERROR:  Excessive fall velocity?
STOP at  CALC_FALLVEL, UCX_mod
===============================================================================
===============================================================================
GEOS-CHEM ERROR:  Excessive fall velocity?
STOP at  CALC_FALLVEL, UCX_mod
```
Based on previous issues, I have modified the transport time from 600 to 300 seconds and the chemistry time from 1200 to 600 seconds. However, this error still persists.

Why does this error occur, and how can it be resolved? Thanks.

### Please attach any relevant configuration and log files.

Here is my HEMCO_Config.rc and HISTORY.rc
[geoschem_config.yml.txt](https://github.com/user-attachments/files/15604480/geoschem_config.yml.txt)
[HEMCO_Config.rc.gmao_metfields.txt](https://github.com/user-attachments/files/15604482/HEMCO_Config.rc.gmao_metfields.txt)
[HEMCO_Config.rc.txt](https://github.com/user-attachments/files/15604483/HEMCO_Config.rc.txt)
[HISTORY.rc.txt](https://github.com/user-attachments/files/15604484/HISTORY.rc.txt)

### What GEOS-Chem version were you using?

14.4.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

ifort 2023

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

2x2.5

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment]
Thanks for writing @XunZhangNJU,  I noticed you have this setting in your `geoschem_config.yml` file:
```yaml
    input_directories:
      fastjx_input_dir: /home/sdc1/data/GCClassic/ExtData/CHEM_INPUTS/FAST_JX/v2021-10/
```
But the proper setting is:
```console
    input_directories:
      fastjx_input_dir: /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData/CHEM_INPUTS/FAST_JX/v2024-05/
```
This is because a relative humidity dependence has been added into the `org.dat` and `so4.dat` files in the `FAST_JX/v2024-05/` folder.  What I think is happening is that your code is reading incorrect aerosol information that is leading to this error.

Also... did you create a new run directory from the 14.4.0 code?  Or were you "recycling" an old run directory?  We always recommend creating a new run directory whenever you update versions so that the configuration files will be consistent with that version of the model.

**Comment by XunZhangNJU** [comment]
That's make sense, thanks for your time and support.

**Comment by yantosca** [comment]
Thanks @XunZhangNJU. Feel free to close out this issue if your problem is resolved now.

**Comment by yantosca** [comment]
Closing out this issue.

**Comment by fangzhoupig** [comment]
I had same issue. I tried change the path of fast j and the time steps.  Neither works. Could anyone give some tips?

**Comment by madhumitamahant** [comment]
Initializing Fast-JX v7.0 standalone CTM code.
FAST-JX (RD_XXX): REQUIRED FILE NOT FOUND /path/to/ExtData/CHEM_INPUTS/FAST_JX/v2024-05/FJX_spec.dat
===============================================================================
GEOS-Chem ERROR: FAST-JX (RD_XXX): REQUIRED FILE NOT FOUND /path/to/ExtData/CHEM_INPUTS/FAST_JX/v2024-05/FJX_spec.dat
-> at RD_XXX (in module GeosCore/fast_jx_mod.F)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in FAST-JX routine "RD_XXX"!
 -> at Init_FastJX (in module GeosCore/fjx_interface_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "Init_FastJX"!
 -> at Init_Photolysis  (in module GeosCore/photolysis_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "Init_Photolysis"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================
     - CLEANUP: deallocating arrays now...
even after done what you mentiioned , I am facing this error

**Comment by madhumitamahant** [comment]
===============================================================================
GEOS-CHEM ERROR:  Excessive fall velocity?
STOP at  CALC_FALLVEL, UCX_mod
===============================================================================
===============================================================================
GEOS-CHEM ERROR:  Excessive fall velocity?
STOP at  CALC_FALLVEL, UCX_mod
===============================================================================
     - CLEANUP: deallocating arrays now...

**Comment by JFBrewer** [comment]
Hi GCST

I'm having this problem again, newly in GEOS-Chem 14.7.0. I've attached HEMCO_Config.rc, geoschem_config.yml, and GC.log. 

Just to get the obvious ones out of the way: I started with a restart file for 14.7.0 from the WashU repository for 20190101, but did shifttime,-4years to get 20150101 because I knew I'd need to spinup anyway. The run directory is brand new, generated from src as per expectation.

Checking the CHEM_INPUT path as recommended above and changing out timesteps to 300/600 instead of 600/1200 also made no difference.

Thanks in advance for helping me figure out whatever dumb error I've made!

[GC.log](https://github.com/user-attachments/files/26122472/GC.log)
[geoschem_config.yml](https://github.com/user-attachments/files/26122471/geoschem_config.yml)

[HEMCO_Config.rc.txt](https://github.com/user-attachments/files/26122476/HEMCO_Config.rc.txt)

**Comment by JFBrewer** [comment]
Also, just following up with further checks here - this problem occurs regardless of the use of 47 vs 72 vertical layers.

**Comment by JFBrewer** [comment]
Also also, just in case you get curious, the use of `/users/5/brewe222/shared/data/geos-chem/ExtData/CHEM_INPUTS/` vs `/scratch.global/milletd/shared/data/geos-chem/ExtData/CHEM_INPUTS/` does not make a difference here. Those are symlinked, but in any case I swapped it out without effect.

**Comment by JFBrewer** [comment]
I have discovered the source of my error, and you will not believe how dumb it was. I downloaded the 20190101 fullchem restart file from `/GEOSCHEM_RESTARTS/GC_14.7.0/` on the WashU repo. Conveniently, this restart file is named `GEOSChem.Restart.**fullchem**.20190101_0000z.nc4`. 

Because I am A Sheep and prone to typos when I write things myself, I simply mindlessly copied this name format when I used `cdo shifttime`. Consequently, when my code looked for `GEOSChem.Restart.20150101_0000z.nc4`, it found no such file. 

It seems like this outcome is occurring when, for whatever reason, HEMCO_Config cannot find a restart file to source, or if the underlying date information is wrong. This is also what was found in issue [1921](https://github.com/geoschem/geos-chem/issues/1921). So there might still be a bug here worth tackling! But my problem is solved and you should feel free to close this issue again. 

Operative bug was between keyboard and chair,
Jared

**Comment by yantosca** [comment]
Thanks @JFBrewer , I'll close out this issue.
