### ISSUE TITLE
[QUESTION] Which way is good to zero out all the anthropocentric emissions outside of United States

### ISSUE THREAD

**Issue by katiegrace-3000** [geoschem/geos-chem#244]
I wondered which way is better to quickly zero out all the anthropocentric emissions outside of United Sates? One way I guess is turning off related emissions from HEMCO_Config.rc, the other way, I guessed may change something in the code. I worried about removing too much or not enough in the process. Is there any anthropogenic emissions mix together with non-anthropogenic emissions I should pay attention to. From another aspect to look at this, maybe I should consider which emission I should keep, maybe only NEI and all the non-anthropogenic emission are all I need. Thanks.

**Comment by msulprizio** [comment]
One way to zero emissions outside of the US by applying masks and scale factors in HEMCO_Config.rc. We actually have a mask file already in [HEMCO/MASKS/v2018-09](http://geoschemdata.computecanada.ca/ExtData/HEMCO/MASKS/v2018-09/) called CONUS_Mask_Mirror.001x001.global.nc. That file has 0s over the CONUS and 1s everywhere else, so applying that mask in combination with a scale factor=0 will zero emissions outside of the CONUS. See our [HEMCO examples wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_examples) for examples of using masks and scale factors.

As you mention, you can also turn off all anthropogenic emission inventories, including global inventories, and only having NEI2011 turned on. That may be faster and easier to do, since you don't need to apply masks and scale factors to all anthropogenic emissions entries in HEMCO_Config.rc, but as you mention you might need to do a sanity check to make sure the emissions are off or on where you want them to be. You can do this using by comparing the HEMCO diagnostic output (specified in `HEMCO_Diagn.rc`) from an out-of-the-box simulation and a simulation with your modified emissions setup to compare the emissions in both scenarios and confirm the emissions are on/off where you want them. See the [HEMCO user's guide](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide#Diagnostics) for more information on the HEMCO diagnostics.

**Comment by katiegrace-3000** [comment]
Thanks a lot. This is very helpful.
