### ISSUE TITLE
SO3 generating H2SO4

### ISSUE THREAD

**Issue by 1392403848** [geoschem/geos-chem#2451]
### Your name

czr

### Your affiliation

student

### Please provide a clear and concise description of your question or discussion topic.

Hello, I'm trying to simulate the process of SO3 generating H2SO4. I have modified the corresponding mechanism using kpp and added the corresponding reaction rates, but the result is that the integration is not convergent. What could be the reason for this?

**Comment by yantosca** [comment]
Thanks for writing @1392403848. We do not have enough information to provide assistance.  Could you attach to this issue the following items:

- geoschem_config.yml
- HEMCO_Config.rc
- GEOS-Chem log file showing the error message
- Your KPP files (e.g. custom.eqn and custom.kpp)

Also, we can only assist with coding/technical issues.  If it turns out to be a science problem (i.e. formulation of the reaction rate) then that lies outside of our expertise.

**Comment by yantosca** [comment]
Closing out this issue
