### ISSUE TITLE
FJX earth radius legacy constant?

### ISSUE THREAD

**Issue by barronh** [geoschem/geos-chem#2453]
### Your name

Barron Henderson

### Your affiliation

US EPA

### What happened? What did you expect to happen?

Everything is working and this probably doesn't matter. I just wanted to make a note in case it is useful.

The radius of the earth is defined in twice within GEOS-Chem, but the second definition may not be used. The first time in physconstants.F90[1] is also what is used in HEMCO and GCPy (Re=6371007.2m). The second time is in CMN_FJX_MOD.F90 (RAD=6375000e2 cm).[2]  All the "USE CMN_FJX_MOD" statements use the "only" option and do not reference RAD.

If it is not used, maybe it could be commented out to avoid confusion. If it is used, should it be consistent with physconstants.F90?

[1] https://github.com/geoschem/geos-chem/blame/main/Headers/physconstants.F90#L44
[2] https://github.com/geoschem/geos-chem/blob/main/Headers/CMN_FJX_MOD.F90#L66

### What are the steps to reproduce the bug?

No bug. Just a note.

### What GEOS-Chem version were you using?

14.4.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

ifort 21.4

### Will you be addressing this bug yourself?

No

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

2x2.5

### What meterology fields did you use?

MERRA-2

**Comment by lizziel** [comment]
Hi @barronh, thanks for bringing this up. RAD is used within Fast-JX to compute air mass factors for sunlight reaching a given location (see code [here](https://github.com/geoschem/geos-chem/blob/bef56c605e018eecbd91646a51ce82c7cd77f56a/GeosCore/fast_jx_mod.F90#L1937)). The old value from Michael Prather's code was never updated to use the GEOS-Chem constant value used elsewhere.

We now use Cloud-J instead of Fast-JX (except for Hg) and the problem persists there. We have a few options:
1. Pass radius of Earth as an input parameter to Cloud-J when Cloud-J is used in external models, for consistency with the parent model.
2. Change the Cloud-J value to be the same as GEOS-Chem. Do you know which is more accurate?

**Comment by lizziel** [comment]
For Fast-JX (Hg sim only) we can remove that parameter to avoid confusion and use the one in GEOS-Chem.

**Comment by lizziel** [comment]
I am checking with Michael Prather on this as well.

**Comment by barronh** [comment]
> 2\. Do you know which is more accurate?

I don't think it is fair to say that one is more accurate... The WGS84 spheroid is has a semi-major axis 6378137 m and a semi-minor axis 6356752.3142 m. Assuming that you wanted to conserve volume, the best perfect sphere would be 6371000.79 m. That's a lot closer to the one in physconstants.F90. There are lots of variants that get used in other contexts (e.g., WRF=6370000m)

I suspect that the 6375000m height represents something different. My guess is that it is the center height of the troposphere on a perfect sphere assuming a surface of 6370000m (like WRF) and an approximate tropospheric depth of 10000m (or 6371000 and 8000m). That being said, I'm not really sure where it came from. :)

I just brought it up because I was surprised when I noticed it isn't 6375000m any more in GC, and saw the comment about the move toward consistency... then accidentally found the old value elsewhere. The consistency is probably important for mass conservation, but may not really matter in the photolysis arena.

So, just raising it.

**Comment by yantosca** [comment]
Thanks @barronh and @lizziel.  I believe we took the NIST value for radius of earth in `physconstants.F90` from their 2014 publication.  I'm not sure how that differs from the WGS84 spheroid.

FYI, I think the 6375000m may have been my fault.  That was the value in Dale Allen's GEOS-CTM (used by Mian Chin and others at GMAO) that became part of GEOS-Chem 1.0.0. I think at the time I didn't want to change it so that it differed from what the NASA folks were doing.  I think that value was an approximation but maybe not taken from a high-accuracy publication like NIST or WGS84.  So, historical baggage. :-)

**Comment by barronh** [comment]
I think the NIST 2014 citation was for other variables. I don’t see the earth radius there. Maybe I’m looking in the wrong NIST 2014.
