### ISSUE TITLE
GCAP2.0 with OFFLINE Natural Emission

### ISSUE THREAD

**Issue by Racha711** [geoschem/geos-chem#2545]
### Your name

Racha Samermit

### Your affiliation

Kyoto University

### Please provide a clear and concise description of your question or discussion topic.

I'm running GEOS-Chem driven by GCAP2.0. 

As we know that the OFFLINE Natural Emissions (e.g., Dust, BiogenicVOC, Seasalt, etc) are now available for the native meteorological fields at resolutions of MERRA-2 and GEOS-FP. Also, the default behavior for GCAP 2.0 is to use online calculations to respond to the underlying climate for natural emission.

However, I would like to design my own simulation. >>  I am now re-gridding offline natural emissions to a 2x2.5 degree resolution to match the GCAP2.0 meteorological field. Then, I set up my experiment using;

- **GCClassic:  v14.4.3**
**- Full Chemistry**
**- Turn off ONLINE natural emission and Turn on OFFLINE natural emission (fixed to year 2015).**

But I found that there is an error with dust_emissions_20.20150101.nc - Cannot get field EMIS_DST1. (attached GC_1.txt)

My question is : **"Is it possible to run GEOS-Chem driven by GCAP2.0 with OFFLINE natural emissions"**

#############################################
Here are the relevant configuration and log files.

[HEMCO_Config.txt](https://github.com/user-attachments/files/17597118/HEMCO_Config.txt)
[HEMCO_Config.rc.gcap2_metfields.txt](https://github.com/user-attachments/files/17597119/HEMCO_Config.rc.gcap2_metfields.txt)
[GC_1.txt](https://github.com/user-attachments/files/17597116/GC_1.txt)

I am looking forward to your constructive feedbacks. Thank you very much.

Racha

**Comment by yantosca** [comment]
Thanks for writing @Racha711.  At present we do not generate offline emissions with the GCAP2 meteorology fields.   You would need to turn on the corresponding HEMCO extensions.  Please see our [Offline vs. online emissions](https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/customize-guide.html#offline-vs-online-emissions) section at ReadTheDocs for more information.

The offline emissions are produced so that GEOS-Chem Classic or GCHP simulations at high resolution will have emissions with consistent annual totals.  This is probably not as much of an issue when using GCAP2 meteorology, as most simulations with GCAP2 are being done at 4x5 or 2x2.5 resolution (I think).
