### ISSUE TITLE
question about adding new invenroy to HEMCO

### ISSUE THREAD

**Issue by rongbing0353** [geoschem/geos-chem#2611]
### Your name

runbin

### Your affiliation

lanzhou university

### Please provide a clear and concise description of your question or discussion topic.

hello, thanks for your reply. my question1: I use the geoc-chem classic 13.0.0 version and i konow it is out of data, but i have to use it right now, I found that  I just find the GEOSChem.Restart.fullchem.20190701_0000z.nc4 in inputdata set, I did't find the restart files of HEMCO, the guide shows that I must find the HEMCO restart.nc ，but i can't find it.

question 2: I find that there is an OFFLINE DUST inventory in HEMCO, and I now want to supplement it with a new dust inventory to make it more comprehensive. My inventory is an estimated annual dust emission inventory, with two units in two nc files septately, one being t/year and the other converted to flux units of kg/m2/s. I am currently confused about how to set up this inventory in HEMCO. Logically, if the inventory uses flux units, it should be the same regardless of whether it is calculated annually, monthly, or daily, right? Is it necessary to set a scaling factor? I now want to get the concentration results after this inventory is simulated in GEOS-Chem. How should I set it up in HEMCO? For example, I now have a new dust inventory for the year 2019, how should I enable, disable, and set it up?
Thanks a lot
best wishes

**Comment by yantosca** [comment]
Thanks for writing @rongbing0353.

> I did't find the restart files of HEMCO, the guide shows that I must find the HEMCO restart.nc ，but i can't find it.

We don't provide a HEMCO restart file in the `GEOSCHEM_RESTARTS` folders.  The HEMCO restart file is mostly needed to provide continuity between successive simulations for Soil NOx emissions.  It is OK to start a simulation without the HEMCO restart file.  Then the next simulation that you run (next month, next year, or whenever) will read the HEMCO restart file generated by the previous simulation.

> My inventory is an estimated annual dust emission inventory, with two units in two nc files septately, one being t/year and the other converted to flux units of kg/m2/s. I am currently confused about how to set up this inventory in HEMCO.

HEMCO is best set up to read flux units for emissions, because then the input will not depend on any horizontal grid.  I would recommend converting tons/year to kg/m2/s in the one file and then reading that into HEMCO.  

> Logically, if the inventory uses flux units, it should be the same regardless of whether it is calculated annually, monthly, or daily, right? 

For a single year's emissions, the value in each grid box would be constant for a given year.

> Is it necessary to set a scaling factor? 

You would probably need to set a scaling factor if you are trying to scale emissions for e.g. your emissions year to another year of your simulation.  But without knowing what you want to do in more detail it's hard to say.

>  I now want to get the concentration results after this inventory is simulated in GEOS-Chem. How should I set it up in HEMCO? For example, I now have a new dust inventory for the year 2019, how should I enable, disable, and set it up?

I would try to follow what is done for the ONLINE_DUST emissions.  You would add new emission entries for your inventory into the `HEMCO_Config.rc`.  I would recommend taking a look at the [hemco.readthedocs.io](https://hemco.readthedocs.io) documentation, as there are several examples of how to add emissions.  You'll want to add the emissions to the BASE EMISSIONS section, as you will be reading the dust emissions from disk.

**Comment by yantosca** [comment]
I am closing out this issue as version 13 is no longer supported
