### ISSUE TITLE
[QUESTION] How would you provide HEMCO with scale factors for each our of each weekday?

### ISSUE THREAD

**Issue by LukeFakes** [geoschem/geos-chem#262]
I have hourly scale factors for each weekday and would like to provide these to HEMCO. 

I have tried creating a netcdf file with time slices 2008-01-WDT0-23, however that didn't work.

I have also tried directly putting the scale factors into HEMCO and setting sourceTime as 2008/1/WD/0-23, but this does not work (I think because if 'WD' is stated you need exactly seven time slices?).

Do you have any suggestions as to how I could do this?

Thanks,
Luke

**Comment by christophkeller** [comment]
Unfortunately, there is currently no clean way to use diurnal scale factors that vary by the day of the week. The HEMCO time and file parser in `hcoio_read_std_mod.F90` would need to be modified to support this.

However, you could use the following hack where you define a separate base emission for every day of the week and turn them on/off using a day-of-the week scale factor field that is 1.0 for the day of interest and 0.0 otherwise:

1. Define a separate base emissions entry for every day of the week with a separate day-of-week and hourly scale factor:

0 BASE_SU /my/base.nc Var 2010/1/1/0 C xy kg/m2/s <Spec> *701/711* 1 1
0 BASE_MO /my/base.nc Var 2010/1/1/0 C xy kg/m2/s <Spec> *701/712* 1 1
...
0 BASE_SA /my/file.nc Var 2010/1/1/0 C xy kg/m2/s <Spec> *707/717* 1 1

2. Define the hourly scale factors for each weekday as scale factors 711-717:
711 HOURLY_SU /my/hourly_sunday.nc Var 2010/1/1/* C xy unitless 1
...
717 HOURLY_SA /my/hourly_saturday.nc Var 2010/1/1/* C xy unitless 1

3. Define the weekday scale factor 'switches':
701 WEEKDAY_SU 1.0/0.0/0.0/0.0/0.0/0.0/0.0 - - - xy unitless 1
702 WEEKDAY_MO 0.0/1.0/0.0/0.0/0.0/0.0/0.0 - - - xy unitless 1
...
707 WEEKDAY_SA 0.0/0.0/0.0/0.0/0.0/0.0/1.0 - - - xy unitless 1

**Comment by yantosca** [comment]
Am closing this issue out but feel free to reopen.

**Comment by LukeFakes** [comment]
Hi Bob,

Thank you for the feedback on the issue, I’m sorry I forgot to respond until now. CurrentlyI plan to get round it by specifying scale factors for each species-sector pair hourly in a netcdf to get round the issue.

Thanks,

Luke
