### ISSUE TITLE
[BUG/ISSUE] HISTORY diagnostics only saves 23 hours of data to diagnostic files (except for Budget)

### ISSUE THREAD

**Issue by ktravis213** [geoschem/geos-chem#269]
Hi support team,
I am running version 12.6.3 at 0.25x0.3125 resolution for the China grid.  I need hourly time series, which I output with the HISTORY.rc diagnostic.  I can only run two days at a time at this resolution on my computing system.  For some reason, the budget diagnostic outputs all 24 hours in a day to the same file, but the other diagnostics (species concentration, prod/loss) output 23 hours and put the 24th hour in a new file.  I am not sure which is correct and how to fix this.
Thank you!

**Comment by lizziel** [comment]
Hi Katie, could you provide your HISTORY.rc file? You can drag and drop it into a comment box if you add extension .txt. Thanks!

**Comment by yantosca** [comment]
Hi Katie, thanks for bringing this to our attention.  @msulprizio and I just looked at some timeseries output that she had handy for another project.  

Long story short: What happens is that at 0Z on the last day of your run, a file is created with one timestamp (e.g. 2018-07-01, 00Z).  But then when you start the next run stage in your, the existing file gets overwritten with data from e.g. 2018-07-01 00 to 2018-07-01 23z.

We think the solution may be simple.  In 12.8.1, we can add a test to see if the file that is trying to be created already exists, and if it does, to use netCDF append mode instead of netCDF write mode.

In the meantime, there are a couple of things you can do as a workaround.  

1. Add a line into your run script to rename the diagnostic files that are created at the last timestep of your run, e.g.

``` 
mv GEOSChem.SpeciesConc.20180701_0000z.nc4 GEOSChem.SpeciesConc.20180701_0000z.1.nc4
````
then you can combine those files with the new files that are created at the end of the month.

2. Or even better, at the end of the run, rename the OutputDir folder, and then create a new blank OutputDir for the next run.  This will avoid having files from a previous run being overwritten.  Then you can either merge the files with nco or cdo, or read them into Python with xr.open_mfdataset,

Anyway, thanks again and stay tuned for the fix!

**Comment by yantosca** [comment]
Also -- to answer your question about why the budget diagnostics were not affected, that is probably because you archived the budget diagnostics as time-averaged.  The bug above only affects instantaneous collections.

**Comment by yantosca** [comment]
I have pushed commit https://github.com/geoschem/geos-chem/commit/28109a76d45063de7d7bac67a6732032279d5a51, which is now currently on the bugfix/NcWrite branch.  This will go into 12.8.1 once that version is ready (but you can check out this update if you need it).

I did a couple of test runs where I ran the transport tracer simulation for 1 day at a time and then saved out instantaneous 3-hourly output.  I then checked to see if the file for the 2nd day had the first timestep (which was written out at the end of the previous day's run) preserved.  Indeed it is!

```
netcdf GEOSChem.SpeciesConc.20160102_0000z {
dimensions:
        time = UNLIMITED ; // (8 currently)
        lev = 72 ;
        ilev = 73 ;
. . .
data:

 time = "2016-01-02", "2016-01-02 03", "2016-01-02 06", "2016-01-02 09", 
    "2016-01-02 12", "2016-01-02 15", "2016-01-02 18", "2016-01-02 21" ;
```
Without the fix, the list of timestamps would have started with 2016-01-02 03 (for 3-hourly output) instead of 2016-01-02 00.

**Comment by yantosca** [comment]
Commit https://github.com/geoschem/geos-chem/commit/28109a76d45063de7d7bac67a6732032279d5a51 has now been merged up to version 12.8.1

**Comment by yantosca** [comment]
Also note, a further commit https://github.com/geoschem/geos-chem/commit/1a160e13971ee978124fa31af01ea42c5bb82846 was made in order to make sure that instantaneous collections where frequency=duration are written to disk with the proper reference time. 

Also, we removed "UTC" from the time:units" string, as this sometimes causes ncdump -t not to display the proper time values.

**Comment by yantosca** [comment]
Also added further commit https://github.com/geoschem/geos-chem/commit/81c71263ea21c192595e52d32b76c9eaa7c24600, which adds extra updates so that instantaneous collections with multiple time points are now archived properly.

Also, we now throw an error if we try to append to an instantaneous netCDF file with more than one time point.  This is now in 12.8.1.

**Comment by yantosca** [comment]
After further consideration, we have decided to remove the need for appending to instantaneous file collection files due to the danger of clobbering data.  This was updated in commit https://github.com/geoschem/geos-chem/commit/94d78a7d3bc1ac205f0fc7b682c65d98e3f4bbe2.
 
### Instantaneous collection with more than one time point per file
- First file timestamp: 1st day of simulation @ 01:00Z
- Llast file timestamp: last day of simulation @ 00:00Z.
 - No appending needed.

For example, a 2-day run with hourly archiving saved to daily files creates this output:
```
GEOSChem.SpeciesConc.20160101_0010z.nc4
GEOSChem.SpeciesConc.20160102_0000z.nc4
GEOSChem.SpeciesConc.20160102_0010z.nc4
GEOSChem.SpeciesConc.20160103_0000z.nc4
```

### Instantaneous collection with only one time point per file
- The file name uses the date/time when the data is written to disk.
- No appending needed.

For example, a multi-day run with hourly archiving saved to hourly files now creates this output:
```
GEOSChem.SpeciesConc.20160101_0100z.nc4
GEOSChem.SpeciesConc.20160101_0200z.nc4
GEOSChem.SpeciesConc.20160101_0300z.nc4
...
GEOSChem.SpeciesConc.20160101_2000z.nc4
GEOSChem.SpeciesConc.20160101_2100z.nc4
GEOSChem.SpeciesConc.20160101_2200z.nc4
GEOSChem.SpeciesConc.20160101_2300z.nc4
GEOSChem.SpeciesConc.20160102_0000z.nc4
GEOSChem.SpeciesConc.20160102_0100z.nc4
... etc ...
```
