### ISSUE TITLE
[BUG/ISSUE] Error "Infinity in DO_CLOUD_CONVECTION"

### ISSUE THREAD

**Issue by RajMLal** [geoschem/geos-chem#275]
## Describe the bug

Hi, I'm running a GEOS_4x5 global run and I get seemingly 1000s of lines of messages in the logfile about "Infinity in DO_CLOUD_CONVECTION" each time it timesteps. The model still runs, but the logfile becomes so massive that the model stops running after 3 months of simulation. 

![image](https://user-images.githubusercontent.com/57201024/78821366-5f160780-79a7-11ea-8a64-7047c9d768c7.png)

I tried various approaches to overcome this (saw discussion about CONV_DEPTH in the lightning data and tried using newly downloaded lightning files, etc.)

I turned off cloud convection in the input file, and the model runs no problem, and the log file no longer includes the "Infinity in DO_CLOUD_CONVECTION!"

Any thoughts/suggestions on this?

**Compilation commands**
1. make -j4 build BOUNDS=y DEBUG=y FPEX=y

**Run commands**
standard script 
![image](https://user-images.githubusercontent.com/57201024/78823113-29265280-79aa-11ea-9cc0-66523ca40f9b.png)

## Expected behavior
The model to run without the "Infinity in DO_CLOUD_CONVECTION!" message to pop up

## Required information
Please include the following:
 - GEOS-Chem version you are using: 12.6.3
 - Compiler version that you are using: gcc 4.9.0
 - netCDF and netCDF-Fortran library version: netcdf 4.3.3
 - Computational environment: a cluster
 - Are you using "out of the box" code, or have you made modifications? Out of the box

## Input and log files to attach
For more info, see: http://wiki.geos-chem.org/Submitting_GEOS-Chem_support_requests
 - The lastbuild file
 - The input.geos file
 - The HEMCO_Config.rc file
 - The GEOS-Chem "Classic" log file
 - The HEMCO.log file

[GC_run_log_global_10day_4_7_2020.log](https://github.com/geoschem/geos-chem/files/4452362/GC_run_log_global_10day_4_7_2020.log)
[HEMCO.log](https://github.com/geoschem/geos-chem/files/4452363/HEMCO.log)

For these three, I had to convert to txt from them to load in GitHub:

[lastbuild.txt](https://github.com/geoschem/geos-chem/files/4452377/lastbuild.txt)
[input.txt](https://github.com/geoschem/geos-chem/files/4452378/input.txt)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/4452369/HEMCO_Config.txt)

Thank you!
Raj

**Comment by yantosca** [comment]
Hi Raj.  Thanks for writing.  A couple of ideas:

(1) You might want to try using a newer Gfortran compiler.  We have seen issues with Gfortran 4 and 5 in the newer versions of the GC 12 series.  If you don't have one available on your system you can use Spack and follow the instructions in these videos on our youtube channel:

(2) You might also try using the standard 72L simulation instead of tropchem.  For the 4x5 simulation you will get better scientific results with standard since the standard mechanism is more integrated than tropchem.  

- [Spack tutorial #1, building gfortran 9.2.0](https://www.youtube.com/watch?v=7eMLYKLK9wY)
- [Spack tutorial #2, building libraries](https://www.youtube.com/watch?v=6tGCD3zQQW0)

(2a) Also, side note: we have started to evaluate using standard with 47L instead of 72L.  We find that the standard 47L simulation takes about the same time (or even a little faster than 47L). CAVEAT: We have not done a full scientific analysis with the standard-47L so we would not quite recommend doing that yet.  But look for news about this in the future.  Tropchem may be totally retired from GEOS-Chem if standard-47L checks out.

**Comment by RajMLal** [comment]
Hi Bob,

Thank you for all the detailed notes. We do have gcc7.3.0 but the netcdf module isn't compatible with gcc7.3.0, yet. The HPC staff here is working on installing that compatibility.

I recompiled using ifort15.0 and was able to begin the run, but I ran into a different issue (the model didn't get stuck here with gfortran):

The same error is on the wiki page, but I couldn't follow along with the solution step (I think it's been included already in the version of GC that I'm running)
http://wiki.seas.harvard.edu/geos-chem/index.php/Run-time_crashes_and_abnormal_exits#Floating_invalid_or_floating-point_exception_error

 Thank you,
Raj
[error_file.txt](https://github.com/geoschem/geos-chem/files/4483280/error_file.txt)
[logfile_4_15.txt](https://github.com/geoschem/geos-chem/files/4483281/logfile_4_15.txt)

**Comment by RajMLal** [comment]
Hi Bob,

I was able to re-compile using Gfortran 8.2.0 on a testflight node and run the model. However, it still came up with the same "Infinity in DO_CLOUD_CONVECTION" warning message in the log file.

I'm using the boundary conditions generated here as input to a nested run over Asia that uses tropchem. My understanding is the chemical mechanism has to be the same between the global runs and the nested grid run. 

Thank you!
~Raj

**Comment by yantosca** [comment]
Hi Raj, Thanks for the update.  Yes, you are right, you need the same chemical mechanism in the BC run and the nested run.

Have you tried turning off operations (e.g. transport, drydep, etc) one at a time in the nested run?  This might help you isolate where the issue is.  For example, if something is messing up in transport that might also have a side-effect in convection that is causing the error.  Probably a species is going very low so there might be some underflow happening that is causing the Infinity.

**Comment by yantosca** [comment]
Also I wonder if there are wonky values in your transport BC files that could be causing the infinity values upstream.  Those BC's are only applied if you have transport on, so shutting off transport might be instructive.

**Comment by RajMLal** [comment]
Hi Bob, I wasn't able to directly solve this issue, but I rebuilt the model (albeit at a 2x2.5 resolution) and the error didn't pop up and the model ran without error for a three month run. I do plan on going back through this issue to try and figure out what was causing it.

**Comment by jennyfisher** [comment]
Hi @yantosca and @RajMLal,

I am encountering this error too. For me it is happening with a nested simulation of TransportTracers. FYI, the "Infinity in ..." statement also captures NaN values (even though there is a separate check for them, it is after and doesn't get triggered). I found mine were NaN not Inf. I've done a bit of debugging with print statements and worked out that there are NaN for the species NHEmis90dayTracer coming into the convection code with the Spc array. However, I've checked the restart file and the BC files and there are no NaN in those files. 

I'm not sure how to debug this further, and for my purposes I'm not particularly interested in that tracer so I might just remove it from my simulation to avoid the messages. But I thought I'd let you know in case this helps in some way.

Cheers,
Jenny

**Comment by yantosca** [comment]
Thanks Jenny.   It may be that your nested region doesn't use all of the NH and thus some missing values are getting added in.  You would have to look at routine CHEM_PASSIVE_SPECIES in chemistry_mod.F90.  But if you don't need that tracer it's better to just remove it.

**Comment by yantosca** [comment]
@RajMLal I will close out this issue for now.  @jennyfisher if you are still having problems, then please open a new issue.  Thanks!
