### ISSUE TITLE
[QUESTION] How to rename species in KPP?

### ISSUE THREAD

**Issue by Barak123748596** [geoschem/geos-chem#276]
I am wanting to use a new mechanism in KPP/Custom. In my Custom.eqn file, I use many different names. For example, I use the name of C4H10 instead of ALK4. I notice that in other modules like GEOS_CORE, many of the species names and ids are used. How can I rename those species in Geos-Chem? Do I have to change every original name of the species in GC to new names in every module? That sounds really crazy. Can I redirect the species with the function _equivalence_, which can redirect the pointers of the species？

Thank you very much!

**Comment by yantosca** [comment]
Thanks for writing.  We would recommend keeping to the GC naming convention for species.  Otherwise, as you say, it will be a mess as most of the entries in the HEMCO_Config.rc and the modules will have to be changed.

Also, we would not recommend using EQUIVALENCE since that is a deprecated command from Fortran 77.  The EQUIVALENCE command can only work with array slices, as is my understanding, and not names.
