### ISSUE TITLE
[QUESTION] Is the offline_lighting data of Flash_cth_merra2_0.25x0.625 available for 2018 11- 2019 01?

### ISSUE THREAD

**Issue by katiegrace-3000** [geoschem/geos-chem#277]
Dear GEOS-Chem expert, 
I am doing simulation for 2018 - 2019 Jan. I noticed the offline_lighting data of Flash_CTH_MERRA2_0.5x0.625 is not complete for 2018 11, and no files after that were found. I wondered do you happen to have more data? Or is there any other solution I could bypass this issue? Thanks a lot.

**Comment by msulprizio** [comment]
Please see https://github.com/geoschem/geos-chem-unittest/pull/20 for lightning NOx data through Dec 2012. We will include this update in GEOS-Chem 12.9.0.

**Comment by katiegrace-3000** [comment]
Thanks a lot. At this moment, I want to turn it off. While after I set 'off' 103     LightNOx               : off    NO  
in HEMCO_Config.rc ,  the simulation can't get through and still looking for the emissions. I wondered is there a way to turn it off? Much appreciated.

**Comment by msulprizio** [comment]
I believe you should be able to fully turn off the lightning NOx extension and reading the fields needed for that extension by doing the following:

(1) Turning the LightNOx extension off in HEMCO_Config.rc, as you've already done.

```103     LightNOx               : off    NO```

(2) Comment out the lines for `FLASH_DENS` and `CONV_DEPTH` in HEMCO_Config.rc.

```
#* FLASH_DENS $ROOT/OFFLINE_LIGHTNING/v2019-01/$MET/$YYYY/FLASH_CTH_$MET_{NATIVE_RES}_$YYY\
Y_$MM.nc4  LDENS 1980-2019/1-12/1-31/0-23/+90minute RFY3 xy  1  * -  1 1
#* CONV_DEPTH $ROOT/OFFLINE_LIGHTNING/v2019-01/$MET/$YYYY/FLASH_CTH_$MET_{NATIVE_RES}_$YYY\
Y_$MM.nc4  CTH   1980-2019/1-12/1-31/0-23/+90minute RFY3 xy  1  * -  1 1
```

(2) Commenting out the following lines in `GeosCore/flexgrid_read_mod.F90`:

```
    !! Read FLASH_DENS
    !v_name = "FLASH_DENS"
    !CALL Get_Met_2D( State_Grid, Q2, TRIM(v_name) )
    !State_Met%FLASH_DENS = Q2

    !! Read CONV_DEPTH
    !v_name = "CONV_DEPTH"
    !CALL Get_Met_2D( State_Grid, Q2, TRIM(v_name) )
    !State_Met%CONV_DEPTH = Q2
```

We are going to be adding updates to a future version to make this automated so users don't need to go into the source code to turn this off. I have add a separate feature request for that update -- please see https://github.com/geoschem/geos-chem/issues/279.

**Comment by neyranaz** [comment]
GC 12.7.0 
Hello, we are performing a 2014-2019 Aerosol only simulation to obtain the Boundary Conditions for a Nested Grid run, and when running 2019, we observed that GC tries to pull offline_lighting data HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP/2019/FLASH_CTH_GEOSFP_0.25x0.3125_2019_08.nc4 as well as others. This intrigued us as GC hadn't tried to pull these data in the run 20140101-20190831. Specifically, when looking more in depth into the files that we have available in our local data, we found that our ExtData directory did not have any OFFLINE_LIGHTNING files for the years 2017 and 2018 and GC still managed to run without them. So we were wondering why GC started requesting the OFFLINE_LIGHTNING files in the 20190831-20191231 range?   Would it be advisable to turn offline_lighting off. 

Also we observed that these files are not available in v2019-01, and we know that we could just pull it from version v2020-03 and just use those data as Yantosca already explained. So would it be advisable to do that in the last segment of the run (20180831-20191231), despite offline_lighting data wasn't being pulled from the previous section of the run (20140101-20190831)? 

One hypothesis that we have is that GC might be requesting these data for the last semester because before it might have been pulling the offline_lightning information from other datasets or from somewhere else. And these datasets might not be complete for the year 2019. Does that make sense? Do you have any insights on how we could approach such an issue?

**Comment by neyranaz** [comment]
GC 12.7.0 
Hello, we are performing a 2014-2019 Aerosol only simulation to obtain the Boundary Conditions for a Nested Grid run, and when running 2019, we observed that GC tries to pull offline_lighting data HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP/2019/FLASH_CTH_GEOSFP_0.25x0.3125_2019_08.nc4 as well as others. This intrigued us as GC hadn't tried to pull these data in the run 20140101-20190831. Specifically, when looking more in depth into the files that we have available in our local data, we found that our ExtData directory did not have any OFFLINE_LIGHTNING files for the years 2017 and 2018 and GC still managed to run without them. So we were wondering why GC started requesting the OFFLINE_LIGHTNING files in the 20190831-20191231 range?   Would it be advisable to turn offline_lighting off. 

Also we observed that these files are not available in v2019-01, and we know that we could just pull it from version v2020-03 and just use those data as Yantosca already explained. So would it be advisable to do that in the last segment of the run (20180831-20191231), despite offline_lighting data wasn't being pulled from the previous section of the run (20140101-20190831)? 

One hypothesis that we have is that GC might be requesting these data for the last semester because before it might have been pulling the offline_lightning information from other datasets or from somewhere else. And these datasets might not be complete for the year 2019. Does that make sense? Do you have any insights on how we could approach such an issue?

**Comment by neyranaz** [comment]
GC 12.7.0 
Hello, we are performing a 2014-2019 Aerosol only simulation to obtain the Boundary Conditions for a Nested Grid run, and when running 2019, we observed that GC tries to pull offline_lighting data HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP/2019/FLASH_CTH_GEOSFP_0.25x0.3125_2019_08.nc4 as well as others. This intrigued us as GC hadn't tried to pull these data in the run 20140101-20190831. Specifically, when looking more in depth into the files that we have available in our local data, we found that our ExtData directory did not have any OFFLINE_LIGHTNING files for the years 2017 and 2018 and GC still managed to run without them. So we were wondering why GC started requesting the OFFLINE_LIGHTNING files in the 20190831-20191231 range?   Would it be advisable to turn offline_lighting off. 

Also we observed that these files are not available in v2019-01, and we know that we could just pull it from version v2020-03 and just use those data as Yantosca already explained. So would it be advisable to do that in the last segment of the run (20180831-20191231), despite offline_lighting data wasn't being pulled from the previous section of the run (20140101-20190831)? 

One hypothesis that we have is that GC might be requesting these data for the last semester because before it might have been pulling the offline_lightning information from other datasets or from somewhere else. And these datasets might not be complete for the year 2019. Does that make sense? Do you have any insights on how we could approach such an issue?

**Comment by neyranaz** [comment]
Thanks a lot @msulprizio, 

Also, for those who are using an earlier version of GC, Lee Murray, replied the following: 

"Lightning is never used in the offline aerosol simulation, so it doesn’t really matter what is being read, so I wouldn’t be too stressed.  Newer versions of GEOS-Chem do not bother trying to read the lightning files in the aerosol-only version.  You can always point HEMCO_Config.rc to newer versions of the lightning flash rates (e.g., v2020-03 vs. v2019-01), which will be more accurate and extend further in time. You may also find the new “dryrun” feature of GEOS-Chem helpful for obtaining all your necessary input files.  But again, the files are read but the data is never used like many of the other meteorological fields depending on the simulation."

**Comment by neyranaz** [comment]
Thanks a lot @msulprizio, 

Also, for those who are using an earlier version of GC, Lee Murray, replied the following: 

"Lightning is never used in the offline aerosol simulation, so it doesn’t really matter what is being read, so I wouldn’t be too stressed.  Newer versions of GEOS-Chem do not bother trying to read the lightning files in the aerosol-only version.  You can always point HEMCO_Config.rc to newer versions of the lightning flash rates (e.g., v2020-03 vs. v2019-01), which will be more accurate and extend further in time. You may also find the new “dryrun” feature of GEOS-Chem helpful for obtaining all your necessary input files.  But again, the files are read but the data is never used like many of the other meteorological fields depending on the simulation."
