### ISSUE TITLE
[QUESTION] the computation time increased much in the v12.5.0 compared with v10.01?

### ISSUE THREAD

**Issue by wddpwzz5** [geoschem/geos-chem#285]
Hi GEOS-Chem team,
      I am Zhiqiang Liu, a student from China. And I used to simulate the CO2 with the old version GEOS-Chem V10.01. And recently, I am trying to use the new version V12.5.0. Luckily, It works. But the computation time doubled, which I could not ignore.  The settings I use were the same as the previous version. The compiler is ifort.
       So, due to the limited computer resource. I a little confused that the computation time really increased in the new version? Or, am I missed something?
       Looking forward to receiving your reply!

Best,
Zhiqiang

**Comment by yantosca** [comment]
Thanks for writing.  It is known that more recent versions of GEOS-Chem are slower than prior versions.  Part of this is because many more species were added to the chemical mechanism.  Part of this is also due to the fact that we are reading in more high-resolution emissions data, some at hourly frequency.  You can see that at [this plot of run time from GEOS-Chem 1-month benchmarks](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_1-month_benchmark_timing_results#Timing_results_from_1-month_benchmarks).

We have made some updates in 12.8.0 that hopefully should reduce the run time.   We are still working on this issue and hope to be able to further reduce the run time in subsequent versions as well.

**Comment by msulprizio** [comment]
Please also see this wiki page with tips on speeding up your GEOS-Chem simulations: http://wiki.seas.harvard.edu/geos-chem/index.php/Speeding_up_GEOS-Chem

**Comment by yantosca** [comment]
I am going to close out this issue. Feel free to reopen if you have further questions.
