### ISSUE TITLE
[FEATURE REQUEST] Remove set_global_ch4_mod

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#287]
Now that `sfcvmr_mod.F90` is in place, it seems that `set_global_ch4_mod.F90` is redundant. We can remove `set_global_ch4_mod.F90` and rename the HEMCO items `NOAA_GMD_CH4` and `CMIP6_Sfc_CH4` to instead just be `SfcVMR_CH4`. This then allows users to choose between NOAA, CMIP6, and WMO estimates or observations of methane (or indeed to prescribe their own), and removes duplicate code. In the long run it would be great to also replicate the (currently `#MODEL_GEOS`-only) "pseudo-emissions" diagnostic code in `set_global_ch4_mod` in `sfcvmr_mod`, but for all species.

**Comment by msulprizio** [comment]
Thanks @sdeastham. We can look into adding this in 12.9.0.

**Comment by msulprizio** [comment]
There is ongoing discussion about how to treat the surface methane fields between the overlapping NOAA_GMD_CH4 and CMIP6_Sfc_CH4 fields. See https://github.com/geoschem/geos-chem/issues/304 for the full discussion. For now, we will keep set_global_ch4_mod.F90 because it handles the logic for deciding which dataset to use.
