### ISSUE TITLE
[BUG/ISSUE] Segfault when ConcAboveSfc History Diagnostic enabled

### ISSUE THREAD

**Issue by colinharkins** [geoschem/geos-chem#297]
## Describe the bug
I'm trying to run GEOSChem with the ConcAboveSfc diagnostic enabled. The only thing that I've changed from a working 4x5 standard simulation is uncommenting the ConcAboveSfc diagnostic and changing the frequency to daily. This causes GEOSChem to fail with a segfault. This also happens at any other resolution as well.

## To Reproduce
Run 4x5 standard simulation with the ConcAboveSfc history diagnostic enabled.

**Compilation commands**
make realclean; make -j4 build DEBUG=y

## Expected behavior
Should run without a segfault and produced the ConcAboveSfc outputs, along with other history diagnostics.

## Error messages
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
libifcoremt.so.5   00002AAAAB7D53BC  for__signal_handl     Unknown  Unknown
libpthread-2.12.s  00002AAAAE0347E0  Unknown               Unknown  Unknown
geos               0000000000BE9847  hco_driver_mod_mp         356  hco_driver_mod.F90
geos               000000000058E157  hcoi_gc_main_mod_        1049  hcoi_gc_main_mod.F90
geos               00000000004FF70E  emissions_mod_mp_         394  emissions_mod.F90
geos               00000000004A98BE  cleanup_                  139  cleanup.F90
geos               0000000000CF3EFC  error_mod_mp_geos         518  error_mod.F90
geos               0000000000CF3E25  error_mod_mp_erro         437  error_mod.F90
geos               00000000005F22B7  MAIN__                    715  main.F90
geos               000000000040393E  Unknown               Unknown  Unknown
libc-2.12.so       00002AAAAE464D20  __libc_start_main     Unknown  Unknown
geos               0000000000403849  Unknown               Unknown  Unknown

HISTORY (INIT): Opening ./HISTORY.rc

GEOS-Chem ERROR: DRYDEPRA10M is not found in the registry for the DIAG object!
 -> at Registry_Lookup (in Headers/registry_mod.F90)

GEOS-Chem ERROR: Could not locate DryDepRa10m diagnostics state registry.
 -> History_AddItemToCollection (in History/history_mod.F90)

GEOS-Chem ERROR: Could not add diagnostic "DryDepRa10m" to collection: ConcAboveSfc
 -> at History_ReadCollectionData (in module History/history_mod.F90)

 -> ERROR occurred at (or near) line    303 of the HISTORY.rc file

GEOS-Chem ERROR: Error encountered in "History_ReadCollectionData"!
 -> at History_Init (in module History/history_mod.F90)

GEOS-CHEM ERROR: Error encountered in "History_Init"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)

## Required information
Please include the following:
 - Version 12.8.0, same thing happens on 12.7.2
 - ifort 18.0.2
 - netcdf version 4.2
 - Computational environment: cluster
 - Out of the box 4x5 standard simulation.  

## Input and log files to attach
Files attached 

Thanks for your help!
Colin

[geos.log.txt](https://github.com/geoschem/geos-chem/files/4595791/geos.log.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/4595793/HEMCO_Config.rc.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/4595796/input.geos.txt)
[lastbuild.txt](https://github.com/geoschem/geos-chem/files/4595797/lastbuild.txt)
[test.o50622.txt](https://github.com/geoschem/geos-chem/files/4595798/test.o50622.txt)

**Comment by lizziel** [comment]
Hi @colinharkins , can you also include your HISTORY.rc file. It looks like there are some diagnostics included that only work when GEOS-Chem is run within the NASA GEOS model.

**Comment by colinharkins** [comment]
Hi @lizziel, sorry about that! I've attached the HISTORY.rc file here.
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/4595988/HISTORY.rc.txt)

**Comment by lizziel** [comment]
Thanks! I was able to reproduce the issue and figured out what the problem is. The issue is in the DryDepRaALT1 diagnostic and the two others containing ALT1 that are in collection ConcAboveSfc. For each of them the string ALT1 is automatically renamed to be 10m for both output and internal storage in the diagnostic name list, history registry, and metadata lookup. However, the original name (with ALT1) was used in a conditional test to determine whether to allocate and register the diagnostic. The new name (with 10m) should be used instead. As a result, the diagnostics were not found in the diagnostics list and neither allocated nor registered in GEOS-Chem.

The fix is simple. We will include it in GEOS-Chem version 12.8.1. In the meantime, you can fix it yourself by updating a few lines in file Headers/state_diag_mod.F90 to replace the original diagnostic name strings with variable DiagID. See commit https://github.com/geoschem/geos-chem/commit/cc7b7903243ef2ae348f391f00ef049def5e00d7 for the details. 

Thanks for reporting this!

**Comment by colinharkins** [comment]
Great, thanks for the quick response!
