### ISSUE TITLE
[BUG/ISSUE] SoilNOx files incorrectly time indexed

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#301]
When running a GEOS-Chem Classic benchmark simulation with online soil NOx, the simulation will fail in HEMCO at the start of a new year with the message "invalid time index".

## To Reproduce
Run a benchmark simulation over a period which starts in one year and ends in another.

## Expected behavior
Simulation works.

## Error messages
```
HEMCO ERROR: Invalid time index in /path/to/ExtData/HEMCO/SOILNOX/v2014-07/soilNOx.fert_res.generic.05x05.nc
```

## Required information
Please include the following:
 - GEOS-Chem version 12.8.0 compiled with ifort 19
 - Benchmark simulation for MERRA-2
 - Simulation period 2007-07-01 to 2017-07-01
Input and log files are attached as a zip, since GitHub has arbitrary rules about file extensions
[inputs_and_logs.zip](https://github.com/geoschem/geos-chem/files/4610394/inputs_and_logs.zip)
.

## Additional context
This can likely be fixed by using the "time_corrected_for_GCHP" version of the relevant file. Inspecting the problem file shows that the times are incorrectly given as "1, 2, 3, ... , 365, 366". The "GCHP version" of the file correctly lists the times as "0, 1, 2, ... , 364, 365" (note that the file is for 2000 so has a leap day, hence having 366 entries is correct).

**Comment by lizziel** [comment]
Thanks for reporting this. The GCHP-compatible version of the file was created about three years with the fix described as this in the data README on gcgrid:
```
(9) soilNOx.fert_res.generic.05x05.time_corrected_for_GCHP.nc

       Same as soilNOx.fert_res.generic.05x05.nc except with time variable
       vector changed from 1-366 to 0-365. The time unit is days since
       Jan 1 00:00:00 and therefore the first entry should have time=0 for
       correct interpretation by GCHP ExtData. Time=1 is interpreted as
       Jan 2 00:00:00 which is the incorrect date for that data slice. This
       causes GCHP to exit with an error if starting a simulation on Jan 1.

       This file is being used for the v11-02b GCHP 1-year benchmark. It will
       replace soilNOx.fert_res.generic.05x05.nc in v11-02c.

          -- Lizzie Lundgren (elundgren@seas.harvard.edu), 28 Jun 2017
```
It is very curious that we have never received any reports of this being a problem in GEOS-Chem Classic. Let us know if swapping the files indeed fixes the issue.

**Comment by sdeastham** [comment]
Indeed! I'll update this channel accordingly. This should only happen when people are using online emissions, but I'm wondering why this wasn't triggered in the full-year 12.8.0 benchmark? I'm assuming this is something that a HEMCO update triggered (I remember that once upon a time HEMCO just ignored time indices).

**Comment by lizziel** [comment]
I have not been able to reproduce this issue. Are you able to see the same thing if starting closer to Jan 1st?

**Comment by sdeastham** [comment]
Unfortunately I've only run one simulation thus far, and it started 2007-07-01. My guess is that it may need to start on the 1st of a month, but that's a pure guess. What have you tried?

**Comment by lizziel** [comment]
I suspected as well so I had started a run from Dec 1st. It’ll take a while (although I turned off most components) and will report back what I see.

--
Lizzie Lundgren
Senior Scientific Programmer
GEOS-Chem Support Team
geos-chem-support@g.harvard.edu<mailto:geos-chem-support@g.harvard.edu>

Please direct all GEOS-Chem support emails to the entire GEOS-Chem Support Team<http://wiki.geos-chem.org/GEOS-Chem_Support_Team>. If you are reporting a bug, please create an issue on GitHub<https://github.com/geoschem/>.

**Comment by lizziel** [comment]
I ran a benchmark simulation from 12/1/2015 00:00:00 to 1/1/2016 03:00:00, and still was not able to reproduce this issue. Were you able to fix it with the file with the corrected time indexes?

**Comment by sdeastham** [comment]
It looks like using the corrected time indices fixes the issue - my run has successfully passed 2008-01-01!

**Comment by lizziel** [comment]
It's very odd that I cannot reproduce this. Can you post you latest output log file (the run that was successful)?

**Comment by sdeastham** [comment]
Sure! This run is still going, but it shows the simulation successfully crossing the year boundary (see attached)
[log.run.txt](https://github.com/geoschem/geos-chem/files/4637348/log.run.txt)

**Comment by jennyfisher** [comment]
Hi @lizziel & @sdeastham -

I just encountered the same issue Seb reported, in my case for a simulation starting on 2008-01-01. I'll try Seb's suggestion of using the time_corrected_for_GCHP file.

-Jenny

**Comment by lizziel** [comment]
Thanks for chiming in Jenny. I've been testing with 2016 which is also a leap year so I don't think that is it.

I looked closer at the files we have on the Harvard server and the README says I applied the same fix to the original file in July 2017. Indeed, an ncdump shows our version has 0-365 and not 1-366 for time values in the file, and diffing the two files shows they are identical. This is consistent with the README that says the corrected version would replace the original in v11-02c. I wonder if this is why I haven't been able to reproduce the issue.

I will check that the correct file is available for download. Perhaps it never got synced. Regardless, it is still curious that it is a problem since my understanding is HEMCO does not look at the file time values. But it seems that understanding is wrong. I'll create a file with 1-366 to further test this.

**Comment by jennyfisher** [comment]
Thanks Lizzie. So it seems like the file was replaced at some stage but since it had the same name and path it was probably ignored when we pulled down new data (e.g. using the HEMCO data downloader or now the python data download script).

Assume we should just re-download the file now from Compute Canada to solve the problem?

**Comment by lizziel** [comment]
Yes, I just verified that ComputeCanada has the correct file so downloading it should fix the issue.

This brings up the larger question of whether to create new directories for files with small changes. In this case I thought it did not impact GEOS-Chem Classic, and I believe that was true at the time given the file had been around for several years before the GCHP fix. However, it is a problem if users automatically download with a script that ignores files with the same path and name, since then the files are not really synced. At the same time we want to reduce storage and not keep around nearly identical files, but still maintain backwards capability. Something to think about and come up with a more robust solution for.
