### ISSUE TITLE
[QUESTION] What frequency and duration should we set for restart files?

### ISSUE THREAD

**Issue by ahsouri** [geoschem/geos-chem#310]
Hi,

Considering that the model can sometimes stop at any time (or the simulation takes longer than the allocated queue system), restart files become pretty useful to resume the simulation. 

I set the frequency and duration of the restart files (in History config) every day, one hour (tried to save the last hour of the simulation). But the model failed at reading it. 

What frequency and duration are you suggesting to create restart files that are similar to the older versions of GC (like v10)?

I couldn't find my answer at (http://wiki.seas.harvard.edu/geos-chem/index.php/Overview_of_History_diagnostics#Sample_HISTORY.rc_diagnostic_input_file, http://wiki.seas.harvard.edu/geos-chem/index.php/Guide_to_GEOS-Chem_History_diagnostics#The_Restart_collection)

Best,

**Comment by yantosca** [comment]
Thanks for writing.  The default setting for the Restart collection is "End", which will create files at the end of each simulation.  But you can definitely change that to be more frequently.  For example, if you are running a 2-month simulation in the queue system, then you can set the frequency and duration to be 00000001 000000 instead of End, so at least you'll get monthly output.  You can also set it to be a certain number of days (like 00000000 070000 for every 7 days, etc.)

We can add some text to the clarifying wiki.  However, there may be no "ideal" setting given that different users on different systems will have different maximum queue time limits. (Or even no time limits, for example, if you are running in the cloud).  

But if you are running a multi-month simulation, you should probbly save out a restart file once a month just to be on the safe side.

**Comment by yantosca** [comment]
I am going to close out this issue.  If you still have questions, feel free to reopen.
