### ISSUE TITLE
[QUESTION] Adding New Module in HEMCO

### ISSUE THREAD

**Issue by debatoshpartha** [geoschem/geos-chem#315]
## Adding New Module in HEMCO

Hello, 

I am trying to add two newly written modules, one is a **deposition module** in GeosCore and other is an **emission module** in HEMCO/Extention. I've followed "hcox_soilnox_mod.F90" for the emission module as the it's very similar to mine. I've called the deposition module by 'USE' in the later HEMCO module and it seems it cannot open/access the deposition module at all. 

I've previously emailed Mr. Yantosca and he advised to put the deposition module in the middle interface between GEOS-Chem and HEMCO (I am not quite sure what he meant). I've tried to put the deposition module in HEMCO/Core and made changes to the "makefile" accordingly. But as the present directory makefile (HEMCO/Core/makefile) doesn't have the necessary .o files called in my deposition module.o file, while compiling, it's showing an error message stating "**No rule to make target those .o files**".   

Kindly help me out here. Thanks.

**Comment by yantosca** [comment]
Hi Debatosh.  Thanks for writing.  So as I said before, HEMCO is compiled first, then GeosCore.  If you look in the GeosCore/Makefile, the order of compilation is specified here:

**https://github.com/geoschem/geos-chem/blob/e3b3b6570af07b1cde3a6d25b143451da25dbb9f/GeosCore/Makefile#L175-L187**

So, as I mentioned before, HEMCO (libhemco) is built first before GeosCore (libcore).  This means that code in the HEMCO sub-folders can be "Seen" by GeosCore.  But any code in "GeosCore" can't be seen by HEMCO.  For this reason we have created a module called GeosCore/hcoi_gc_main_mod.F90.  This is the "bridge" between GEOS-Chem and HEMCO.  You might consider putting your routine there.  You could also create an array in the State_Chm object where you could copy your data.  That would make it easier for it to be passed to HEMCO.

Can you provide us with a specific example from your Makefiles?  Otherwise it's hard for us to visualize the problem.

I did a google search on the error message to "No rule to make target", and here are a few links that came up:

- https://stackoverflow.com/questions/834748/gcc-makefile-error-no-rule-to-make-targe
- https://stackoverflow.com/questions/46122404/makefile-make-no-rule-to-make-target-all-stop
- https://stackoverflow.com/questions/52745325/makefile-no-rule-to-make-target-how-to-set-the-correct-rules

**Comment by debatoshpartha** [comment]
Thank you Mr. Yantosca for your detailed help. I am working on transferring the routines to hcoi_gc_main_mod.F90. Please don't bother about the makefile issue, I got that. I will ask further questions here if I get stuck in future.

**Comment by yantosca** [comment]
Thanks.  Feel free to open a new issue (or to reopen this issue).  I'll close it out for now.

**Comment by debatoshpartha** [comment]
Hello, I have tried adding my deposition subroutines to hcoi_gc_main_mod.F90 and then tried calling them from my HEMCO emission module but still got no luck as HEMCO modules cannot read GeosCore modules due to the compilation order. 

Now I am trying to write my emission module within GeosCore (in reference with the mercury_mod.F/EMISSMERCURY and land_mercury_mod.F) so that my GeosCore emission module can use my geoscore deposition module. I understand I may still have to pass my emission inventories to HEMCO through hcoi_gc_main_mod.F90. I assume (kindly correct me if I'm wrong) calling my emission module by "USE" in hcoi_gc_main_mod.F will automatically be passed to HEMCO.  I'd like to know if this is the right way to proceed. If so, can you give me some heads up/suggestion in adding geoscore emission module in hcoi_gc_main_mod.F and how to pass them to HEMCO later?

Thank you in advance.
