### ISSUE TITLE
[FEATURE REQUEST] Set permissions in data download script

### ISSUE THREAD

**Issue by jennyfisher** [geoschem/geos-chem#318]
I've been loving the new data download python script that ships with GEOS-Chem. I have two questions/requests that would make it even more useful.

1. When the script runs, it uses wget which as I understand it inherits permissions setting from the user's default umask settings. On our servers, these do not include group write permissions. This means that when new files are downloaded, they don't have group write permissions. That is usually fine - the files only need to be downloaded once. But the problem comes in when the required file is in a directory that we don't have yet. The directory will get created on our servers without group write permissions. This means that if someone else needs to add a file (e.g. running for a different year), they can't by default until the original downloader changes permissions. This can get difficult to manage in multi-user groups.

Is it possible to add something to the script that would automatically set permissions on newly downloaded data directories to group write access? (Or at least a setting that would allow a user to choose that option?)

2. I've noticed this script seems to use a surprising amount of memory, and it scales with the length of the run. I figured that since the model isn't actually running, it shouldn't need much memory. But when I set up a dryrun to cover my 1-year run period (which I will eventually do in monthly batches), it was crashing with 10GB memory allocated. Works fine if I use it monthly. Is this kind of memory use expected?

Thanks!
Jenny

**Comment by yantosca** [comment]
Thanks for writing.  I did a lot of my initial testing for the dry-run on the AWS cloud, since it's easier to start from a fresh directory.  On the AWS the permissions are not as much of a problem since you own the whole node.

I think I have a pretty simple fix.  Try this on your end and let me know if it works:

Change line 311 from this:
```
cmd_prefix = 'wget -r -np -nH -R "*.html" -N -P ' + \
                     paths["local_prefix"] + " "
```

to this:
```
cmd_prefix = 'umask 002; wget -r -np -nH -R "*.html" -N -P ' + \
                     paths["local_prefix"] + " "
```
This will force the setting of umask to 022 (i.e to add group writeability) in the shell where the wget command is being executed.

As for the memory, I'm not sure if there is an easy fix for that.  The download is controlled by wget so perhaps that is what is driving the memory usage.  I think it is probably best to download in monthly chunks.  That way, if there is an issue with the network connectivity dropping out you can just restart from the last month.  (Or better yet, do a new dryrun from the last date of good data).

I'll push this fix to dev/12.8.1.

**Comment by jennyfisher** [comment]
Thanks Bob, I'll give this a go!

Re: memory, I wasn't thinking clearly when I wrote the message. What actually uses a ton of memory is not the data downloading script but the actual dry run of GEOS-Chem that creates the log file to use. I was surprised by this because I thought it was just gathering a list of files, so not sure why it would need so much memory (or why it would scale so dramatically with run length).

I figure if I'm going to do a multi-year run, it's easiest to get the full list of files I'll need at the start so I don't forget any...

**Comment by yantosca** [comment]
Thanks Jenny.  In 12.8.1 I pushed a fix that should reduce the amount of memory.  Basically we skip allocating arrays (esp. in HEMCO) when we do the dry-run.  Should keep the memory below 6GB.  See issue: https://github.com/geoschem/geos-chem/issues/306

**Comment by jennyfisher** [comment]
Ah, that's great, thanks Bob! I'll look forward to using this version when 12.8.1 is released. ;)

**Comment by yantosca** [comment]
Version 12.8.1 is being released today (21 May 2020).  This update is now added in commit: https://github.com/geoschem/geos-chem-unittest/commit/49916834d4f707596a00a0a6d5322dca431dcbe9.
