### ISSUE TITLE
[QUESTION] Does height in Plane flight diagnostic above ground or above sea level?

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#320]
Just a quick question. I’m using GC 12.5.0. I was wondering if the altitude in Plane flight diagnostic is above ground or above sea level?

**Comment by yantosca** [comment]
Thanks for writing.  The planeflight diagnostic writes out the pressure at which the observation occurred.  In GEOS-Chem this is computed using the surface pressure and the hybrid Ap and Bp coordinates, as described here:

http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_vertical_grids#Hybrid_grid_definition

I believe that this can be interpreted as height above the ground, as the hybrid grid formulation transitions from terrain-following (at the lower levels) to constant pressure (at the higher levels.

The transition from terrain-following to constant pressure levels occurs around ~170 hPa.  If the plane is higher than that, then all of the grid boxes for a given level index L will have the same pressure value.  At that point you're far enough above the ground so that the variations in height of Earth's terrain doesn't matter.

Hope this helps!
