### ISSUE TITLE
[BUG/ISSUE] Error creating run directories in 12.8.1

### ISSUE THREAD

**Issue by lfreese** [geoschem/geos-chem#322]
## Describe the bug
When running the updated 12.8.1 and trying to create a run directory I repeatedly get:
`Use of uninitialized value within @txt in pattern match (m//) at ./gcCopyRunDirs line 323.
`
## To Reproduce
I've modified the CopyRunDirs.input to have local input and output locations, and have done the same for previous versions of GEOS-Chem (most recently using 12.6.1). I just updated to start using 12.8.1 and this is the first time I've seen this error. It comes up repeatedly when I enter:

`./gcCopyRunDirs run_name.input
`
## Expected behavior
Typically a new run directory is created.

## Error messages
```
Use of uninitialized value within @txt in pattern match (m//) at ./gcCopyRunDirs line 323.
```
In order to stop the error from continuously repeating nonstop, I have to ctrl+c to exit, cancelling the run directory

## Required information
I'm using a cluster and an intel compiler.

**Comment by yantosca** [comment]
Thanks for writing.  This error can happen if there is a blank line in your CopyRunDirs.input file.  The fix is to make sure the line for each of the run directories that you don't want to use has a # comment character in front of it... and to remove any blank lines at the end of the file.

We are going to be moving the run directory creation out of the unit tester and into the GEOS-Chem source code repository starting in 13.0.0 so this error will eventually be a thing of the past.

**Comment by lfreese** [comment]
Thanks for the help-- there was an extra blank line at the bottom of the input file and it is fixed now.
