### ISSUE TITLE
[BUG/ISSUE]UCX horizontal resolution issue with FlexGrid

### ISSUE THREAD

**Issue by eamarais** [geoschem/geos-chem#329]
## Describe the bug
I’m finding an issue with FlexGrid over a custom domain (West Africa) at the native horizontal resolution of the met fields when using standard chemistry mechanism with UCX in version 12.8.1. My run stops with the debug error message in UCX_INIT “'NetCDF NOx coeffs only preprocessed for 2x25 and 4x5 - try setting the module variable UCXNETCDF=.FALSE.”
 
My current fix is to just hardcode this to “FALSE” for 4x5 boundary condition and nested grid runs.

**Comment by sdeastham** [comment]
Thanks for raising this! My apologies – I’ve principally been using GCHP recently so I knew in principle that there’s no reason for GC’s UCX code to be hardcoded for 4x5 or 2x2.5. But I hadn’t realized we still had this old legacy code. It’s an inconsistency which I agree we need to iron out. I think it would make most sense to:
 
1)	Remove the UCXNETCDF option, and trim ucx_mod.F90 so that only the UCXNETCDF=.FALSE. options are used throughout
2)	Unify the behavior in GEOS and GEOS-Chem. There seem to be a few places in ucx_mod.F90 which use more recent BCs for GEOS than for GEOS-Chem, which seems unnecessary.
 
The good news is that hardcoding UCXNETCDF=.FALSE. should have the exact intended effect.
 
@GCST: How soon could we:
 
a)	Change the default for UCXNETCDF to .FALSE.?
b)	Incorporate a fix (I’m happy to write this) which removes the old, redundant code and updates GC-Classic & GCHP to be consistent with GEOS?
 
My guess is that we could get a) in soon but b) will be a few versions later? Part b) will actually take some work, because I’m realizing that there’s a (science) issue with some of the assumptions about how the NOx data is indexed.

**Comment by msulprizio** [comment]
This is now resolved in https://github.com/geoschem/geos-chem/commit/af4edc9406284abf51c931e9a544117c5320ae26 and will be included in GEOS-Chem 13.0.0
