### ISSUE TITLE
[BUG/ISSUE] 'Species not found in the database' error even though the species are present.

### ISSUE THREAD

**Issue by Asmitab13** [geoschem/geos-chem#336]
Hi,

I am using a modified version of GEOS-Chem 12.7.1 on my stand alone computer. The code has been modified to include other species that have already been added to the 'Case' statement in the species_database_mod file. However, when i edit my input.geos file to add the species, I get the following error:
```
Species  not found in the database!
Please add the information to the CASE statement
in module Headers/species_database_mod.F90!
 ### Could not get species info!
```
I have tried using different editors like vim, emacs and gedit to see if this is an editor issue. However, that doesn't solve the problem and I continue to get this error. 
I am using Ubuntu 7.5.0 and my netcdf version (downloaded using Spack) is 4.7.3

Any help would be appreciated. Thanks!

**Comment by yantosca** [comment]
Thanks for writing,  Can you post the entire log file from the failed run here (you can drag & drop the file into the text window.  You'll have to append .txt to the log file name or else Github won't post it).  

One thing to check: does your species name have mixed capital and lowercase letters?  If so, in the case statement in species_database_mod.F90, that expects all capital letters.

Also note, since v12.7.1 we have pushed a fix to the species database lookup so that we avoid hash collisions.  In other words, the algorithm used to search for species could return erronous matches.  This issue was fixed in 12.8.0: https://github.com/geoschem/geos-chem/issues/264.  

You might want to update to the latest version (12.8.2), which contains a several other minor fixes since 12.8.0.

**Comment by Asmitab13** [comment]
The error was resolved once I used :wq to save the changes made using vim editor as opposed to :x

**Comment by yantosca** [comment]
Thanks for letting us know.  I'll go ahead and close this out.
