### ISSUE TITLE
[BUG/ISSUE] RRTMG fixes for GEOS-Chem 13.0.0

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#350]
## Overview

RRTMG has been an option in GEOS-Chem for a while, but the NetCDF implementation does not perfectly mirror the BPCH implementation. Some recent work (#347) has addressed these questions in part, but the new implementation will not look identical to the old. This thread stores information about the upcoming changes so that people are able to see them and comment.

## Additional information

The following was sent in an e-mail to Daniel Jacob and Colette Heald as part of a discussion on issues with RRTMG in GEOS-Chem since the transition to NetCDF diagnostics:

### True “bugs” in RRTMG code
 
I discovered one genuine bug in the RRTMG code, which I believe crept in when we went from 1-D (“CSPEC”-style) indexing to 3-D (“STT”-style) indexing. This was causing any aerosol in the stratosphere to have incorrect single scattering albedos and asymmetry parameters, which would then mess up fluxes beneath those layers as well. The fix to this is simple (extending a couple of arithmetic calculations to all grid boxes, rather than restricting it to lower grid cells). I’ve provided the fix (which comes down to deleting 6 lines) to the GCST as a pull request on GitHub. This bug would affect both BPCH and NetCDF diagnostics.
 
With that fixed, I believe that RRTMG should now be working perfectly in GEOS-Chem Classic with NetCDF diagnostics. I should note that it currently looks like the NetCDF diagnostics only put out fluxes, so SSA and asymmetry parameters are not output. This should be relatively straightforward to fix, though.
 
### How fluxes are defined
 
Something that Jonathan Moch noted in his earlier testing of the RRTMG NetCDF diagnostics is that the output for each individual species didn’t seem correct, and that the difference between that and the baseline looked more realistic. After digging through the code a bit more, I actually believe the NetCDF diagnostics are fine, and are simply defined a little differently from how they were in the BPCH version. For the BPCH diagnostics, only the flux with all components included (“flux_baseline”) was reported as a true radiation flux. Other flux calculations (for example, the “RF due to PM”) were calculated by first calculating the flux when PM was *removed* (call this “flux_no_PM”), and then subtracting this from the baseline. So, what was reported was:
 
`BPCH “BA” = “flux_baseline”`
`BPCH “PM” = “flux_baseline” – “flux_no_PM”`

With the NetCDF diagnostics, a more direct approach was taken. These diagnostics instead report the fluxes directly. Unfortunately, they still use the old names. So, in contrast to the BPCH diagnostic definitions above, NetCDF diags report:

`NCDF “BA” = “flux_baseline”` < As before
`NCDF “PM” = “flux_no_PM”` < Note not subtracted from baseline!

However, it’s easy to recover the “old” diagnostics:

`BPCH “PM” = NCDF “BA” – NCDF “PM”`
 
So to my mind this is pretty much a non-issue, except from a user-confusion perspective.

### Time-averaging
 
Jonathan also noticed that it can be difficult to interpret the NetCDF diagnostics. To my understanding this essentially comes down to needing to divide the diagnostic output by the number of chemistry timesteps which have occurred per radiation timestep. However, I did not look into this, as I did all my work with GCHP.

### GCHP

Finally, I decided to see if I could get RRTMG running in GCHP. Long story short, this seems to work fine; I’ve submitted a pull request which implements RRTMG in GCHP. I was also able to have RRTMG be called on a different schedule than GEOS-Chem (specifically, allowing it to only be called once every N hours, rather than on every chemistry step). If RRTMG is called once every 3 simulation hours, the overhead appears to be about +10% (as a fraction of the total chemistry time only). 

## Action items

Based on this discussion, the following recommendations were made:

* Incorporate these changes into an upcoming version of GEOS-Chem
* Rename the flux diagnostics. Specifically:
   * `BA` is now `BASE`
   * Each component is now `NOX` rather than `X`, e.g. `NOPM` rather than `PM`

## Further notes

As implemented in GCHP, the new version of RRTMG will (by default) run once every 3 hours. Specifically, it will run using the output from the final chemistry step immediately prior to each 3-hour boundary. It is *strongly recommended* that users:

* Retain the 3-hour timestep, in `input.geos`, in `GCHP.rc` (as `RRTMG_DT`), and in `HISTORY.rc`;
* Use 3-hour instantaneous output in `HISTORY.rc` rather than using time-averaging; and
* Perform post-processing themselves using the 3-hour instantaneous output.

If users genuinely cannot afford the disk space required for this, then (currently) it is also viable to use time-averaged diagnostics. However: the first sample produced will be incorrect, since (until 3 hours have passed) there will be no data available. Users who wish to use longer time averaging periods without post processing should therefore discard the first diagnostic entry.

Finally, please note that there has been a change in how you calculate the direct radiative effect of a specific component. The fluxes reported with `NoPM` are specifically the longwave and shortwave fluxes when PM is not included. So, to get the longwave, all-sky, direct radiative effect of PM and of ozone at the top of the atmosphere, you would need to request the following three fields in `HISTORY.rc`:

```
'RadAllSkyLWTOA_BASE   ', 'GIGCchem'
'RadAllSkyLWTOA_NOPM   ', 'GIGCchem'
'RadAllSkyLWTOA_NOO3   ', 'GIGCchem'
```

The direct radiative effect of PM can then be calculated as

`'RadAllSkyLWTOA_BASE - RadAllSkyLWTOA_PM`

Further naming conventions:
* To get clear sky data, replace `All` with `Clr`
* For shortwave, replace `LW` with `SW`
* For surface rather than top-of-atmosphere, replace `TOA` with `Surf`
* The component options are (replacing `PM`, above):
   * `SU`: Sulfate aerosol
   * `NI`: Nitrate aerosol
   * `AM`: Ammonium aerosol
   * `DU`: Dust
   * `DU`: Sea salt
   * `BC`: Black carbon
   * `OA`: Organic aerosol
   * `ST`: Stratospheric aerosol (sulfate and nitrate)
   * `PM`: All PM (i.e. all of the above)
   * `O3`: Ozone
   * `ME`: Methane

**Comment by lizziel** [comment]
I am in the process of comparing bpch vs netcdf RRTMG diagnostics for a GC-Classic dev/13.0.0 run. The criteria for retiring bpch RRTMG diagnostics is to test the netcdf to ensure that they match the bpch diagnostics *exactly* and *all* of the parameters currently saved to bpch are saved to netcdf. I will post progress, results, and issues here since additional work may be needed to achieve this criteria. Ideally the bpch RRTMG diagnostics will be retired for GEOS-Chem 13.0.0.

**Comment by lizziel** [comment]
I made several updates to the RRTMG code in GEOS-Chem for the 13.0.0 release. GCHP netcdf diagnostics, GEOS-Chem Classic netcdf diagnostics, and GEOS-Chem Classic binary diagnostics now match very well. The difference between GEOS-Chem classic netcdf and binary diagnostic values is numerical noise. The difference between GCHP and GEOS-Chem Classic netcdf diagnostic values is due to use of different grids as well as slightly different times when RRTMG is called (0, 2:40, 5:40, etc for GCHP versus 0, 3:00, 6:00, etc for GEOS-Chem Classic). This difference is deemed acceptable for the 13.0.0 release but could be revisited in the future to adjust the GCHP RRTMG call times to exactly match those of GEOS-Chem Classic, if deemed appropriate.

This update consisted of the following changes:

1. ALL RRTMG diagnostics implemented for binary format and are now also implemented in netcdf format. This includes the addition of optics diagnostics, namely AOD, single scattering albedo, and asymmetry parameter. 

2. I changed the flux calculations used for netcdf diagnostics to use the same definition as the analogous binary diagnostics.  This drew upon Seb’s observation that the existing flux diagnostics were base fluxes without the aerosol of interest, e.g. all aerosols except PM. It is now base minus base without aerosol of interest to isolate the flux of the aerosol of interest only.

3. I reverted the new netcdf names introduced by Seb (NOO3, NOME, etc) back to the names used in the binary (O3, ME, etc). Now that the netcdf diagnostic definitions are updated the “NO” is no longer applicable.

4. I updated GCPy to include the comprehensive bpch and netcdf name mapping such that the bpch can be read as netcdf and optionally converted to use the netcdf names for comparison.

5. I originally added a scale factor adjustment to the netcdf diagnostic arrays applied the very first time RRTMG is called in a run. This was a kludge to prevent the zero values leading up to the first RRTMG call from factoring into the first time-averaged diagnostic calculation. The effective result was back-propagation of the first values to the beginning of the run. Ultimately the better solution was to shift the time of the RRTMG calls from center of the radiation timestep to start of the radiation timestep, e.g. from 1:30, 4:30, 7:30, etc to 0, 3:00, 6:00, etc. This removed the need for the netcdf kludge and resulted in extremely good agreement between binary and netcdf diagnostics in GEOS-Chem Classic.

Both the binary and netcdf diagnostics will be included in GEOS-Chem 13.0.0. RRTMG binary diagnostics will be retired in 13.1.

**Comment by lizziel** [comment]
Several other RRTMG updates went into 13.0.0. See the following issues/PRs:

- issue https://github.com/geoschem/geos-chem/issues/346
- issue https://github.com/geoschem/geos-chem/issues/438
- pull request https://github.com/geoschem/geos-chem/pull/348
- pull request https://github.com/geoschem/geos-chem/pull/347
- pull request https://github.com/geoschem/geos-chem/pull/429

**Comment by eamarais** [comment]
Hi @lizziel, I have a clarification question about RRTMG. I'm using GEOS-Chem version 12.9.3 (though the RRTMG code is the same in 13.0.2). In rrtmg_rad_transfer_mod.F90, there are the following 2 lines in the subroutine do_rrtmg_rad_transfer:

!N.B. STRAT CH4 NOT CURRENTLY INCLUDED IN THE DRE OF CH4
!N.B. STRAT O3  NOT CURRENTLY INCLUDED IN THE DRE OF O3

My impression is that DRE calculations for CH4 and O3 cover all model vertical levels. I checked this by printing CH4 and O3 values of order 1e-6 and 1e-7 kg/kg in layers 39-47 of a sample gridsquare for the 47-layer model before the routines to calculate DREs (RRTMG_LW, RRTMG_SW) are called.

**Comment by lizziel** [comment]
Hi @eamarais, I checked the git history and those lines were added by Dave Ridley back in 2015 for version 10-01i. I am not sure if they are relevant anymore. We can certainly remove them if they are not accurate. Perhaps check in with @sdeastham or other recent RRTMG users for clarification, or look in the DRE calculation files? If there are any bugs please create a GitHub issue for it.

**Comment by sdeastham** [comment]
Hi both - I think that those 2 lines are copied erroneously. They are correct _if_ `LUCX=.FALSE.`, but when `LUCX=.TRUE.` stratospheric CH4 and O3 should be included (just looking at the code as written).

**Comment by lizziel** [comment]
It appears twice in Dave's original code update, both with and without UCX defined (back when we had a CPP switch for this):
@@ -540,6 +547,38 @@
```
            ! WE ARE IN THE STRATOSPHERE
            !-----------------------------
 
+#if defined( UCX )
+            !N.B. STRAT CH4 NOT CURRENTLY INCLUDED IN THE DRE OF CH4
+            !N.B. STRAT O3  NOT CURRENTLY INCLUDED IN THE DRE OF O3
+             O3VMR(IJLOOP,L)  = State_Chm%Tracers(I,J,L,IDTO3)*AIRMW /
+     &                     (TRACER_MW_G(IDTO3)*State_Met%AD(I,J,L))
+             CH4VMR(IJLOOP,L) = State_Chm%Tracers(I,J,L,IDTCH4)*AIRMW /
+     &                     (TRACER_MW_G(IDTCH4)*State_Met%AD(I,J,L))
+            N2OVMR(IJLOOP,L) = State_Chm%Tracers(I,J,L,IDTN2O)*AIRMW /
+     &                     (TRACER_MW_G(IDTN2O)*State_Met%AD(I,J,L))
+            CFC11VMR(IJLOOP,L) =State_Chm%Tracers(I,J,L,IDTCFC11)*
+     &       AIRMW/(TRACER_MW_G(IDTCFC11)*State_Met%AD(I,J,L))
+            CFC12VMR(IJLOOP,L) =State_Chm%Tracers(I,J,L,IDTCFC12)*
+     &       AIRMW/(TRACER_MW_G(IDTCFC12)*State_Met%AD(I,J,L))
+            CCL4VMR(IJLOOP,L)  =State_Chm%Tracers(I,J,L,IDTCCL4)*
+     &       AIRMW/(TRACER_MW_G(IDTCCL4)*State_Met%AD(I,J,L))
+            CFC22VMR(IJLOOP,L) =State_Chm%Tracers(I,J,L,IDTHCFC22)*
+     &       AIRMW/(TRACER_MW_G(IDTHCFC22)*State_Met%AD(I,J,L))
+
+
+! TEST IMPACT OF STRAT CHEM
+!            O3VMR(IJLOOP,L)  = 0.0d0
+!            CH4VMR(IJLOOP,L) = 0.0d0
+!            N2OVMR(IJLOOP,L) = 0.0d0
+!            CFC11VMR(IJLOOP,L) = 0.0d0
+!            CFC12VMR(IJLOOP,L) = 0.0d0
+!            CCL4VMR(IJLOOP,L)  = 0.0d0
+!            CFC22VMR(IJLOOP,L) = 0.0d0
+
+#else      
+            !N.B. STRAT CH4 NOT CURRENTLY INCLUDED IN THE DRE OF CH4
+            !N.B. STRAT O3  NOT CURRENTLY INCLUDED IN THE DRE OF O3
+
            !! DENSITY OF AIR IN G/CM2
            AIR_TMP = State_Met%AIRDEN(L,I,J)*
```

However, I know this doesn't clarify anything other than this has been there for a long time.

**Comment by eamarais** [comment]
Thanks @lizziel and @sdeastham. Perhaps worth removing these lines in the next version to avoid confusion? I'm confident from scrolling through the code and with my print statements that the stratospheric component of the column is included in the RRTMG calculations.

**Comment by lizziel** [comment]
Will do. Thanks for reporting this.
