### ISSUE TITLE
[QUESTION] NEI scaling

### ISSUE THREAD

**Issue by lfreese** [geoschem/geos-chem#361]
The wiki page on the EPA/NEI11 has scale factors for up to the year 2013. I have two related questions to clarify for this: 

1. Will HEMCO automatically scale to the year that I am using, or is this a manual input I need to add?
2. What happens beyond the year 2013--have additional scale factors been added to 2016/2017, or are all runs past the year 2013 using an earlier year (either 2013 or 2011 based on the response to the above question)?

**Comment by yantosca** [comment]
Hi Lyssa, thanks for writing. 

If the current met field year goes beyond 2013, then I believe HEMCO will keep reusing the emissions for 2013, because the default setting is cycle/range/exact option is set to C (cycle).  See [this HEMCO_Config.rc file snippet](https://github.com/geoschem/geos-chem-unittest/blob/54097a28204b15608f46187dc526be985ac3f854/runs/shared_inputs/fullchem/HEMCO_Config.template.standard#L420-L425).

Also, HEMCO can only use the scale factors that are provided in the HEMCO_Config.rc file.  You would have to add additional years if you wanted to go out further in time.  But you might want to check with the Emissions Working Group if it is scientifically valid to extrapolate NEI2011 outward past 2013 first.

Supposedly there is supppsed to be a NEI2016 update coming soon.  Barron Henderson (@barronh) might know more about that.

**Comment by lfreese** [comment]
Hi Bob,

Thanks so much! Yes, I'm actually in touch with Barron and have been working with him on running some of the new files in GEOS Chem. I'm trying to compare the results of some of his NEI2016 to those of the current NEI files to make sure there aren't any glaring discrepancies or issues with regridding. I figured it might be helpful to scale the old files to 2016 to just get a newer value to compare to (with the knowledge that it wouldn't be entirely accurate); however, it seems like 2013 might be fine enough and we can just be cautious knowing that it is not representative of 2016 (likely a bit high in most emissions), so there need to be other checks in place as well.

**Comment by barronh** [comment]
Lyssa,

I think I have some 2016 scalars. I’ll email them when I get to the virtual office. 

-Barron

Barron Henderson, PhD
352-682-3579; barronh@gmail.com

**Comment by yantosca** [comment]
Thank you all.  I will go ahead and close out this issue but feel free to reopen if you still have questions.

**Comment by IshirDutta** [comment]
Hi folks,

I was calculating scale factors for NEI2011 for 2014-2019 to use as a first-order approximation while NEI2016 was being implemented, and I noticed that my numbers for 2006-2013 differed from those on the wiki / in the HEMCO_Config.rc file. (I'm using GC v13.0.0.)

I used the "National Annual Emissions Trend" file here (https://www.epa.gov/air-emissions-inventories/air-pollutant-emissions-trends-data), as specified on the [wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/EPA/NEI11_North_American_emissions#Annual_Scale_Factors), to calculate the scale factors.

For example, for CO, I find that the scale factor is
2006: 1.276 (total, without wildfires) 
2006: 1.164 (total, with wildfires),

whereas the wiki / HEMCO_Config file report a scale factor of 1.271 for CO in 2006. Most of the other years / scale factors are similarly off by small amounts. I'm assuming that calculating the scale factor from the "total, without wildfires" value is the correct approach, but I'm not sure why I'm getting slightly different numbers for every year / species.

Thanks!

**Comment by barronh** [comment]
My guess is that the trends report has been updated since the scalar was calculated. The README sheet in the trends report shows many updates over time. For example, an update to 2011 occurred on February 27, 2014. The 1.271 value traces back to https://github.com/geoschem/geos-chem-unittest/commit/814b4bfa78608f7570caec43211f0a648c836120 on May 2015. My guess is that it predates that, I just couldn't trace it further via git blame.

So, you could expect differences. The differences you see don't seem large compared to the uncertainty in scaling nationally from 2011 to 2006.

**Comment by IshirDutta** [comment]
Thanks, Barron! That makes sense, given the factors for most of the species only differ by a percentage point or two (except NH3, which is off by ~5% for every year in 2006-2013), so it seems that most of the changes noted in the 2014v2 update roughly cancelled out, whereas NH3 was only impacted by the changes to "misc" emissions.

I assume that the manual decrease of SO2 (~15%) and BC (30%) scale factors indicates that extrapolating scale factors beyond 2013 might a bad idea?

**Comment by barronh** [comment]
EPA's Emissions Inventory and Analysis Group (thanks to EIAG) gathered some older copies that they could find, and I checked the CO just to test the hypothesis. The factors I found were consistent with Ishir's numbers. The older copies we have, however, stopped at the 2014v2. This is likely not far enough back. For example, a trends report where 2011 changed would be most influential in affecting the type of change you see.

Also, note that it'd be better to use newer NEI. See https://github.com/geoschem/geos-chem/issues/547 for a description and link to files. Please note that these may be incorporated into a later version, but for now have not been reviewed and included in the standard model.
