### ISSUE TITLE
[QUESTION] How to save out GFAS scale factor in hemco output?

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#366]
Hi, in the hemco handbook, it seems all output are emissions. Is that possible to save out other variables in hemco netcdf output? 

In my case I am trying to save out GFAS scale factor/mami variable (0.1x0.1) in configure input as nested resolutions (0.25x0.3125). I turned on GFAS and added some lines in HEMCO_diagnositcs.rc, which is shown below. But it doesn't work at all. I was wondering if anyone has any insight on it?

###############################################################################
###############################################################################
mami     mami     300      -1  -1   2   m  Mean altitude of maximum injection

**Comment by msulprizio** [comment]
There is not currently a way to output scale factors to the HEMCO diagnostics output. However, you may be able to fake this by modifying one of the GFAS entries to use a value of 1.0 instead of the file path (i.e. use 1.0 kg/m2/s for every grid box) and apply the scale factors to that field. When you save out the GFAS emissions for that species via the HEMCO diagnostics, it should return 1.0 x the scale factor.

**Comment by jinlx** [comment]
Cool! Thanks for answering the question. I really appreciate it. I will close this issue now.
