### ISSUE TITLE
[QUESTION]A question about the GCARR Function in gckpp.kpp 

### ISSUE THREAD

**Issue by yutao-chen** [geoschem/geos-chem#378]
The GCARR FUNCTION _( GCARR =  DBLE(A0) * EXP(DBLE(C0)/TEMP) * (300._dp/TEMP)**DBLE(B0))_ in gckpp.kpp file is used to calculate the reaction rate constant and it was compiled according to Arrhenius equation. But I don't know what does the last term of the formula , (*300._dp/TEMP)**DBLE(B0),  mean to do?  It seems redundant comparing with the Arrhenius equation.
And What does "B0" stand for in FUNCTION GCARR? 
Look forward to your reply.

GOOD LUCK, GOOD HEALTH

**Comment by yantosca** [comment]
I'm not a chemist, so I'm not 100% sure.  I think the GCARR function is written to accomodate rate reactions where the first term is the Arrhenius equation and the second term is an inverse temperature exponential.  I agree, that function should have been documented better.  If the rate is just a pure Arrhenius reaction then B0 can be set to zero.   Otherwise if the rate is the inverse temperature exponential, then A0 can be set to zero.  But 

@msulprizio: any ideas?

**Comment by yantosca** [comment]
I can close out this issue for now.  Feel free to reopen.
