### ISSUE TITLE
[FEATURE REQUEST] Update KPP functions to have unique names in KPP namespace

### ISSUE THREAD

**Issue by tsherwen** [geoschem/geos-chem#387]
Hello GCST, 

Please could we update a few of the new KPP functions to have unique names in *.eqn/*.kpp files?

Some of the new functions have the same name as species used elsewhere in KPP namespace (e.g. PAN, NIT). This causes issues for various parsers I have been using with GEOS-Chem's KPP files since version 10/11, and suspect it could affect other people using these parsers or other automated methods for working with KPP files. For KPP functions in the past, we have typical prefixed the functions (E.g. with 'GC_') and this removes the namespace issues.  I would suggest this as the approach for these new functions too. 

I have made these changes in the branch linked below, which I just submitted as a pull request (#386) for if the suggested changes are agreed. GitHub says this branch, which was forked off v12.9.1, will merge now without conflicts. As this is just changes to namespace and formating, no change in output etc would be expected. 

https://github.com/tsherwen/geos-chem/tree/v12.9.1_dev_namespace

In this branch, I have also parsed the (4) GC mechanism KPP *.eqn files to ensure the formatting is consistent. 

Cheers, 

Tomas

**Comment by yantosca** [comment]
I merged this PR into the dev/GC_13.0.0 branch, which will be eventually merged up to main for the 13.0.0 release.

These updates result in zero differences w/r/t the reference code, as long as parallelization is turned off. However, I believe that this is caused by an unrelated parallelization error (e.g. some variable not being held PRIVATE), which I will address in a separate issue. Therefore I think we are OK to close out this PR.

**Comment by tsherwen** [comment]
Great, thanks for doing this Bob!
