### ISSUE TITLE
[BUG/ISSUE] If not prioritized would double generation of restart file lead to errors when running in segments?

### ISSUE THREAD

**Issue by neyranaz** [geoschem/geos-chem#398]
Model version: 12.7.0
AMI Name: GEOSChem_12.7.0_tutorial_20200205

# Double generation of restart file

Considerations: GC generates a restart file at the end of a run period, and the dry-run pulls a restart at the beginning of the dry run period. 

**Description of the issue**

Lets say we run a 2014 annual simulation in segments: 
-Segment A  (20140101-20140601) 
-Segment B (20140601-20141231) 

After we run segment A, GC generates a restart file at the end of the run, which would be called 

`HEMCO_restart.201406010000.nc`

When we are preparing to run Segment B, we do a dry-run and download the data, which pulls a restart file from 
the GC input repository called 

`GEOSChem.Restart.20140601_0000z.nc4`

So at certain point there are two restart files for the same date, with different characteristics. Since both restart files are intended to do the same, we wanted to know if GC would prioritize. 

`HEMCO_restart.201406010000.nc` over  `GEOSChem.Restart.20140601_0000z.nc4` 

even if both files were in the same directory.  Because, if it was the other way around, running in segments would lead to errors.

**Comment by yantosca** [comment]
Thanks for writing.  The HEMCO_restart file is for certain quantities from the HEMCO extensions (mostly soil NOx for the fullchem simulation) that need to be preserved between run stages. 

Also -- the GEOS-Chem restart file that gets pulled from the ExtData/GEOSCHEM_RESTARTS folder is a sample restart file that is meant just to get your simulation initialized.  This is OK for starting the very first stage of a simulation.  But you should not use that for subsequent run stages.  You should use the restart files that are generated from the prior run stage.

For example: 

- Run stage 1: 20140101-20140601:  this will link to the "sample" restart file from ExtData/GEOSCHEM_Restarts.  But in this run directory you should have a restart file generated at the time the run finishes: GEOSChem.Restart.20140601_0000z.nc4.

- Run stage 2: You would want to use the GEOSChem.Restart.20140601_0000z.nc4 file from Run Stage 1, and not the sample restart file from ExtData/GEOSCHEM_RESTARTS.  Otherwise you are discarding the results of the first 6 months of spinup.

Hope this helps!

**Comment by yantosca** [comment]
I will close out this issue for now. If you are still having problems, please let me know, and I can reopen this.
