### ISSUE TITLE
[BUG/ISSUE] CH4 Lake Emissions

### ISSUE THREAD

**Issue by ahsouri** [geoschem/geos-chem#409]
# Ask a question about GEOS-Chem:
Hi, 

I've faced an issue while running CHEM=CH4 (Code.12.8.0). I think it should be easily addressed.
HEMCO complains about the lake emissions:
```
**"HEMCO: Opening /scratch/sao_atmos/ahsouri/INPUT_LEVEL0_4MODELS/GEOS_Chem/ExtData/HEMCO/CH4/v2017-10/Lakes/Maasakkers_Lakes_2014.01x01.nc
 Invalid time unit: months
 HEMCO ERROR: NC_READ_TIME_YYYYMMDDhhmm
 Error in HCOIO_DATAREAD called from HEMCO ReadList_Fill: CH4_LAKES
 Error in ReadList_Fill (3) called from HEMCO ReadList_Read
 Error in ReadList_Read called from hco_run"**

#==============================================================================
# --- Emissions from Lakes (Maasakkers et al., in prep) ---
#==============================================================================
(((LAKES
0 CH4_LAKES $ROOT/CH4/v2017-10/Lakes/Maasakkers_Lakes_$YYYY.01x01.nc emi_ch4 $YYYY/1-12/1/0 C xy molec/cm2/s CH4 - 12 1
)))LAKES
```
Best,

**Comment by yantosca** [comment]
Thanks for writing.  It looks like the netCDF file that you are using is not COARDS-compliant. The error is:
```
Invalid time unit: months
HEMCO ERROR: NC_READ_TIME_YYYYMMDDhhmm
```
This is because the netCDF files that HEMCO reads in must adhere to the [COARDS conventions](http://wiki.seas.harvard.edu/geos-chem/index.php/The_COARDS_netCDF_conventions_for_earth_science_data).  For compatibility with COARDS, the time units must be:

- days since YYYY/MM/DD hh:mm:ss
- hours since YYYY/MM/DD hh:mm:ss
- minutes since YYYY/MM/DD hh:mm:ss
- seconds since YYYY/MM/DD hh:mm:ss

where YYYY/MM/DD hh:mm:ss is a reference time (preferably the first time in the netCDF file).

Months are not an acceptable time unit for COARDS because different months have different days.  I think if you change the time values in the netCDF file from "months since" to one of the other time units then HEMCO should be able to read it in properly.

You can use the isCoards script (in the NcdfUtil/perl folder of your GEOS-Chem source code) to check if a netCDF file is [COARDS-compliant](http://wiki.seas.harvard.edu/geos-chem/index.php/The_COARDS_netCDF_conventions_for_earth_science_data#Determining_if_a_netCDF_file_is_COARDS-compliant).

**Comment by yantosca** [comment]
@msulprizio has a fix and will comment here shortly.

**Comment by msulprizio** [comment]
Hi Amir,

In general, we do not recommend using the CH4 emissions from lakes because they tend to double-count wetland emissions in some areas. For that reason, the lakes switch is set to false by default in HEMCO_Config.rc.

If you do choose to use the CH4 lakes emissions, you should be able to bypass that error by fixing the units in those files. As Bob mentioned above, the units for time in the lakes files is "months", which does not meet the COARDS standards:

```netcdf Maasakkers_Lakes_2009.01x01 {
dimensions:
        time = 12 ;
        lat = 1800 ;
        lon = 3600 ;
variables:
        float time(time) ;
                time:standard_name = "time" ;
                time:long_name = "Time" ;
                time:units = "months" ;
```

when I run our `IsCoards` script on one of the lakes files, I get:

```
The following items DO NOT ADHERE to the COARDS standard:
---------------------------------------------------------------------------
-> time:calendar is missing
"-> time:units" should be "{days,hours,minutes,seconds} since" a reference date/time"
```

I have a script `fix_time.sh` that I've used to fix a few of the other CH4 emissions files. I've fixed the files on our end. The corrected files and the `fix_time.sh` script can now be found at http://geoschemdata.computecanada.ca/ExtData/HEMCO/CH4/v2017-10/Lakes/.
