### ISSUE TITLE
[QUESTION] Problem compiling 12.7.2

### ISSUE THREAD

**Issue by fredbarretoc** [geoschem/geos-chem#427]
Problem compiling geoschem 12.7.2 is not creating files in the / bin directory
How to install and compile to run the application?

**Comment by yantosca** [comment]
Thanks for writing.  We don't have enough information to solve your problem.  Please see our wiki page [Submitting GEOS-Chem support requests](http://wiki.seas.harvard.edu/geos-chem/index.php/Submitting_GEOS-Chem_support_requests).

Also you may have encountered a compilation error, which is why the executable file was not created.

For more information about compiling, please see our [Getting Started with GEOS-Chem](http://wiki.seas.harvard.edu/geos-chem/index.php/Getting_Started_with_GEOS-Chem) user manual.

**Comment by fredbarretoc** [comment]
The first error was the lack of the species_database.yml file in Code.12.7.2 / Headers. This did not prevent the execution from continuing but may affect the expected result in some way.

 

The second error indicates the missing geos file in Code.12.7.2 / bin. This yes interrupted the execution and reported an error message:



./CodeDir/bin/geos is equivalent to Code.12.7.2 / bin / geos. This is a symbolic link.

look at the folder of the previous version (/Code.12.3.2/bin) the geos file will be present, it is the result of the installation.

**Comment by yantosca** [comment]
Again, I cannot see any of your files unless you post them here.

**Comment by yantosca** [comment]
I will close out this issue for now since we have not heard from you for a while.
