### ISSUE TITLE
Compiler error when building with PRECISION=4

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/geos-chem#43]
Hi everyone,

In yesterday's MDS meeting I mentioned that I was having trouble building GEOS-Chem with `PRECISION=4`. This issue is following up on that.

When I try to build GEOS-Chem Classic with `PRECISION=4` I get a complier error when `state_chm_mod.F90` is compiling. The compiler error is the following:

```console
$ ifort -cpp -w -auto -noalign -convert big_endian -O2 -vec-report0 -fp-model source -openmp -mcmodel=medium -shared-intel -traceback -DLINUX_IFORT -DBPCH_DIAG -DBPCH_TIMESER -DBPCH_TPBC -DNC_HAS_COMPRESSION -module ../mod -I/software/include -c -free state_chm_mod.F90
state_chm_mod.F90(2982): error #5286: Ambiguous generic interface REGISTER_CHMFIELD: previously declared specific procedure REGISTER_CHMFIELD_R4_3D is not distinguishable from this declaration. [REGISTER_CHMFIELD_RFP_3D]
  SUBROUTINE Register_ChmField_Rfp_3D( am_I_Root, metadataID, Ptr2Data,  &
-------------^
compilation aborted for state_chm_mod.F90 (code 1)
../Makefile_header.mk:1277: recipe for target 'state_chm_mod.o' failed
make[5]: *** [state_chm_mod.o] Error 1
```
## Info
- GEOS-Chem version: 12.1.1, 12.2.1, 12.4.0 (the only version I've checked)
- No modifications to the source

## To reproduce
1. Create a new `geosfp_4x5_standard` run directory and `cd` into it
2. Build with `PRECISION=4`
    ```
    make PRECISION=4 mpbuild
    ```

## Attachements
- Build log from when I tried with 12.4.0: [build.log](https://github.com/geoschem/geos-chem/files/3477024/build.log)
- Complete run directory: [geosfp_4x5_standard.tar.gz](https://github.com/geoschem/geos-chem/files/3477027/geosfp_4x5_standard.tar.gz)

---

Is there something I'm missing?

**Comment by yantosca** [comment]
Hi Liam,

I think I see what is going on here.  In state_chm_mod we have an interface:


      INTERFACE Register_ChmField
         MODULE PROCEDURE Register_ChmField_R4_3D
         MODULE PROCEDURE Register_ChmField_Rfp_2D
         MODULE PROCEDURE Register_ChmField_Rfp_3D
         MODULE PROCEDURE Register_ChmField_Rfp_4D
      END INTERFACE Register_ChmField

so if you type Register_ChmField, then based on the types of the input arguments, "under-the-hood" the compiler will select the proper function.

This all works when you use the default PRECISION=8 because subrotuine Register_ChmField_Rfp_4D has this argument:

    REAL(fp),          POINTER       :: Ptr2Data(:,:,:,:) ! pointer to data   

but fp defaults to REAL(f8).  But when you set PRECISION=4, fp switches over to REAL(f4), and then you have two subroutines (MODULE PROCEDURE Register_ChmField_R4_3D and MODULE PROCEDURE Register_ChmField_R4_3D) with identical input arguments.  So the compiler can't tell which subroutine to pick.

I think the solution would be to add more subroutines to the interface:

      INTERFACE Register_ChmField
         MODULE PROCEDURE Register_ChmField_R4_2D
         MODULE PROCEDURE Register_ChmField_R4_3D
         MODULE PROCEDURE Register_ChmField_R4_4D
         MODULE PROCEDURE Register_ChmField_R8_2d
         MODULE PROCEDURE Register_ChmField_R8_3D
         MODULE PROCEDURE Register_ChmField_R8_4D
      END INTERFACE Register_ChmField

and declare Ptr2Data with REAL(f4) or REAL(f8) but not REAL(fp).  That should work.

In any case... a while ago we thought that PRECISION=4 would reduce memory, but then we realized that it was causing mass not to be conserved.  So we still keep the flexible precision in the code but in practice we do not use it.  See:

http://wiki.geos-chem.org./Flexible_precision_in_GEOS-Chem#Mass_conservation

**Comment by LiamBindle** [comment]
Hi Bob, 

Thanks for the explanation. I'll go ahead and remove the option to build GC-Classic with `PRECISION=4` from the CMakeLists in `dev/12.6.0` then.

Thanks again

Liam
