### ISSUE TITLE
[QUESTION] How to add non-advected chemical species to Budget Diagnostic?

### ISSUE THREAD

**Issue by chfite** [geoschem/geos-chem#431]
I was wondering how I might add non-advected species to the Budget Diagnostic? 

Essentially what I am wanting is budget diagnostic output (in kg/s) for a dummy species that I have tagged for the purpose of tracking a specific reaction. I have been using the ProdLoss diagnostic so far to get production rates (molec/cm3/s) for my tagged reaction, but ideally I also want the vertically integrated values for the PBL, which is why the budget diagnostic is appealing. 

My assumption was that if I added a basic molecular weight of 1.0 g/mol for my dummy species in the species database then there would in theory be a way for that budget calculation to still be performed and with the output I could do my own unit conversions to apply it to the molecular weights of the specific molecules I was concerned with in that tagged reaction. However, I would not want this dummy species to be advected since it is a dummy species, which is where the issue comes in since right now the budget diagnostic appears to only provide output for advected species?

Is there a more adequate way to get my ProdLoss tagged reactions added to the budget diagnostic? What kinds of changes would have to be made? Or, is there a better way of going about getting the type of output I want?

I am currently using GC 12.9.2.

**Comment by lizziel** [comment]
Hi @chfite,

The budget diagnostic arrays are allocated for `nAdvect` species in `Headers/state_diag_mod.F90`. You could edit your version to allocate `nSpecies` instead so that you calculate budgets for non-advected species stored in `State_Chm%Species` as well. You would also then need to edit the same file such the `TagId` for each budget diagnostic is `ALL` instead of `ADV`. Finally, you would need to change `GeosCore/diagnostics_mod.F90` subroutines `Compute_Budget_Diagnostics` and `Compute_Column_Mass` to loop over all species rather than the argument `numSpc` passed in, and remove the mapping between the species loop index and the `State_Chm%Species` 4th dimension index. Beware that much of this code changed in 13.0.0 so this strategy would need to be edited if you update versions.

If you are looking to get values for one species you could also create a new standalone diagnostic for it.

**Comment by chfite** [comment]
@lizziel Thanks for the reply! I have a few follow up questions. If I expanded the budget diagnostic to State_Chem%Species instead of just the advected would I run into issues if some of the dummy species don't have molecular weights or would I need to assign them all one? Wasn't sure if it would assume a value of 1 g/mol or something.

Getting output for ALL species would likely be overkill. So, if I requested in HISTORY.rc that I wanted specifically BudgetChemistryPBL_dummyrxn, for example, would memory still be allocated and budgets calculated for ALL species and not just the one I specified? Or would it only allocate memory for the specific species I wanted output for?

Would creating a new mapping vector of my own to specify which species I want in my output simplify changes or would it just add to the number of changes needed to be made?

And lastly, do you think making all the changes I want would be easier in GC 13.0.0 versus 12.9.2?

**Comment by lizziel** [comment]
If you are using version 12 then budgets for ALL advected species will be allocated and computed regardless of what you put in HISTORY.rc. The same would apply for all species, both advected and non-advected, if you expand the arrays to include all of them. It is indeed overkill and wasteful. For this reason GEOS-Chem 13.0 will only allocate for what is specified in the history config file. This update is still in progress in the dev branch of 13.0.

Creating a new mapping vector is definitely a possibility. You could pass that mapping to the Compute_Column_Mass and Compute_Budget_Diagnostics calls, and make the appropriate changes in state_diag_mod.F90 for the array allocation. As I said earlier, however, this may no longer work in 13.0.0. @yantosca would be the best one to comment on how exactly 13.0.0 changes with regard to the array allocation and mapping, and whether it would be most efficient if you waited for 13.0.0 to make your changes.

If you do go the route of expanding the budget diagnostics to all species then I think you should be okay with regards to molecular weights. It should use a default value if a species is not found in the species database. However, I am not 100% certain on this given many recent changes with usage of the species database. If it does not work please report this since it may be a bug we would want to fix or potentially give more error handling for.

**Comment by lizziel** [comment]
Hi @chfite, just checking in on if you are all set with this question. I will close it out if you are satisfied with the result.

**Comment by chfite** [comment]
@lizziel Yes I am all set with this question, thanks.
