### ISSUE TITLE
IO error reading merra2 meteorological file

### ISSUE THREAD

**Issue by huoxiao-C** [geoschem/geos-chem#44]
Hi everyone,

I simulate CO2 from 2005-01-01-00 to 2005-01-01-01, and I downloaded the merra2 data which is put in ~/GEOS_CHEM/data/GEOS_2x2.5/MERRA2/2005/01 directory.The error when I run ./geos.mp command is followiing:

```
HEMCO: Opening /home/huoxiao/GEOS_CHEM/data/GEOS_2x2.5/MERRA2/2015/01/MERRA2.20150101.CN.2x25.nc4

In Ncop_Rd, cannot open:  /home/huoxiao/GEOS_CHEM/data/GEOS_2x2.5/MERRA2/2005/01/MERRA2.20050101.A3cld.2x25.nc4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 
This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!
```

I have two problems:
1)My simulation time is 2015-01-01. why does it open meteorological file in 2015:
```
Opening /home/huoxiao/GEOS_CHEM/data/GEOS_2x2.5/MERRA2/2015/01/MERRA2.20150101.CN.2x25.nc4
```

2)In "A question about GEO-Chem v 12.1.1 need netcdf4 library?", the answer is the data file maybe not exsit, but  in my directory :
```
/home/huoxiao/GEOS_CHEM/data/GEOS_2x2.5/MERRA2/2005/01
```
the file is exsiting, why can't the program read this file? 
```
MERRA2.20150101.CN.2x25.nc4
```
Is there something I'm missing?

**Comment by yantosca** [comment]
Hi Huoxiao,

The MERRA-2 met fields also contains a "constant fields" file:
http://wiki.geos-chem.org/List_of_MERRA-2_met_fields#Constant_fields 
This file contains time-invariant data, such as the fraction of land in each grid box, the fraction of ocean in each grid box, etc.  We only read this once instead of on every timestep.  For MERRA-2 the constant file is in the MERRA/2015/01 folder, so you will need to copy this file:

    GEOS_2x2.5/MERRA2/2015/01/MERRA2.20150101.CN.2x25.nc4

to your data directory.

Bob Y.

**Comment by lizziel** [comment]
It is strange that you are getting a message about an error reading MERRA2.20050101.A3cld.2x25.nc4 if the issue is actually reading the constants file. I wonder if two things are going on here: (1) you don't have the constants file so the model is crashing, and (2) there is a bug in the error handling that prints the wrong filename.

Let us know if having the constants file available fixes the issue. If it does I think we should look into the error handling for missing files.

**Comment by huoxiao-C** [comment]
Hi Bob,lizziel,

In my data directory, I have file:
```
GEOS_2x2.5/MERRA2/2015/01/MERRA2.20150101.CN.2x25.nc4
```
and the program open also the file from HEMCO.log output.
I forget to tell that my GEOS-CHEM version is 12.4.0.
 
Thank your reply,
huoxiao

**Comment by huoxiao-C** [comment]
Hi everyone,

My problem is solved. The problem is downloaded ``` MERRA2.20050101.A3cld.2x25.nc4``` data not complete, but my browser shows download process finished and no error information.

Sincerely thank Bob and lizziel again!
huoxiao
