### ISSUE TITLE
Some questions about the running  CO2 simulation

### ISSUE THREAD

**Issue by huoxiao-C** [geoschem/geos-chem#45]
Hi everyone,

I have a questions that don't quite understand.
```
TMPU1    not found in restart, keep as value at t=0
 SPHU1    not found in restart, keep as value at t=0
 PS1_WET  not found in restart, keep as value at t=0
 PS1_DRY  not found in restart, keep as value at t=0
 DELP_DRY not found in restart, set to zero
```
In my understanding, initial time there is no need for meteorological restart file, Why do these state variables need to be initialized? Do they have an impact on the results by not passing the file to the initial value?could anyone help me? Thank you very much!

huoxiao

**Comment by msulprizio** [comment]
Hi Huoxiao,

In GEOS-Chem 12.1.0, several fields were added to the GEOS-Chem restart file in an attempt to reduce differences between single runs (e.q. one 3-month run) and multi-segmented runs (e.g. three 1-month runs). Please see http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_restart_files#New_fields_added_to_the_GEOS-Chem_restart_file. Those met fields were added to the restart file at that time because they are fields that are interpolated each timestep. The impact of including those fields in the restart file is fairly small.

**Comment by huoxiao-C** [comment]
Yeah, I read wiki too carefully，thank you very much!
