### ISSUE TITLE
[QUESTION] How to Restart a simulation using existing restart files?

### ISSUE THREAD

**Issue by debatoshpartha** [geoschem/geos-chem#452]
I was running a 2x2.5 global simulation which was interrupted in the middle. The simulation has created restart files in .nc format. I want to know how to use the latest restart file (April 2016) to restart my interrupted simulation and which file(s) should be modified in order to do that? My running directory is copied below: 
```
lrwxrwxrwx 1 hc3346 wsu        53 Aug  3 21:06 CodeDir -> /wsu/home/hc/hc33/hc3346/read_source_code/Code.12.6.3
-rw-r--r-- 1 hc3346 wsu     92694 Aug  3 23:57 compile.log
-rw-r--r-- 1 hc3346 wsu     13640 Aug  3 23:59 diaginfo.dat
-rwxr-xr-x 1 hc3346 wsu  14246096 Aug  3 23:57 geos
lrwxrwxrwx 1 hc3346 wsu        97 Aug  3 21:06 GEOSChem.Restart.20150701_0000z.nc4 -> /wsu/home/groups/yhgroup/ExtData/GEOSCHEM_RESTARTS/v2018-11/initial_GEOSChem_rst.2x25_standard.nc
-rwxr-xr-x 1 hc3346 wsu      6816 Aug  3 21:06 getRunInfo
-rw-r--r-- 1 hc3346 wsu    385150 Aug  3 23:53 HEMCO_Config.rc
-rw-r--r-- 1 hc3346 wsu     32195 Aug  3 21:06 HEMCO_Diagn.rc
-rw-r--r-- 1 hc3346 wsu  60156898 Aug 17 08:55 HEMCO.log
-rw-r--r-- 1 hc3346 wsu    206008 Aug  5 11:17 HEMCO_restart.201508010000.nc
-rw-r--r-- 1 hc3346 wsu    210594 Aug  6 22:44 HEMCO_restart.201509010000.nc
-rw-r--r-- 1 hc3346 wsu    213609 Aug  8 10:01 HEMCO_restart.201510010000.nc
-rw-r--r-- 1 hc3346 wsu    213942 Aug  9 21:24 HEMCO_restart.201511010000.nc
-rw-r--r-- 1 hc3346 wsu    213747 Aug 11 06:14 HEMCO_restart.201512010000.nc
-rw-r--r-- 1 hc3346 wsu    213603 Aug 12 15:58 HEMCO_restart.201601010000.nc
-rw-r--r-- 1 hc3346 wsu    213751 Aug 14 01:57 HEMCO_restart.201602010000.nc
-rw-r--r-- 1 hc3346 wsu    214112 Aug 15 06:28 HEMCO_restart.201603010000.nc
-rw-r--r-- 1 hc3346 wsu    213956 Aug 16 13:10 HEMCO_restart.201604010000.nc
-rw-r--r-- 1 hc3346 wsu     32986 Aug  3 21:06 HISTORY.rc
-rw-r--r-- 1 hc3346 wsu     16127 Aug  3 21:09 input.geos
-rw-r--r-- 1 hc3346 wsu       871 Aug  3 23:57 lastbuild
-rwxr-xr-x 1 hc3346 wsu     19561 Aug  3 21:06 Makefile
drwxr-xr-x 2 hc3346 wsu      4096 Aug 16 13:10 OutputDir
-rw-r--r-- 1 hc3346 wsu   3774316 Aug  4 00:02 Ox.mass.initial
-rw-r--r-- 1 hc3346 wsu       708 Aug  3 21:06 README
-rw-r--r-- 1 hc3346 wsu  14492126 Aug 17 08:57 runGCnested.log
-rw-r--r-- 1 hc3346 wsu 314528428 Aug 16 13:10 trac_avg.geosfp_2x25_standard.201507010000
-rw-r--r-- 1 hc3346 wsu    105420 Aug  3 23:59 tracerinfo.dat
-rwxr-xr-x 1 hc3346 wsu      9273 Aug  3 21:06 validate.pl
```

**Comment by WilliamDowns** [comment]
Unfortunately you won't be able to resume your run because those monthly `HEMCO_restart` files you have only save out a [small subset variables handled by HEMCO](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_restart_files#Do_I_need_a_HEMCO_restart_file_for_my_initial_spin-up_run.3F). By default, GEOS-Chem does not save out extra species restart files (like the `GEOSChem.Restart.20150701_0000z.nc4` file you started your run with) except at the intended end of your run. In the future if you are worried about your runs being interrupted, you can edit the `Restart.frequency` setting in `HISTORY.rc` to something like `Restart.frequency:          00000100 000000,` to save out your progress in species restart files at the beginning of every month, and then if your run ends you can edit `Start YYYYMMDD, hhmmss` in `input.geos` to start at beginning of the latest available month (GEOS-Chem will automatically recognize that you have a `GEOSChem.Restart` file for that date and use it to initialize).

**Comment by debatoshpartha** [comment]
Professor,

I got this reply from GitHub. What should I do now?

Sincerely,
Debatosh


[1512071508530_PastedImage]
Debatosh Banik Partha
PhD Student
Department of Civil & Environmental Engineering
5050 Anthony Wayne Dr., Detroit, MI 48202, USA
hc3346@wayne.edu<mailto:hc3346@wayne.edu>

**Comment by yantosca** [comment]
The only thing you can do is to restart the simultion from the date when the last GEOS-Chem restart file (in this case: GEOSChem.Restart.20150701_0000z.nc4).

You may want to dig into your code a bit more to try to discover why the run was interrupted in the first place.
