### ISSUE TITLE
[QUESTION] Should I provide more species for offline seasalt?

### ISSUE THREAD

**Issue by hongjianweng** [geoschem/geos-chem#472]
Hi all, 

The seasalt extension adds many new species in version 12.9.3.
```
107     SeaSalt                : on    SALA/SALC/SALACL/SALCCL/SALAAL/SALCAL/BrSALA/BrSALC/MOPO/MOPI
    --> SALA lower radius      :       0.01
    --> SALA upper radius      :       0.5
    --> SALC lower radius      :       0.5
    --> SALC upper radius      :       8.0
    --> Model sea salt Br-     :       true
    --> Br- mass ratio         :       2.11e-3
```
Our offline seasalt just provides SALA and SALC, so should I offer more of the above species for offline seasalt?

Thanks!
Hongjian

**Comment by msulprizio** [comment]
Hi @hongjianweng. There is no need to save out the additional species for the offline sea salt emissions. The emissions for SALAAL, SALACL, BrSALA are all computed from SALA and the emissions for SALCAL, SALCCL, BrSALC are computed from SALC using the scale factors defined at the bottom of HEMCO_Config.rc:

```
#==============================================================================
# --- Offline sea salt scale factors ---
#
# NOTES:
# - Sea salt alkalinity and chloride values obtained from hcox_seasalt_mod.F90
# - BrContent obtained from '--> Br- mass ratio' in SeaSalt extension above
#==============================================================================
(((OFFLINE_SEASALT
615 SSAlkalinity 1.0     - - - xy 1 1
616 SSChloride   0.5504  - - - xy 1 1
617 BrContent    2.11e-3 - - - xy 1 1
)))OFFLINE_SEASALT
```

The additional species MOPO and MOPI are for the marine POA option, which requires additional species and a logical switch in input.geos. It's not clear to us how much that option is utilized by the community. If users want to marine POA, it should be fine for them to use online sea salt emissions instead.

**Comment by hongjianweng** [comment]
Hi @msulprizio .  

So, there is no need to set seasalt extension on if you want to get SALAAL, SALACL, SALABr when using offline seasalt.
However, MEGAN is set to on even though the offline biogenic VOC emissions are also on because of additional emissions (like methanol) that are now used in MEGAN after the offline biogenic VOC emissions were generated.  
This may confuse the user if he wants to use these offline emission.
So I don't know if it's more convenient  if I provide offline SALAAL, SALACL, SALABr, EOH and so on.
 
Thanks.
hongjian

**Comment by msulprizio** [comment]
It doesn't seem necessary to save out the additional sea salt species since they are directly computed from SALA and SALC emissions both in the sea salt extension and in the offline sea salt emissions. Saving out the additional species would create larger files, especially at the native resolution. I think it makes sense to just continue saving out SALA and SALC emissions for the offline sea salt option.

For the additional species in MEGAN, I think it does make sense to save those out for the offline biogenic VOC emissions. Ideally, users would not have to have the MEGAN extension on if using offline biogenic VOC emissions but because methanol emissions were not in the offline biogenic VOC files at the time we added methanol as a species in GEOS-Chem, we had no choice but to turn on the MEGAN extension to get those emissions.

**Comment by hongjianweng** [comment]
I think I can later add methanol emission in the offline biogenic VOC files if necessary and users could have the MEGAN extension off when using offline biogenic VOC emissions.
