### ISSUE TITLE
[QUESTION] How to make use of the updated version CEDS (v2020-08) 

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#473]
Hi there,

I am trying to run simulations with latest version CEDS (v2020-08). However, variables in new version are different from the default version (v2018-08) in HEMCO.Config and we can't use it by simpily changing the directory setting. I was wondering how to modify Config file to make use of the latest data.

Thanks!
Lixu

**Comment by yantosca** [comment]
Thanks for writing @jinlx.  The updated CEDS will be included in the GEOS-Chem 13.0.0 release.

We do plan on issuing a 13.0.0 release candidate after the initial 1-month benchmark takes place.  You will be able to obtain this version and "kick the tires" so to speak.  The 13.0.0 release candidate period is a time when we encourage users to download and run the code and to report any issues so that we can correct them before the official 13.0.0 release.

We hope to start the initial benchmarking for 13.0.0 very soon, and to have a release candidate ready by the end of October 2020 (knock on wood).   The full benchmarking for 13.0.0 will take much longer, so it might be a while before the official 13.0.0 release is ready.

**Comment by jinlx** [comment]
Sounds good! Thank you for clarifying it! Please feel free to closs the issue. -Lixu
