### ISSUE TITLE
The problem of GEOS-Chem RRTMG model

### ISSUE THREAD

**Issue by yinhao1995** [geoschem/geos-chem#483]
When I compile rrtmg mode, the following compilation error occurs. The compile command I run is: make -j4 mpbuild NC_DIAG=y BPCH_DIAG=n TIMERS=1. I don't know how to correct such a mistake.

> ifort: command line error: option ‘-override-limits’ is not supported. Please use the replacement option ‘-qoverride-limits’ make[5]: *** [rrlw_vsn.o] 1 error1
make[5]: ***
ifort: command line error: option ‘-override-limits’ is not supported. Please use the replacement option ‘-qoverride-limits’ make[5]: [parkind.o] error 1
ifort: command tine error: option ‘-override-limits’ is not supported. Please use the replacement option ‘-qoverride-limits’ make[5]: *** [rrsw_vsn.o] error 1
ifort: command line error: option ‘-override-limits’ is not supported. Please use the replacement option ‘-qoverride-limits’ make[5]: *** [test_arr_mult.o] error 1
make [5]: Leaving directory ‘/home/yinhao/GC/Code. 12.2. 1/GeosRad’ make[4J: *** (librad] 2
make[4]: Leaving directory ‘/hoaie/yinhao/GC/Code. 12.2. 1/GeosCore’ make[31: *** [lib] 2
make[3]: Leaving directory ‘/hoaie/yinhao/GC/Code. 12.2. 1/GeosCore’ make[2J: *** [all] 2
make[2]: Leaving directory ‘/hoaie/yinhao/GC/Code. 12.2. 1/GeosCore’ make[1J: [all] 2
make[1]: Leaving directory ‘/home/yinhao/GC/Code. 12.2.1’ make: [mpbuildl 2

**Comment by lizziel** [comment]
Hi @yinhao1995. Are you building with gfortran compiler? If yes, I think you need this fix: commit https://github.com/geoschem/geos-chem/commit/9ac8864af2dea29d6d570400e7c75aa3bdc2cd31. Previously the CMake code in the `GeosRad` directory was hard-coded for Intel compilers only.

That being said, beware that there are problems with the RRTMG netcdf diagnostics in GEOS-Chem 12. If using that version we recommend that you stick with binary format output. The RRTMG netcdf diagnostics are updated in GEOS-Chem 13.0 (soon to be release) so that they match the binary output values. 

For more information see the following GitHub issues:
- https://github.com/geoschem/geos-chem/issues/350
- https://github.com/geoschem/geos-chem/issues/481

**Comment by FeiYao-Edinburgh** [comment]
Hi @lizziel could please help me re-open #481 as I cannot re-open an issue closed by you. I only have two minor points to comment there. Thanks.

**Comment by lizziel** [comment]
Looking closer at this issue I now see that you are using an Intel compiler. The bug fix I included was on top of a different commit since 12.2.1 that enabled the override-limits option, but without the 'q' for Intel. Putting in the new code shown in my commit should still fix the issue.

I am closing this out but feel free to reopen if you still have issues.

**Comment by yinhao1995** [comment]
I use this command to compile, but I still get the following error.

> make -j4 mpbuild NC_DIAG=y BPCH_DIAG=n TIMERS=1

> ifort -cpp -w -auto -noalign -convert big_endian -O1 -override-limits -vec-report0 -fp-model source -qopenmp -mcmodel=medium -shared-intel -traceback -DLINUX_IFORT -DBPCH_DIAG -DBPCH_TIMESER -DBPCH_TPBC -DRRTMG -DGEOS_FP -DGRIDREDUCED -DGRID2x25 -DNC_HAS_COMPRESSION -DUSE_REAL8 -module ../mod -I/opt/netcdf/4.1.3/intel/2019.update2/include -r8 -c -O1 -override-limits parkind.F90
ifort -cpp -w -auto -noalign -convert big_endian -O1 -override-limits -vec-report0 -fp-model source -qopenmp -mcmodel=medium -shared-intel -traceback -DLINUX_IFORT -DBPCH_DIAG -DBPCH_TIMESER -DBPCH_TPBC -DRRTMG -DGEOS_FP -DGRIDREDUCED -DGRID2x25 -DNC_HAS_COMPRESSION -DUSE_REAL8 -module ../mod -I/opt/netcdf/4.1.3/intel/2019.update2/include -r8 -c -O1 -override-limits rrlw_vsn.F90
ifort -cpp -w -auto -noalign -convert big_endian -O1 -override-limits -vec-report0 -fp-model source -qopenmp -mcmodel=medium -shared-intel -traceback -DLINUX_IFORT -DBPCH_DIAG -DBPCH_TIMESER -DBPCH_TPBC -DRRTMG -DGEOS_FP -DGRIDREDUCED -DGRID2x25 -DNC_HAS_COMPRESSION -DUSE_REAL8 -module ../mod -I/opt/netcdf/4.1.3/intel/2019.update2/include -r8 -c -O1 -override-limits rrsw_vsn.F90
ifort -cpp -w -auto -noalign -convert big_endian -O1 -override-limits -vec-report0 -fp-model source -qopenmp -mcmodel=medium -shared-intel -traceback -DLINUX_IFORT -DBPCH_DIAG -DBPCH_TIMESER -DBPCH_TPBC -DRRTMG -DGEOS_FP -DGRIDREDUCED -DGRID2x25 -DNC_HAS_COMPRESSION -DUSE_REAL8 -module ../mod -I/opt/netcdf/4.1.3/intel/2019.update2/include -c -free test_arr_mult.F90
ifort: command line error: option '-override-limits' is not supported. Please use the replacement option '-qoverride-limits'
ifort: command line error: option '-override-limits' is not supported. Please use the replacement option '-qoverride-limits'
ifort: command line error: option '-override-limits' is not supported. Please use the replacement option '-qoverride-limits'
make[5]: *** [parkind.o] error 1
make[5]: *** 
make[5]: *** [rrlw_vsn.o] error 1
make[5]: *** [rrsw_vsn.o] error 1
ifort: command line error: option '-override-limits' is not supported. Please use the replacement option '-qoverride-limits'
make[5]: *** [test_arr_mult.o] error 1
make[5]: Leaving directory `/home/yinhao/GC/Code.12.2.1/GeosRad'
make[4]: *** [librad] error 1
make[4]: Leaving directory `/home/yinhao/GC/Code.12.2.1/GeosCore'
make[3]: *** [lib] error 1
make[3]: Leaving directory `/home/yinhao/GC/Code.12.2.1/GeosCore'
make[2]: *** [all] error 1
make[2]: Leaving directory `/home/yinhao/GC/Code.12.2.1/GeosCore'
make[1]: *** [all] error 1
make[1]: Leaving directory `/home/yinhao/GC/Code.12.2.1'
make: *** [mpbuild] error 2

**Comment by FeiYao-Edinburgh** [comment]
Hi @yinhao1995 At least to GC12.9.3, we should always compile RRTMG model with BPCH_DIAG=y. You might would like to try `make -j4 mpbuild NC_DIAG=y BPCH_DIAG=y` to see if any changes.

**Comment by lizziel** [comment]
Hi @yinhao1995,
Based on your latest compile log you are still using compiler option `-override-limits`. You need to change this to `-qoverride-limits` as the ifort error message suggests. You can find where this flag is used with this command:
`git grep -in "override-limits"`

For 12.2.1 I get this result, indicating where the flag needs to be changed.
```
GeosRad/Makefile:64:OPT     := -O1 -override-limits
GeosRad/Makefile.mcica:57:OPT     = -O1 -override-limits
GeosRad/Makefile.nomcica:57:OPT     = -O1 -override-limits
```

The previous commit I linked to made this change to the CMake file. GNU make is retired in GEOS-Chem 13.0 so the files listed above are deleted. However, the fix is the same for both.

**Comment by yinhao1995** [comment]
OK！Thanks for your help! I have been solve this problem!

**Comment by yinhao1995** [comment]
You can close this issues.

**Comment by FeiYao-Edinburgh** [comment]
> The previous commit I linked to made this change to the CMake file. GNU make is retired in GEOS-Chem 13.0 so the files listed above are deleted.

Hence I see CMakefile can automatically select `-override-limits` versus `-qoverride-limits` automatically. GNUMakefile currently support either `-override-limits` or `-qoverride-limits` at one time. We thus need to manually specify it according to the compiler and its version we have in hand.
