### ISSUE TITLE
[QUESTION]Concentration units in GEOS-Chem12.9.3

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#486]
In GEOS-Chem 12.9.3, I use “THE SpeciesConc COLLECTION” (_HISTORY.rc_) to save daily average concentration of species. However, the species concentration units are “mol mol-1 dry”. I want to save the concentration unit of some species as “ug/m3”. How can I make that happen in GEOS-Chem 12.9.3?

Thank you.

**Comment by lizziel** [comment]
Hi @yangxiajie,

One option is to create a new diagnostic array following [instructions on the wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/Adding_new_History_diagnostics). Since molecular weights are not available for all species, but are available for all _advected_ species, you can allocate the array for all advected species and safely do the unit conversion. If you only need output for a few species then you could simply create a new diagnostic for each.

Alternatively, you can edit code in `diagnostics_mod.F90` to change units for just the species you want, but this will be a hack and we do not recommend it. All `SpeciesConc` diagnostics have the same units attribute in the netcdf files so changing units for some species but not others may lead to confusion and errors.

You could also approach this problem via post-processing. You can output meteorology via the StateMet collection to get the values needed for the conversion, or even add them directly to the SpeciesConc collection in HISTORY.rc to output them to the same file. You could also tap into `https://github.com/geoschem/gcpy` to do the conversion for you, depending on what you need to look at. The benchmark plotting in GCPy currently converts all aerosol species to ug/m3, for example, for comparison plots. You could harness what is there to make the plots you would like to see.

**Comment by yangxiajie** [comment]
Hi @lizziel . Thank you for reply.

I found a variable in StateMet collection, which is named "Met_AIRDEN"(unit: kg/m3). I try to convert mol/mol to ug/m3 with the formula "ug/m3 = mol/mol * Met_AIRDEN * 1e9". I wonder whether this conversion is correct.

**Comment by lizziel** [comment]
You can check your unit conversion by writing out the terms in your equation with units.

[mol species / mol dry air] * [kg dry air / m3] * [1e6 ug / 1 g] * [1000 g / 1 kg]
= mol species / mol dry air * ug dry air / m3 * 1e9

This is not equivalent to [ug species / m3]. You need to further reduce using the molecular weights of dry air and species.

**Comment by yangxiajie** [comment]
Hi @lizziel 
Thank you for your help. Now I understand the conversion of mol/mol to ug/m3.
Thank you very much again!
