### ISSUE TITLE
[QUESTION] Offline soil NOx data after 2018

### ISSUE THREAD

**Issue by xpye98** [geoschem/geos-chem#508]
# Ask a question about GEOS-Chem:

Hi, all

In [offline soil NOx data after 2018.01.01](http://geoschemdata.computecanada.ca/ExtData/HEMCO/OFFLINE_SOILNOX/v2019-01/0.25x0.3125/2018/), emissions from fertilizer only and soil (total) are the same. There must be some incorrect operations when  calculating them, maybe related to the [issue](https://github.com/geoschem/geos-chem/issues/433) I mentioned before.
I checked the value of total soil emissions, it looks fine, which means it doesn't affect the chemistry associated to NOx.

Another question is, since 2018, the unit of offline soil NOx emission is kgN/m2/s, while in HEMCO_Config.rc, we still read it with the unit of kg/m2/s. Will GEOS-Chem convert the unit automatically? Or I have to add a scale factor behind manually? 

Thanks!

Xingpei Ye

**Comment by yantosca** [comment]
There was a bug in HEMCO that caused fertilizer emissions to be zeroed out.  Please see this issue: https://github.com/geoschem/geos-chem/issues/433.

In GEOS-Chem 12, I believe that HEMCO is doing the unit conversion automatically.  I know that we will change he HEMCO_Config.rc files starting with 13.0.0 so that all carbon units will be converted from kg C to kg.  I am not sure if this also includes changing kg N to kg, I think not.  @msulprizio might be able to clarify.

**Comment by msulprizio** [comment]
In the offline soil NOx emissions, only one value (`SOIL_NOx`) is read from file. This value represents the total soil NOx, including fertilizer NOx emissions. It is not possible to separate fertilizer NOx emissions from the offline soil NOx emissions. If users want to explore fertilizer NOx separately, they must use the online soil NOx emissions.

Input units of kgN/m2/s should automatically be converted to kg/m2/s. This automatic unit conversion has been removed in the GEOS-Chem 13.0.0 / HEMCO 3.0.0 and should now be replaced by explicit conversions (i.e. scale factors) in HEMCO_Config.rc.

**Comment by xpye98** [comment]
Thanks for your replies.
I check the HEMCO.log, it can convert kgN automatically to kg.
