### ISSUE TITLE
[BUG/ISSUE] HEMCO diagnostic shows zero globally for offline SSA emissions 

### ISSUE THREAD

**Issue by wswanson3** [geoschem/geos-chem#512]
I am using GEOS-Chem to look at sea salt aerosol emissions, including the variables SALA, SALACL, SALAAL, BrSALA, and comparable coarse mode quantities. I ran GEOS-Chem 12.9.3 for an hour on 7/1/2016 generating HEMCO diagnostics and budget diagnostics. The HEMCO diagnostics file reports zero for all sea salt aerosol quantities (EmisSALA_Natural, EmisBrSALA_Natural, etc...) despite correctly storing other offline emissions such as biogenic MTPO.  Offline sea salt aerosol quantities were stored correctly in the previous version of GEOS-Chem that I ran (12.6.1). 
The Budget diagnostic quantity BudgetMixingFullTropSALA is nonzero, and the HEMCO log shows that GEOS-Chem appears to be reading sea salt aerosol quantities correctly from the offline files. I believe this problem may be within the HEMCO diagnostic.

**Comment by lizziel** [comment]
Hi @wswanson3, could you provide your `HEMCO_Diagn.rc` and `HEMCO_Config.rc` files here? You can add extension `.txt` to the filename and then drag and drop them into the comment box. I suspect that your H`EMCO_Diagn.rc` file lists the online extension as source for those diagnostics in 12.9.3 but your `HEMCO_Config.rc` file has online extension turned off and offline turned on instead. This would result in zeros in the diagnostic output as making that switch in `HEMCO_Config.rc` will not automatically update `HEMCO_Diagn.rc`.

**Comment by wswanson3** [comment]
Lizzie,
That would explain it! I have attached both files, and the HEMCO_Diagn.rc file does list the extension as the diagnostic source. I will change the Extension Number in HEMCO_Diagn.rc to -1, which should solve my problem. 
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/5514524/HEMCO_Config.rc.txt)
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/geos-chem/files/5514525/HEMCO_Diagn.rc.txt)

**Comment by lizziel** [comment]
Thanks @wswanson3. Yes, looks like your `HEMCO_Diagn.rc` is indeed programmed to output the online extension diagnostics, as you noted. Your `HEMCO_Config.rc` file has online sea salt on and offline off, so that should be set up correctly to produce and output online sea salt diagnostic data. But toggling `HEMCO_Config.rc` to turn off the sea salt extension and turn on offline sea salt would result in zero values in your diagnostics.

I took a look at the our defaults for the new version in development, 13.0.0, and found there's a mismatch between `HEMCO_Diagn.rc` and `HEMCO_Config.rc` for sea salt diagnostics where offline sea salt is on by default but `HEMCO_diagn.rc` lists the extension for sea salt diagnostics. This will be fixed before the 13.0.0 release so others do not run into the issue you are seeing.

For future reference, when creating a run directory the offline sea salt is enabled by default and the sea salt extension is off, in both GEOS-Chem Classic and GCHP. The only exception to this is the benchmark simulation. Toggling between offline and online after run directory creation will require manual update of `HEMCO_Diagn.rc` to tap into the correct diagnostic source in HEMCO.
