### ISSUE TITLE
[QUESTION] Could not locate SpeciesConc diagnostics state registry

### ISSUE THREAD

**Issue by xpye98** [geoschem/geos-chem#552]
# Ask a question about GEOS-Chem:

Hi,

I'm using GEOS-Chem v11-02-rc, and trying to output species concentration in netCDF. I compile with `NC_DIAG=y` but an error occurred saying `Could not locate SpeciesConc_NO diagnostics state registry` (same thing also happened to other collections like AerosolMass).
So I'm not sure is t
here anything extra I need to set? Or maybe v11-02-rc just doesn't support netCDF output?
[log.txt](https://github.com/geoschem/geos-chem/files/5577088/log.txt)

Thanks,
Xingpei

**Comment by yantosca** [comment]
Thanks for writing @xpe98.  In earlier versions of GEOS-Chem, not all of the netCDF diagnostic collections were activated

v11-02rc is by now an old version (released in Jun 2018).  We would advise you to download to one of the more recent versions of GEOS-Chem, as many of the issues with diagnostics have since been resolved.
