### ISSUE TITLE
[QUESTION] Nested grid simulation using daily Boundary Condition files?

### ISSUE THREAD

**Issue by JinZheeee** [geoschem/geos-chem#572]
Hi,
I'm trying nested grid CO2 simulation. I have prepared optimized daily CO2 concentration at hour 0 and want to use them as boundary condition files. Can I use daily boundary condition files or only hourly and 3-hourly files are allowable?

Thanks.

**Comment by msulprizio** [comment]
At the moment, only 3-hourly boundary conditions saved to daily files are allowed. This is because the code in hcoi_gc_main_mod.F90 that applies the boundary conditions is hardcoded to accept data with 8 time slices. In routine `Get_Boundary_Conditions` in that module:

```
   ! Find the proper time-slice to read from disk                                         
   t_index = ( HHMMSS / 030000 ) + 1

   ! Stop w/ error if the time index is invalid                                           
   IF ( t_index < 1 .or. t_index > 8 ) THEN
      WRITE( MSG, 100 ) t_index
100   FORMAT( 'Time_index value ', i5, ' must be in the range 1 to 8!' )
      CALL GC_Error( MSG, RC, LOC)
      RETURN
   ENDIF
```

See also commit https://github.com/geoschem/geos-chem/commit/722a151c9748bc117b6fcfcb910892f3858836be.
