### ISSUE TITLE
[QUESTION]HEMCO Diagnostic output when using QFED and GFAS

### ISSUE THREAD

**Issue by chfite** [geoschem/geos-chem#579]
Having run various v12.6.0 simulations with differing biomass burning emissions I have noticed that HEMCO Diagnostic output for the `EmisBCPO_BioBurn` variable is all 0's when I use QFED and GFAS, but not when I use GFED. I know that QFED and GFAS are read in as base emissions and do not have their own HEMCO extension like GFED and FINN, so I assume that is why the HEMCO Diagnostic is showing 0's? Is this expected behavior, or should there be non-zero diagnostic output when using QFED and GFAS?

**Comment by yantosca** [comment]
Thanks for writing @chfite, and Happy New Year.

I think this is because the extension number for the Emis*_Bioburn diagnostics in HEMCO_Diagn.rc is set to GFED (111).  See this snippet:

https://github.com/geoschem/geos-chem/blob/7e9bfc36e4c1e939bc45398a8332fcaab386e8dc/run/GCClassic/HEMCO_Diagn.rc.templates/HEMCO_Diagn.rc.fullchem#L61-L72

If you are using QFED or GFAS, you should change the 111 (GFED extension number) to 0.  That should pick up the base emissions.  You can also set the extension number to -1, which will pick up biomass burning from all sources.  That should let you go back & forth between biomass data sets without having to keep editing the HEMCO_Diagn.rc file.

**Comment by yantosca** [comment]
Hi @chfite, Happy New Year. Just checking to see if the suggested fix resolved your issue.  Let us know.

**Comment by chfite** [comment]
@yantosca apologies, but yes it seemed to have fixed the issue and so now I get non-zero values in the HEMCO diagnostic output when using QFED and GFAS, as I should. Thanks!

**Comment by yantosca** [comment]
Thanks @chfite!  I'll close out this issue now. Best wishes for 2021!
