### ISSUE TITLE
[QUESTION]HEMCO Onroad emission

### ISSUE THREAD

**Issue by JeanJGuo** [geoschem/geos-chem#581]
NEI2011 has a file called NEI11_0.1x0.1_$YYYY$MM_monmean_onroad_catx.nc. This file is not referenced in the unittest HEMCO_Config.rc file. The [README ](
http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/NEI2011/v2017-02-MM/README) file mentions that both onroad and offroad emissions files are provided and they should both be scaled. I could not find the offroad emissions files in the HEMCO/NEI2011 directory and I don't understand how to apply the scaling. 

Does NEI2011 already had onroad emissions in the surface monthly file? 

Should this file be incorporated into the HEMCO_Config.rc script instead of using the default setup (that doesn't include these files)? If these files need to be added, how should that be done?

@ktravis213

**Comment by yantosca** [comment]
Thanks for writing.  I took a look at the [script we used to create the monthly mean files](http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/NEI2011/v2017-02-MM/scripts/NEI2011_monthly_mean.sh).  The monthly mean of each category is just computed from the daily files in that category.

As to whether or not the surface data contain onroad emissions, I am not 100% sure.  The GEOS-Chem Support Team typically relies on the inventory developers to provide us with the relevant documentation.  That being said, I am tagging @barronh (Barron Henderson) and @lfreese (Lyssa Freese), who have been working with the NEI2011 data and who may know more.

**Comment by msulprizio** [comment]
The onroad files for NEI2011 are not included in the default HEMCO_Config.rc following the recommendations from @ktravis213. Those emissions were found to be overestimated. Since they weren't used in the original implementation of hourly NEI2011 emissions, we did not include those emissions when computing the monthly mean NEI2011 emissions. 

If you would like to generate monthly mean onroad and offroad emissions, you should be able to modify the script that Bob links to above. The offroad emission files are in the `HEMCO/NEI2011/v2015-03/*/*_nonroad.nc` files. Scale factors can be applied to those fields by following the [instructions in the HEMCO User's Guide](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User's_Guide#Scale_factors).

**Comment by barronh** [comment]
Katie Travis is the right person to check with here, but I'll do my best.   @lfreese and I have been working with the 2016 data that is some what different, but has a similar structure. Basically, the implementation for CMAQ-ready that was used as a basis for GEOS-Chem has point source files and one "merged surface file." The "merged surface file" has any mass that is not being treated by plume rise. To summarize, all surface-level emissions are in the merged file.

I have found many others have similar questions that might be well documented here. It is important to note that even "point sources" may have mass in the merged surface file. I'll use a couple sector examples and err on the side of verbosity for the record. 

I'll use EGUs as an example. Even the point sources (e.g., ptegu) actually have some mass that is treated as an area source. The emissions processor SMOKE would put that mass into an "intermediate" surface file. The data treated as points remained in a combination of files (meta: stack groups and fluxes: inlin). So, there would be an intermediate file and a point source file. This is similar for most "point sectors."

Area sources are generally simple -- they have one "intermediate" surface file. The exception is onroad mobile sources that actually have two "intermediate" files. One is for all states except California and Texas (catx), and the other for catx. California and Texas are special cases because they supplied their own data to supersede the MOVES run by EPA. The total masses from California and Texas were used to "adjust" the MOVES results from the EPA. So the total mass matches the state reported values. So, MOVES has two intermediate files: onroad (all other states) and onroad_catx.

Oil and gas is also a special case. For oil and gas, there some emissions are treated as point and others as nonpoint -- often treated two separate "sectors." The point "sector" can have both "point" and surface intermediate files. So, you can have a point file and two surface files.

A similar processing happens for all sectors. After all sectors are done, you have a combination of intermediate files and point files. The point files will treat each mass rate separately to account for stack-specific properties in plume-rise, so they must stay separate. The surface fluxes will be treated identically. For computational and storage efficiency, all the "intermediate" surface files are all merged together.

We often keep the intermediates for more complex analyses (e.g., OSAT). Depending on the emissions platform version, the complete set of sectors and those that get merged can vary. So, it is important to know what is in the merged files.

Hope this helps,
B
