### ISSUE TITLE
[QUESTION]species_database.yml with more species

### ISSUE THREAD

**Issue by JeanJGuo** [geoschem/geos-chem#592]
I'm trying to add more species to `input.geos`, but I realize I need to add those species to `species_database.yml` in order to run GEOS-Chem. Is there a `species_database.yml` file that has more species? 

I found the species names and a lot of other information on the wiki here (http://wiki.seas.harvard.edu/geos-chem/index.php/Species_in_GEOS-Chem), but it doesn't have Henry's constant and some other values that seem to be required in the yml file.

Also, I saw that in older versions, there was a `GAMAP MENU` that doesn't seem to be used anymore, but it's still in the `input.geos` file. How does `input.geos` know not to go looking for tracerinfo.dat and diaginfo.dat? Are those files obsolete now?

```
%%% GAMAP MENU %%%      :
diaginfo.dat path       : diaginfo.dat
tracerinfo.dat path     : tracerinfo.dat
```

Species I am trying to add:
```
1 | DHDN
2 | HC187
3 | HPALD
4 | IEPOX
5 | IMAE
6 | IPMN
7 | ISN1
8 | ISN1OA
9 | ISN1OG
10 | ISOPNB
11 | ISOPND
12 | MACRN
13 | NPMN
14 | SOAME
15 | SOAMG
16 | MOBA


```

**Comment by yantosca** [comment]
Thanks for writing @JeanJGuo.  Which version are you using?  I believe these species were removed in 12.9.0 and later versions due to the updated mechanism.  Am also tagging @msulprizio and @wdowns, who worked on the updated mechanisms.

The tracerinfo.dat and diaginfo.dat files will not be generated unless you compile GEOS-Chem with BPCH_DIAG=y.  In recent versions, most of the bpch diagnostics have been removed, as netCDF equivalent diagnostics are now available via the GEOS-Chem History diagnostic output.  We have been phasing out the bpch diagnostics in favor of netCDF (so that we can use open-source Python code such as GCPy for visualization and analysis).  A few bpch diagnostics remain (e.g. ND51) but only because we have not yet been able to replicate these in netCDF yet.  These bpch diagnostics will eventually be removed completely.

**Comment by msulprizio** [comment]
Those species were removed in [GEOS-Chem 12.8.0](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_12#12.8.0) with the updated isoprene chemistry. The species database was converted to .yml format in [GEOS-Chem 12.9.0](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_12#12.9.0). Before that, species properties were found in `Headers/species_database_mod.F90`. To obtain the species information for the species listed above, you can view the [`species_database_mod.F90` corresponding to GEOS-Chem 12.7.2](https://github.com/geoschem/geos-chem/blob/c4b68994f9720f246f38a76489bff4913cf489ed/Headers/species_database_mod.F90).
