### ISSUE TITLE
[BUG/ISSUE] Why can't I save hourly OH concentrion with v12.3

### ISSUE THREAD

**Issue by plutologic** [geoschem/geos-chem#593]
I am now using GEOS-Chem v12.3, I would like to save OH concentration for ND51 and ND49, but OH tracer is empty in the bpch file. 
Why does this happen? I can save OH concentration in ND51 with v11-1.

**Comment by yantosca** [comment]
Thanks for writing @plutologic.  We have been phasing out the bpch diagnostics in the GEOS-12 series.

To replicate the ND49 output, [please follow these instructions](http://wiki.seas.harvard.edu/geos-chem/index.php/Replicating_the_behavior_of_the_prior_timeseries_diagnostics).

ND51 output is still allowed even in GEOS-Chem 12.  Have you tried compiling with BPCH_DIAG=y?  That will make sure that the (remaining) bpch diagnostics will be turned on.

**Comment by plutologic** [comment]
> Thanks for writing @plutologic. We have been phasing out the bpch diagnostics in the GEOS-12 series.
> 
> To replicate the ND49 output, [please follow these instructions](http://wiki.seas.harvard.edu/geos-chem/index.php/Replicating_the_behavior_of_the_prior_timeseries_diagnostics).
> 
> ND51 output is still allowed even in GEOS-Chem 12. Have you tried compiling with BPCH_DIAG=y? That will make sure that the (remaining) bpch diagnostics will be turned on.

Yes, I compiled with BPCH_DIAG=y. Actually, I saved NO2, uwind, vwind and OH tracers in ND51, only the OH tracer is empty.

**Comment by yantosca** [comment]
Thanks for writing.  I think it is because the OH concentration is now part of the species concentration.  See this code:

https://github.com/geoschem/geos-chem/blob/e9fa458262865a8c353e0b09524eb63cf1798740/GeosCore/diag51_mod.F90#L507-L551

In older versions of GEOS-Chem, the OH concentration was stored in the `SAVEOH` array, because OH was stored separate from the advected species.  Now the OH should be included with the rest of the GEOS-Chem species.

**Comment by plutologic** [comment]
> Thanks for writing. I think it is because the OH concentration is now part of the species concentration. See this code:
> 
> https://github.com/geoschem/geos-chem/blob/e9fa458262865a8c353e0b09524eb63cf1798740/GeosCore/diag51_mod.F90#L507-L551
> 
> In older versions of GEOS-Chem, the OH concentration was stored in the `SAVEOH` array, because OH was stored separate from the advected species. Now the OH should be included with the rest of the GEOS-Chem species.

Thank you for your reply.  the SAVEOH part is commented out in the diag51_mod.F90, saying "We can restore this once we figure out what the  proper unit conversion is (bmy, 11/20/17)", so, OH concentration cann't be saved in ND51 now. I hope it will be solved soon.
Thanks again for your help.

**Comment by yantosca** [comment]
I have now fixed this issue, which will ship in the final 13.0.0 release.  (Right now we are still in the release-candidate per iod and fixing minor issues.)  See commits ce052209826479a4ea46dfcf4abbfc8286741642 and https://github.com/geoschem/GCClassic/commit/2bb0382231ae8d1599f816237ff11a9d9584dd4c.

The fix is simple, make sure the IF block for OH in both GeosCore/diag51_mod.F90 and GeosCore/diag51b_mod.F90 look like this:

```F90
             ELSE IF ( N == 501 .and. IS_FULLCHEM ) THEN

                !--------------------------------------
                ! OH [molec/cm3]
                !--------------------------------------

                ! Accumulate data
                Q(X,Y,K,W) = Q(X,Y,K,W) + &
                     ( State_Chm%Species(I,J,L,id_OH) * GOOD(X) )
```
The OH is now stored in the `State_Chm%Species` array and its index `id_OH` is already computed above in the routine.

I will close out this issue as it is now solved.  If you follow my suggestion above you will be able to get OH printed out to the ND51 and ND51b diagnostics.  Thanks again for reporting this, @plutologic!
