### ISSUE TITLE
[QUESTION] How to incorporate/migrate to the new GC-Classic directory structure?

### ISSUE THREAD

**Issue by joeylamcy** [geoschem/geos-chem#596]
# Ask a question about GEOS-Chem:

Hi GEOS-Chem Support Team, 

As I am preparing for a PR, I wonder how I can incorporate/migrate to the new GC-Classic directory structure (i.e. the super project wrapper) with my branches and git histories in the old code directory (i.e. the science codebase directory here). Any suggestions for that? 

Best, 
Joey

**Comment by yantosca** [comment]
Thanks for writing @joeylamcy.  What you can do is to clone a copy of GCClassic and check out the submodules, then check out a new branch in the src/GEOS-Chem folder:
```
git clone https://github.com/geoschem/GCClasssic.git
cd GCClassic
git submodule update --init -recursive
cd src/GEOS-Chem
git checkout feature/ecophys_module
```

Then go to your existing copy of GEOS-Chem, 
```
cd /path/to/Code.12,.9.3   # or whatever it's called
```
and then make a new branch called `feature/ecophys_module` at the same commit where your existing code already is.  Then checkout the new branch
```
git checkout feature/ecophys_module
```
So at this point you are in your existing GEOS-Chem code and on the new branch.  Then to prep the code to merge up to 13.0.0, do the following:
```
rm -rf HEMCO
rm -rf mod
rm -rf doc
rm -rf lib
rm -rf bin
rm -rf Makefile
rm -rf Makefile_header.mk
rm -rf */Makefile
rm -rf */*/Makefile
```
Then if you have introduced any new files in GeosCore, make sure to add them to the `GeosCore/CMakeLists.txt` file.

Then go back to the GCClassic/src/GEOS-Chem folder:
```
cd /path/to/GCClassic
cd src/GEOS-Chem
```
make sure you are on the new branch you just created
```
git branch
```
and pull the changes from your old GEOS-Chem code
```
git pull /path/to/Code12.9.3 feature/ecophys_module
```

That should merge all the changes up from 12.9.3 to 13.0.0.

Also note if you have modified HEMCO you will need to add those changes in `geoschem/HEMCO`, since HEMCO is now totally split off from GEOS-Chem.

Hope this helps!

@msulprizio @WilliamDowns: feel free to add any other suggestions





Then check out a new branch

**Comment by msulprizio** [comment]
>Then to prep the code to merge up to 13.0.0, do the following:
>
>rm -rf HEMCO
>rm -rf mod
>rm -rf doc
>rm -rf lib
>rm -rf bin
>rm -rf Makefile
>rm -rf Makefile_header.mk
>rm -rf */Makefile
>rm -rf */*/Makefile

When merging older GEOS-Chem code into 13.0.0 I haven't found that I need to do this step. Git seems to know how to handle most of that and identify any conflicts. I've only had to manually remove, for example, the HEMCO directory if I had `.o` files left there from a previous compilation. As Bob mentioned, if you did modify any files in the HEMCO source code you'll need to manually bring those into the HEMCO repository (you may also need to delete them manually here if they remain as a conflict after the merge).

**Comment by joeylamcy** [comment]
Thank you for your detailed guide. I think it works but I just need to resolve all the conflicts before merging. Luckily, I didn't modify anything in HEMCO.
