### ISSUE TITLE
[QUESTION] OH concentrations in the mesosphere and stratosphere

### ISSUE THREAD

**Issue by Aydr199406** [geoschem/geos-chem#597]
Hi support team,
I'm using the v12.9.3 model for the global OH simulation. I have a question. Though GEOS-Chem is predominantly used for simulating tropospheric chemistry, can i use this model to get the OH concentrations in the mesosphere and stratosphere? Thank you very much !

**Comment by msulprizio** [comment]
Thanks for writing. GEOS-Chem has been able to simulate stratospheric chemistry since the implementation of the [UCX mechanism](http://wiki.seas.harvard.edu/geos-chem/index.php/UCX_chemistry_mechanism) in GEOS-Chem v10-01. This mechanism quickly became adopted as our standard recommended full-chemistry mechanism. We continued to offer the troposphere-only chemistry option for users who were concerned about the computational cost of including stratospheric chemistry which added more species, chemical reactions, and required the use of the native 72-level vertical grid (instead of the optional reduced 47-levels). In GEOS-Chem 13.0, we've retired the troposphere-only mechanism and now exclusively use the UCX chemistry mechanism but we allow users to choose their chemistry grid (troposphere+stratosphere or troposphere only). 

If you are interested in accurately simulating OH in the stratosphere, we recommend you use the UCX mechanism (aka "Standard" in 12.9.3) and 72-level vertical grid. The troposphere-only mechanism only simulates chemistry in the troposphere and uses archived P/L rates above.

There has been talk about extending the UCX mechanism into the mesosphere, but that has not been implemented in the standard code. It would require updating the GEOS-Chem source code. @sdeastham proposed that update and may be able to provide more information.

**Comment by sdeastham** [comment]
The GEOS-Chem chemistry has indeed been extended successfully to the mesosphere, with (as I understand it) minimal modifications. To my knowledge this has been done twice now: first by the NASA GMI folkd, and second by Eloïse Marais' group at UCL. My hope is that they will push their modifications to the main branch soon, but you may want to reach out either to her or to her postdoc Rob Ryan to find out exactly what they had to do.

To my knowledge, if you wanted to do this quickly then all that would be necessary is changing `StateGrid%MaxChemLev` in `GeosUtil/gc_grid_mod.F90` (starting line 136 in my version of the code) from
 
```
If ( Input_Opt%LUCX ) Then
    State_Grid%MaxChemLev = State_Grid%MaxStratLev
Else
    State_Grid%MaxChemLev = State_Grid%MaxTropLev
EndIf
```

to

```
If ( Input_Opt%LUCX ) Then
    State_Grid%MaxChemLev = State_Grid%NZ
Else
    State_Grid%MaxChemLev = State_Grid%MaxTropLev
EndIf
```

A more permanent solution would be either to make `State_Grid%MaxChemLev` be something which is set from `input.geos` or to add an `Online mesosphere` option. There may be some additional questions about short-lived bromine species conservation, but in the short term the above would get you started.

**Comment by Aydr199406** [comment]
Thanks for your reply!
