### ISSUE TITLE
[QUESTION] List of OC-equivalent species in complexSOA_SVPOA simulations?

### ISSUE THREAD

**Issue by chfite** [geoschem/geos-chem#599]
I am running simulations in version 12.6.0 with the complexSOA_SVPOA mechanism. I know that OCPO and OCPI are not species that are output when doing complexSOA_SVPOA simulations, but I was wondering if you all could provide a list (or if I can be directed to one if one already exists) which lists all of the species I would need to lump together if I was trying to sum the masses/concentrations of organic carbon with my output? I essentially want to be able to get the OC mass and want to make sure I include all correct species.

   A second question I have is that I notice that OCPO and OCPI are still emitted in HEMCO (like via biomass burning) when running complexSOA_SVPOA simulations, so I wondered how GEOS-Chem handles taking OCPO and OCPI emissions in complexSOA_SVPOA if they are not advected species in this chemical mechanism?

**Comment by msulprizio** [comment]
I would refer your first question to the [Aerosols Working Group](http://wiki.seas.harvard.edu/geos-chem/index.php/Aerosols_Working_Group). @theloniuspunk, do you have any suggestions?

>I notice that OCPO and OCPI are still emitted in HEMCO (like via biomass burning) when running complexSOA_SVPOA simulations

OCPO and OCPI are still listed in HEMCO_Config.rc for complexSOA_SVPOA simulations, but those entries should be ignored by HEMCO because OCPO and OCPI are not defined as species in those simulations. HEMCO defines its list of emitted species following the list of advected species in GEOS-Chem. I don't believe there are any emissions specific to the complexSOA_SVPOA species, other than perhaps in the MEGAN extension. However, the simple SOA simulation does account for emissions of SOA species by scaling CO emissions and emitting as the SOAP (SOA precursor) species.

**Comment by theloniuspunk** [comment]
Thanks, Melissa, and hi Charlie.

I have not worked closely with the complex scheme myself. Charlie, are there entries in HEMCO for emissions from POG/POA from combustion sources as well, or is it just emissions to OCPI and OCPO? Maybe a HEMCO extension takes care of converting it to POG and POA for the complex scheme? I'd need to look more into this if no one here has an answer. Does Sid Pai post on github? He'd likely know.

**Comment by msulprizio** [comment]
>Are there entries in HEMCO for emissions from POG/POA from combustion sources as well, or is it just emissions to OCPI and OCPO? Maybe a HEMCO extension takes care of converting it to POG and POA for the complex scheme? 

That's a good point. Yes, there are scale factors used in HEMCO_Config.rc for converting OCPO emissions to POG emissions:

```
74 POGSCAL  1.27 - - - xy unitless 1
76 SV2POG1  0.49 - - - xy unitless 1
77 SV2POG2  0.51 - - - xy unitless 1
```

@sidhantp Do you have anything else to add?

**Comment by sidhantp** [comment]
Yep! The POG emissions are scaled from the base OC inventories as @msulprizio mentioned. This is following the recommendation from Pye and Seinfeld (2010), although it's worth noting they classify it as likely being a conservative estimate.

**Comment by sidhantp** [comment]
@chfite To calculate the total OA burden in the complex scheme (with SVPOA), you can include the following species (v12.1.1). There has been some restructuring of the code since then so the relevant species are slightly different now.
- POA[1-2]
- OPOA[1-2]
- TSOA[0-3]
- ASOA[N-3]
- SOAGX
- SOAME
- SOAIE
- SOAMG
- LVOCOA
- INDIOL 
- ISN1OA 

You can refer to (http://wiki.seas.harvard.edu/geos-chem/index.php/Species_in_GEOS-Chem) for the MW of each species. Please refer to Pye et al. (2010), Marais et al. (2016) and Fisher et al. (2016) for the specifics. I'm sure you've come across this already, but just in case this might also provide some helpful context on the OA simulation (http://wiki.seas.harvard.edu/geos-chem/index.php/Secondary_organic_aerosols). Hope that's useful!

**Comment by theloniuspunk** [comment]
Thanks, Sid!

**Comment by chfite** [comment]
Thank you all for your help and advice! Yes, I had noticed that the biomass burning emissions in HEMCO scale CO for SOAP and some scale OC to emit POG1 and POG2. However, if I am correct, I think GFED and FINN are the only biomass burning datasets in HEMCO that scale OC emissions for POG1 and POG2. QFED and GFAS do not emit POG1 and POG2 and have no reference to the scale factors that were mentioned above. They do emit SOAP via CO. They also do list as emitting OCPO and OCPI even in the complexSOA_SVPOA simulation, but like @msulprizio said, those lines would get ignored by HEMCO since they are not species in this simulation.

Would it be better for HEMCO to emit POG1 and POG2 when using QFED and GFAS for complexSOA simulations?  I am currently using QFED, so if I need to make sure OC gets emitted through POG1 and POG2 then that is good to know.

As far as the list of OA species go, thank you @sidhantp, that is very helpful. I had noted down some of those but it is nice seeing a clear list. Would  IONITA and MONITA also be included in that list?

**Comment by sidhantp** [comment]
I did not include MONITA and IONITA in my analysis because I was advised against putting them in since there were still some questions about the associated uncertainties in the organic nitrates. I think Jenny Fisher and Eloise Marais would be the appropriate people to ask about current best practices.
