### ISSUE TITLE
[QUESTION] Simulating global OH concentrations

### ISSUE THREAD

**Issue by Aydr199406** [geoschem/geos-chem#601]
Dear support team,
I'm a new user to use the  Geos-Chem v 12.9.3 for the global OH  concentrations simulation. I have a question. There is no chance to edit the CopyRunDirs.input file to simulate the concentrations of OH. I do not know how to set the parameter in the input.geos and something other folders. Can you give me a guider for simulating the OH concentrations! Thank you very much !

**Comment by msulprizio** [comment]
OH is included in the [full-chemistry mechanism](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_chemistry_mechanisms), so you will need to run one of the full-chemistry simulations in order to simulate OH concentrations. Please note that [OH](http://wiki.seas.harvard.edu/geos-chem/index.php/Species_in_GEOS-Chem#O) is only a chemically active species (i.e. found in KPP) and it not advected. To save out concentrations of OH, you will need to modify the SpeciesConc collection in HISTORY.rc to make sure you save out OH concentrations. You can do this by using the `?KPP?` or `?ALL?` wildcards or by specifying `SpeciesConc_OH` in the SpeciesConc.fields list (see [our Guide to History diagnostics](http://wiki.seas.harvard.edu/geos-chem/index.php/Guide_to_GEOS-Chem_History_diagnostics) for details).

**Comment by Aydr199406** [comment]
I have simulated the "standard" type. However, i do not find the OH concentrations in the output files. I will try to modify the HISTORY diagnostics now. Thanks!

**Comment by ltmurray** [comment]
Hi @Aydr199406, because OH is not advected, it is not saved in the SpeciesConc diagnostics (advected tracers), but in the ConcAfterChem diagnostics (chemically important but non-advected tracers).
