### ISSUE TITLE
[BUG/ISSUE] Wrong results from BaP simulation in China

### ISSUE THREAD

**Issue by ruifeili** [geoschem/geos-chem#626]
# Report a GEOS-Chem bug or technical issue

## Describe the bug:
I want to simulate the BaP concentrations in China from 2014 to 2015 on the AWS cloud with nested grid simulation with 0.25×0.3125 resolution. 

Th first problem: As @WilliamDowns suggested, when I apply GEOS-Chem 13.0.0 to run the simulation for one day to test, the result seems wrong. The surface concentrations over the land were almost zero, but those on the sea were high. I tried under two situations (GEOS-FP, 0.25×0.3125, AS domain and MERRA-2, 0.5×0.625, AS domain). Both of the results are wrong. Do you know which files lead to this error?

The second problem: I think the error maybe caused by OCPO and BCPO downloaded from HECMO. So I try to simulate them by myself. Then I choose the simulation (aerosol, EOS-FP, 0.25×0.3125, global). When I do the dry run to download the data, the error occurred as 
```
fatal error: An error occurred (404) when calling the HeadObject operation: Key "GEOSCHEM_RESTARTS/v2018-11/initial_GEOSChem_rst.025x03125_aerosol_as.nc" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "HEMCO/GFED4/v2020-02/2015/GFED4_gen.025x025.201512.nc" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "HEMCO/SAMPLE_BCs/v2020-03/tropchem/GEOSChem.BoundaryConditions.20151201_0000z.nc4" does not exist".
```
### Expected behavior: ###
The simulated results should be high concentrations over land areas (cities).
The download of data for aerosol simulation can be done.

### Actual behavior: ###

The surface concentrations over the land were almost zero, but those on the sea were high.

**Comment by yantosca** [comment]
Thanks for writing @ruifeili.  I think you may have a run-directory mismatch.  You are trying to simulate BaP, which is the POPs simulation, but your dry-run ist trying to download the restart file for the aerosol-only simulation.

I would recommend updating to the GEOS-Chem 13.0.0-rc code, as this will avoid run-directory mismatches.

**Comment by ruifeili** [comment]
> Thanks for writing @ruifeili. I think you may have a run-directory mismatch. You are trying to simulate BaP, which is the POPs simulation, but your dry-run ist trying to download the restart file for the aerosol-only simulation.
> 
> I would recommend updating to the GEOS-Chem 13.0.0-rc code, as this will avoid run-directory mismatches.

Thank you for the comment. But I think you don't understand my questions.  The simulation results for BaP were wrong. So I want to change the OCPO and BCPO files. Please read my questions. Thank you very much!

**Comment by yantosca** [comment]
Thanks for writing @ruifeili. I am not sure the POPs simulation was ever tested with 0.25 x 0.3125 resolution.  Have you tried running at coarser resolution first?  If that works, then try to run with finer resolution.  You might need to manually download data files because some of the specialty simulations like POPs do not have high-resolution input data.

We do not have a 0.25 x 0.3125 restart file for the aerosol simulation.  You might have to manually download the from the `s3://gcgrid/GEOSCHEM_RESTARTS/v2018-11/initial_GEOSChem_rst.2x2.5_aerosol_as.nc` folder.  HEMCO should be able to regrid the 2 x 2.5 restart file to fine resolution.

If you need OCPO/BCPO then you might consider taking the data from the SpeciesConc collection of one of our more recent benchmark simulations (such as: http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/13.0.0-beta.1/GCClassic/FullChem/OutputDir.tar.gz).

We will post updated data from our 13.0.0 10-year benchmark simulations that can be used with specialty simulations like POPs.  This is still pending final 13.0.0 benchmark approval.
