### ISSUE TITLE
[QUESTION] For which meteorological years is GCHP available?

### ISSUE THREAD

**Issue by nadineunger** [geoschem/geos-chem#646]
# Ask a question about GEOS-Chem:

**Comment by yantosca** [comment]
Thanks for writing @nadineunger.  GCHP can use the same met fields as GEOS-Chem classic (any resolution, but for GCHP we recommend running with the native resolution if possible).

Right now we have MERRA-2 data from 1980-2020, and GEOS-FP from April 2012 thru 2020.  We recommend using MERRA-2 since that is a stable product (i.e. the GCM version and assimilation system is not changed).  GEOS-FP, on the other hand, is an operational product, and from time to time there are system changes that affect the output.
