### ISSUE TITLE
[QUESTION] the two-way nested simulation is not updated? How to create a HEMCO emission file?

### ISSUE THREAD

**Issue by wddpwzz5** [geoschem/geos-chem#657]
Dear GEOS-Chem experts,
I have read the documentation about the two-way nested simulation (http://wiki.seas.harvard.edu/geos-chem/index.php/Two-way_coupling_between_global_and_nested_GEOS-Chem_models#Files_in_the_new_PKUCPL_subdirectory). But it looks like it only works for the old version of GC. I guess it should work for the latest version of GC. But I can not find a clue.
Another question is that the emission files are provided by the GC team. What if I have created a new emission dataset and I want to put it into the GC? I have tried to create a netCDF file and following the HEMCO.rc file and it failed. 
thanks,
Zhiqiang

**Comment by yantosca** [comment]
Thanks for writing @wddpwzz5.  The PKUCPL two-way nesting coupler is broken in the latest GEOS-Chem.  This is because we had to make structural modifications for keeping pace with development at NASA/GMAO that broke compatibility with PKUCPL.

Right now in GEOS-Chem there are a couple of better options for two-way nesting:

  1. [Use WRF-GC](https://fugroup.org/index.php/WRF-GC)
  2. Use [GCHP](https://gchp.readthedocs.io) with the stretched grid option (in GEOS-Chem 13.0.0, to be released this week)

**Comment by yantosca** [comment]
FYI, GEOS-Chem 13.0.0 is now officially released.  Please see our newsletter for details: http://wiki.seas.harvard.edu/geos-chem/images/d/de/GEOS-Chem_Newsletter_Spring_2021.pdf

**Comment by wddpwzz5** [comment]
@yantosca thanks for your help!

**Comment by yantosca** [comment]
Thanks @wddpwzz5.  I will close out this issue for now.  Let us know if you run into any more problems.
