### ISSUE TITLE
[FEATURE REQUEST] Extract FAST-JX code into separate directory

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#666]
Separating FAST-JX into a separate directory from GeosCore would be advantageous for use in ESMs. It would benefit integration of GEOS-Chem into CESM. NCAR has also expressed interest in having a stand-alone FAST-JX module extracted from GEOS-Chem for their longer-term MUSICA plans. In addition, GMAO has expressed interest in pulling FAST-JX code out of GEOS-Chem for use in GMI.

This update has been identified as a model development priority and will take place over the next several months.

**Comment by msulprizio** [comment]
Just a heads up: PR https://github.com/geoschem/geos-chem/pull/615 is going into 13.1.0 and brings some FAST-JX fields into planeflight_mod.F90.

**Comment by lizziel** [comment]
I am starting work on this feature. Looking through the FAST-JX code I am wondering if we should move the module arrays in `CMN_FJX_MOD` to a derived type object, such as `State_FJX`, initialized in `init_fjx`. Does anyone recall why we haven't done that - is it just legacy code we haven't gotten to yet?

Also, @fritzt and @christophkeller, could you give feedback on any constraints or requests for the new FAST-JX design regarding interfacing with GEOS and CESM? The FAST-JX public submodules rely on GEOS-Chem state objects (Chm, Met, Diag, Grid). Is including that in the FAST-JX subdirectory a problem? Let me know your thoughts on this.

**Comment by yantosca** [comment]
Hi @lizziel.  I think it is just legacy that we haven't pulled out the FAST-JX common variables into a state yet.  That would be a good thing to do. Maybe even make it a substate of State_Chm if that's easier.

**Comment by lizziel** [comment]
Right, State_Chm may make more sense. I'm thinking if outside projects want to use FAST-JX separate from GEOS-Chem it might be more convenient if it's in a separate smaller container. But I'm still figuring out the scope of just how self-contained the FAST-JX directory (potentially a future submodule) needs to be.

**Comment by fritzt** [comment]
Hi @lizziel! Sorry for the late reply! I think it would be really convenient to have a derived type object for FAST-JX. It might make more sense to put it in its own container, rather than `State_Chm`, as other chemistry modules, such as CAM-Chem, could possibly use it in the future and I believe it would be easier to setup this way. 

I don't see direct issues with having FAST-JX in its own subdirectory and there's no particular constraints with CESM2-GC regarding FAST-JX.

**Comment by lizziel** [comment]
Thanks for the feedback @fritzt!

**Comment by christophkeller** [comment]
I agree that a separate derived type object for FAST-JX would be ideal. The optimal case for GEOS would be to have everything related to FAST-JX in a self-contained place, so that it can be run 'standalone' by invoking a top-level routine that is model-agnostic. This way, we could call it from both GEOS-Chem and GMI without modification/dependencies. @lizziel My understanding is that this is what you have in mind already and I don't think that there are any other particular challenges for making this work within GEOS.

**Comment by sdeastham** [comment]
Hi all - just weighing in to say that this sounds like a _great_ plan. Using a single derived type object for things which are specific to Fast-JX makes a lot of sense to me.

**Comment by yantosca** [comment]
Agreed.  That will also make the code instance-safe.

**Comment by jennyfisher** [comment]
Hi @lizziel - thanks for updating us about this work at GCSC, exciting! I'm just wondering whether the code will still use those external text files to define cross sections & quantum yields, or whether that will get embedded in the code in some form?

If those files will change, one thing we might want to think about is the way they are currently done, which is kind of a mismash. Some species have the quantum yield embedded in the cross-section calculation while others don't. This isn't great for traceability/reproducibility, and also makes it hard to change just a quantum yield for those species where it's embedded (as you have to first extract the cross sections from the quantum yield x cross section, and there's a risk of doing this wrong if the documentation/notes about it aren't great). If this kind of work is in scope, I'll put you in touch with one of the UOW PhD students who has been dealing with this issue (and we should rope in the Chemistry WG chairs in that case)!

Cheers,
Jenny

**Comment by sdeastham** [comment]
@jennyfisher - that inconsistency has been bugging me for years! Two thoughts:
1. The file structure is taken directly from Fast-JX, so (in order to facilitate future updates to Fast-JX) it would be helpful to keep the file structure as-is; and
2. Agreed that it would be great to see a more consistent approach taken with regards to the cross sections and quantum yields! If we do improve it, I'd suggest that we push the updated cross section/yield data back to the Fast-JX developers, too.
