### ISSUE TITLE
[BUG/ISSUE] Units of PRECTOT in HISTORY diagnostics

### ISSUE THREAD

**Issue by ktravis213** [geoschem/geos-chem#676]
### Description of the problem
If I request hourly meteorological diagnostics from HISTORY.rc, I get some units that say x/day.  For example, PRECTOT comes out with a unit of mm/day.  However, if it is output hourly, I would assume this should actually be mm/hour. Could you confirm this? Is there a way to fix this?

### GEOS-Chem version
12.7.2

**Comment by lizziel** [comment]
Hi @ktravis213, thanks for asking about this. The diagnostic output rate is implicit rather than explicit. For example, hourly time-averaged PRECTOT has units _average mm/day over that hour_. Instantaneous output of PRECTOT would be _mm/day at that time_. 

This is probably easier to understand for emissions diagnostics since the rate is per second. So time-averaged emissions output hourly or daily or monthly are all still kg/m2/s.

Does this make sense?

**Comment by lizziel** [comment]
Hi @ktravis213 , are you all set with this issue?

**Comment by ktravis213** [comment]
Yes this is fine!  I would imagine it will confuse other users though.
