### ISSUE TITLE
[QUESTION] Is O3 available in the Hg simulations?

### ISSUE THREAD

**Issue by HarrietGRN** [geoschem/geos-chem#683]
### Ask a question about GEOS-Chem:
How can I have as an output the concentrations of O3 in a Hg simulation? Or should I run an 03 simulation in parallel?
I can see Br, O3 concentration in polar regions etc. but not O3. I tried to add SpeciesCon_O3 but failed.
Thank you

**Comment by yantosca** [comment]
Thanks for writing @HarrietGRN.  In the Hg simulation, the O3 source is read from disk.  There is not an easy way to merge the Hg and fullchem simulations so that O3 is computed on-the-fly along with the Hg species.

Probably the best thing to do would be to use previously-generated O3 fields and then to read those into the Hg simulation via HEMCO.   You can specify this in the `HEMCO_Config.rc` file, in this section:
```
==============================================================================
# --- Oxidant fields ---
#==============================================================================
(((OXIDANT_FIELDS
* GLOBAL_Cl   $ROOT/GCClassic_Output/13.0.0/$YYYY/GEOSChem.SpeciesConc.$YYYY$MM01_0000z.nc4 SpeciesConc_Cl   2010-2019/1-12/1/0 C xyz 1 * - 1 1
* GLOBAL_ClO  $ROOT/GCClassic_Output/13.0.0/$YYYY/GEOSChem.SpeciesConc.$YYYY$MM01_0000z.nc4 SpeciesConc_ClO  2010-2019/1-12/1/0 C xyz 1 * - 1 1
* GLOBAL_HNO3 $ROOT/GCClassic_Output/13.0.0/$YYYY/GEOSChem.SpeciesConc.$YYYY$MM01_0000z.nc4 SpeciesConc_HNO3 2010-2019/1-12/1/0 C xyz 1 * - 1 1
* GLOBAL_HO2  $ROOT/GCClassic_Output/13.0.0/$YYYY/GEOSChem.SpeciesConc.$YYYY$MM01_0000z.nc4 SpeciesConc_HO2  2010-2019/1-12/1/0 C xyz 1 * - 1 1
* GLOBAL_HOCl $ROOT/GCClassic_Output/13.0.0/$YYYY/GEOSChem.SpeciesConc.$YYYY$MM01_0000z.nc4 SpeciesConc_HOCl 2010-2019/1-12/1/0 C xyz 1 * - 1 1
* GLOBAL_NIT  $ROOT/GCClassic_Output/13.0.0/$YYYY/GEOSChem.SpeciesConc.$YYYY$MM01_0000z.nc4 SpeciesConc_NIT  2010-2019/1-12/1/0 C xyz 1 * - 1 1
* GLOBAL_NO   $ROOT/GCClassic_Output/13.0.0/$YYYY/GEOSChem.SpeciesConc.$YYYY$MM01_0000z.nc4 SpeciesConc_NO   2010-2019/1-12/1/0 C xyz 1 * - 1 1
* GLOBAL_NO2  $ROOT/GCClassic_Output/13.0.0/$YYYY/GEOSChem.SpeciesConc.$YYYY$MM01_0000z.nc4 SpeciesConc_NO2  2010-2019/1-12/1/0 C xyz 1 * - 1 1
* GLOBAL_O3   $ROOT/GCClassic_Output/13.0.0/$YYYY/GEOSChem.SpeciesConc.$YYYY$MM01_0000z.nc4 SpeciesConc_O3   2010-2019/1-12/1/0 C xyz 1 * - 1 1
* GLOBAL_OH   $ROOT/GCClassic_Output/13.0.0/$YYYY/GEOSChem.SpeciesConc.$YYYY$MM01_0000z.nc4 SpeciesConc_OH   2010-2019/1-12/1/0 C xyz 1 * - 1 1
* GLOBAL_OA   $ROOT/GCClassic_Output/13.0.0/$YYYY/GEOSChem.AerosolMass.$YYYY$MM01_0000z.nc4 TotalOA          2010-2019/1-12/1/0 C xyz 1 * - 1 1
* GLOBAL_OCEAN $ROOT/MERCURY/v2018-04/ocean_fixed.nc ocean_conc 2007/1-12/1/0 C xyz 1   * - 1 1
)))OXIDANT_FIELDS
```
The `GLOBAL_O3` field specifies the source of O3 to be read from disk.

If you are using GEOS-Chem 13.0.1, then note that the HEMCO_Config.rc file is already set up to read monthly-mean O3 concentrations generated by our 10-year benchmark simulation.  If that is good enough for your purposes, then that will be the easiest way to proceed.

If you need more frequent output than monthly mean, you can run a fullchem simulation and then archive the O3 concentrations (SpeciesConc diagnostic) at e.g daily intervals.

We do plan on implementing the Hg chemistry as a KPP mechanism, but that is likely some time away.

**Comment by yantosca** [comment]
Also note that you should use GEOS-Chem 13.0.2 when it is released.  That will fix a bug that caused met fields only to be read once instead of continously throughout the simulation.  See #686 for more information. If you need the fix faster you can get it from the bugfix/bmy/TimeCycleEFYO branch as described in #686.

**Comment by yantosca** [comment]
NOTE: Bugfix version [GEOS-Chem 13.0.2](https://github.com/geoschem/GCClassic/releases/tag/13.0.2) has been officially released as of 12 Apr 2021.

**Comment by HarrietGRN** [comment]
Thank you very much for the answer and the update.
How do I use the run and test in these kind of versions?
They are not folders containing the createRunDir.sh..
New user :D
Thank you!

**Comment by yantosca** [comment]
@HarrietGrn: The test folder contains scripts for integration tests (which is really only used by the GEOS-Chem Support Team).  You can ignore that.

If you are in the top-level GEOS-Chem Classic source code folder, then 
```
$ cd run
$ ./createRunDir.sh
answer the prompts
```
For more information, please see [Creating run directories for GEOS-Chem 13.0.0 and later](http://wiki.seas.harvard.edu/geos-chem/index.php/Creating_run_directories_for_GEOS-Chem_13.0.0_and_later), which is part of our [Getting Started with GEOS-Chem](http://wiki.seas.harvard.edu/geos-chem/index.php/Getting_Started_with_GEOS-Chem) manual.
