### ISSUE TITLE
[QUESTION] Nested Grid for 2013

### ISSUE THREAD

**Issue by bsuther** [geoschem/geos-chem#694]
I am trying to run GEOS-Chem with a nested grid over North America for 2014. I have already done a coarse resolution simulation to get the boundary conditions. I have two general questions:
1) How long is the recommended spin up time for a nested grid run?
2) How do I handle the Met fields since the spin up will have to include some of 2013 and there is no GEOS_FP data for 2013 on the 0.25x0.3125 grid available on the computecanada server?
Thank you for your help.

**Comment by msulprizio** [comment]
Hi @bsuther. 

>How long is the recommended spin up time for a nested grid run?
The recommended spin-up time for a nested-grid simulation is at least 1 month. The actual amount of time you choose may depend on your domain size and species of interest. The idea is that you want to choose enough time for the initial conditions to be advected out of the nested window.

>How do I handle the Met fields since the spin up will have to include some of 2013 and there is no GEOS_FP data for 2013 on the 0.25x0.3125 grid available on the computecanada server?
You have the option of using the MERRA-2 meteorology fields for your spin-up period since they are available for earlier years. Please note that MERRA-2 has a native resolution of 0.5x0.525. HEMCO can handle taking a restart file from a different resolution and regridding to the model resolution (i.e. 0.25x0.3125) for your production runs with GEOS-FP, but I would still recommend running for at least a week or more to remove the impact of the coarser initial conditions. Another option would be to spin up with GEOS-FP meteorology for a different year. For example, if your production run starts on Jan 1, 2014, but you don't have meteorology fields for 2013, you could do a spin-up simulation for December 2014 and modify the date in the name and timestamp of the resulting restart file from Jan 1, 2015 to Jan 1, 2014.

**Comment by bsuther** [comment]
Hello,

I have a related follow up question. I am now trying to get output for 2013 (production run, not just spin up) on a 0.25x0.3125 nested grid over NA. What would be the correct way to handle the meteorology in this case (or for other earlier periods for which ExtData/GEOS_0.25x0.3125_NA/GEOS_FP meteorology files are not available)? 

Would the best option be to use the ExtData/GEOS_0.5x0.625_NA/MERRA2/2013 files? In this case, I am thinking the correct steps would be to:
1) create a run directory using ./createRunDir.sh and choose the meteorology source as GEOS-FP, and the horizontal resolution as 0.25 x 0.3125
2) modify the METDIR in HEMCO_Config.rc and HEMCO_Config.rc.gmao_metfields to point to the MERRA2 files rather than the GEOS_FP ones.
Am I on the right track here? Are there any other necessary modifications which I have not thought of? 

Would using the coarser met fields be problematic for any reason? I know in your answer to my previous question you had said 

> I would still recommend running for at least a week or more to remove the impact of the coarser initial conditions

would there be similar impacts for regridding the meteorology for the entire production run?
