### ISSUE TITLE
[QUESTION] Generating boundary conditions with multi-segmented runs

### ISSUE THREAD

**Issue by bsuther** [geoschem/geos-chem#698]
### Ask a question about GEOS-Chem:
On the [wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/FlexGrid#Read_in_boundary_conditions_via_HEMCO) it says 

"When generating boundary conditions make sure you start your coarse-resolution simulation at least one day before the start of your nested grid simulation to ensure the boundary condition file for the first day includes hour 0." 

Does this mean that all of the boundary conditions must be created during a single run? If you are trying to create the boundary conditions for a long time period, is there a way to split the course run into several shorter chunks with restart files and still have all the necessary times saved in each of the boundary condition files?

**Comment by msulprizio** [comment]
Yes, you may split your coarse resolution simulation into several smaller simulations. Just note that you will need to take an extra step to ensure all files include 8 timestamps (hours 0, 3, 6, 9, 12, 15, 18, 21).

If you are using GEOS-Chem 12.8.0 or earlier, you will need to rename the BC file at the end of the first segment so that it does not get overwritten by the second segment. For example, if you split your run into monthly segments starting on January, you will get a BC file for Feb 1 containing hour 0. Once you start the second month, the BC file for Feb 1 will be overwritten with hours 3-21. To avoid losing the BC field for hour 0, you can rename the BC file at the end of the January run and at the end of the February run you can combine the two files using a tool like CDO (e.g. `cdo mergetime file1.nc file2.nc finalfile.nc`). You may choose to automate this in your run scripts.

A fix for this was implemented in GEOS-Chem 12.8.1. From issue https://github.com/geoschem/geos-chem/issues/248:
>@yantosca implemented a fix in the dev/12.8.1 branch so that the output for hour 0 on 20160701 will not be overwritten, but instead saved to a different file. This means that between the two monthly 4x5 runs, there would be two BC files for that day -- GEOSChem.BoundaryConditions.20160701_0000z.nc4 with hour 0 and GEOSChem.BoundaryConditions.20160701_0300z.nc4 with hours 3-21. The two files will need to be merged with `cdo mergetime` before starting the nested run so that all of the BCs for one day can be found in a single file.
