### ISSUE TITLE
[FEATURE REQUEST] Can CMake put the GEOS-Chem version number into main.F (for log file printout)?

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#70]
For GEOS-Chem "Classic", we currently use an include file with the version number (```GeosCore/gc_classic_version.H```).  This is inlined into routine Display_Model_Info of main.F so that the version number can be printed to the log file.  This prints out to the top of the log file, e.g.

```
*************   S T A R T I N G   G E O S - C H E M   *************

===> Mode of operation         : GEOS-Chem "Classic"
===> GEOS-Chem version         : 12.7.0
===> Compiler                  : GNU Fortran compiler (aka gfortran)
===> Parallelization w/ OpenMP : ON
===> Binary punch diagnostics  : ON
===> netCDF diagnostics        : ON
===> netCDF file compression   : SUPPORTED
```

But the version number that CMake uses is defined at the top of the CMakeList in the source code folder:
```cmake
cmake_minimum_required(VERSION 3.5)
project(GEOS_Chem VERSION 12.7.0 LANGUAGES Fortran)
```

Is there a way for CMake to automatically add the version number from the CMakeList into main.F so that GEOS-Chem can print it out to the log file?  We probably don't want to keep defining the version number in the CMakeList and in gc_classic_version.H, as that could lead to mismatches.

**Comment by LiamBindle** [comment]
Hi Bob. This is a good idea. Then the version number is only in one place. This should be pretty straightforward.

## Getting the version numbers
First off, the `project` command creates the following version number variables:
```
PROJECT_VERSION, GEOS_Chem_VERSION
PROJECT_VERSION_MAJOR, GEOS_Chem_VERSION_MAJOR
PROJECT_VERSION_MINOR,GEOS_Chem_VERSION_MINOR
PROJECT_VERSION_PATCH, GEOS_Chem_VERSION_PATCH
PROJECT_VERSION_TWEAK, GEOS_Chem_VERSION_TWEAK
```

See `project()`'s documentation [here](https://cmake.org/cmake/help/latest/command/project.html).

So, getting the version numbers delcared in `project()` is easy.

## Putting version numbers into `GeosCore/gc_classic_version.H`
Two options come to mind right away:
1.  Add preprocessor definitions with GEOS-Chem's version numbers (major, minor, patch). This would be something like
    ```cmake
    target_compile_definitions(BaseTarget PUBLIC
        GEOS_Chem_VERSION_MAJOR=${GEOS_Chem_VERSION_MAJOR},
        ...
    )
    ```
2. Use `configure_file` (see docs [here](https://cmake.org/cmake/help/v3.2/command/configure_file.html)) to replace `@GEOS_Chem_VERSION@` in `GeosCore/gc_classic_version.H.in` with the CMake variables. 
    ```fortran
          GC_CLASSIC_VERSION = '@GEOS_Chem_VERSION@'
    ```
    and then in `GeosCore/CMakeLists.txt`
    ```cmake
    configure_file(gc_classic_version.H.in gc_classic_version.H @ONLY)
    ```
    For this approach, we should make sure `gc_classic_version.H` is in `.gitignore`. 

Personally, I'd lean towards option 2 because I think it's best to avoid preprocessor definitions. There are probably other ways too though!

I've done the approach (2) in  #72. It didn't take any time to do, so I thought I would add it.

**Comment by yantosca** [comment]
Yeah, I like option #2 better -- to get the version variable.  Seems very clean.

I wonder if there is a way to make this backwards compatible, for the couple of versions where CMake and GNU Make will be concurrent?  People will still be using GNU Make for a while.

**Comment by LiamBindle** [comment]
We could add use `sed` extract the version string from `CMakeLists.txt` and then `sed` again to generate `gc_classic_version.H` from `gc_classic_version.H.in`. It's a bit hacky, but what do you think of that? Alternatively, we could manually update it in both places until GNUMake support is dropped.

**Comment by yantosca** [comment]
This will likely have to go into 13.0.0, once we get rid of GNU Make.

**Comment by yantosca** [comment]
This has been completed (using method #2 above, with configure_file) in commit d73641388af7f2fa5cdf52017f1427a16b6e1cb9.  The version number listed in the gcc_dev repository is now printed to the GEOS-Chem log file.

**Comment by yantosca** [comment]
Update: to avoid issues caused by the file `gc_classic_version.h` being missing from the GeosCore folder, we have moved the `main.F90` file as well as `gc_classic_version.H.in` to the `Interfaces/GCClassic` folder. This is also consistent with the way we handle driver programs for external modeling contexts like NASA/GEOS and GCHPctm.  This was added in commit f603b1104083d5de019fe05411b04a0e41781e62
