### ISSUE TITLE
Configure GEOS-Chem to simulate Fossil Fuel CO2 (FFCO2) Simulation [QUESTION]

### ISSUE THREAD

**Issue by idfarhan** [geoschem/geos-chem#716]
I am intended to simulate the CO2 emitted by fossil fuel combustion for a period of 10 years. All I require to make changes in HEMCO config file? Or is there anything else I need to consider?

Regards,
Farhan Mustafa

**Comment by yantosca** [comment]
Thanks @idfarhan.  You would want to run the GEOS-Chem CO2 simulation.  If all you need to do is to change out an emissions source, then that can be done by editing the HEMCO_Config.rc file rather than making code changes.

Please see our wiki page [The HEMCO User's Guide](http://wiki.geos-chem.org/The_HEMCO_Users_Guide) for more information about how to modify the HEMCO_Config.rc file.

To set the start & stop time of your simulation, you would need to modify the input.geos file, as described in our [Getting Started with GEOS-Chem](http://wiki.geos-chem.org/Getting_Started_with_GEOS-Chem) manual.

**Comment by idfarhan** [comment]
@yantosca Thank you very much. I have another little query as well. GEOS-Chem is providing CO2 at 47 vertical levels. Is there any formula to calculate the pressure weighted-averaged CO2.

Kind regards

**Comment by yantosca** [comment]
I think you can multiply each level by State_Met%DELP_DRY field (which is the thickness in pressure of each grid) and then divide by the surface pressure (or sum of DELP_DRY).  Try that.

**Comment by kimm1na** [comment]
> I think you can multiply each level by State_Met%DELP_DRY field (which is the thickness in pressure of each grid) and then divide by the surface pressure (or sum of DELP_DRY). Try that.



Do you mean to multiply the mixing ratio of each grid by Met_DELPDRY/sum(Met_DELPDRY) for weighting?
Is there any reason not to use Met_DELP other than Met_DELPDRY?

Regards, Mina Kim
