### ISSUE TITLE
[QUESTION] Emission source of chlorinated hydrocarbons (CHxCly)  in GEOS-Chem

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#725]
In HEMCO, _CMIP6 files_ can provide concentrations of  chlorinated hydrocarbons (CH2Cl2, CH3Cl, CHCl3). Due to the units of _CMIP6 files_ in HEMCO (_ppbv_), I try to use HEMCO_Diag.rc to save emissions of chlorinated hydrocarbons as _kg_. However, they cannot be saved in HEMCO_diagnostics.nc when I want to calculate emissions of chlorinated hydrocarbons. Are there any ways to calculate accurate emission source of chlorinated hydrocarbons? And if I turn off _CMIP6 files_, are there any other emission of chlorinated hydrocarbons in GEOS-Chem?

Thanks.

**Comment by tsherwen** [comment]
Hello @yangxiajie,

We have tended to calculate the released chlorine instead of the emitted chlorine. This is done by tracking the release by chemical or photo-chemical reaction (e.g. CHxCly + X, CHxCly + OH, CHxCly + hv,...) using the production and loss diagnostic (e.g. example numbers in the Cl+Br+I paper below). 

_Sherwen, T., Schmidt, J. A., Evans, M. J., Carpenter, L. J., Großmann, K., Eastham, S. D., Jacob, D. J., Dix, B., Koenig, T. K., Sinreich, R., Ortega, I., Volkamer, R., Saiz-Lopez, A., Prados-Roman, C., Mahajan, A. S., and Ordóñez, C.: Global impacts of tropospheric halogens (Cl, Br, I) on oxidants and composition in GEOS-Chem, Atmos. Chem. Phys., 16, 12239–12271, https://doi.org/10.5194/acp-16-12239-2016, 2016._

We talked about adding a "psuedo flux" calculation like is done for methane to the code when we added the fixed surface new concentration approach. I don't think we have made any movement on this since pushing the `SfcFix` code with the CMIP6 emissions. Maybe @sdeastham or @christophkeller or @msulprizio are aware if anything more has happened on this?

Cheers, 

Tomas

**Comment by yangxiajie** [comment]
Thank you @tsherwen 
I find that in GEOS-Chem 12.9.3, units of production and loss diagnostic is molec/cm3/s. Is there any way to convert it to kg?

**Comment by tsherwen** [comment]
Hello @yangxiajie, 

Just responding to your email and this thread together.  I see you raised this specific point with issue #729 too. Is your question answered now?

```
In GitHub, you said that you have tended to calculate the released chlorine instead of the emitted chlorine. This is done by tracking the release by chemical or photo-chemical reaction (e.g. CHxCly + X, CHxCly + OH, CHxCly + hv,...) using the production and loss diagnostic. However, I found that there is no production of CHxCly in Tropchem.eqn file, which means, from my perspective, CHxCly cannot be produced from chemical reactions. On the other hand, I find that CMIP6 can provided a fixed concentration of CHxCly.

Therefore, I convert CHxCly concentrations from CMIP6 (pptv) to mass (Tg). Then, I use this mass to subtract the loss one, which is calculate from GEOS-Chem production and loss diagnostic. I wonder if this calculation is correct.
```

Cheers, 

Tomas

**Comment by yangxiajie** [comment]
Hi @tsherwen 

Thank you for reply.

Yes, the specific question is answered by Bob and has been solved now.

Now I have only one question, which is about the source of CHxCly. I can save loss rate of CHxCly from P/L diagnostic. I try to convert loss rate of CHxCly (unit: molec/cm3/s) to mass (Tg), then use this mass as  source of CHxCly. I wonder if this calculation is correct.

**Comment by tsherwen** [comment]
Great. 

What is the conversion that you have used? I've linked below to [my Python code on Github](https://github.com/tsherwen/AC_tools) to do things including this. The function `get_PL_ars4mech_NetCDF` does something similar to what you are after. 

[Tomás Sherwen, Ben Newsome, Killian Murphy, & Dan Ellis (2021, May 25). tsherwen/AC_tools: v0.1.2 (Version v0.1.2). Zenodo. DOI:10.5281/zenodo.4789902
](http://doi.org/10.5281/zenodo.4789902)

However, I'm not sure I fully follow what you have got out of the Prod/Loss diagnostic. Surely you would need to get the _loss_ of each `CHxCly` species separately, then convert this to Tg/s (...or year) production. I tend to extract all species and routes individually so that I can fully break apart the halogen source budgets.

**Comment by yangxiajie** [comment]
Thank you @tsherwen 

I save CH3Cl, CH2Cl2 and CHCl3 seperately from P/L diagnostic. Then I did something as follows (e.g. CH2Cl2, loss rate: `a molec/cm3/s` in 1 month) :

`M (Mass of CH2Cl2, Tg/month) = a molec/cm3/s  /  6.022*10^23 molec/mol * 84.93 g/mol * AIRVOL m3 * 10^-6 * 30 * 24 * 3600`

where AIRVOL can be saved by `StateMet diagnostic` . 

Then I use `M` as source of CH2Cl2 in 1 month.  I wonder if this calculation is correct.
