### ISSUE TITLE
HEMCO_Config files in GC v12.5.0 point to BIOFUEL v2014-07 rather than the "default" v2019-08

### ISSUE THREAD

**Issue by MaggieMarvin** [geoschem/geos-chem#74]
**Bug description**

The online documentation states that v2019-08 of the BIOFUEL inventory is used as the default BIOFUEL inventory in GEOS-Chem v12.5.0, but all of the HEMCO_Config template files that come with this version still point to v2014-07.

GEOS-Chem compiles and runs as normal, but points to an older version of the BIOFUEL inventory. The only documented change in v2019-08 from v2014-07 is that the inventory has been regridded from 4x5 to 2x2.5 degrees horizontal resolution, so this bug should not result in an error message and may not be easily identifiable in model output.

This bug can be easily fixed by updating the HEMCO_Config templates, then re-running the UT and re-compiling. Only known instance occurs at or near line 1694. Suggested changes are highlighted in bold:

BIOFUEL_C3H8 $ROOT/BIOFUEL/**v2019-08**/biofuel.geos.**2x25**.nc     BIOFUEL_C3H8 1985/1/1/0 C xy kgC/m2/s C3H8 -         1 10

**Required information**
 - GEOS-Chem version you are using: 12.5.0
 - Are you using "out of the box" code, or have you made modifications? Out of the box

**Comment by msulprizio** [comment]
The HEMCO_Config template files are correct. You should use the biofuel emissions in http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/BIOFUEL/v2014-07/ for C3H8 when running GEOS-Chem 12.5.0. The 2x2.5 file in v2019-08 was added for use in [GCHP](http://wiki.seas.harvard.edu/geos-chem/index.php/GCHP_Main_Page) only because of the implementation of MAPL v1.0.0 in GCHP 12.5.0, which cannot handle 4x5 input files when running at high resolutions. On the wiki it the update to the 2x2.5 file in v2019-08 should only be listed under updates specific to GCHP. Please send us the exact link if the documentation is unclear and we can fix it.

**Comment by MaggieMarvin** [comment]
Oh ok! I didn't make that connection. I was looking at the docs here: http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_12#12.5.0

**Comment by msulprizio** [comment]
At the wiki page linked to above, the update in question is listed under "Updates that will only affect GCHP." I've also modified the description of the update to hopefully clarify that it is for GCHP only.

**Comment by MaggieMarvin** [comment]
Ok great, thanks!
