### ISSUE TITLE
[QUESTION] Question about SF6 species

### ISSUE THREAD

**Issue by yinhao1995** [geoschem/geos-chem#745]
I found that GEOS-Chem transport scheme have a Species, SF6tracer. What I want to ask is whether SF6tracer can represent the concentration of SF6? Can I also compare this concentration with the observed value? 
Thank you

**Comment by yantosca** [comment]
> What I want to ask is whether SF6tracer can represent the concentration of SF6? 

Yes, it is the SF6 species.

> Can I also compare this concentration with the observed value?

Yes you can, provided that you have access to an SF6 global dataset.  (The GCST cannot provide this for you.)

**Comment by yinhao1995** [comment]
I would like to ask one more question. Does this model require a longer spin up to get a more accurate SF6 concentration？

**Comment by yantosca** [comment]
@yinhao1995 I am not sure how long you would need to spin up for SF6, but my guess would be for several years, or maybe a decade.  If all you are interested in is SF6, then you can modify the input.geos and delete the non-SF6 species, then the simulation will proceed faster since there are less species to advect.

**Comment by yantosca** [comment]
I will close out this issue for now.  Please feel free to open a new issue if you still have questions.

**Comment by yinhao1995** [comment]
> I will close out this issue for now. Please feel free to open a new issue if you still have questions.

ok,thank you.
