### ISSUE TITLE
[QUESTION]  Video (or info) on installing Intel Fortran with Spack?

### ISSUE THREAD

**Issue by rsignell-usgs** [geoschem/geos-chem#755]
### Ask a question about GEOS-Chem:
I learned a lot from watching the [Spack tutorial #1: Building gfortran 9.2.0 on the AWS cloud ](https://www.youtube.com/watch?v=7eMLYKLK9wY). 

Thank you!  😺 

Is there a similar video or instructions for installing the Intel Fortran compiler with Spack?  
I ask because the [Intel instructions from Spack](https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html#intel-packages-in-spack) describe several different paths so it would be interesting to see which one you guys take (and why!).   

I have a license file for Intel® oneAPI Base & HPC Toolkit, Multi-node, purchased today!

**Comment by yantosca** [comment]
Thanks so much for the feedback!  I presume you are referring to the Intel 2021 (free and open source) compiler.  I haven't tried this yet, as I prefer the GCC compilers.  Gfortran flags a bunch of things that Intel fortran will let you get away with, so that is what I tend to stick with when available.

I am also looping @WilliamDowns into this discussion, as he has had more experience than me installing Intel compilers and MPI with Spack.
