### ISSUE TITLE
[QUESTION] How to run lightning NOx online in GEOS-Chem v12.5.0?

### ISSUE THREAD

**Issue by MaggieMarvin** [geoschem/geos-chem#76]
Is there a (relatively easy) way to turn off the offline lightning NOx emissions, but still run LNOx online, in GC v12.5.0? I would like to run GC at 0.25x0.3125 resolution for 2014, with spin up at 4x5 for 2013, but it doesn't look like the offline LNOx emissions are available for 2013 from GEOS-FP. I would still like to include lightning NOx in the spin up run, but unsure how to do so. Thanks!

**Comment by msulprizio** [comment]
Hi @MaggieMarvin. The offline lightning fields still do online lightning NOx emissions but they utilize offline lightning flash densities (FLASH_DENS) and convective-cloud depth (CONV_DEPTH) fields at the native meteorology resolutions (0.25x0.3125 for GEOS-FP, 0.5x0.625 for MERRA-2). There isn't currently a way to turn those off, but you could instead hardwire your HEMCO_Config.rc to use a specific year for the FLASH_DENS and CONV_DEPTH fields if they're not available for your simulation year. In other words, you could use the 2014 fields for your 2013 4x5 spinup simulation. 

@ltmurray Do you have any other suggestions?

**Comment by ltmurray** [comment]
Hi Maggie,

Flash rates for MERRA2 and GEOS-FP are archived for all years of available meteorology at Harvard and Dalhousie in the OFFLINE_LIGHTNING directory of HEMCO, with the exception of the most recent few months, due to a lag-time in processing.

If you want to run with different lightning flash rates than what are provided, you just need to generate a NetCDF file containing FLASH_DENS (flashes per area per time; used to calculate the NOx emissions) and CONV_DEPTH (meters; used to determine the vertical extent of the emission distribution).

Note: I do not recommend using lightning flash rates from a different year for anything but testing.  it is important for the chemistry that the NOx emissions occur during the convective lofting of surface precursors in the model.

All the best,
Lee

---------------------------------------------------------------------------------------------------
Lee T. Murray
Assistant Professor of Earth and Environmental Sciences
University of Rochester
url: http://ees.rochester.edu/atmos


On Sep 27, 2019, at 10:29 AM, Melissa Sulprizio <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @MaggieMarvin<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MaggieMarvin&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=FZTgar4ZcAerjX-R_LaBWCoXl65de8pQBuW_W4Wb_wQ&m=nGu5Wvr54DjSnd-C_KS1UUqfGoOG1G4Zi7C8y2_Uk9A&s=XhiJ4ORu19kUnTzBRXq5TXu_1hxoOGjZw8KikVMq4EM&e=>. The offline lightning fields still do online lightning NOx emissions but they utilize offline lightning flash densities (FLASH_DENS) and convective-cloud depth (CONV_DEPTH) fields at the native meteorology resolutions (0.25x0.3125 for GEOS-FP, 0.5x0.625 for MERRA-2). There isn't currently a way to turn those off, but you could instead hardwire your HEMCO_Config.rc to use a specific year for the FLASH_DENS and CONV_DEPTH fields if they're not available for your simulation year. In other words, you could use the 2014 fields for your 2013 4x5 spinup simulation.

@ltmurray<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ltmurray&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=FZTgar4ZcAerjX-R_LaBWCoXl65de8pQBuW_W4Wb_wQ&m=nGu5Wvr54DjSnd-C_KS1UUqfGoOG1G4Zi7C8y2_Uk9A&s=UlRUI1y0WG3KipxPYB8y6URzcb4HC5JyaCtzbQD-huA&e=> Do you have any other suggestions?

**Comment by MaggieMarvin** [comment]
Hi Lee and Melissa,

It's my understanding that GEOS-FP meteorology is available for the 4x5 and 0.25x0.3125 grids going back to 2011, but I've only found flash rates going back to 2014 in the OFFLINE_LIGHTNING directories. Are flash rates available for GEOS-FP back to 2011, and I just can't find them?

If the flash rates are not available for GEOS-FP for 2013, would there be any problem using MERRA2 to drive my spin-up run and then GEOS-FP for the main simulation?

Best,
Maggie

**Comment by ltmurray** [comment]
Hi all,

GEOS-FP is only available from 2014 at global 0.25 x 0.3125 resolution, from which the offline emission products are derived.  GCST, are there plans to make the global native-resolution fields available for 2011-2013?  If so, I can include them the next time I process the offline lightning flash rates.

Note, Maggie, that MERRA-2 is the recommended reanalysis product for scientific applications that require multi-year simulations.  GEOS-FP is an operational assimilated product with a constantly changing code base, while MERRA-2 is a fixed version of the climate model in which GMAO tries to remove spurious trends induced by changing observations (e.g., new satellites coming online).

If you DM me with the simulation details (years and region) you are trying to perform, I can make a specific recommendation re: lightning. But your suggestion to use MERRA-2 is probably sufficient for 2011-2013 for now; in many ways the MERRA-2 lightning product is superior for reasons listed above, and the fact that it is trained on the full availability of satellite lightning observations (1995-2014), it is just available at the coarser MERRA-2 resolution.

All the best,
Lee

On Sep 30, 2019, at 6:19 AM, Maggie Marvin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Lee and Melissa,

It's my understanding that GEOS-FP meteorology is available for the 4x5 and 0.25x0.3125 grids going back to 2011, but I've only found flash rates going back to 2014 in the OFFLINE_LIGHTNING directories. Are flash rates available for GEOS-FP back to 2011, and I just can't find them?

If the flash rates are not available for GEOS-FP for 2013, would there be any problem using MERRA2 to drive my spin-up run and then GEOS-FP for the main simulation?

Best,
Maggie

**Comment by MaggieMarvin** [comment]
Hi Lee,

Ok, thanks very much for this info! I'd prefer to use GEOS-FP for the main simulation, because I'm aiming for a nested simulation at 0.25x0.3125 resolution, but I can message you separately with further details.

One more quick question for the thread: Would it be possible to use MERRA2 lightning fields with GEOS-FP meteorology? Or should the MERRA2 and GEOS-FP lightning products always be used together with their respective met fields?

Best,
Maggie

**Comment by ltmurray** [comment]
Hi Maggie,

Yes, it is possible, just specify the path to the MERRA2 fields in HEMCO_Config.rc (which you can take from one of the MERRA2 run directories), and GEOS-Chem will re-grid the flash rates to the resolution of any simulation.  Lightning flashes are now treated as a met field, and the new FlexGrid code for treating met fields allows us to mix and match.

It is more ideal to use consistent meteorology, since you will be guaranteed to having lightning occurring in active deep convection. However, since GEOS-FP and MERRA-2 have variants of the same model and observations underlying them, the overlap should be fairly consistent, and both products are constrained to the LIS/OTD climatology as described in my 2012 JGR paper to make sure that local flash rates are the correct order of magnitude.

—Lee

On Sep 30, 2019, at 10:47 AM, Maggie Marvin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Lee,

Ok, thanks very much for this info! I'd prefer to use GEOS-FP for the main simulation, because I'm aiming for a nested simulation at 0.25x0.3125 resolution, but I can message you separately with further details.

One more quick question for the thread: Would it be possible to use MERRA2 lightning fields with GEOS-FP meteorology? Or should the MERRA2 and GEOS-FP lightning products always be used together with their respective met fields?

Best,
Maggie

**Comment by MaggieMarvin** [comment]
Great, thanks Lee! All questions answered and I think this issue can be closed, unless @msulprizio has any other feedback?
