### ISSUE TITLE
[BUG/ISSUE] Errors when trying to run a nested simulation of AS using GCClassic 13.1.0

### ISSUE THREAD

**Issue by Alex-Fang66** [geoschem/geos-chem#784]
### Description of the problem
Sorry for bother!
I was going to run a nested simulation of AS(05x0625, standard), and  successfully ran the 2x25 global simulation(standard). However, something went wrong probably owing to the HEMCO_Config.rc or restart files. I wanna know if it is proper that using the same restart file for 2x25 simulation which was downloaded from the '10yr_benchmarks/13.0.0/GCClassic/restarts'. Besides, the error report is a little vague for debugging, and didn't generate any information in HEMCO.log.
![dry_run](https://user-images.githubusercontent.com/65645232/126029806-63db3f6f-b051-48bc-a3f3-5c95c73103b2.jpg)

I saw a similar error when running nested simulation, and the answers implied that the error may be due to inconsistent in two grids or boundary files. I cannot be sure whether it suits for my situation as well, so if necessary I will also attach the boundary file.

### Description of troubleshooting performed
At the very beginning, the HEMCO.log gave the error info like  "HEMCO ERROR:  No scale factor with ID:        268" and disappeared after I added '268 NEI11_OC2OCPO     0.5                                           - -               - xy 1 1'.
Now when I run a dry-run, error of below appears as well：
![errors](https://user-images.githubusercontent.com/65645232/126029777-fb2f5117-84a3-45a0-9fd5-2d4ca1e3e2e7.jpg)

### GEOS-Chem version
GEOS-Chem "Classic"   v13.1.0 

### Log files
[run_log.zip](https://github.com/geoschem/geos-chem/files/6834344/run_log.zip)

### Software versions
- CMake version: cmake@3.16.1
- Compilers (Intel or GNU, and version): gcc@9.3.0
- NetCDF version: netcdf-fortran@4.5.3

**Comment by Alex-Fang66** [comment]
@msulprizio Thanks a lot for the reply! I did what you said and it turns out you are right. The errors do originate from MEIC and MIX inventory and the very beginning error which I mentioned before things about '268' appears again. In fact, my target area is China, so I really need to add MEIC. Could you help me to solve the problem occurred in HEMCO.log? I have encountered it many times and have no idea what to do with it.
Here I attach new dry_run.log.
[dryrun.zip](https://github.com/geoschem/geos-chem/files/6845279/dryrun.zip)

**Comment by msulprizio** [comment]
I think I see the issue. The entries for `MEIC_OCPO_*` in your HEMCO_Config.rc use scale factor 268 to convert from OC to OCPO. However, this scale factor is blocked off by the logical `(((NEI2011_HOURLY.or.NEI2011_MONMEAN ... )))NEI2011_HOURLY.or.NEI2011_MONMEAN`. Both NEI2011 options are set to false, so HEMCO won't read those scale factors. You will want to modify those lines to be `(((NEI2011_HOURLY.or.NEI2011_MONMEAN.or.MEIC ... )))NEI2011_HOURLY.or.NEI2011_MONMEAN.or.MEIC` so that scale factor 268 is available for MEIC as well.

**Comment by Alex-Fang66** [comment]
@msulprizio   Thank you for your help!  I worked out this issue finally based on your methods!
But another issue that bothers me from the MERRA2 file read.
I did choose nested simulation on AS when creating rundirs, but the target dir seems to be wrong. So I changed the target dir from '/Data/fuyu/geos/ExtData/GEOS_0.5x0.625' to '/Data/fuyu/geos/ExtData/GEOS_0.5x0.625_AS'.(PS: maybe I should not)
It is weird that its file name is different from the one I have which downloaded from [http://geoschemdata.computecanada.ca/ExtData/GEOS_0.5x0.625_AS/MERRA2/](http://geoschemdata.computecanada.ca/ExtData/GEOS_0.5x0.625_AS/MERRA2/). 
As you can see, it required file named like this showing below.
![required file](https://user-images.githubusercontent.com/65645232/126423064-de608234-8075-464b-8eb1-d5e44bdc9765.jpg)
However, what I have is:
![existed](https://user-images.githubusercontent.com/65645232/126423215-88d75731-6c0c-4b4b-b0f1-7c4cacd7ac8f.png)
So how can I manually change the file name by adding '.AS'?

**Comment by msulprizio** [comment]
By default, the nested grid simulations are set up to read the global high-resolution met fields. This allows users to choose their own nested domain, rather than sticking to the traditionally used North America, Asia, or Europe domains supported in GEOS-Chem. However, if you are using one of those three domains it does make most sense to use the fields that have been cut to those regions to improve file I/O and therefore model performance.

It looks like your simulation is looking in the correct path (GEOS_0.5x0.625_AS) with your update, but you will also need to change the met field filenames in HEMCO_Config.rc to include ".AS". You can do this any number of ways, one example would be to use search and replace in that file to replace "05x0625" with "05x0625.AS".

**Comment by Alex-Fang66** [comment]
Thank you for your help! @msulprizio
