### ISSUE TITLE
[QUESTION]How to run a nested model with Acid uptake on dust module?

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#785]
In GEOS-Chem v12.9, I want to run a nested model with Acid uptake on dust module. However, errors reported when I did it :

```
GEOS-CHEM ERROR: NetCDF NOx coeffs only preprocessed for 2x25 and 4x5 - try
setting the module variable UCXNETCDF=.FALSE.
STOP at INIT_UCX (UCX_mod.F90)!
```

Is there any way to run a nested Acid uptake module in v12.9?

**Comment by msulprizio** [comment]
Hi @yangxiajie. You have a few options here. You may either disable UCX (online stratospheric chemistry) and run the acid uptake option with the tropchem simulation, or you may do as the error message instructs and set `UCXNETCDF=.FALSE.` in GeosCore/ucx_mod.F90. Essentially, when UCXNETCDF is true, the code in ucx_mod.F90 will look for a file name with the model resolution and since files not available for resolutions other than 2x2.5 or 4x5, your simulation crashes. Using the text file instead of the netCDF file should get you past that error.

**Comment by yangxiajie** [comment]
Hi @msulprizio , thank you for reply.

I fixed the error above, by turnning off `Use UCX strat. chem?`  and `Active strat. H2O?`   . However, another error reported:

```
GEOS-Chem ERROR: CHEM_STATEPSC is not found in the registry for the CHEM object!
 -> at Registry_Lookup (in Headers/registry_mod.F90)

GEOS-Chem ERROR: Could not locate Chem_StatePSC chemistry state registry.
 -> History_AddItemToCollection (in History/history_mod.F90)

GEOS-Chem ERROR: Could not add diagnostic "Chem_StatePSC" to collection: Restart
 -> at History_ReadCollectionData (in module History/history_mod.F90)

 -> ERROR occurred at (or near) line     76 of the HISTORY.rc file

GEOS-Chem ERROR: Error encountered in "History_ReadCollectionData"!
 -> at History_Init (in module History/history_mod.F90)

GEOS-CHEM ERROR: Error encountered in "History_Init"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
```
I did not find that when I ran the same module but with 2*2.5 resolutions. Is there any to fix that?

**Comment by msulprizio** [comment]
It looks like you will need to comment out UCX-specific diagnostics in your HISTORY.rc file. You can start with commenting out the line for "Chem_StatePSC" -- that is place a `#` at the beginning of that line.

You would not have seen this error when running at 2x2.5 because you had UCX turned on in that simulation. You also didn't see the previous UCXNETCDF error then because there was an existing netCDF file at that resolution.

**Comment by yangxiajie** [comment]
Thank you @msulprizio , now I fix the problem.

Thank you very much again for your kindness help.
