### ISSUE TITLE
[QUESTION] CH4 simulation

### ISSUE THREAD

**Issue by zhuhaors** [geoschem/geos-chem#787]
Hi
I am a new user of GEOS-Chem, and I have two questions: (My version of GEOS-Chem is 13.1.2)

  1. Why only the emission inventory of methane is used in the “CH4 simulation”, and the emission inventory of other species is not used? For example, the NO2 emission inventory. I think the concentrations of other species also affect methane's concentrations, so I have doubts about that.

  2. Whether or not the download_data.py script can only download specific sample GEOS-Chem restart files. For example, in the CH4 simulation, the initial time is set to February 1, 2019, and the download result is "initial"_ GEOSChem_ rst.2x25_ CH4.nc”. This file actually corresponds to the initial conditions on January 1, 2019, so should I manually download the initial data of February 2019 from the 10-year full-chemistry benchmark for 13.0.0.

Thanks for your reply！

**Comment by zhuhaors** [comment]
@msulprizio Thanks a lot for the reply!

**Comment by yantosca** [comment]
@zhuhaors, thanks for your comment.  While it would be optimal to do an integrated CH4 chemistry simulation, we often have to make tradeoffs due to computational constraints.  For example, to construct a Jacobian matrix for inverse modeling takes many independent CH4 simulations.  If the simulations contained the full chemistry mechanism it would an inordinate amount of time before they all completed.

**Comment by zhuhaors** [comment]
@yantosca, thanks a lot for the reply! I get it.

**Comment by msulprizio** [comment]
I'm going to close this issue for now, but please feel free to reply here with additional questions and we will reopen. You may also choose to open a new issue.
