### ISSUE TITLE
[QUESTION] Change in definition of Jval_O3O3P and Jval_O3O1D in 13.0.0

### ISSUE THREAD

**Issue by jimmielin** [geoschem/geos-chem#804]
### Ask a question about GEOS-Chem:

Hi all,

When comparing J-values for `O3` between GEOS-Chem Classic, CESM2-GC and CAM-chem, @fritzt and I noticed that the reference values in the 1-yr benchmarks for GEOS-Chem Classic versions 12.9.0 and 13.0.0 are different by 3-4 orders of magnitude:

* **12.9.0** Page 117, 118: http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/12.9.0/FullChem/GCC/Plots/JValues/Jan2016/Jval_Surface_Jan2016.pdf
* **13.0.0** Page 1, 2: http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/13.0.0-beta.1/GCClassic/FullChem/BenchmarkResults/JValues/Jan2019/Jval_Surface_Jan2019.pdf

It would appear that the definition for these has changed across versions because the pattern looks similar. Perhaps we missed the discussion of this being changed, we could appreciate any documentation on this so we can compare across versions and implementations of GEOS-Chem. Thank you!

Best,
Haipeng

**Comment by msulprizio** [comment]
This difference was also noted in the [1-month benchmark assessment form for 13.0.0](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_13.0.0#Benchmark_assessment_form). From the additional notes in that form:

>There appears to be an issue in the diagnostics for O3+hv->O(1D) and O(3P), but this is simply due to a diagnostic name change. In GEOS-Chem 12.9.0, those fields were saved to Jval_O3OP and Jval_O3O1D. In 13.0.0, they’re saved out to JvalO3OP and JvalO3O1D. Bob wrote, “This was intentional. Prior to the netCDF reduction of memory the State_Diag%JVal array had nPhotol+2 slots. The extra 2 were JVal_O1D and Jval_O3P. But we coudln't wild card O1D and O3P because they are not species names found in the species database. Rather than put in a kludgey workaround I decided to make it JvalO3O1D and JvalO3O3P. The _ implies a wild-card-able species name.” The GCPy plotting routines were only recognizing diagnostics beginning with “Jval_” so the new diagnostics were not plotted. I’ve fixed this and regenerated the J-value plots, so we can compare those fields (see pages 1-2 and 119-120). For future versions, GCPy will properly plot the differences using the new diagnostic names.

**Comment by msulprizio** [comment]
I am still looking into the order of magnitude difference between the two versions.

**Comment by msulprizio** [comment]
I compared the log files for the 12.9.0 and 13.0.0 benchmarks to check the FAST-JX output that prints there. The output is identical between the two versions, indicating there appears to be no change to the mapping of species or reactions that would impact the J-value diagnostic output.

I suspect much of the difference may be resulting from the [updates introduced in 13.0.0](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_13.0.0#Version_overview). Unfortunately, we no longer have the output files from our 13.0.0 internal benchmarks and the [benchmark plots](http://ftp.as.harvard.edu/gcgrid/geos-chem/validation/InternalBenchmarks/) that are archived for those simulations do not include J-values for O1D or O3P because of the diagnostic issue noted above. However, these are some of the changes that may have contributed to the differences:

- Changes to benchmark setup:
-- Use MERRA-2 meteorology instead of GEOS-FP
-- Update benchmark year from 2016 to 2019
-- Use restart file that has been spun up (July 2016 restart file from GEOS-Chem 12.9.0 1-year benchmark)
- [Update to CEDS_GBD-MAPS emission inventory (1970 - 2017)](https://github.com/geoschem/geos-chem/issues/447)
- [Heterogeneous chem fixes, performance improvements, and clarification](https://github.com/geoschem/geos-chem/pull/396)

**Comment by yantosca** [comment]
Also note we have fixed an issue (described in #810) where the diagnostic arrays for JvalO3O1D and JvalO3O3P were not getting zeroed at the start of each new chemistry timestep.  This might not explain all of the differences observed in the outputs between 13.x and 12.x versions.

**Comment by jimmielin** [comment]
This is correctly closed but I'm just updating this for future reference. The fixes implemented in #810 have correctly resolved the order-of-magnitude differences in the J-value diagnostics. There are differences between 12.9 and 13.x but those would be science questions. I will update further on this if I have more information.

Thanks everyone for looking into this!
