### ISSUE TITLE
[QUESTION] Low load_avg of SGE

### ISSUE THREAD

**Issue by Alex-Fang66** [geoschem/geos-chem#808]
Hi, I allocated 32 cpus for the simulations, but the load_avg is low. As is shown below, the all.q@compute-0-1.local and all.q@compute-0-10.local are for  global 2x25 simulations and the all.q@compute-0-2.local and all.q@compute-0-3.local are for nested simulations of AS.
![qstat](https://user-images.githubusercontent.com/65645232/127744907-0fdbe795-b01a-40ba-950b-864ea2819185.jpg)
![qhost](https://user-images.githubusercontent.com/65645232/127744930-6816819d-d51e-4d9f-8a05-811490ad44eb.jpg)

I submitted jobs to the SGE by a bash script, where I gave plenty of memory and OMP_STACKSIZE.
![qsub_script](https://user-images.githubusercontent.com/65645232/127745030-fc320c3b-e82a-4c23-b6fb-1d4be95f8877.jpg)

It takes an hour for a simulation of a day, and all the simulations are standard full_chemistry.

**Comment by yantosca** [comment]
Thanks for writing @Alex-Fang66.  I see your CPU architecture is AMD.  Can you remind me if you are using GNU or Intel compilers?  As it turns out, you will never get great performance with Intel compilers on an AMD chipset, because the Intel compiler does not take advantage of AMD-based chip optimizations.  This is because Intel wanted to drive AMD out of the market about 20 years ago.

We would recommend that you use Gfortran on AMD if possible, as there is no similar restriction.  GEOS-Chem should optimize pretty well on both AMD and Intel chips (although gfotran-compiled code on Intel chips may be a little slower than Intel-compiled code on Intel chips).

**Comment by Alex-Fang66** [comment]
Thanks for replying @yantosca. I am using gfortran. It is worth mentioning that when I use 64 cores to occupy an entire node, the utilization will be improved. However, when using 32 cores, computing resources are not fully utilized I suppose.

**Comment by yantosca** [comment]
Thanks for the feedback @Alex-Fang66.  The utilization issue would be something to run by your sysadmins.  It could be that when you request an entire node you get better performance because there aren't any other competing jobs on the same node.

**Comment by Alex-Fang66** [comment]
Thank you!
