### ISSUE TITLE
[BUG/ISSUE] Floating divide by zero when History collections turned on

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#917]
@zsx-GitHub submitted the following issue:

From: https://github.com/geoschem/gchp/issues/37:

> Hi @joeylamcy, the original error you reported is occurring in MAPL history during diagnostic write. Are you able to make it go away by turning off diagnostics? This might help hone in on the problem.

@lizziel Hi Lizzie and all, I recently run into a similar issue. I enforced particulate matter concentration in GEOS-Chem to be at the measured value in the lowest 8 layers. After my revisions, the model can run smoothly if all HISTORY COLLECTIONS are turned off. The model will stop with 'forrtl: error (73): floating divide by zero' if any of the HISTORY COLLECTIONS (eg: SpeciesConc) is turned on. Does anyone have any ideas on how to fix this? Thank you!

Below I am pasting the out messages in slurm***.out:

```
forrtl: error (73): floating divide by zero
Image PC Routine Line Source
gcclassic 00000000011699CF Unknown Unknown Unknown
libpthread-2.17.s 00002ADA281F5630 Unknown Unknown Unknown
libnetcdf.so.7.2. 00002ADA27881D9C NC4_def_var Unknown Unknown
libnetcdf.so.7.2. 00002ADA27806FCB nc_def_var Unknown Unknown
libnetcdff.so.6.0 00002ADA2717A70C nf_def_var_ Unknown Unknown
gcclassic 0000000000FD5865 m_netcdf_io_defin 203 m_netcdf_io_define.F90
gcclassic 0000000001010914 ncdf_mod_mp_nc_va 3816 ncdf_mod.F90
gcclassic 000000000099AB0E history_netcdf_mo 465 history_netcdf_mod.F90
gcclassic 00000000009970C7 history_mod_mp_hi 2885 history_mod.F90
gcclassic 0000000000412E39 MAIN__ 2082 main.F90
gcclassic 000000000040C11E Unknown Unknown Unknown
libc-2.17.so 00002ADA28424555 __libc_start_main Unknown Unknown
gcclassic 000000000040C029 Unknown Unknown Unknown
/var/slurmd/spool/slurmd/job45642322/slurm_script: line 23: 94051 Aborted (core dumped) ./gcclassic - > $log

real 6m44.986s
user 104m8.109s
sys 1m46.121s
```

**Comment by lizziel** [comment]
Hi @zsx-GitHub, could you post your configuration and log files here? You can add extension '.txt' to the filenames and then drag and drop them into the GitHub comment box. Files to include are:

- input.geos
- HEMCO_Config.rc
- HISTORY.rc
- GEOS-Chem log file
- HEMCO.log

Please also let us know what version you are using and what simulation you are running.

**Comment by zsx-GitHub** [comment]
Hi @lizziel, thank you very much! Please see below my configuration and log files.

[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/7237232/HEMCO.log.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/7237220/input.geos.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/7237224/HEMCO_Config.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/7237226/HISTORY.rc.txt)
[v13.0.2.log.txt](https://github.com/geoschem/geos-chem/files/7237230/v13.0.2.log.txt)
[slurm-45656213.out.txt](https://github.com/geoschem/geos-chem/files/7237245/slurm-45656213.out.txt)

Please let me know if other information id needed. Thank you very much again.

Best,
Shixian

**Comment by yantosca** [comment]
Hi @zsx-Github, thanks for providing the information.  I took a quick look at the config files and didn't see anything out of the ordinary.  Can you point me to your rundir on Cannon?  I can try to run in the debugger, since the job seems to choke after an hour.  Also, which Intel compiler version are you using?

**Comment by yantosca** [comment]
Hi Shixian.  I used gfortran 10.2.0.  I copied your run directory and code directory to my scratch space and built the model with debugging flags.  It found an error right away because you are missing a couple of species from the `species_database.yml` file in your run directory.  You need to add the following entries:
```yaml
PSO4OH:
  FullName: Dummy species to track production of SO4 from OH
  Is_Gas: true
  MW_g: 96.06
SO4OH:
  Formula: SO4
  FullName: Sulfate produced by OH
  Is_Gas: true
  MW_g: 96.06
```
I was able to run until I got this error:
```
HEMCO ERROR: Cannot find file for current simulation time: /n/home02/szhai/data_files/emissions/KORUSv5/v2021_05/agts_l.20150401.1.KORUS_01d.KORUSv5_01d.GC.nc - Cannot get field KORUS_NO_agts. Please check file name and time (incl. time range flag) in the config. file
```
but that is because I don't have permission to read the data files in your home directory.  

Try updating the species database and see if you get past the error in the history concentrations.  There was probably an error with the indexing for e.g. `SpeciesRst_?ALL?` as it could not find the model ID for PSO4OH and SO4OH dummy species.

NOTE: All species (even dummy species to track production) have to be listed in the `species_database.yml` file, because we assign a molecular weight to each species.  This is used for unit conversions, etc.

**Comment by zsx-GitHub** [comment]
Hi @yantosca, thank you so much for building the model! I realized that I have still been using the ifort17. Now I changed to gfortran 10.2.0 (by 'source ~/envs/gcc.gfortran10.2_cannon.env' with the newly downloaded cannon-env). However, while compiling, it prompt:

[  4%] Building Fortran object src/HEMCO/src/Shared/Headers/CMakeFiles/HeadersHco.dir/hco_precision_mod.F90.o

Error: A license for Comp-FL is not available (-76,61026,2).

License file(s) used were (in this order):
    1.  Trusted Storage

Error: A license for Comp-FL is not available (-76,61026,2).

License file(s) used were (in this order):
    1.  Trusted Storage

Error: A license for Comp-FL is not available (-76,61026,2).

License file(s) used were (in this order):
    1.  Trusted Storage

Error: A license for Comp-FL is not available (-76,61026,2).

License file(s) used were (in this order):
    1.  Trusted Storage

Error: A license for Comp-FL is not available (-76,61026,2).

License file(s) used were (in this order):
    1.  Trusted Storage

Error: A license for Comp-FL is not available (-76,61026,2).

License file(s) used were (in this order):
    1.  Trusted Storage
**  2.  /n/sw/intel-cluster-studio-2017/compilers_and_libraries_2017.4.196/linux/bin/intel64/../../Licenses
**  3.  /n/home02/szhai/Licenses
**  4.  /opt/intel/licenses
**  5.  /Users/Shared/Library/Application Support/Intel/Licenses
**  6.  /n/sw/intel-cluster-studio-2017/compilers_and_libraries_2017.4.196/linux/bin/intel64/*.lic

I must have missed something here. Now the emission inventories have been copied  to _holyscratch01_ and emission directories in HEMCO_Config.rc have been changed accordingly. Actually, the model won't get stuck in the history concentrations without changes in /n/holyscratch01/jacob_lab/szhai/GCClassic.13.0.2/src/GEOS-Chem/Set_DST3_to_PMC_patch_zsx.diff. Not sure if it is the old ifort compiler that caused the problem.

**Comment by yantosca** [comment]
Hi @zsx-GitHub, I would open up a ticket with FASRC (rchelp@rc.fas.harvard.edu) about the  license and storage issue.  That is something that the GCST cannot resolve.

**Comment by yantosca** [comment]
Also @zsx-GitHub, I would open up a new terminal window and load modules for gfortran 10.2.0.  If you tried loading the gfortran 10.2.0 in the same window as ifort 17 there may be errors.

I can try copying your run directory again and running so that I won't get stuck on the permission error.

**Comment by yantosca** [comment]
@zsx-GitHub Also I can't get to the point of where HISTORY.rc fails because your HEMCO_Config.rc is still looking for files in your home directory: /n/home02/szhai/holyscratch01/EMISSIONS/MEIC.  If you make your home directory readable then I can run.

```bash
cd /n/home02
chmod 755 szhai
```

**Comment by zsx-GitHub** [comment]
Hi @yantosca, thank you so much! I redid the compiling with gfortran 10.2.0. The model is running smoothly with SpeciesConc outputs! So it seems that compiler matters!! Thank you very much for pointing this out. 

There are, however, some warnings in the slurm****.out file:

At line 744 of file /n/home02/szhai/GC_run/clean.13.0.2/gc_merra2_fullchem_05x0625_AsiaPM_LDSTUP_obsPMC/CodeDir/src/GEOS-Chem/GeosCore/transport_mod.F90
Fortran runtime warning: An array temporary was created for argument 'ps1' of procedure 'tpcore_window'
At line 745 of file /n/home02/szhai/GC_run/clean.13.0.2/gc_merra2_fullchem_05x0625_AsiaPM_LDSTUP_obsPMC/CodeDir/src/GEOS-Chem/GeosCore/transport_mod.F90
Fortran runtime warning: An array temporary was created for argument 'ps2' of procedure 'tpcore_window'
At line 745 of file /n/home02/szhai/GC_run/clean.13.0.2/gc_merra2_fullchem_05x0625_AsiaPM_LDSTUP_obsPMC/CodeDir/src/GEOS-Chem/GeosCore/transport_mod.F90
Fortran runtime warning: An array temporary was created for argument 'ps' of procedure 'tpcore_window'
At line 687 of file /n/home02/szhai/GC_run/clean.13.0.2/gc_merra2_fullchem_05x0625_AsiaPM_LDSTUP_obsPMC/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90
Fortran runtime warning: An array temporary was created for argument 'u' of procedure 'air_mass_flux'
At line 687 of file /n/home02/szhai/GC_run/clean.13.0.2/gc_merra2_fullchem_05x0625_AsiaPM_LDSTUP_obsPMC/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90
Fortran runtime warning: An array temporary was created for argument 'v' of procedure 'air_mass_flux'
At line 697 of file /n/home02/szhai/GC_run/clean.13.0.2/gc_merra2_fullchem_05x0625_AsiaPM_LDSTUP_obsPMC/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90
Fortran runtime warning: An array temporary was created for argument 'xmass' of procedure 'air_mass_flux'
At line 697 of file /n/home02/szhai/GC_run/clean.13.0.2/gc_merra2_fullchem_05x0625_AsiaPM_LDSTUP_obsPMC/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90
Fortran runtime warning: An array temporary was created for argument 'ymass' of procedure 'air_mass_flux'
At line 822 of file /n/home02/szhai/GC_run/clean.13.0.2/gc_merra2_fullchem_05x0625_AsiaPM_LDSTUP_obsPMC/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90
Fortran runtime warning: An array temporary was created for argument 'q' of procedure 'qmap' # # #

I will let you know if the outputs are reasonable so that we can close this issue.

**Comment by yantosca** [comment]
Thanks @zsx-Github. Those warnings
```
At line 744 of file /n/home02/szhai/GC_run/clean.13.0.2/gc_merra2_fullchem_05x0625_AsiaPM_LDSTUP_obsPMC/CodeDir/src/GEOS-Chem/GeosCore/transport_mod.F90
Fortran runtime warning: An array temporary was created for argument 'ps1' of procedure 'tpcore_window'
```
are caused by pointer references to fields of State_Met before calling TPCORE_WINDOW. Gfortran complains about it, ifort does not.

Hopefully the run will finish OK!

**Comment by yantosca** [comment]
Hi @zsx-GitHub, I will close out this issue as it seems that this is now resolved.  Please feel free to submit a new issue if you are still having problems.  Thanks so much!
