### ISSUE TITLE
[QUESTION] Column integrated AOD diagnostic output

### ISSUE THREAD

**Issue by chfite** [geoschem/geos-chem#939]
I am wanting to save out netcdf files of the vertically summed AOD for different aerosol species. Currently in the Aerosols diagnostic in History.rc the AOD is saved out at all vertical levels and has dimensions (time, lev, lat, lon). I only want the vertically summed AOD values, thus dimensions (time, lat, lon), because it will reduce the space I need to store output on disk. Is there a way to specify in History.rc that I want the column integrated values? I am currently using GC 12.6.0 for this work.

**Comment by yantosca** [comment]
Thanks for writing @chfite.  You would have to add a new diagnostic for column-integrated AOD, because the dimensions of HISTORY diagnostics are fixed and are specified before the diagnostics arrays are allocated. 

We have outlined the basic steps for adding new History diagnostics [here http://wiki.seas.harvard.edu/geos-chem/index.php/Adding_new_History_diagnostics].  You can also cut-n-paste the existing history diagnostics and metadata to create new diagnostic arrays in state_diag_mod.F90 (but for the column-averaged diagnostics you'd have to specify the rank as 2 and not 3 where the metadata is defined).
